### ISSUE TITLE
Random texture flicks on Dungeon Keeper 2 + PMMX + Win98 + Voodoo3/Banshee

### ISSUE THREAD

**Issue by mgtroyas** [86Box/86Box#1489] opened 2021-06-16 10:03 UTC
When playing Dungeon Keeper 2 (patch 1.7) with hardware acceleration (Direct3D) enabled on Windows 98 host with Voodoo3/Banshee graphic card, ingame textures (UI, menus, game scenario) have random flicks during gameplay.

- Run Dungeon Keeper 2 (SafeDisk protection removed with unsafedisc)
- Start a scenario.
- Scroll arround or open menu.

I've recorded a video (please watch at full resolution) (sometimes errors are more frequent than this):
https://www.youtube.com/watch?v=WGWuAF8wky4

I haven't seen these errors on other games so far.

My system:
 - OS: Windows 10
 - 86Box version: #3016 (initially detected on PCem v17).
 - Build type: regular

**Comment by eddmanx** [comment] 2024-01-30 01:30
Which board? Can you post the machine files, cfg, nvr and HDD?

I couldn't replicate this. At first I thought it might be related to the 4 render threads bug, but even that works fine here.

**Comment by OBattler** [comment] 2024-03-05 19:45
Does this still happen?

**Comment by OBattler** [comment] 2024-03-05 19:50
@eddmanx: This was most likely the 64-bit Voodoo recompiler bug whose behavior was all over the place and which has since been fixed. As such, I'm closing this. It can be-reopened if the issue is discovered to still be present.

**Closed by OBattler** 2024-03-05 19:50 UTC
Labels: bug

**Comment by mgtroyas** [comment] 2024-03-06 09:45
Sorry for the delay. Yes, I downloaded latest stable version of 86box (4.1), using a Windows 98 machine with a Voodoo3 3000, launched Dungeon Keeper 2 and now the graphical glitches are gone. You guys are doing god's work, thank you very much.
