### ISSUE TITLE
Bugs while running Area 5150

### ISSUE THREAD

**Issue by FavoritoHJS** [86Box/86Box#2589] opened 2022-08-07 21:46 UTC
**Describe the bug**
As you might have been aware, a new demo dropped for the IBM PC: Area 5150 by CRTC and Hornet. Download here: https://www.pouet.net/prod.php?which=91938

And as per tradition, it breaks all your emulators (though PCem and 86Box _almost_ make it through -- namely, if what `phoenix` posted in that thread is correct, they both seem to break at the same places in (likely) identical ways, except that PCem also fails PWM playback while 86Box doesn't). In the "Aditional context" section, I've attatched parts that break or don't seem to work as intended.

Small note: This was run on an emulated 5160, running DR-DOS 5.0, with ~~256k of main memory and 384k provided by an AST SixPakPlus.~~ 640k of main memory. I don't think that would break anything IRL (I don't think ISA memory has wait states), but I'm no expert here.

Lastly, all bugs are to be referenced against real hardware. If you don't have one, use this: https://www.youtube.com/watch?v=-xJZ9I4iqg8

**To Reproduce**
1. Download the Area 5150 demo here: https://www.pouet.net/prod.php?which=91938
2. Jam those files into floppies. You will need at least 1x 720k or 2x 360k diskettes.
3. Make a IBM PC machine and install the software. I just dumped them into a folder of the hard disk, but you could also make 2 foppies and split them if you found what each part used (namely, the pre-commanche and post-commanche sections).
4. Run and enjoy (or cry if you want to fix this).

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2 x64
 - 86Box version: 3.7.1, build 4037, updated for build ~~4048 4335~~ 4341
 - Build information: Windows x64, Old Dynarec

**Additional context**

Note: Mark off these checkboxes as these bugs are squashed.

- [ ] I wasn't able to capture this, but some effects seem to cause small black flashes at the top of the screen, likely due to timing problems. That twistly bar effect seems specially prone to this.
Can't reproduce in build 4048, I'm guessing the timer optimizations might have accidentally solved this? Or maybe that was just my eyes...
Nevermind, saw them in 3.11b4335. I'm guessing timing issues.

- ~~Every now and then, while switching executables, the screen flashes black. This might be due to running on disk, a buggy demo dispatcher, DR-DOS jank...~~ Seems to also happen on real hardware.

- [ ] When the demo edits an 80-column tweakmode, snow appears despite the original capture not having snow.
![Monitor_1_20220807-170254-464464](https://user-images.githubusercontent.com/69703458/183311788-f3b8031a-b36b-4831-a702-bebdaa2f0b27.png)

- [ ] When the plasma displays here, the emulator runs extremely slowly... despite the toolbar saying it's at 100%. Unsure if this is the machine being _just_ slow enough to cause problems or if this is a legitimate problem with 86Box.
![Monitor_1_20220807-170430-683683](https://user-images.githubusercontent.com/69703458/183311870-d5fea96d-b633-4612-881b-069461c05662.png)
\
- [ ] Forgot to place this one earlier, but this effect with APA graphics intersperced with character graphics is unstable. I'm guessing the problem is poor IO timing.
This is how it's meant to look:
![Monitor_1_20220810-152418-713713](https://user-images.githubusercontent.com/69703458/184004295-54e97985-db42-48e9-a624-34f5ccca9041.png)
\
but it sometimes flashes these instead:
![Monitor_1_20220810-152417-634634](https://user-images.githubusercontent.com/69703458/184004411-265be344-f9a3-46a0-a28d-a21268aef2cf.png)
Timing failure, image enters and exists APA early, causing color distortion.
\
![Monitor_1_20220810-152423-495495](https://user-images.githubusercontent.com/69703458/184004562-b2d49a5e-86d0-4016-8552-93d52efb553d.png)
This can also result in parts of the image being skipped, likely due to the frame start register being changed at an improper time.

If this fails even with otherwise accurate IO writes, consider sub-line emulation of this, as the real hardware might have some slack that the emulator doesn't.

- [ ] The big one. The final couple effects cause the display to break _completely_, causing massive flicker.
\
![Monitor_1_20220807-170718-76076](https://user-images.githubusercontent.com/69703458/183311897-6b5eda72-3db5-48ad-9fca-b2bba6fa9f58.png)
Even when it works it's broken...
\
![Monitor_1_20220807-170719-026026](https://user-images.githubusercontent.com/69703458/183311913-6cab550b-2476-42b7-9754-ede121cb4717.png)
...and when it doesn't work, it _dies_.
\
![Monitor_1_20220807-170741-87087](https://user-images.githubusercontent.com/69703458/183311951-7dadb36a-cdcf-41e7-8650-0d16dc0b6824.png)
Also happens at the end, while playing PWM data.
\
![Monitor_1_20220807-170742-01001](https://user-images.githubusercontent.com/69703458/183311966-c113d5a5-ef18-4e65-805f-d343800f2397.png)
This should be a reflection effect, but it's glitch art now.

- [ ] Also, as can be seen on these pictures, the overscan isn't calculated correctly -- it seems to be a border around the visible area instead of a less trimmed image.

~~PS: The demo seems to hog a massive ammount of resources, especially with per-scanline effects. Might be worth looking into some code refactoring.~~ By b4341 the worst of this has been fixed -- while cpu usage is 3 times higher than normal, it's still under 5% -- an idling Firefox tends to consume more!

**Comment by dbalsom** [comment] 2023-05-21 12:30
The last two scenes are called "Wibble" and "Lake" respectively according to the demo script list. They're similar effects and in fact share the same setup code, which is a chain of 8 timer interrupts with various delays to create what is essentially a precisely positioned vsync interrupt that triggers two scanlines before the effect begins drawing.

Both effects are similar to the Kefrens effect from 8088MPH in that they are a completely cycle-counted - no polling is done for display enable to detect scanlines, everything must happen in exactly 304 cpu cycles per scanline from start to finish, except now there's a lot more going on.  

The effects create two CRTC frames per scanline, the 2nd frame being a single character wide, hidden off in the right overscan and apparently used to advance the VMA pointer by one byte for the next scanline. I can see from the brief bits of legible output that this isn't being done as you can notice the first character column of the effect has the incorrect data in it.  This is actually how the graphics are stored in memory, but that 2nd frame trick causes a one byte offset.

I suspect some CPU inaccuracies may be at play here as well. The horizontal discontinuities sort of indicate to me that each scanline isn't executing in 304 cycles.  The effect has to execute in exactly 79,648 clock cycles per frame or it loses synchronization as the entire effect is contained within the frame-aligned timer ISR.  If a frame finishes early or late then we enter the next frame at the wrong relative position on screen and there's a cascading failure to update the CRTC registers at the correct times, and funky stuff starts happening like scanline wrap-around, missed hsyncs, late vsync, etc and I assume 86box's CGA is not having a fun time with all that.

These effects use a lot more instruction types than the Kefrens did and as such encounter a few prefetch/bus delay scenarios not encountered in 8088MPH. A single missed bus delay could mean you skip up to 3 clock cycles, and 3 clock cycles is 9 pixels, and the window to hit the ISR at the right point on the screen is very small indeed.

The polygon effect is called 'Tetra3d' and it is indeed changing from 40 col text mode to graphics mode and back on a single screen. The top and bottom 'graphics' are text mode with the traditional CRTC tricks used everywhere else in the demo, while the polygon itself is graphics mode. The black bar glitch is the polygon being rendered in text mode, and the 'noise' is the text mode graphics being rendered in graphics mode. Both of these occur because the timer ISR triggered mode switch occurred too early or too late.   This is not a heavily cycle-counted effect.  It just relies on very accurate interrupt synchronization and again there are cascading failures if we are inaccurate.

**Comment by dbalsom** [comment] 2023-05-23 03:23
In the process of debugging Tetra3d I discovered something very interesting. 

It relies on undocumented(?) PIT behavior. 

The effect sets Timer channel 0 to Mode 2, Rate Generator, LsbMsb, and pretty much leaves it there the whole time.
During startup, it sets the reload value to 2.  This is, I presume, to immediately assert INTR so that when we finally HLT, the first ISR will immediately fire off.

Just before halting, the setup procedure sets the timer value to 3724 @ CS:3052. This value equates to 49 scanlines exactly. This schedules the ISR that changes to graphics mode to fire off after all the cloud text-mode-graphics are drawn.  This ISR should always trigger on the next scanline after the cloud graphics, so why is the mode change sometimes late?

Bear in mind, the reload value is still 2 at this point when the new timer value is being written.  In Mode 2, the timer does not stop while writing a new reload value, but terminal count will reload the count register(reload value) into the counting element. 

A reload value of 2 gives us at most eight CPU cycles to update the LSB and MSB together.  Unfortunately a single OUT is 13 clock cycles, 

```
seg000:3052                 mov     al, 8Ch
seg000:3054                 out     40h, al
seg000:3056                 mov     al, 0Eh         ; Timer expires and is reloaded with just new LSB
seg000:3058                 out     40h, al         ; Timer value should be 0E8C (Exactly 49 scanlines) but ends up 008C
seg000:305A                 sti
seg000:305B                 hlt                     ; Wait for ISR1
```

So what happens, is that we manage to set the LSB, the timer hits terminal count, and reloads with _just the updated LSB_  and carries on, meaning the intended delay for the next interrupt is incorrect, and since each interrupt sets the delay for the next interrupt in the chain, our interrupt timing is thrown off for the rest of the effect.

The designers of the 8253 must have considered this, because on real hardware, something interesting happens.  When the timer is reloaded from an 'incomplete count', **the timer reloads again when the MSB is finally loaded.**  I don't believe this is documented anywhere, but I have confirmed it happens on real hardware, and have added a test case to my little 8253 acid test.  I am calling this feature "MSB recovery". I'd be very curious if it has ever been mentioned anywhere before. I don't know if this also happens on the 8254, but I would assume so.

Attached is a floppy image with my acid test utility for the 8253.  All tests pass on a real IBM 5150.  86box currently only fails two.
[acid8253.zip](https://github.com/86Box/86Box/files/11538910/acid8253.zip)

**Comment by dbalsom** [comment] 2023-05-23 12:52
There's an additional bug not mentioned, but this one is trivial.
![image](https://github.com/86Box/86Box/assets/7229541/4628e346-cc9c-4529-89ce-ebf47eb1eefc)

in 86box, the background of the text is a solid black bar. The actual effect has some gradient lines:
![image](https://github.com/86Box/86Box/assets/7229541/cf036c37-86aa-49d0-a1c5-76097e9cb05f)

The effect draws these lines by toggling the video enable bit in the mode register.   When cleared, the CGA will emit the overscan color, I believe 86box is assuming we will always display nothing...

**Comment by FavoritoHJS** [comment] 2023-05-26 00:48
> In the process of debugging Tetra3d I discovered something very interesting.
> 
> It relies on undocumented(?) PIT behavior.
> 
> The effect sets Timer channel 0 to Mode 2, Rate Generator, LsbMsb, and pretty much leaves it there the whole time. During startup, it sets the reload value to 2. This is, I presume, to immediately assert INTR so that when we finally HLT, the first ISR will immediately fire off.
> 
> [...]
> 
> So what happens, is that we manage to set the LSB, the timer hits terminal count, and reloads with _just the updated LSB_ and carries on, meaning the intended delay for the next interrupt is incorrect, and since each interrupt sets the delay for the next interrupt in the chain, our interrupt timing is thrown off for the rest of the effect.
> 
> The designers of the 8253 must have considered this, because on real hardware, something interesting happens. When the timer is reloaded from an 'incomplete count', **the timer reloads again when the MSB is finally loaded.** [...] I am calling this feature "MSB recovery". I'd be very curious if it has ever been mentioned anywhere before. I don't know if this also happens on the 8254, but I would assume so.

So you can load a 1-byte _or_ 2-byte value and have it Just Work? Thanks Intel!

Appears to be added in https://github.com/86Box/86Box/commit/ab733b7f6c1e0fd737d601b25e93f3196b38ae1

**Comment by dbalsom** [comment] 2023-06-13 14:26
> The effect draws these lines by toggling the video enable bit in the mode register. When cleared, the CGA will emit the overscan color, I believe 86box is assuming we will always display nothing...

My apologies, I was wrong about this.  If you model this behavior, then the background of the display area in the UFO effect during its intro/outro will be brown like in my youtube recording, instead of black like it is on hardware. 

In text mode, clearing the enable bit makes the CGA behave as if the graphics memory is all 0's. In text mode, this will always render black if you are in the active display area.  The overscan color can only be drawn in the overscan area.

Unless, apparently, you set the mode register to 0x03. This is a seemingly illegal combination of the high-res text bit and the graphics mode bit. We stay in text mode, but the graphics mode bit seems to control whether we draw the alternate/overscan color as our background.  The effect is toggling the graphics mode in this way to draw the horizontal bars above and below the center text.

**Comment by dbalsom** [comment] 2023-06-28 12:26
I've recorded a video of the Area 5150 end credits effect "Lake" being generated one instruction at a time, so you can see the timings of each instruction and the current CRTC registers as each scanline is produced.  

https://www.youtube.com/watch?v=bT2fQpz0l1E

**Comment by dbalsom** [comment] 2023-10-17 12:31
I announced this on discord, but not everyone might be in there and this may be of interest to some. This is a full logic analyzer dump of the end credits effect of Area5150:

https://github.com/dbalsom/marty_tools/blob/main/bus_sniffer/captures/area5150/README.md

My 8088 decoder is also in that repo. With it you can see the full instruction disassembly of the entire effect, with live bus signals, interrupts, and DMA.  I'll have a blog article shortly on the process of debugging Area5150 in MartyPC.

**Comment by OBattler** [comment] 2024-01-14 23:38
Closing this as it's being tracked in https://github.com/86Box/86Box/issues/4044.

**Closed by OBattler** 2024-01-14 23:38 UTC
Labels: bug
