### ISSUE TITLE
Windows 95 can't read floppy on first insert.

### ISSUE THREAD

**Issue by Xuser641** [86Box/86Box#3427] opened 2023-06-26 10:44 UTC
**Describe the bug**
Windows 95 cannot read a floppy disk the first time you insert it, you have to eject it and then re-insert it before it can read it.

**To Reproduce**
1. Start Win95
2. Insert Floppy
3. Try and read it
4. No disk access for a while and then error message
5. Re-insert disk
6. Try again and it will work

**Expected behavior**
It should read the disk on the first time

**Desktop (please complete the following information):**
Windows 10 64 bit
86box 3.11 build 4311 32 bit

**Additional context**
Emulated machine is:
AOpen Vi15G
486DX2-66
8MB Ram
Trident TVGA8900D
Microsoft Serial Mouse - COM1
Crystal CS4236B
3.5 1.44MB FDD
4x CD-ROM

**Comment by OBattler** [comment] 2023-06-26 23:41
This is the same bug as the Windows 3.1 floppy timeout / error. It's caused by the dynamic recompiler because it processes all the timers and handles interrupts after every block of instructions instead of after every instruction. As such, I'm closing this with CANTFIX.

**Closed by OBattler** 2023-06-26 23:41 UTC
Labels: bug
