### ISSUE TITLE
Selection of display should be more closely tied with selection of machine.

### ISSUE THREAD

**Issue by Videogamer555** [86Box/86Box#1093] opened 2020-11-17 11:38 UTC
As of right now, you can mix and match machine types and display types. For example, you can emulate a modern PC (which would actually have no ISA slots on the motherboard) with an old ISA-bus MDA (monochrome display adapter), an impossible combination based on separate settings in the Machine and Display settings tabs in the settings menu of 86Box. Likewise you can emulate an old IBM-XT with a 3D-capable graphics card, another impossible combination. My suggestion is to make it so that only graphics cards that would work in the machine you are trying to emulate are visible in the graphics card selection menu, so you can't emulate impossible combinations of computers and graphics cards.

And it's not just a matter of the bus used, IDE or ISA. Not all motherboards with the same card slot type would work with all the same graphics cards, even if the graphics card would fit in the slot. For example, an IBM PC with an ISA bus, would NOT work with a more modern SVGA, XGA, or VESA type graphics card (those that support 256 or more colors and resolutions of 640x480 or more pixels), even if the card was designed for the ISA-bus. Other factors like chipset, and other electronics on the motherboard itself determine whether or not a given card is compatible with a given computer.

I would like to see the team that makes 86Box do some research on which of the dozens of graphics cards it can emulate, would actually work in which of the dozens of the computer it can emulate, and then make the graphics card selection menu only allow you to select graphics cards that are compatible with the computer that you've selected to emulate. I want the system I'm emulating to be realistic, not an obviously fake mix&match of computers and graphics cards as you can do now. I've already got an idea of which cards work in some of the older computers like the original IBM-PC only working with MDA and CGA graphics cards when using real hardware, so I can configure that realistically. But I don't know about other combinations of computers. What kind of graphics cards would work in a Tandy, or Amstrad, or Intel 286 or Intel 386 computers? I'm pretty sure that 286 can do EGA or lower, and 386 can do VGA or lower in real life. Not sure if you would need a Intel 486 to do SVGA though, or if 386 can also do SVGA.

So when experimenting with the various computers that 86Box can emulate, since I don't know what most of them are capable of in terms of supporting graphics cards, it would really help if the "display" menu would only show cards that would be supported by the computer you had selected in the "machine" menu, so I can make a more realistic setup with any computer I select to emulate in 86Box.

**Comment by maximus105** [comment] 2020-11-17 15:43
@Videogamer555 You are absolutely right. Since, for example, you choose some kind of videocard for a certain machine, and the machine does not start. And it is not clear: this is due to the fact that there is a bug in the 86Box or simply this machine does not support this video card.

**Comment by OBattler** [comment] 2020-12-06 07:59
I'm quite sure that plenty of VGA and (S)VGA cards are going to work just fine on a 286 (even if they are going to be bottlenecked by the CPU), given that VGA was intended to be mostly backwards compatible EGA, and most BIOS'es treat EGA and VGA as the same (as the EGA/VGA option).

Now, the IBM PC with the 1981 BIOS is only going to work with graphics cards that do not use a video BIOS, because it does not look for third-party BIOS'es at all. The one with the 1982 BIOS, however, I see no reason why it would not work with any 8-bit ISA card with a video BIOS, so long as the video BIOS does not use instructions that do not exist on a 808x.

Also, doing such research is very hard, anyway, as a lot of times, we would need to have the real hardware to test if that particular combination works. Given that the project is currently barely able to pay for the server that hosts the builds and the domains, I hope you can see why we can't currently afford to buy all the real hardware needed.

Also, the code to do this would be very complex and it would require a lot of time to write, as it would have to check for all sorts of things and even make machine-specific exceptions.

**Comment by OBattler** [comment] 2021-04-07 00:25
I'm closing this since this issue has outlived its purpose.

**Closed by OBattler** 2021-04-07 00:25 UTC
