### ISSUE TITLE
S3 graphics clip on some graphic elements

### ISSUE THREAD

**Issue by jadasse** [86Box/86Box#1739] opened 2021-09-27 00:57 UTC
**Describe the bug**
On my Windows for Workgroups 3.11 machine, with an S3 Vision964 (Diamond Stealth 64 4 MB of VRAM), when I play stuff like Space Cadet from Full Tilt PInball, the ball sometimes clips. That would make it difficult for me to focus. Also, in Tic Tac Drop from Microsoft Entertainment Pack 4, when you drag the chips around, they clip, too! I predict this would happen to other programs, too. The mouse itself is not affected, however.

On my Windows 95 OSR 2.5 machine, with an S3 Trio64, 4 MB of VRAM, the mouse would clip on the right half of the screen; this also goes for sub-menus in the Start menu. Also, Space Cadet is again affected.

**To Reproduce**
1. Use WfW 3.11 and Windows 95.

**Expected behavior**
There is not supposed to be any clipping whatsoever. I used these VMs in the same config with the same programs in the past, and I did not recognize any clipping. So, this must be a bug with the program.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: v3.0 build 3224
 - Build type: regular

**Additional context**
The graphics card drivers are built-in from 86Box.

**Comment by TC1995** [comment] 2021-09-29 15:01
What color bpp?

**Comment by TC1995** [comment] 2021-09-29 15:22
Actually, try build 3226.

**Comment by SeanRamey** [comment] 2021-09-29 18:15
Also, what renderer was used?

**Comment by jadasse** [comment] 2021-09-29 18:33
> Also, what renderer was used?

SDL (Software)

**Comment by SeanRamey** [comment] 2021-09-29 18:38
Can you manage to get a screenshot or video of the issue?

**Comment by jadasse** [comment] 2021-09-29 18:39
alright, one second:

**Comment by jadasse** [comment] 2021-09-29 18:50
https://user-images.githubusercontent.com/71288109/135330532-c9987d26-c12b-47dc-ba08-25b44cf95bfc.mp4

**Comment by jadasse** [comment] 2021-09-29 18:51
Also, the build did not work, and when you change the renderer, the problem still persists!

**Comment by TC1995** [comment] 2021-09-29 18:52
Can't reproduce the issue.

**Comment by jadasse** [comment] 2021-09-29 18:53
Basically, when I use WIndows 95, the mouse just clips and I do not know why that is happening, could be a bug.

**Comment by TC1995** [comment] 2021-09-29 18:54
Tried build 3226?

**Comment by jadasse** [comment] 2021-09-29 18:55
yes

**Comment by TC1995** [comment] 2021-09-29 18:57
Tried the SDL Hardware renderer, OpenGL?

**Comment by jadasse** [comment] 2021-09-29 18:58
OpenGL renderer does not work either

**Comment by SeanRamey** [comment] 2021-09-29 19:01
What about other graphics cards? Same issue?

**Comment by TC1995** [comment] 2021-09-29 19:02
Wait, is your driver s3mm.drv by any chance?

**Comment by jadasse** [comment] 2021-09-29 19:03
> Wait, is your driver s3mm.drv by any chance?

How do I know that? I am using an S3 Trio64 (Phoenix) 4 MB, by the way.

**Comment by TC1995** [comment] 2021-09-29 19:03
yes, check regedit or the display properties.

**Comment by jadasse** [comment] 2021-09-29 19:05
yes

**Comment by TC1995** [comment] 2021-09-29 19:11
Now I see it, it's only on s3mm.drv, let me try to fix it.

**Comment by jadasse** [comment] 2021-09-29 19:11
ok

**Comment by TC1995** [comment] 2021-09-29 19:26
As for the 964, what drivers are you using? Generic or Diamond specific?

**Comment by jadasse** [comment] 2021-09-29 19:27
S3 VIsion964 (Diamond Stealth64 4 MB VRAM)

**Comment by TC1995** [comment] 2021-09-29 19:28
I meant the drivers, not the card.

**Comment by jadasse** [comment] 2021-09-29 19:31
https://drive.google.com/file/d/1k8RFb_0nrDs5_mu7vz86mIoSXQUVh4rh/view?usp=sharing

**Comment by jadasse** [comment] 2021-09-29 19:43
![20210929-194249-198](https://user-images.githubusercontent.com/71288109/135337687-fd720c67-1379-4b0c-9e0c-35b29d77f232.png)
 Also, stlth64.drv as well.

By the way, when I select a file in File Manager, until I click something, the selection clips, too.

**Comment by jadasse** [comment] 2021-09-29 19:51
https://user-images.githubusercontent.com/71288109/135338460-8efcfdf3-74b6-457c-8918-4aed91ed9a3f.mp4

Have you ever seen space cadet on Windows 3.1?

Also, the clipping happens here too.

**Comment by jadasse** [comment] 2021-09-29 20:04
https://user-images.githubusercontent.com/71288109/135340470-2d35737a-666b-496c-b7eb-954d54da9d96.mp4

Tic Tac Drop clipping

**Comment by jadasse** [comment] 2021-09-29 20:51
How is it going?

**Comment by TC1995** [comment] 2021-09-29 20:52
Trying to download MS Entertainment Pack 1-4.

**Comment by jadasse** [comment] 2021-09-29 20:53
ok

**Comment by jadasse** [comment] 2021-09-29 22:31
What's up?

**Comment by jadasse** [comment] 2021-09-29 23:08
However, everything seems fine when I switch to S3 Vision964 (Diamond Stealth64 4 MB VRAM) in Windows 95. I wonder why that is not the case with Windows 3.1?

**Comment by jadasse** [comment] 2021-09-29 23:12
This MUST be a bug; with behavior like that.

**Comment by TC1995** [comment] 2021-09-29 23:13
Slow down a bit I'm about to commit a fix for this tomorrow.

**Comment by jadasse** [comment] 2021-09-29 23:14
sorry

**Comment by jadasse** [comment] 2021-09-29 23:15
> What about other graphics cards? Same issue?

No, everything seems fine when I switch to S3 Vision964 (Diamond Stealth64 4 MB VRAM) in Windows 95. I wonder why that is not the case with Windows 3.1? This MUST be a bug; with behavior like that.

**Comment by TC1995** [comment] 2021-09-30 22:54
it's fine, sorry for the delay.

**Comment by jadasse** [comment] 2021-09-30 22:55
Cool, I meant have you made any progress?

**Comment by TC1995** [comment] 2021-09-30 22:56
yep, but I'm testing something else to make sure it doesn't break such.
In other words, making sure this fix doesn't break anything else.

**Comment by jadasse** [comment] 2021-09-30 23:09
ok

**Comment by jadasse** [comment] 2021-10-03 23:11
Another thing I should mention, older versions still have the problem intact.

**Comment by jadasse** [comment] 2021-10-04 20:41
How is it going now?

**Comment by TC1995** [comment] 2021-10-04 20:41
Almost done, though I've integrated other changes as well.

**Comment by jadasse** [comment] 2021-10-04 21:24
Cool

**Closed** 2021-10-05 20:32 UTC
Labels: bug
