### ISSUE TITLE
Switch host resolution to match guest resolution on fullscreen on CRT/TV

### ISSUE THREAD

**Issue by mgtroyas** [86Box/86Box#3662] opened 2023-08-30 18:41 UTC
I use a real CRT monitor connected to my "modern" computer (via a DisplayPort to VGA adapter) to run emulators and classic games. When running 86box full screen on it, would be great having the monitor switching to the resolution the content is being emulated, in order to get an 1:1 pixel mapping, instead of maintaining the current resolution and letting 86box stretch the image to fill the screen or do letterboxing, which is the case as of now.

As an example, DosBox allows this automatic resolution change by choosing "fullresolution=original" on the conf file. RetroArch does something similar via [SwitchRes](https://docs.libretro.com/guides/crtswitchres/). I see on my CRT both Vulkan and OpenGL video renderers use a real dedicated fullscreen mode, so I think they could be good candidates.

**Comment by OBattler** [comment] 2023-09-01 05:07
Closing as a duplicate of #395.

**Closed by OBattler** 2023-09-01 05:07 UTC
Labels: feature
