### ISSUE TITLE
Microsoft Symbolic Debugging Utility (Windows Version 2.00) from Windows 1.03 SDK spews memory garbage to screen and then crashes when using help command

### ISSUE THREAD

**Issue by starfrost013** [86Box/86Box#3812] opened 2023-11-07 23:13 UTC
### What happened?

I am attempting to debug a debug Windows 1.03 kernel in slowboot configuration on 86box 4.0.2.5188 using the provided SDK debug tool, the Microsoft Symbolic Debugging Utility (version "Windows Version 2.00"), connected to a second MDA monitor using the `symdeb -e.` command line. It works until the "?" command is entered (to view the available debugging commands), and then enter is pressed to view more commands. When this happens, garbage from memory (including recently run symdeb instructions) is printed instead of the intended second page of help information. Sometimes, SYMDEB freezes, but sometimes it can recover and continue to be used (although I don't know if it corrupts memory doing so). This didn't happen on 86Box 4.0 early builds, but I don't remember the exact build it worked on.

Initial help command:
![image](https://github.com/86Box/86Box/assets/12046237/dc4af477-7d2e-4b4f-a441-8e58c7ba70a9)

After enter is pressed:
![image](https://github.com/86Box/86Box/assets/12046237/f986e948-d89e-4ce9-97aa-5a0676f9f987)

Command-line information:
`symdeb gdi.sym kernel.sym user.sym kernel.exe`

### Configuration file

```ini
[EGA]
memory = 256
monitor_type = 9

[General]
vid_renderer = qt_software

[Machine]
machine = acc386
cpu_family = i386dx
cpu_speed = 16000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
mem_size = 1024

[Video]
gfxcard = ega
gfxcard_2 = mda

[Input devices]
mouse_type = logibus

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = xtide_at_386
cassette_mode = load

[Hard disks]
hdd_01_parameters = 26, 8, 306, 0, ide
hdd_01_fn = C:/Users/mario/emulation/86Box/Manager/dos3.2.vhd
hdd_01_speed = ramdisk
hdd_02_parameters = 26, 8, 306, 0, ide
hdd_02_fn = C:/Users/mario/emulation/86Box/Manager/mdos4.vhd
hdd_02_speed = ramdisk
hdd_01_vhd_blocksize = 4096
hdd_01_ide_channel = 0:0
hdd_02_ide_channel = 0:1

[Floppy and CD-ROM drives]
fdd_02_type = 35_2dd
fdd_01_image_history_01 = E:/Users/Cosmo/Archive/Microsoft/Source Code/dos/MSDOS2-original/Disk03.img
fdd_01_fn = E:/Users/Cosmo/Archive/Microsoft/Windows SDKs/Microsoft Windows 1.x/1.03/Disk 1 - Utilities Disk 1 (050-150-078).img
fdd_01_writeprot = 1
fdd_01_image_history_02 = C:/Users/mario/ModernPersonality/research/mdos4/tools/mdos4fix.IMA
fdd_01_image_history_03 = C:/Users/mario/ModernPersonality/research/mdos4/tools/doscals.IMA
fdd_01_image_history_04 = C:/Users/mario/ModernPersonality/research/mdos4/tools/choice.IMA
```

### Operating system

Windows 11 23H2 (2022 Update Moment 4) (OS Build 22621.2506)

### CPU

AMD Ryzen 5 5600

### 86Box version

4.0.2, build 5188

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment] 2023-11-08 05:09
Can you upload the VM so I can attempt to reproduce this?

**Comment by starfrost013** [comment] 2023-11-08 15:27
[dos3.2 for win16 debug.zip](https://github.com/86Box/86Box/files/13298468/dos3.2.for.win16.debug.zip)

you'll probably have to change where the cfg points to the hard drives ofc

**Comment by TC1995** [comment] 2023-11-16 12:20
this actually happens on builds as early as 3.7.1.

**Comment by OBattler** [comment] 2024-01-14 15:14
Closing this because it turned out the reporter may have been using a different version of the utility back then.

**Closed by OBattler** 2024-01-14 15:14 UTC
Labels: bug
