### ISSUE TITLE
Windows XP SP2 Setup crashes on "Registering components" on Pentium II Overdrive

### ISSUE THREAD

**Issue by explorerdotexe** [86Box/86Box#1192] opened 2020-12-23 15:28 UTC
**Describe the bug**
86box program window closes mid-way through Windows XP Setup registering components.

**To Reproduce**
1. Setup a Socket 8 virtual machine with a Gigabyte GA-686NX motherboard and a 333mhz Pentium II Overdrive with 512mb of RAM.
2. Start the virtual machine and boot into your Windows XP SP2 Installation medium.
3. Install Windows XP SP2 as you normally would.

**Expected behavior**
The setup finishes normally and the virtual machine boots into Windows XP.

**Additional Files**
[nvr](https://drive.google.com/drive/folders/1z5CYNGCUCrDkDY1PDJ1COzjR7ueu72LT?usp=sharing)
[86box.cfg](https://drive.google.com/file/d/12t70qQtr_c-QwQ7pSQSC-Hjxs_aUrJeR/view?usp=sharing)

**Screenshots**
Portion of Windows XP Setup it crashes on.
![vlcsnap-2020-12-23-15h48m36s137](https://user-images.githubusercontent.com/74715154/103013062-d3480980-453c-11eb-869d-6c854cb68e13.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home version 20H2
 - 86Box version: v3.0 [da7878ce, build 2712]
 - Build type: Regular

**Comment by qeeg** [comment] 2020-12-23 20:53
What video card are you using? XP shouldn't have such a low color depth at that point in setup on most cards...

**Comment by explorerdotexe** [comment] 2020-12-23 21:00
> 
> 
> What video card are you using? XP shouldn't have such a low color depth at that point in setup on most cards...

The standard [ISA] VGA option.

**Comment by qeeg** [comment] 2020-12-23 21:15
That's... not what you're supposed to use for Windows XP. Try the S3 ViRGE/DX, Voodoo Banshee, or Voodoo 3.

**Comment by explorerdotexe** [comment] 2020-12-23 21:17
> 
> 
> That's... not what you're supposed to use for Windows XP. Try the S3 ViRGE/DX, Voodoo Banshee, or Voodoo 3.

Well it worked in other installs so i'm not sure why it wouldn't work here, but i'll try it, also just because it probably looks a whole lot better.

**Comment by explorerdotexe** [comment] 2020-12-23 22:19
Still didn't work, but thank you for the graphics advice.

**Comment by explorerdotexe** [comment] 2020-12-26 17:47
Another thing to add, it seems that Windows 2000 setup doesn't crash on "Registering components" like XP does. The only difference between the two is the type of mouse used, 2000 having setup a Logitech serial mouse, and XP instead having a PS/2 standard mouse, which i don't think makes much of a difference when it registers components. Do keep in mind that the 2000 version i installed is RTM, so things could be different on SP1-4.

**Comment by OBattler** [comment] 2020-12-28 04:47
Going to tag this as v5.0 as that's going to be the CPU-focused version.

**Comment by xerz-one** [comment] 2022-11-05 18:03
Don't know if this issue is directly related, but OS/2 Warp 4.52 fails as well on the Gigabyte GA-686NX, as the installer reboots when trying to load the GUI, and a finished install will get into the desktop but crashes the whole emulator in the process (enabling a Sound Blaster 16 just makes OS/2 hang during boot, though, which does not happen with other CPU or motherboard choices). Surprisingly, no issues on Rhapsody DR2. Most noticeably, *the issue is fixed when switching motherboards*, as the second one I have tried (Intel VS440FX) works fine. CPU clock and RAM amount seem irrelevant. Using the Flatpak build of 86Box 3.7.1.

**Comment by OBattler** [comment] 2023-02-21 18:28
I think this is fixed now - the same old recompiler fatal as the Windows 2000 update unpacking. Reported to affect Windows XP Setup on Pentium II already by Foxlet as far back as 2021.

**Closed by OBattler** 2023-02-21 18:28 UTC
Labels: bug
