### ISSUE TITLE
Right shift key

### ISSUE THREAD

**Issue by ericdestefano** [86Box/86Box#3169] opened 2023-03-03 12:39 UTC
Hello, 

I saw an earlier report that the right shift was not working, but was corrected back in August or so.  Version 3.11 on Windows appears to have the same issue.

**Comment by OBattler** [comment] 2023-06-26 23:47
See if the latest build of 86Box still has the same problem.

**Comment by ericdestefano** [comment] 2023-06-30 05:21
I can confirm in build b4673 the issue is still present (Windows x64)

**Comment by OBattler** [comment] 2023-08-09 04:36
I can not confirm this at all. I literally just tested and right shift is working just fine.

**Comment by OBattler** [comment] 2023-08-15 00:30
I'm closing this because I can't reproduce this at all, which indicates a problem with the user's host system rather than with 86Box.

**Closed by OBattler** 2023-08-15 00:30 UTC
