### ISSUE TITLE
Add ATI 3D Rage Cards

### ISSUE THREAD

**Issue by TheDell1998** [86Box/86Box#3149] opened 2023-03-01 06:17 UTC
Please add the following ATI 3D Rage Cards in 86Box including:
ATI 3D RAGE PCI
ATI 3D RAGE II PCI
ATI 3D RAGE II+DVD PCI
ATI 3D RAGE PRO PCI
ATI 3D RAGE PRO AGP
ATI 3D RAGE PRO AGP 2X
ATI Rage IIC PCI
ATI Rage IIC PCI
ATI Rage LT Pro AGP
ATI Rage Pro Turbo AGP
ATI Rage 128 VR
ATI Rage 128 GL
ATI Rage 128 Pro
ATI Rage 128 Ultra
ATI Rage Fury MAXX
Because ATI Mach64GX and ATI Mach64VT2 video cards doesn't support 3D Acceleration at all.
Thank you.

**Comment by JimboMumbo** [comment] 2023-03-01 06:20
Sorry pal, both issues already exists but it was now in discussions.

**Comment by OBattler** [comment] 2023-03-01 06:33
Closing for duplicate of an existing discussion.

**Closed by OBattler** 2023-03-01 06:33 UTC
Labels: feature
