### ISSUE TITLE
[ENHANCEMENT] Disable ISA RTC module on machines with on-board RTC to prevent 86Box crash

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#1929] opened 2021-12-11 22:32 UTC
This feature enhancement is in response to this [thread](https://github.com/86Box/86Box/issues/1928) that has been recently been marked NOTABUG.

On 808x and early 80286-based machines, they had to rely on a real time clock (ETC) ISA card in order to keep the date and time after a soft or hard reboot. On later machines that have a CMOS setup, the on-board RTC is included.

What I would like to suggest is to disable (gray-out) the ISA RTC module on machines that have a on-board RTC and this is to properly prevent 86Box from crashing. There is no need to have a emulated ISA RTC card on a machine that has a on-board RTC.

Thank you for your time. :)

**Comment by OBattler** [comment] 2021-12-12 01:08
Added this to the UI rewrite milestone, since I agree with the proposal (in fact, I was the one who originally proposed it).

**Comment by ppgrainbow** [comment] 2021-12-12 01:21
> Added this to the UI rewrite milestone, since I agree with the proposal (in fact, I was the one who originally proposed it).

Thank you for the heads up! I can't wait to see it get added in the UI rewrite! :)

**Comment by dhrdlicka** [comment] 2021-12-13 02:05
Duplicate of #1928.

**Closed by dhrdlicka** 2021-12-13 02:05 UTC
Labels: duplicate
