### ISSUE TITLE
Once Upon a Forest Crash

### ISSUE THREAD

**Issue by ualaa1** [86Box/86Box#1961] opened 2021-12-24 01:38 UTC
**Describe the bug**
The game crashes into DOS and gives error after clicking an area twice. Could potentially be me using a corrupt copy?

**To Reproduce**
Start a new game. Go outside the house once the cutscene finishes. While outside, wait for cutscene to finish. Click once on small hole on bottom left of the screen. Wait for cutscene. Cursor should now show a different sign at the hole. Click on it again. Game crashes.

**Expected behavior**
The game should go to another area instead of crashing.

**Screenshots**
Error message
![20211223-103725-361](https://user-images.githubusercontent.com/68984176/147305282-c7878e19-e27d-4773-b128-99a50a3d88dd.png)

Crash video

https://user-images.githubusercontent.com/68984176/147305415-f4ecdc80-df49-4ab4-8ebb-d804fbe4872c.mp4 (Part 1)
https://user-images.githubusercontent.com/68984176/147305316-22384491-4c38-4d44-ba60-426269e7b929.mp4 (Part 2 and crash)

**Desktop (please complete the following information):**
Windows 10 v 3.0

**Additional context**

Installed the ISO version of the game. Ran via OUAF.bat

**Comment by ualaa1** [comment] 2021-12-24 02:02
It seems game is not installing fully from CD even with Full Installation selected. Attempting to put all the CD files into the installed directory manually seems to result in the game not recognizing sound cards?
I'll be testing with a floppy version

**Comment by OBattler** [comment] 2023-08-21 05:50
Closing this for being basically a duplicate of this previous issue: https://github.com/86Box/86Box/issues/1942 .

**Closed by OBattler** 2023-08-21 05:50 UTC
Labels: bug
