### ISSUE TITLE
Ensoniq AudioPCI MS-DOS Prompt MIDI/Wave/OPL output works for a short amount of time and then suddenly stops

### ISSUE THREAD

**Issue by Ompronce** [86Box/86Box#1612] opened 2021-08-19 06:38 UTC
**Describe the bug**
On the Ensoniq AudioPCI sound card, when the DOS Box (MS-DOS Prompt) MIDI out (both the internal synth and external MIDI port) is used, MIDI data is only transmitted for a short amount of time, and it then stops suddenly with no explanation. Once the MIDI application is reopened in a new DOS Box session, MIDI data is transmitted until the aforementioned bug recurs. (Edit: After further testing, a similar issue occurs with Epic Pinball where the sound plays for a while and it hangs on the last played sound until the application is closed. The OPL emulation has the same problem as the MIDI output in addition to this).

**To Reproduce**
1. Open the Device Manager, select "Sound, video and game controllers".
2. Select the name of the device that corresponds to the Ensoniq AudioPCI (the drivers I tested this with use "Sound Blaster PCI 128" as the device name).
3.  Select "Properties", and go to the "Settings" tab.
4.  Select either "Internal Synthesizer" or "External MIDI port".
5. Select "OK" on both the device settings dialog box and the Device Manager.
6.  Play any DOS game that can run in Windows 9x and set the game to use either General MIDI (use internal synth or external MIDI port,) or MT-32 (use external MIDI port and MT-32 or CM-32L emulation for proper Sysex data receipt). As mentioned above, the hanging with wave sounds and the OPL sound suddenly stopping can also be reproduced similarly.
7.  The aforementioned bug should appear after some time (in Doom 2 v1.9 it appeared after 40 seconds, the amount of time it takes to appear in other games may vary but it will appear).

**Expected behavior**
The MIDI data being transmitted normally without stopping suddenly (both to the internal synth and the external MIDI device).

**Screenshots**
![20210819-060306-099](https://user-images.githubusercontent.com/88358700/130016295-02aff92a-5a1c-4090-879a-4d15009b9667.png)
![20210819-060255-931](https://user-images.githubusercontent.com/88358700/130016316-1b35eee3-4d44-49b2-9f70-ae0e98851e5d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 version 2004
 - 86Box version: v3.0 build 3114
 - Build type: Regular

**Additional context**
Windows-based MIDI applications (both the internal synth and the external MIDI port) appear to work properly, I tested CANYON.MID and it played with no problems.

VXD drivers for the Ensoniq AudioPCI were used. (and were obtained from this installation CD dated Sep. 02 1999 - https://archive.org/download/soundblasterpci128softwareiso/Sound%20Blaster%20PCI128%20Software%20ISO.zip/Sound%20Blaster%20PCI128%20Software.ISO)

MIDI playback from the internal synth in MS-DOS mode appears to work correctly as well.

Using an external MIDI device in MS-DOS mode is not possible, as the external MIDI device passthrough is only available in a Windows 9x DOS Box.

The system configuration used was an Intel Advanced/ZP with a 75MHz Pentium processor, 8MB of RAM, a 545MB HDD, a PCI Cirrus Logic GD-5430 1MB graphics card, a 2x CD-ROM, an Ensoniq AudioPCI sound card, and Windows 95 RTM was used as the operating system.

**Comment by OBattler** [comment] 2021-09-02 13:16
I think this has to do withour bad NMI implementation, NMI's are supposed to be edge-triggered, but for some reason, they are level-triggered on 86Box. I need to fix that.

**Comment by OBattler** [comment] 2021-09-02 13:24
See if the latest build (that's, as I speak, still being compiled) fixes this.

**Comment by Ompronce** [comment] 2021-09-02 16:04
> See if the latest build (that's, as I speak, still being compiled) fixes this.

The latest build does not fix this, although it does appear to fix a separate issue where restarting (hard or CTRL+ALT+DEL) after loading the DOS driver SBINIT.COM causes the BIOS to not make the "OK" POST beep and load Windows (it hangs there and you have to quit and reopen 86Box to resume normal operations).

**Comment by OBattler** [comment] 2021-09-02 20:04
Then I have no idea what causes that.

**Comment by Ompronce** [comment] 2021-09-02 22:06
> Then I have no idea what causes that.

I suspect it could be the NMI requiring edge-triggered interrupts (as evidenced by the other bug no longer appearing). I have tried different drivers from early 1999-c. 2002 and the problems with legacy SB/MPU I/O in Windows 9x occur still. In version 2.07, the problems do not occur. Also, when the issues occur, the running DOS application becomes laggy (seen in Mortal Kombat 1) and sometimes causes the VM to lock up (Sierra/Dynamix intelligent mode games like Space Quest 3 and Stellar 7 and EA games like Budokan and Ski or Die), (Sierra /Dynamix intelligent MPU games can work with the AudioPCI which emulates a standalone MPU-401 by sending ACK bytes in response to intelligent mode commands, but does not actually carry out the commands, which is real behavior).

**Comment by OBattler** [comment] 2021-09-02 22:49
The lock-up indicates that the emulated CPU is constantly executing the same block of code, without end. This could indeed be a NMI problem. I need to read up on how NMI's work on real hardware.

Also, can you upload the drivers so I can test them?

**Comment by Ompronce** [comment] 2021-09-02 23:26
> The lock-up indicates that the emulated CPU is constantly executing the same block of code, without end. This could indeed be a NMI problem. I need to read up on how NMI's work on real hardware.
> 
> Also, can you upload the drivers so I can test them?
> 
> Edit:
> 
> > In version 2.07, the problems do not occur.
> 
> Then, can you please upload the hard disk image, nvr folder, and 86box.cfg, so I can bisect and see what build this bug was introduced in?

I have uploaded the hard disk image, nvr folder and 86box.cfg here: https://drive.google.com/file/d/1B72SeWkeUKyMOFtM9FQ_rj97C9TSjpWu/view?usp=sharing

Links to the driver CDs I tested are as follows:
https://archive.org/download/sound-blaster-pci-64-v-driver/Sound%20Blaster%20PCI%2064V%20driver.iso (oldest)
https://archive.org/download/soundblasterpci128ct4750iso/Sound%20Blaster%20PCI128%20CT4750%20ISO.zip/Sound%20Blaster%20PCI128%20CT4750.ISO (newest)
https://archive.org/download/soundblasterpci128softwareiso/Sound%20Blaster%20PCI128%20Software%20ISO.zip/Sound%20Blaster%20PCI128%20Software.ISO (this one I mainly use for testing and is the one installed in the hard disk image)

**Comment by OBattler** [comment] 2021-09-03 19:17
I have just finished overhauling the ES1371 code. Attached is my local 86Box compile with said overhauled code - please test it and see if the problem is now gone.
[86Box_overhauled_es1371.zip](https://github.com/86Box/86Box/files/7108075/86Box_overhauled_es1371.zip)

**Comment by Ompronce** [comment] 2021-09-03 19:33
> I have just finished overhauling the ES1371 code. Attached is my local 86Box compile with said overhauled code - please test it and see if the problem is now gone.
> [86Box_overhauled_es1371.zip](https://github.com/86Box/86Box/files/7108075/86Box_overhauled_es1371.zip)

Unfortunately, the problem still occurs as before.

**Comment by OBattler** [comment] 2021-09-03 21:42
I have now traced the problem back to build 2103. Now I just need to figure out which of the changes in that build introduced this bug.

**Comment by OBattler** [comment] 2021-09-05 15:36
After two more days of debugging this, I now know that the bug was introduced when we implemented SMM (System Management Mode). From what it looks like to me, it's a bug on the Intel Advanced/ZP BIOS that was masked in v2.07 because SMM was not implemented, and implementing SMM brought it to light. Changing to a different machine should work, for example, I get no hangs on the ASUS P/I-P54TP4XE.

As such, I'm closing this, since it's nothing I can fix.

**Closed by OBattler** 2021-09-05 15:36 UTC
Labels: bug

**Comment by Ompronce** [comment] 2021-09-06 05:47
> After two more days of debugging this, I now know that the bug was introduced when we implemented SMM (System Management Mode). From what it looks like to me, it's a bug on the Intel Advanced/ZP BIOS that was masked in v2.07 because SMM was not implemented, and implementing SMM brought it to light. Changing to a different machine should work, for example, I get no hangs on the ASUS P/I-P54TP4XE.
> 
> As such, I'm closing this, since it's nothing I can fix.

I changed the machine to the ASUS P/I-P55T2P4, reinstalled Windows 95, and no errors have occurred so far. Is an NMI code rewrite to allow for the NMIs to use edge-triggered interrupts instead of level-triggered interrupts planned?
