### ISSUE TITLE
Voodoo Graphics recompiler bugged in x64 builds

### ISSUE THREAD

**Issue by Korkman** [86Box/86Box#2923] opened 2022-12-01 14:12 UTC
**Problem**
The Voodoo Graphics recompiler is not stable in x64 builds. It causes heavy visual glitches in some scenarios, examples seen in [#1137](https://github.com/86Box/86Box/issues/1137#issuecomment-1303671786) and [#2891](https://github.com/86Box/86Box/issues/2891#issuecomment-1329397924)

**Workaround**
A workaround is to use the 32 bit x86 build instead.

**Reproduction**
Easiest reproduction is with 3DMark 99 Max and a Voodoo3 2000 PCI, whose first test will show the corruption immediately.

![grafik](https://user-images.githubusercontent.com/3186931/204340164-bd9634a7-241b-4fd7-ac44-1fd576ad6c8d.png)

**Comment by katho3d** [comment] 2024-02-13 11:06
Some of the issues like https://github.com/86Box/86Box/issues/3304 are not related to the 64bit recompiler bug, because it happens with 32bit version too. Could you please reopen this one. Thanks!

**Comment by TC1995** [comment] 2024-02-27 14:56
Can't reproduce on my end as of the latest build of 86box.

**Comment by OBattler** [comment] 2024-02-27 16:16
It appears to somehow be fixed now, so I'm closing this. It can be re-opened if it re-appears.

**Comment by OBattler** [comment] 2024-03-01 06:46
It now appears to be actually fixed, at least from my and Dizzy's test. Waiting for further tests to confirm it.

**Comment by Korkman** [comment] 2024-03-01 08:48
Can confirm. Build 5555 is bugged, 5587 is fine.

**Comment by OBattler** [comment] 2024-03-01 11:40
Then this can indeed be closed.

**Closed by OBattler** 2024-03-01 11:40 UTC
Labels: bug
