### ISSUE TITLE
Graphics artifacts on Qt render

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#2736] opened 2022-10-24 16:31 UTC
**Describe the bug**
1. When starting any 8088 machine with a CGA video card on a Qt (OpenGL) renderer, a horizontal bar flickers at the top of the screen in 86Box windowed and full screen modes. This bug appeared in build 4082 and persists until the last build. In build 4081 everything is fine.

**Screenshots**
![2022-10-24_173727](https://user-images.githubusercontent.com/58270614/197575798-d5c90ed7-a99e-4db2-9e67-67d94ca14d3a.png)

2. When running 8088 machines IBM PC (1981), IBM PC (1982), IBM XT (1982), IBM XT (1986), AMI XT clone with a CGA video card on a Qt (OpenGL) renderer, immediately in full screen mode (with the 86Box parameter .exe -f) a white screen appears, and the image against it shifts to the left of the screen. This bug appeared in build 3889 and persists until the latest build. In build 3888 everything is fine.

**Screenshots**
![2022-10-24_183721](https://user-images.githubusercontent.com/58270614/197575741-9213a15c-333a-4df8-8b9d-c61ec1a97bc3.png)

3. When starting any machine on Qt (OpenGL), OpenGL (3.0 Core) renderers, a white screen appears for 3 seconds. This bug appeared in build 4045 and persists until the last build. In build 4044 everything is fine.

**Screenshots**
![2022-10-24_181720](https://user-images.githubusercontent.com/58270614/197575766-b822b7bd-f6b7-4c61-8de3-acda8f3592a1.png)

**Expected behavior**
Horizontal flickering bar in windowed and full screen modes, white screen should be absent in 86Box.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 v21H2
 - 86Box v3.8.0 x64 Build 4122
 - Build type: regular, old recompiler.

**Comment by OBattler** [comment] 2022-10-24 23:05
Except that 4082 didn't change anything that could have caused this. It literally only changed the Discord timer.

**Comment by Cacodemon345** [comment] 2022-10-26 10:17
I can't reproduce the 2nd issue.

Also the top bar flickering issue appears to happen on software renderer as well.

**Comment by maximus105** [comment] 2022-10-26 12:55
> I can't reproduce the 2nd issue.

It seems that the second problem was partially fixed in build 4125. In build 4145, the shifting image on the white screen background appears for 2 seconds and disappears. In build 4124, a shifting image on a white screen appeared and did not disappear.
Here is the config to reproduce the second problem. Start the machine immediately in full screen mode: with the -f option
[86box.zip](https://github.com/86Box/86Box/files/9869614/86box.zip)

**Comment by OBattler** [comment] 2022-10-30 16:16
The flickering (problem #1) is now fixed - I had to get rid of vid_blit_memtoscreen_8() and rework where the palette processing is done to solve that.

**Comment by OBattler** [comment] 2022-10-30 17:36
Now #2 is fixed as well. Only #3 remains, which I can confirm as well. But, that also exists on Win32, and always has - the blank screen just used to black instead of white.

**Comment by OBattler** [comment] 2022-10-30 19:41
I think for #3, it's now improved as much as it can be. Therefore, I'm closing this.

**Closed by OBattler** 2022-10-30 19:41 UTC
Labels: bug

**Comment by maximus105** [comment] 2022-11-01 14:16
Problem №1 is still present. Tested in build 4205.

**Comment by OBattler** [comment] 2022-11-01 14:31
No, it's not. I can't reproduce it myself anymore.

**Comment by OBattler** [comment] 2022-11-02 05:35
OK, I was told how to reproduce it and another person reproduce it. I do have a tentative fix in my mind that I'm going to try tomorrow.

**Comment by maximus105** [comment] 2022-11-05 08:07
> OK, I was told how to reproduce it and another person reproduce it. I do have a tentative fix in my mind that I'm going to try tomorrow.

**Comment by maximus105** [comment] 2022-11-09 06:43
Is it possible to undo the fix that caused issue №1? That is, to remove the flickering of the horizontal bar on CGA video cards?

**Comment by maximus105** [comment] 2022-11-25 07:21
Issue №1 is still present in latest builds of 86Box. Is it possible to undo the fix that caused issue №1? That is, to remove the flickering of the horizontal strip on CGA video cards?

**Comment by OBattler** [comment] 2022-11-25 15:51
I have a proper fix for that on my queue, as I said. I've just been busy fixing other bugs.

**Comment by maximus105** [comment] 2023-02-03 16:06
Issue №1 is still present in recent builds of 86Box. Could you fix this bug please?

**Comment by OBattler** [comment] 2023-02-03 22:02
Final warning - stop pressuring me. I'm doing this for free in my spare time. I told you I'm going to fix this bug but there's no ETA. Eppearing here every month and half begging for a fix isn't going to bring it any closer.
