### ISSUE TITLE
[linux] support older libc

### ISSUE THREAD

**Issue by arrowgent** [86Box/86Box#2159] opened 2022-02-21 17:57 UTC
**Describe the bug**

```
Libraries used to compile this x86_64 build of 86Box:
       libc6 2.31-13+deb11u2
```
etc

**To Reproduce**
libc < 2.31 will not run these appimages

**Expected behavior**

libc should be built against the CI for ubuntu 18.04 until this version is no longer supported

ubuntu 18.04 libc v 2.27 = April, 2023
ubuntu 20.04 libc v 2.31 = April, 2025

debian Stretch v 2.24 = June 30, 2022
debian Buster v 2.28 = August, 2022
debian Bullseye v 2.31

[https://endoflife.software/operating-systems/linux/debian](https://steamcommunity.com/linkfilter/?url=https://endoflife.software/operating-systems/linux/debian)

[https://endoflife.software/operating-systems/linux/ubuntu](https://steamcommunity.com/linkfilter/?url=https://endoflife.software/operating-systems/linux/ubuntu)

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - 86Box version: 86Box-Linux-x86_64-b3600 & 3602
 - Build information: x86_64

**Comment by richardg867** [comment] 2022-10-24 22:01
Our packaging solution (appimage-builder) produces AppImages containing a fallback libc that is loaded automatically if the host libc is too old. Whatever issue you're having (if any) is certainly not related to the host libc version. The Debian Bullseye target we use was carefully selected as a balance between availability of CMake/Qt/etc. features and compatibility with older LTS distributions.

I have tried the 3.2.1 and 3.7 stable binaries as well as the latest Jenkins build on a stock Ubuntu 18.04 x86_64 live image, and all of them start up just fine. Therefore, closing as cannot reproduce.

![image](https://user-images.githubusercontent.com/540874/197637218-d428787e-5cbc-4c2e-b0ca-883c647f9681.png)

**Closed by richardg867** 2022-10-24 22:01 UTC
Labels: bug
