### ISSUE TITLE
86Box can't detect roms files, even if files are put in.

### ISSUE THREAD

**Issue by randomsomeone69** [86Box/86Box#2335] opened 2022-05-09 19:47 UTC
**Describe the bug**
When changing or starting a virtual machine, a error shows up saying that no roms files are present 

**To Reproduce**
1. Extract the 'roms' package
2. Start WinBox for 86Box
3.Secect a virtual machine and start it up

**Expected behavior**
It should start the virtual machine.

**Desktop (please complete the following information):**
 - OS: Windows 7 (SP1)
 - 86Box version: any
 - Build information: any

**Additional context**
I want to start an upgrading experience but I can't because 86Box says that no roms are present. I've already started an issue weeks ago, but the person thinks that I've putted the roms in the wrong folder. (details: https://github.com/86Box/86Box/issues/2280) I should say that the machine has an Intel Core 2 processor. That's all.  
[roms output.log](https://github.com/86Box/86Box/files/8654872/roms.output.log)

**Comment by dhrdlicka** [comment] 2022-05-09 20:05
Duplicate of #2280

**Closed by dhrdlicka** 2022-05-09 20:05 UTC
Labels: duplicate
