### ISSUE TITLE
ELKS issue

### ISSUE THREAD

**Issue by jv84** [86Box/86Box#2160] opened 2022-02-22 08:24 UTC
**Describe the bug**

I'm simply forwarding this link. It's relevant.
[https://github.com/sarah-walker-pcem/pcem/issues/121](url)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - 86Box version: [e.g. v3.00 build 3333; saying "Latest from Jenkins" isn't helpful]
 - Build information: [i.e. new/old dynarec, architecture and build type]

**Additional context**
Add any other context about the problem here. If you are using an Optimized build, make sure to try the regular build too before filing a bug report!

The context is fully described in the issue which I opened. Check the link.

**Comment by daviunic** [comment] 2022-02-22 08:26
We would appreciate it if you could fill out the bug report with all the relevant information, it makes solving problems easier.

**Comment by jv84** [comment] 2022-02-22 08:28
Read the link. There's nothing to add.

**Comment by jv84** [comment] 2022-02-22 09:26
> These new images won't finish booting on PCem/86Box.
> "xms: A20 was off" is the last message.
> 
> [https://github.com/jbruchon/elks/releases/tag/v0.5.0]

**Comment by jv84** [comment] 2022-02-22 09:27
And by the way, I'm going berserk if I have to fill out idiotic templates. :)

**Comment by dhrdlicka** [comment] 2022-02-22 11:01
Works just fine on my end:
![image](https://user-images.githubusercontent.com/13226155/155119317-0bb0daed-e165-4bc9-bd73-ecaa8ec03cac.png)

**Comment by jv84** [comment] 2022-02-22 11:54
What settings?

**Comment by OBattler** [comment] 2022-02-22 12:20
What emulated machine are you having the problem on? This is very important because of differences in A20 handling. Some machines (mostly earlier ones) only handle it through the keyboard controller, later machines add port 92h (originally introduced on the IBM PS/1 and PS/2 series) but not all of them to, and some machines even add a proprietary method of handling it on the chipset.

**Comment by OBattler** [comment] 2022-02-22 14:47
The default configuration is a 1981 IBM PC with 64 kB of RAM and a 8088 @ 4.77 MHz. While ELKS can be compiled for such a platform, the build you are using is not compiled for it, as evidence by the fact it tries to initialize XMS and A20, which are not a thing on 808x.

You have to either obtain (or compile yourself) a build of ELKS for 808x or configure 86Box to a machine with at least a 286 and more than 1 MB of RAM.

**Comment by waltje** [comment] 2022-02-22 16:46
> And by the way, I'm going berserk if I have to fill out idiotic templates. :)
As my teacher used to tell us:
"The quality of the question determines the quality of the answer."
In your case... don't expect anything :P
--FredMessage ID: ***@***.***>

**Comment by telanus** [comment] 2022-02-22 18:52
Found another error

**Describe the bug**
ELKS not seeing Floppy on an IBM AT

**To Reproduce**
Steps to reproduce the behavior:
My config:
[Machine]
machine = ibmat
cpu_family = 286
cpu_speed = 6000000
cpu_multi = 1
cpu_use_dynarec = 0
time_sync = local
mem_size = 4096

[Video]
gfxcard = ega

**Expected behavior**
To boot without errors

**Screenshots**
Minix flavour:

![20220222-204754-399399](https://user-images.githubusercontent.com/19357986/155198823-5abfae6e-53f4-42fb-bd9c-0fc8d47ff81a.png)

Fat Flavour:

![20220222-205145-136136](https://user-images.githubusercontent.com/19357986/155199287-c89667ad-c5e2-406b-84ec-4fc6bbc11f38.png)


**Desktop (please complete the following information):**
 - OS: Kubuntu 20.04
 - 86Box version: 3.3 Build 3622
 - Build information: x64 Build with gcc 11

**Additional context**
Was using the 360kb version

**Comment by jriwanek** [comment] 2022-02-22 18:55
> > What emulated machine are you having the problem on? This is very important because of differences in A20 handling. Some machines (mostly earlier ones) only handle it through the keyboard controller, later machines add port 92h (originally introduced on the IBM PS/1 and PS/2 series) but not all of them to, and some machines even add a proprietary method of handling it on the chipset.
> 
> I'm using this AppImage and I haven't changed any machine settings.
> 
> [https://github.com/86Box/86Box/releases/download/v3.2.1/86Box-Linux-x86_64-b3602.AppImage](url)

If you've not changed any machine settings then you'd have been using an IBM PC 5150 with 64k of ram, not an AT with 640k, thank you *finally* for providing a machine config however.

We however shouldn't have to fight through misleading claims, or ask for actual info just to be told that you've already provided everything we need when you havn't.

**Comment by jv84** [comment] 2022-02-23 20:04
I don't know what happened. Now ELKS won't boot at all and those 360k disk images resized to 160k ?!?!?!?!

**Comment by dhrdlicka** [comment] 2022-02-23 20:29
We don't know what happened either.

Given that your original problem has been determined to be an ELKS bug, as confirmed by [its developers](https://github.com/jbruchon/elks/issues/1168#issuecomment-1046257920), I will now close this issue. If you run into any other separate problems, open a new separate issue.

**Closed by dhrdlicka** 2022-02-23 20:29 UTC
Labels: bug

**Comment by jv84** [comment] 2022-02-23 20:38
> We don't know what happened either.
> 
> Given that your original problem has been determined to be an ELKS bug, as confirmed by [its developers](https://github.com/jbruchon/elks/issues/1168#issuecomment-1046257920), I will now close this issue. If you run into any other separate problems, open a new separate issue.

Calling it a bug is misleading. 286 is a new requirement.
