### ISSUE TITLE
Add a volume control

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#666] opened 2020-04-02 10:57 UTC
Please add to 86Box the ability to adjust the sound volume (not only increase, but also decrease the volume). For example, PC Speaker volume is too high. Please add to 86Box the ability to adjust the sound volume (increase and decrease) for different sources. For example, for PС Speaker, Sound Blaster, Midi, etc. (as done in DOSBox SVN-Daum). In different DOS games, the volume of these sound sources is different, and it would be very convenient to adjust the sound volume for different sources.
And more questions:
1. Why the 4: 3 aspect is not saved in the https://ci.86box.net builds in full screen mode (the image is stretched and shifted to the right). Is there any way to fix this?
2. In which direction will 86Box move? What are you planning to add in future versions?
3. Will x64 version 86Box?
4. Will hardware virtualization be implemented?
5. Will new accessories be added? For example, Pentium 3, Athlon XP, Riva TNT2 Pro, GeForce 256, GeForce 3 Ti, GeForce 4 Ti.

**Comment by dhrdlicka** [comment] 2020-04-02 12:06
You can use the operating system's volume mixer functionality for this. I am not sure if any other emulators/virtualizers offer this option anyway, but we will look into this.

Regarding your other questions:
1. Sounds like #586 to me
2. I think @OBattler might answer this one
3. This already exists, we just don't offer it on Jenkins since the dynamic recompiler is way too buggy on x64.
4. That doesn't make much sense for an emulator project, and would probably end up breaking stuff due to the CPU running too fast, incompatible model specific registers, or similar issues. We had a discussion about this recently, and don't think it's worth it for now.
5. In the future, maybe? We can't even emulate a Pentium II at the full speed yet, anyway...

You might want to consider joining our [Discord server](https://discord.gg/QXK9XTv) if you have more questions!

**Comment by maximus105** [comment] 2020-04-02 15:59
An BUG was also discovered: when the "Configure" button is pressed in 86Box Manager screens, the settings window 86Box is constantly shifted to the upper left corner of the screen. Can I fix this somehow?
Can you also add the following functions to the 86Box?
1. Set custom resolution
2. Full screen on input grab
3. Vsync
4. Fullscreen mode (Borderless/Exclusive)
5. Dim display on lost focus
6. Scale filtering (Nearest/Linear)

**Comment by daviunic** [comment] 2020-04-02 16:03
You can adjust the volume in the windows sound mixer.

**Comment by dhrdlicka** [comment] 2020-04-02 17:27
> An BUG was also discovered: when the "Configure" button is pressed in 86Box Manager screens, the settings window 86Box is constantly shifted to the upper left corner of the screen. Can I fix this somehow?

Again, this was already reported as #586. Also, please create separate tickets for other feature requests.

**Comment by maximus105** [comment] 2020-04-15 06:22
Please add to 86Box the ability to adjust the sound volume (increase and decrease) for different sources. For example, for PС Speaker, Sound Blaster, Midi, etc. (as done in DOSBox SVN-Daum). In different DOS games, the volume of these sound sources is different, and it would be very convenient to adjust the sound volume for different sources.

**Comment by windows-95-420** [comment] 2020-04-16 01:06
> Please add to 86Box the ability to adjust the sound volume (increase and decrease) for different sources. For example, for PС Speaker, Sound Blaster, Midi, etc. (as done in DOSBox SVN-Daum). In different DOS games, the volume of these sound sources is different, and it would be very convenient to adjust the sound volume for different sources.

He said seperate ticket...

**Comment by OBattler** [comment] 2020-06-06 04:15
> Please add to 86Box the ability to adjust the sound volume (increase and decrease) for different sources.
I would have already done that if I knew how to do per-source volume control and if every emulated sound device actually used a different source, which they don't - they all use the same source, other than CD Audio and MIDI which use their own sources (though MIDI only when using FluidSynth or Munt, otherwise it just outputs MIDI commands directly to the host, so you'll need to use the host's volume control instead).
At one point, the sound code is indeed going to be rewritten, at which point I am going to most likely indeed add a separate source for each emulated device, but that won't happen in v2.10. I'm also going to need to figure out how to do per-source volume/gain control, the last time I tried, it didn't quite work as intended.

**Comment by maximus105** [comment] 2020-11-17 16:28
Is it possible at least to add the ability to reduce the sound volume in 86Box regardless of the Windows sound mixer. For example, in my Windows Sound Mixer, the volume is always set to 100%. And accordingly, the volume in desktop speakers and in all programs and games is set the same. However, the volume in the 86Box is too high. And it would be nice if it was possible to turn down the volume in the 86Box to match the same volume level as in all programs and games configured in Windows.

**Comment by daviunic** [comment] 2020-11-18 13:51
You can already turn down 86Box volume in the Windows sound mixer - every 86Box process shows up separately, and the volume level you set stays that way. Actual volume control in the emulator wouldn't hurt, but I don't see how using the sound mixer is not a  perfectly adequate workaround until then?

**Comment by OBattler** [comment] 2022-10-16 00:10
Cacodemon345 attempted a rewrite of the sound stack to multi-source and it ended up showing it's unfeasible as it slows down the emulator. As such, I'm closing it. Will reopen it if a way is found in the future.

**Closed by OBattler** 2022-10-16 00:10 UTC
Labels: feature
