### ISSUE TITLE
Croc does not detect AGP

### ISSUE THREAD

**Issue by ualaa1** [86Box/86Box#3302] opened 2023-05-04 03:53 UTC
**Describe the bug**
When starting the game and going into driver settings, does not detect voodoo 3500 AGP card and can only use software rendering. The settings warns that AGP is not detected. Trying to use Voodoo rendering causes game to go to black screen. 

**To Reproduce**

**Expected behavior**
Driver settings to show that AGP is detected

**Screenshots**
![Monitor_1_20230502-232634-746746](https://user-images.githubusercontent.com/68984176/236109232-1d7ffdff-4e1a-44d5-8e64-e55f0ff1ad1c.png)
Screenshot shows an AGP card exists, but the right side of screenshot, Croc doesnt detect it

**Desktop (please complete the following information):**
Windows 10 x64 3.11

**Additional context**
Config: 
[86box.zip](https://github.com/86Box/86Box/files/11392770/86box.zip)

**Comment by cold-brewed** [comment] 2023-06-11 21:07
Is there a particular reason you need to use AGP? Have you tried using a Voodoo 2 instead? You could combine it with the S3 Trio64 V2/DX (just as an example, that one works for me in 98SE with Voodoo 2).

The Voodoo 3 isn't required for good 3D. In fact, you won't even be able to run a system fast enough to take full advantage of a 3. 

You may want to also check your disc image. Another user has reported success with Croc after discovering the issues [were caused by a bad rip](https://github.com/86Box/86Box/issues/3185#issuecomment-1586191761).

**Comment by OBattler** [comment] 2023-08-15 00:28
Closing this because no further feedback from the user and it is likely to have been caused by a bad rip.

**Closed by OBattler** 2023-08-15 00:28 UTC
Labels: bug
