### ISSUE TITLE
Novell Netware 6.0 crashes on startup

### ISSUE THREAD

**Issue by admnd** [86Box/86Box#3379] opened 2023-06-01 12:25 UTC
**Describe the bug**
The first phase goes fine, DR DOS is installed on a small bootable hard drive partition then the Novell Netware kernel is loaded but the loader crashes immediately (general protection fault). QEmu does not exibit the issue. 

**To Reproduce**
1. Create a VM with the following specs: Slot 2/Gigabyte GA-6GXU or Supermicro S2DGE/512 MB of RAM/IDE HDD 10G/ATAPI CD-ROM/VGA/No sound/AMD PCNet Fast III  (the CPU has to be of Pentium-II/AMD K7 type at minimum).
2. In the BIOS, ensure the HDD Is properly configured and set the boot sequence as CDROM,C,A
3. Grab a Novell 6.0 CD and boot on it, there is one on archive.org
4. From the installer create a bootable partition as proposed (Caldera DR DOS 7.02 will be installed as a boot environment)
5. Once the machine reboots, loads the Netware kernel and tries to start it, the loader complains about a general protection fault : "LOADER-4.10-6: An exception interrupt occurred while loading the OS. Exception number D, (General Protection)"

Does not seems to be a graphic issue as the installer is still in text mode at this point.

**Expected behavior**
No crash :)

**Screenshots**
![image](https://github.com/86Box/86Box/assets/65023823/b148a8d3-c288-43ac-99a0-a03fdb333baf)

**Desktop (please complete the following information):**
 - OS: Gentoo Linux 
 - 86Box version: 3.11
 - Build information: old dynarec

**Additional context**
Tried with the master branch code (and the "new dynarec"). the crash still happens.
Perhaps the loader is trying to switch the CPU in some mode that the emulator does not like (?), unsure. 
Caldera DR-DOS 7.02 might have an issue under 86Box, still have to test with a MS-DOS 6.22 boot environment.
All Pentium II based machines exhibit the issue (untested with AMD K7 class machines as they are currently not supported)
A Google search returns... nothing! This is definitely not something that is supposed to happen :)

**Comment by OBattler** [comment] 2023-06-11 17:15
- cold-brewed: DR-DOS = Novell DOS. Given that Novell bought it, I'd say it's **the** DOS intended to be used with NetWare.

**Comment by cold-brewed** [comment] 2023-06-11 17:27
DR-DOS 6 (released ~1991, same year Novell purchased Digital Research) predates Netware 6 (2001) by about 10 years, that's why I ask.

**Comment by waltje** [comment] 2023-06-11 17:31
Its DR-DOS with their Netware client built in. So, no TSRs etc to deal with.Fred--Sent via my Samsung Galaxy Note® 4 4G LTE

-------- Original message --------
From: Miran Grča ***@***.***> 
Date: 6/11/23  1:15 PM  (GMT-05:00) 
To: 86Box/86Box ***@***.***> 
Cc: Subscribed ***@***.***> 
Subject: Re: [86Box/86Box] Novell Netware 6.0 crashes on startup (Issue #3379) 


- cold-brewed: DR-DOS = Novell DOS. Given that Novell bought it, I'd say it's the DOS intended to be used with NetWare.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/86Box/86Box/issues/3379#issuecomment-1586252358",
"url": "https://github.com/86Box/86Box/issues/3379#issuecomment-1586252358",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by cold-brewed** [comment] 2023-06-11 17:35
> Its DR-DOS with their Netware client built in. So, no TSRs etc to deal with

I think that's Novell DOS 7, which I did install the other day. It worked fine, successfully attaching to a Netware 3.12 server.

I believe the one I installed included native support up to Netware 5.x servers.

**Comment by nosredniw** [comment] 2023-07-07 02:27
HI guys, any solution for Netware 6

**Comment by OBattler** [comment] 2023-08-08 23:34
This is now fixed. It was caused by the absence of a particular 686 MSR.

**Closed by OBattler** 2023-08-08 23:34 UTC
Labels: bug

**Comment by admnd** [comment] 2023-08-09 11:12
> This is now fixed. It was caused by the absence of a particular 686 MSR.

Which branch to checkout to try again?
