### ISSUE TITLE
Win2K/WinXP setup crashes on Klamath P2 and later

### ISSUE THREAD

**Issue by WinFutureX** [86Box/86Box#654] opened 2020-03-31 13:46 UTC
**Describe the bug**
Windows XP will encounter a IRQL_NOT_LESS_OR_EQUAL BSOD while formatting the hard disk during the Setup text-mode stage if the CPU is Pentium 2 Klamath/Deschutes or Celeron Mendocino. The only CPU that won't cause this crash is the VIA Cyrix 3.

**To Reproduce**
Any Slot 1/Socket 370 machine with the aforementioned buggy CPUs
1. Insert XP ISO image, boot to Setup HDD format screen
2. Create C: drive
3. Select "format as NTFS" option
4. Wait for BSOD

**Expected behavior**
Successful format, setup able to complete

**Screenshots**
![20200328-074818-531](https://user-images.githubusercontent.com/29031916/78033043-772ecb00-7398-11ea-8f94-c389ea52fa0f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10  1909 18363.720
 - Version 2.10, x64 dev branch + Zen optimizations

**Additional context**
I managed to format the disk with a Windows 2000 CD and continue copying XP's files, but when rebooting into GUI Setup, the CPU double faults:
![20200328-080515-048](https://user-images.githubusercontent.com/29031916/78033269-c2e17480-7398-11ea-911e-a400d3e1a12a.png)
Additionally installing Win2K would cause it to freeze while detecting hardware.

**Comment by tiseno100** [comment] 2020-03-31 13:51
We are aware of this issue. It's caused by missing(? not aware if they actually exist or not) SYSENTER & SYSEXIT instructions found at the Pentium II's. Try using the VIA C3's as of now.

**Comment by OBattler** [comment] 2020-04-11 09:18
I disabled SYSENTER/SYSEXIT for time being, so it should now work.

**Comment by qeeg** [comment] 2020-11-27 19:41
This should be closed now.

**Comment by OBattler** [comment] 2020-11-30 01:00
Yes, this is now fixed so it's getting closed.

**Closed by OBattler** 2020-11-30 01:00 UTC
Labels: bug
