### ISSUE TITLE
Tseng ET4000 is one letter off

### ISSUE THREAD

**Issue by Winins0** [86Box/86Box#789] opened 2020-06-07 18:54 UTC
As you can see.
![20200607-184900-856](https://user-images.githubusercontent.com/65453129/83977454-4d020800-a909-11ea-8267-26915cbbff25.png)
Ryuzaki pointed out that this is a bug so I am posting it here.

**Comment by dhrdlicka** [comment] 2020-06-07 19:01
It's also crashing on certain configurations, like the ASUS PCI/I -486SP3G.

**Comment by dhrdlicka** [comment] 2020-06-07 19:09
![image](https://user-images.githubusercontent.com/13226155/83977732-280a9680-a903-11ea-93dd-0d591fe2648d.png)
Seems like the crash could be in fact related to the missing first column.

**Comment by OBattler** [comment] 2020-06-07 19:34
The crash is now fixed. The cutoff, however, is caused by greatpsycho's changes, so I'll talk to him when he's back (ajnd it only happens on the Cardex variant of the card).

**Comment by Winins0** [comment] 2020-06-07 20:10
(Unrelated but, how do you add a label to a bug?)

**Comment by dhrdlicka** [comment] 2020-06-07 20:11
You need to use the bug report template on the new issue page:
![image](https://user-images.githubusercontent.com/13226155/83979048-d4e91180-a90b-11ea-8107-76147f206178.png)

**Comment by ppgrainbow** [comment] 2020-07-20 00:37
Can I provide a link to greatpsycho's changes that caused the cutoff? I'm sure that the cutoff also occurs on VGA cards when the text display mode is set to 40 x 25:
![40x25 Text Cutoff](https://user-images.githubusercontent.com/32658796/87889400-4f668000-c9e6-11ea-8417-16e9968dbf4d.png)

On the Cardex Tseng ET4000/w32p, two characters are cut off when the text display mode is set to 40 x 25.

**Closed** 2020-12-18 17:10 UTC
Labels: bug
