### ISSUE TITLE
[BUG] Random lock ups on 8086 cpu based machines 

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#355] opened 2019-02-07 14:34 UTC
Hello!

I tested the latest commit of 86box: 

There are mixed results, The 8088 cpu emulation as well as CGA card emulation, and PC speaker are closer to the real hardware. There are new issues with 8086 machines,  though they are fewer than 8088.

btw: More games works now, including Boulderdash Booter disk, now it does not stick on level 1 when it is finished.

1. The 8086 (not 8088) emulation seems broken. I experienced random lock ups on Tandy 1000/SL2 using stable 86box branch and the 8086 based Laser XT with dev branch.
This does not affect the 8088 based Tandy and 8088 based Laser XT.

2. As minor glitch Hercules's CGA emulation and Tandy 1000 machines with Tandy graphics of Bubble Bobble is still broken, but I can use the native CGA/EGA emulation for it.  
 (at start of the game the bubble of the dragon never blasts, but the music the "Hurry up!" message appears later on)
Both emulations (Hercules's CGA emulation and native Tandy 16 colors mode) has the same issue.
Also, if I recall correctly, on real hardware the Hercules card was detected as CGA in the game initial menu after BBSIMCGA was loaded.

3. Question: might, the CGA graphics changes, be apllied to Hercules card  and Tandy 1000 machines?

I know the Tandy 1000 chip is based on CGA. I don't know how compatible is the Hercules with CGA.

Here is the Image of the file: [https://drive.google.com/file/d/1QqmrRUlkVdEXVqyi7xRVX1vyZEtDGz0U/view?usp=sharing](url)

Note: For CGA emulation on Hercules BBSIMCGA.COM must be loaded. The game is know to be very speed sensitive.
The BBFAST.EXE  is a speed fix for 386 based machines,  but it does not work on 486 DX/2 machines.

Thanks for your work in this awesome emulator!

**Comment by OBattler** [comment] 2019-02-07 15:54
How exactly do I reproduce those 8086 lockups?

**Comment by Fenix770** [comment] 2019-02-07 19:10
I experienced random lock ups 

- at dos prompt (but it's hard to reproduce) 
- when editing config.sys with Freedos Edit utility with serial mouse
- l and playing Tetris (spectrum Holobyte, 1987). I started in level 0 and the lock up ocurred in level 2.

I tested both 8086 configurations and and 8088.

On stable brach I tested:

- TANDY 1000 SL/2 with and without hard disk configuration, (some color text garbage can occur with the lock up) and I use 768kb of ram in configuration
- 8088 based  Tandy has no luck ups.

On deb branch:
-I tested the 8086 Laser XT with same results
-On 8088 Laser XT the lock up does not occurs

Respect of the second problem is seems to be related to Hercules and Tandy graphics emulation. but native CGA had the same problem on 8088 machines, and the last commit fixed it.

**Comment by Fenix770** [comment] 2019-02-07 19:45
PD: the tetris game locks ups only  on T1000 SL/2 in Tandy graphics mode. 

I tested the game with Ollivetti M24 wich has 8086 cpu and CGA graphics and the games seem to works without any issue.

**Comment by OBattler** [comment] 2019-02-08 04:01
* As minor glitch Hercules's CGA emulation and Tandy 1000 machines with Tandy graphics of Bubble Bobble is still broken, but I can use the native CGA/EGA emulation for it.
  (at start of the game the bubble of the dragon never blasts, but the music the "Hurry up!" message appears later on)
  Both emulations (Hercules's CGA emulation and native Tandy 16 colors mode) has the same issue.
  Also, if I recall correctly, on real hardware the Hercules card was detected as CGA in the game initial menu after BBSIMCGA was loaded.
* Question: might, the CGA graphics changes, be apllied to Hercules card  and Tandy 1000 machines?
----
I applied the display on/off bit of port 3B8 (the MDA/Hercules equivalent of CGA's port 3D8) and for what is worth, the game seems to start up fine, but the dragon's bubble didn't blast. I'm not sure what else could be causing that.

**Comment by OBattler** [comment] 2019-02-09 07:23
I have the 8086 lockups fixed now, they were caused by the emulator reading 2 bytes (this is 8086-specific, 8088 always only reads one at a time) into the prefetch queue on the 8086 when the IP (instruction pointer) is even, even when there was just one free byte left in the queue - since the 8086's prefetch queue is 6 bytes array was itself 6 bytes, this was causing a write beyond the upper bound of the array, messing up who knows what was in the emulator's memory after that.

As for the Hercules stuff, I'm still investigating that.

**Comment by Fenix770** [comment] 2019-02-10 18:47
I tried the Bubble Bobble with DosBox-X.

The game seems to work in Hercules mode after loading BBSIMCGA.COM.
I found an strange behevior on the game
But I also found that one copy of the game has no text and no score/credit during game play, and the other works ok. 
On 86box both copies of the game has the text and the issue of the bubble that no blasts.
Here I ttach the copy that worked in Dosbox-X.

[bubble bobble herc.zip](https://github.com/86Box/86Box/files/2849228/bubble.bobble.herc.zip)

**Comment by MoochMcGee** [comment] 2019-05-04 11:24
Since the original bug that spawned this issue has been fixed, might I suggest that this issue be closed, and any other bug reports splintered into their own issues?

**Comment by daviunic** [comment] 2019-05-04 11:36
Agreed.

**Closed by daviunic** 2019-05-04 11:36 UTC
Labels: bug

**Comment by MoochMcGee** [comment] 2019-05-04 13:24
@Fenix770 In the future, please keep separate bugs to separate issues.
