### ISSUE TITLE
Support for version-controlled (or something similar) hard disk images

### ISSUE THREAD

**Issue by qeeg** [86Box/86Box#591] opened 2020-02-02 20:26 UTC
**Is your feature request related to a problem? Please describe.**
I was thinking that since storage space can sometimes be a bit low for some people, that we could make a patching system for hard disk images that people can revert to or even make new branches from!

**Describe the solution you'd like**
Basically, I was thinking something similar to git, but optimized for binary file formats and with no internet support.

**Additional context**
MAME has similar functionality with diff files for their CHDs for hard drive and optical disc images.

**Comment by jvernet** [comment] 2020-02-02 20:56
Something like a VMware snapshot would be a great thing. At least, a "backup image" inside 86Box that duplicate HDD image and zip it fastly should be a first level.
Bored to reinstall W3.1 each time i tried and failed some installation tests ;)

**Comment by daviunic** [comment] 2020-02-02 21:50
I think this could be done with differencing VHDs, which has been discussed as a possible future addition several times.

**Comment by Altheos** [comment] 2020-02-03 07:35
Maybe it's a duplicate with #517 ?

**Comment by MoochMcGee** [comment] 2020-02-03 13:27
I was thinking something more sophisticated, maybe with branches where in one you did one thing, and in the other, you did another thing?

**Comment by nickbeee** [comment] 2020-02-04 18:59
> 
> 
> Something like a VMware snapshot would be a great thing. At least, a "backup image" inside 86Box that duplicate HDD image and zip it fastly should be a first level.
> Bored to reinstall W3.1 each time i tried and failed some installation tests ;)

I do this using 7zip and make progressive backups of the HD image when I'm building an installation. However, it would be useful to have such a feature available though.

**Comment by OBattler** [comment] 2020-06-17 12:13
Going to close this as a duplicate of #517 .

**Closed by OBattler** 2020-06-17 12:13 UTC
Labels: disk, feature request
