### ISSUE TITLE
Quake 2 corrupts CD music

### ISSUE THREAD

**Issue by Tasosgemah** [86Box/86Box#3262] opened 2023-04-20 01:48 UTC
**Describe the bug**
The CD music is corrupted (sounds like horrible loud noises and scratches)

**To Reproduce**
Just play the game with CD music.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: 3.11.0.4311

**Additional context**
At first i thought the CD image was corrupted but i mounted it on my host machine and played the music through a music player and it sounds fine. So the CD is good.

**Comment by cold-brewed** [comment] 2023-04-20 15:43
I just happened to play Quake 2 yesterday and it was running perfectly for me, including CD audio. Are you using a bin/cue for the image? That is required for proper CD audio.

I was also using the latest version of 86box. Could I get you to grab a CI build and give it another test?

https://ci.86box.net/job/86Box/

**Comment by Tasosgemah** [comment] 2023-04-21 00:49
> I just happened to play Quake 2 yesterday and it was running perfectly for me, including CD audio. Are you using a bin/cue for the image? That is required for proper CD audio.
> 
> I was also using the latest version of 86box. Could I get you to grab a CI build and give it another test?
> 
> https://ci.86box.net/job/86Box/

Thanks, i made another guest system with slightly better specs (133Mhz and 24MB RAM instead of 16) and the music seems to work well, though the game randomly crashes. I think it doesn't crash as often with CD music disabled but i have to do more tests.

My image is cue/bin as well.

**Comment by cold-brewed** [comment] 2023-04-21 15:59
As far as the game randomly crashing, that is likely a combination of: your selected hardware, the guest OS, and the drivers. In other words: standard fare 90s computing.

With the right system / diver combination (and of course a sufficiently fast guest / host system) Quake II can definitely run well in 86Box.

Bad CD audio can also be caused by bad images from bad / improper rips. I would also suggest trying a different quake II image.

**Comment by Tasosgemah** [comment] 2023-06-05 19:25
> 

I tried my image on my host computer and it never gets corrupted.

I made another guest system with different specs. Problem still occurs. 

The music plays fine until i press ESC to bring the menu. When i do that the music gets corrupted 100% of the time.

**Comment by Tasosgemah** [comment] 2023-06-05 19:27
Seems like the music gets corrupted if i use my P133/32MB RAM guest.

Whenever i press ESC to bring up the menu, it happens, 100% of the time.

**Comment by OBattler** [comment] 2023-08-09 04:31
You said you hear loud noises and scratches - that definitely sounds like it's playing data instead of music, which would indicate a bad CD rip. You need to download a better version.

**Comment by Tasosgemah** [comment] 2023-08-09 06:04
> You said you hear loud noises and scratches - that definitely sounds like it's playing data instead of music, which would indicate a bad CD rip. You need to download a better version.

The CD is fine. It plays fine in PCEM, Virtual PC or natively. Only 86Box has a problem with it.

**Comment by mr-falafel** [comment] 2023-08-15 00:45
Quake II plays fine for me. I'd recommend checking the sha1 checksums of your bin files against those found on [redump.org](http://redump.org/).
Either the [US](http://redump.org/disc/2569/) or [EU](http://redump.org/disc/14931/) release, depending on your region. For me personally, I have problems with audio playback of CD games in numerous programs where my cue files have more than one bin file. You can merge your bin files and automatically generate a new cue file using [binmerge](https://github.com/putnam/binmerge), which works great in WSL incidentally. Using this method, I've completed Quake and Quake II multiple times in 86box, with no issue.

**Comment by OBattler** [comment] 2023-08-15 17:17
Then this can be closed as NOTABUG.

**Closed by OBattler** 2023-08-15 17:17 UTC
Labels: notabug

**Comment by OBattler** [comment] 2025-02-01 04:41
This turned out to have actually be a bug (some CD-ROM commands were not stopping audio playing even though they should have been) and it is now fixed.
