### ISSUE TITLE
CD Drives Not Working Properly as of 6145

### ISSUE THREAD

**Issue by Mal752** [86Box/86Box#4805] opened 2024-09-07 08:09 UTC
### What happened?

"Inserting" a new CD image gives General Drive Read Error. Typing (R)etry a few times finally able to read the drive.

After changing the CD, 86Box still shows the old CD files loaded. Does not refresh.

### Configuration file

```ini
[Trident TVGA 8900D]
memory = 1024

[Logitech Serial Mouse]
port = 0
buttons = 3
revision = 3
rts_toggle = 1

[Logitech/Microsoft Bus Mouse]
base = 023C
irq = 3
hz = 45
buttons = 3

[System MIDI]
midi = 1

[Roland MPU-IPC-T]
base = 0330
irq = 2
receive_input = 1

[Adaptec AHA-154xCF #1]
base = 0334
irq = 11
dma = 6
bios_addr = 00000
fdc_addr = 0000

[Everex EV-159 RAM 3000 Deluxe #1]
size = 2048
start = 0
length = 0
width = 0
speed = 0
ems = 1
base = 0258
base2 = 0268

[General]
vid_renderer = qt_opengl
force_43 = 1
video_fullscreen_first = 0
confirm_reset = 0
confirm_exit = 0
iconset = legacy
status_icons_fullscreen = 1
sound_gain = 5
host_cpu = Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
emu_build_num = 6145
uuid = 26afe695-0a8e-5918-8600-6203d734614f

[Machine]
machine = cmdsl386sx25
cpu_family = i386sx
cpu_speed = 25000000
cpu_multi = 1
fpu_type = 387
cpu_use_dynarec = 0
time_sync = local
fpu_softfloat = 0
mem_size = 4096

[Video]
gfxcard = vga

[Input devices]
mouse_type = ltserial
joystick_type = 2axis_2button
joystick_0_nr = 1
joystick_0_axis_0 = 0
joystick_0_axis_1 = 1
joystick_0_button_0 = 0
joystick_0_button_1 = 1
joystick_1_nr = 0

[Sound]
sndcard = sbprov2
midi_device = system_midi
mpu401_standalone = 1
fm_driver = nuked

[Ports (COM & LPT)]
lpt1_device = lpt_dac

[Storage controllers]
hdc = ide_isa
cassette_mode = load

[Floppy and CD-ROM drives]
fdd_01_type = 525_2hd
fdd_02_type = 35_2hd
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 0:1
fdd_01_image_history_01 = /home/**user**/FILES/DOSFILES/Dos Games Archives/Disk Images/Where in the World is Carmen Sandiego (5.25 1.2MB)/Where in the World is Carmen Sandiego_ (5.25 1.2MB)Disk 5.img
fdd_01_image_history_02 = /home/**user**/FILES/DOSFILES/Dos Games Archives/Disk Images/Where in the World is Carmen Sandiego (5.25 1.2MB)/Where in the World is Carmen Sandiego_ (5.25 1.2MB)Disk 4.img
fdd_01_image_history_03 = /home/**user**/FILES/DOSFILES/Dos Games Archives/Disk Images/Where in the World is Carmen Sandiego (5.25 1.2MB)/Where in the World is Carmen Sandiego_ (5.25 1.2MB)Disk 3.img
fdd_01_image_history_04 = /home/**user**/FILES/DOSFILES/Dos Games Archives/Disk Images/Where in the World is Carmen Sandiego (5.25 1.2MB)/Where in the World is Carmen Sandiego_ (5.25 1.2MB)Disk 2.img
cdrom_01_type = 86BOX_CD-ROM_1.00
cdrom_01_image_path = /home/**user**/FILES/CDROMS/Mario Teaches Typing (USA).cue

[Other peripherals]
isamem0_type = ev165a

[Hard disks]
hdd_01_parameters = 17, 15, 900, 0, ide
hdd_01_fn = /run/media/**user**/FILES/EMULATION/86Box/hdd/386SX_112MB.img
hdd_01_speed = 1992_3600rpm
hdd_01_ide_channel = 0:0

[Mouse Systems Serial Mouse]
port = 0
buttons = 3
rts_toggle = 1

[rts_toggle]
status_icons_fullscreen = 1

[status_icons_fullscreen]
status_icons_fullscreen = 1

[status_icons_fullscreen]
status_icons_fullscreen = 1

[Tertiary IDE Controller]
irq = 11

[Sound Blaster Pro v1 #1]
base = 0220
irq = 7
dma = 1
opl = 1
receive_input = 1

[Everex Magi Magic EV-165A #1]
size = 2048
start = 0
length = 0
ems = 1
base = 0258
```

### Operating system

Debian

### CPU

Core i7 9750H

### 86Box version

6145

### Build architecture

Linux - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by eddmanx** [comment] 2024-09-07 11:04
Can't reproduce this. It does show the CDR101 message, yes, but after one Retry it reads the disc and shows the correct files.

You might have to upload the full machine files (cfg, nvr, hdd).

**Comment by OBattler** [comment] 2024-09-08 05:22
This is exactly what's being reported. And I'd like know based on what this is considered improper behavior, given that Windows XP explicitly relies on a medium change being preceded by a not ready state, which also makes perfect sense - a medium change by definition means one medium is being removed and another inserted.

**Comment by OBattler** [comment] 2024-09-08 05:23
> After changing the CD, 86Box still shows the old CD files loaded. Does not refresh.

Given that we explicitly send the medium changed unit attention in addition to the not ready state, there must be something strange going on.

**Comment by OBattler** [comment] 2024-09-08 05:24
Also, which DOS CD-ROM driver exactly is being used?

**Comment by OBattler** [comment] 2024-09-09 22:12
Closing this because I can't try to reproduce this without knowing which CD-ROM driver is being used.

**Comment by Mal752** [comment] 2024-09-10 03:41
Sorry, I was away for sometime.

The CD-ROM driver is QCDROM.SYS, which is the only driver I have been using since the inception of 86Box, and alos in my real DOS machines.

The problem is I only noticed in the version I input above. Before this I didn't notice it.

The problem seems to be somewhere during the evolutioin and I am unable to pinpoint in which build this problem cropped up.

**Comment by Mal752** [comment] 2024-09-10 03:43
I cannot find the re-open issue button. If OBattler have read this, please re-open this issue. Thank you.

**Comment by OBattler** [comment] 2024-09-11 00:05
Can you upload this QCDROM.SYS somewhere?

**Comment by Mal752** [comment] 2024-09-11 03:09
> Can you upload this QCDROM.SYS somewhere?

It's downloaded from here: 

https://www.hiren.info/downloads/dos-files

I don't think it's a driver error, since I have been using the same in previous builds without problems.

**Comment by Mal752** [comment] 2024-09-11 03:15
Tried with a clean boot floppy. Same problem.

Thing is it works, but shows General Read Error on first access, for eg when typing <DIR>. After typing (R)etry, it loads normally. This behaviour was not noticed before.
![Screenshot_2024-09-11_11-12-13](https://github.com/user-attachments/assets/0c2d781b-edf3-403d-bb5b-25a154df6b84)
![Screenshot_2024-09-11_11-13-23](https://github.com/user-attachments/assets/2e4543a0-e05d-4cf7-8f9a-55aab42fdbf2)

**Comment by Mal752** [comment] 2024-09-11 03:21
Tried other machine configuration. Also the same.

**Comment by Mal752** [comment] 2024-09-11 03:24
Okay, I tried using an older build - 6047. The problem doesn't exist here using the above machine configurations. Changing discs and typing DIR doesn't produce errors and works normally.

**Comment by OBattler** [comment] 2024-09-11 03:51
The problem is that in those older builds, it was Windows XP who had that problem.

**Comment by OBattler** [comment] 2024-09-18 02:12
The driver is strange - it sends the TEST UNIT READY command and then proceeds to send READ TOC even if TEST UNIT READY returned error. That's definitely not correct behavior.

**Closed** 2024-09-18 06:01 UTC
Labels: bug

**Comment by Mal752** [comment] 2024-09-18 08:29
I tried using the latest build (6162), but the problem persists.  After "changing" a CD, it STILL gives a general drive read errror. Pressing (R)etry loads it properly, though. By right, once changed the CD, it should be reflected immediately on typing DIR...

**shrugs**

![Screenshot_2024-09-18_16-28-14](https://github.com/user-attachments/assets/3af9054f-652d-46b5-9764-9203222594ee)

**Comment by Mal752** [comment] 2024-11-30 05:58
> > By right, once changed the CD, it should be reflected immediately on typing DIR...
> 
> Are you sure? Because a real drive would also go through a not ready phase before transitioning to medium has changed - I probed my real drive back when I still had that Pentium Dual-Core, and that's how it behaved. This isn't a floppy drive where the controller immediately treats the drive as ready, with the updated change line bit on port 3F7.

Sorry for the unclear words. I meant to say that once the CD is changed, it should display the new contents when seeking, like using DIR command. Problem is it doesn't even after waiting much longer. 

Yes, the results of seeing the changes is immediate when it comes to using the iso images in emulators (contrary to using actual CD-ROM drive).

But anyway, now I have changed the driver to vide-cdd.sys and mscdex (instead of qcdrom and shsucdx) and now it is working as it should. And the changes are reflected immediately. (Now using build 6300.)

**Comment by RobertSundling** [comment] 2024-12-08 16:28
> But anyway, now I have changed the driver to vide-cdd.sys and mscdex (instead of qcdrom and shsucdx) and now it is working as it should. And the changes are reflected immediately. (Now using build 6300.)
> 
> So I think the problem lies with shsucdx.exe or qcdrom.sys running in 86Box.

This problem also happens with a default [FreeDOS](https://www.freedos.org/) installation, which uses `shsucdx.exe`. I tried substituting `vide-cdd.sys` as the driver but the problem remains. So I believe it's `shsucdx.exe`.

It appears the problem was introduced with d5b0fd1, because if I revert *just* the file `scsi_cdrom.c` to that version and rebuild 86Box, the problem remains. But if I revert it to the version *before*, it's fine. This comment, explaining what that change does,  ...

```c
    /* Transition, pretend we're not ready for one check so that
       Windows XP can recognize a medium change. */
```

... seems to give a hint to the crux of the issue. By pretending that the drive isn't ready on the first access after a medium change, we get that "not ready" error in DOS. The user has to respond to the prompt (such as by pressing "R" to retry) so that the drive is then accessed a second time.

In FreeDOS, the error looks like this:

![image](https://github.com/user-attachments/assets/60dec48a-0f3e-4256-a312-290572533ea7)

and it occurs the first time the CD-ROM drive is accessed after a CD change. There seems to be no way to prevent the message from appearing upon the first access. In this particular screenshot, you can see it's when the volume label of the drive is being read on a "dir" command.

I'm temporarily using a custom 86Box build with the old `scsi_cdrom.c` file. Unfortunately, since I only run DOS and Windows 9x systems, and not XP, I wouldn't want to try to submitting a fix for the problem myself, as any fix I made could easily re-introduce the problem (#4766) that d5b0fd1 was trying to solve.

**Comment by OBattler** [comment] 2024-12-08 20:11
A real drive would cause this as well, I know because I probed mine years ago, and there would not be a medium change state without a prececing not ready state, also because you had to physically open the tray and then close it.

**Comment by RobertSundling** [comment] 2024-12-08 21:59
I just confirmed that this does *not* happen on a physical machine. Here's what I did, on a Gateway Pentium 233 MHz machine:

1. Made a minimal FreeDOS boot floppy that uses `vide-cdd.sys` and `shsucdx.com` to map the CD-ROM as drive Z.
2. Booted a machine with that.
3. Inserted a Windows 95 install CD-ROM, closed the CD tray, waited 15 seconds.
4. Changed to that drive (`Z:`) and did a `DIR` on that CD-ROM.
5. Ejected the CD-ROM.
6. Inserted a Windows 98 install CD-ROM, closed the CD-tray, waited 15 seconds.
7. Did a `DIR` on that CD-ROM.

The result was no "(A)bort, (R)etry, (F)ail" message. Instead, it displayed "Volume in drive Z" then paused for a moment as it spun up and read the CD, then displayed the volume name ("is WINDOWS 98"), and listed the directory.

![no-arf](https://github.com/user-attachments/assets/40236cc9-af16-4559-bd20-3060831ca618)

However, when booting 86Box 4.2.1 or 4.3.0 (f94a30d) from the same floppy, then doing the exact same process (loading one CD image, waiting, doing a `DIR`, ejecting the CD image, loading another CD image, waiting, and doing a `DIR`), I  *do* get the "(A)bort, (R)etry, (F)ail" message. If the machine is booted without a CD-ROM image mounted, I get it twice (on both "DIR" commands). So something is definitely different compared to a real machine. I can wait any length of time after "inserting" the CD (I've tried up to a minute) and I still get the message.

I'm happy to provide the boot floppy image if that's useful.

**Comment by Mal752** [comment] 2024-12-08 22:46
On a physical CD and DVD drive, yes, we need to wait until the drive starts spinning the disc to make it ready for reading. My first CD-ROM based system was a Pentium 133 that I got back in 1996.

On the other hand, in emulators, such as 86Box, Kega Fusion, Duck station, etc, when you "change" the CDs, the result is immediate, since they are using iso/cur-bin images. And the emulators are programmed to just detect the change. The reason being, to read images, the emulators don't need to "wait" for drive spins when using disc images.

Back to 86Box, I first noticed this as I explained in my first 2 posts. It didn't occur before that. 

But anyway, I was having problems running Time Commando in DOS. It just didn't work. Finally I zeroed in to SHSUCDX because when using MSCDEX, the game loads. (After the Adeline splash screen, the screen goes black when using SHSUCDX.)

And when I tried back checking the changes when changing discs after changing to MSCDEX and VIDE-CDD, 86Box reads normally without errors, immediately.

From RobertSundling's post above, it seems the problem lies only with the SHSUCDX and not the CD-ROM drivers.

**Comment by OBattler** [comment] 2024-12-09 02:20
Well, I have no idea what to do then, if I restore the old behavior, Windows XP breaks because it completely ignores the "medium may have changed" condition unless it has detected the "not ready" condition at least once. I need to see what exactly SHSUCDX is doing there.

@RobertSundling Something is definitely strange then, 86Box reports "not ready" once, then "medium may have changed", and after that, no error.

**Comment by RobertSundling** [comment] 2024-12-09 02:42
Here’s one thought. Windows XP must poll the drive with relative frequency, and not *just* when something tries to read from the disk. For example, it (somehow) immediately notices when a new disk has been inserted, so that it can do the “autorun.inf” stuff. It doesn’t wait for a user to click on the drive.

So that means there could probably simply be a timeout added to 86Box. For example, during the first 2 seconds (or some configurable time) after a CD change, the first time CD drive is read from, it’d respond “not ready”—that is, following the new behavior. That’d fix XP. However, if the drive isn’t read from at all in those two seconds, it’d revert to the old behavior, and report no error. So things like SHSUCDX, which only poll the drive when data is requested, would still work properly when trying to read from the drive, later, and wouldn’t get that “not ready” error even after time has passed.

**Comment by OBattler** [comment] 2024-12-09 02:53
Well, this gets more interesting, because I can't reproduce this at all, with VIDE-CDD.SYS 2.15 and SHSUCDX: 
![imagem](https://github.com/user-attachments/assets/6e478982-7983-444b-a46c-f7752fd3e9c3)
Can I have your boot floppy please?

**Comment by RobertSundling** [comment] 2024-12-09 03:00
Sure, here is the boot floppy:

[freedos-cd-boot.zip](https://github.com/user-attachments/files/18055824/freedos-cd-boot.zip)

If *that* doesn't work then I can send the 86box.cfg I'm using too (probably after scrubbing it a bit), but it's a pentium_p55c on an ms5172 motherboard.

**Comment by OBattler** [comment] 2024-12-09 03:04
![imagem](https://github.com/user-attachments/assets/b19c2750-60a8-42a1-9221-a41792d284ba)
It says not enough drive letters because of all the hard disks. Let me create a new VM.

**Comment by RobertSundling** [comment] 2024-12-09 03:06
That's weird, that's exactly why I have LASTDRIVE=Z in the CONFIG.SYS file...

**Comment by RobertSundling** [comment] 2024-12-09 03:07
Oh, maybe it's because you have two CD-ROM drives. And it's trying to do "Z" and then a letter after it.

**Comment by OBattler** [comment] 2024-12-09 03:10
I agree, it must be that.

**Comment by RobertSundling** [comment] 2024-12-09 03:11
I didn't put a text editor on there, but changing the AUTOEXEC.BAT line to

```
SHSUCDX /D:FDCDX001,Y
```

would probably fix it.

**Comment by OBattler** [comment] 2024-12-09 03:15
![imagem](https://github.com/user-attachments/assets/470a0c2a-044f-40fb-aedc-dab38f6c4494)
OK, I don't get errors but it also doesn't see the new contents for some reason

**Comment by OBattler** [comment] 2024-12-09 03:16
But it does if I eject the old disc first. Strange.

**Comment by RobertSundling** [comment] 2024-12-09 03:17
Oh, so I've only ever ejected before changing to a new image. For me, it's always I eject the folder that's mounted, to release locks, modify some files there, then remount it.

**Comment by RobertSundling** [comment] 2024-12-09 03:26
Yes, I can definitely reproduce things not changing unless I choose "Eject"--even with the old `scsi_cdrom.c` file. I've simply never not chosen "Eject" before!

**Comment by RobertSundling** [comment] 2024-12-09 03:41
I just checked with the real system to see if I could get it to return the same directory contents by doing the swap "faster." I couldn't. It would always check the actual drive. I'd either get an Abort/Retry/Fail prompt if I did it too quickly, or it'd simply return the new directory contents if I waited long enough.

(As an aside, this floppy boots in under 5 seconds on an actual machine, but takes well over a minute for me in 86Box, on that initial "......" part. Not sure if that's the same for you, too, or not. "Turbo timings" doesn't seem to make a difference.)

**Comment by OBattler** [comment] 2024-12-09 04:17
I think it's the MS-5172 and other such BIOS'es that have slow floppy code. Turbo timings do make a difference, but it's slower than it's on the Intel Advanced/EV.

**Comment by OBattler** [comment] 2024-12-09 04:19
Also, even more strangeness - sometimes, it does detect the disc change but it shows a sector other than root.

**Comment by OBattler** [comment] 2024-12-09 04:50
So what I see happening is this: TEST UNIT READY returning NOT READY, and then READ (10) returning no error - the unit attention "medium may have changed" condition completely disappears in the process.

**Comment by RobertSundling** [comment] 2024-12-09 05:04
Are you seeing the "(A)bort, (R)etry, (F)ail" message from FreeDOS at all?

**Comment by OBattler** [comment] 2024-12-09 05:30
Before, I wasn't. Now that I made TEST UNIT READY explicitly move to the "medium may have changed" condition, I do, and I see that it's actually acknowledging that a disc cahnge has occurred.

**Comment by OBattler** [comment] 2024-12-09 07:03
An idea would be returning to the old code and simply requiring the user to eject first.

**Comment by RobertSundling** [comment] 2024-12-09 14:38
> An idea would be returning to the old code and simply requiring the user to eject first.

Requiring the user to eject first reminds me of the original Sony Playstation: You’d normally eject the CD to load a new one, but modders used custom cases to swap CDs from the top without ejecting. This “disc-swap hack” bypassed the copy protection check triggered by disc changes.

*If* there is some reason to allow that type of hack on a PC, the old behavior would allow for changing the image without the PC registering the ejection. However, even if that’s a feature some people would want, it’s probably an edge case and likely wouldn’t be worth confusing everyone else.

How about something like this when mounting a new image:

1. If no image is currently mounted (i.e., the prior image was already ejected), always use the old behavior.
2. If an image is currently mounted, either follow the new behavior, or (as a possible code simplification) simply treat it as an “eject” followed by a “mount,” as if both actions were chosen by the user back-to-back.

I *think* that solves all situations?

Finally, if a “disc-swap hack” is deemed useful, a possible future feature could be a toggle somewhere in the menus that would allow using the old behavior always (could name it something like “Mount new CD images without ejecting first”), that the user could choose before changing images. I’ve personally never heard of a disc-swap hack on a PC, though, and my gut feeling is this probably isn’t actually useful.

**Comment by OBattler** [comment] 2025-02-03 06:10
This should now be fixed.

**Comment by RobertSundling** [comment] 2025-02-11 16:23
> This should now be fixed.

I'm not entirely sure, as in my tests FreeDOS under ab3d849 now seems to often no longer notice a CD has changed, even when choosing "Eject" first. It often (but not always!) keeps caching the old root directory for some reason, with no errors until you try to access a folder or file, which it then notices isn't there. It then either works or gives an error. If it gives an error and you press "Retry," it will usually reload the entire new CD, but not always. However, sometimes, instead, of giving any error at all, it gives weird results, such as corrupt directory listings that can't be resolved, as it somehow ends up with a mix of the old CD and the new.

As one example, putting in a Windows 98 image, ejecting it, and then putting in a Windows Me image, it (sometimes!) doesn't notice things have changed. Here is after that. Instead of listing the Me contents, it still lists the Win98 CD contents if you do a "dir":

![Image](https://github.com/user-attachments/assets/0f8a8613-f0e7-442e-bbac-d428c6dc4d97)

However, trying to access the (now missing) "WIN98" folder it gives a "File not found" error and then it starts working OK. 

Sometimes, instead, it gives totally corrupt directory listings. It's apparently pulling some sectors from the now-ejected CD and some from the new one:

![Image](https://github.com/user-attachments/assets/e39ccf60-fa10-4a5a-8a6b-39c0c22229e7)

Note that screenshot is not cut off; it really did think the directory was called `INDOWS` rather than `WINDOWS`.

It's fairly inconsistent. Sometimes it just works. Sometimes it gives a "Retry" error. Sometimes it does that weird mixed caching thing. It's not as predictable as it used to be, and I haven't identified patterns of when it works and doesn't, so I'm honestly not entirely sure what's going on.

For my primary personal use case (which is automatically ejecting, modifying, and reloading the same directory again, as a CD image, with just a couple changed files as part of an automated build process), it seems to work most of the time without throwing an "Abort/Retry/Fail" error or giving corrupt directories at least. However, I'm not sure if that is just because the file sizes haven't really changed, so everything is all still in the same place anyway. 🤷
