### ISSUE TITLE
Blurry or missing pixels with fractional Windows DPI scaling

### ISSUE THREAD

**Issue by nyanpasu64** [86Box/86Box#3243] opened 2023-04-08 16:01 UTC
**Describe the bug**
On Windows 10 set to 125% DPI scaling, when I uncheck menu View -> HiDPI Scaling, on the NT4 installer the height of the window is 1 pixel shorter than the framebuffer size, resulting in blurry pixels with linear scaling enabled or a missing row of pixels with linear scaling disabled.

**To Reproduce**
1. Start 86Box on Windows 10, on a display set to 125% scaling.
2. Uncheck menu View -> HiDPI Scaling. Leave View -> Window scale factor at 1x.
3. Boot the NT4 installer floppies 1 and 2.

**Expected behavior**
86Box sets the size of the canvas (in physical pixels) equal to the size of the framebuffer.

**Screenshots**
Linear scaling:
![86Box_Av6ObA7GWP](https://user-images.githubusercontent.com/913957/230729562-13c7f74f-551a-411e-aac5-d883238072a6.png)

Nearest scaling:
![86Box_NomeGruCOk](https://user-images.githubusercontent.com/913957/230729571-1cbcb050-4e8e-4059-beac-84665d0a24f8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - 86Box version: 86Box v3.11 [build 4311] [ab086750e]
 - Build information: 86Box-Windows-64-b4311.zip

**Additional context**
I decided to go poking at the implementation. AHKv2's Window Spy, says 86Box's About dialog is labeled `ahk_class Qt5152QWindow`, so this is probably a Qt5 build rather than Qt6 or Win32 UI.

This is handled at (`mon_scrnsz_x` is already scaled by "Windows scale factor"):
https://github.com/86Box/86Box/blob/a4ff1f72c8360c6bb44339718f96c11fa7d4e6b5/src/qt/qt_mainwindow.cpp#L2220-L2229

I *think* but did not verify that window resizing is handled by:
https://github.com/86Box/86Box/blob/a4ff1f72c8360c6bb44339718f96c11fa7d4e6b5/src/qt/qt_mainwindow.cpp#L263-L280

This code appears to divide the framebuffer size by a scaling factor, then assign it back to an integer, losing precision, before resizing the GUI. I'd suggest rewriting it to set the widget size to a floating-point value based off the framebuffer, but unfortunately [QWidget::resize()](https://doc.qt.io/qt-6/qwidget.html#size-prop) only accepts integer sizes. And since you call `QApplication::setHighDpiScaleFactorRoundingPolicy(Qt::HighDpiScaleFactorRoundingPolicy::PassThrough);` (starting in #2090), now even the same integer sized widget can have *different* on-screen sizes in physical pixels, depending on its position!

## Fixing

My personal preference is to set `QApplication::setHighDpiScaleFactorRoundingPolicy(Qt::HighDpiScaleFactorRoundingPolicy::RoundPreferFloor);` so you can position and size on-screen items in integer multiples of physical pixels. Then to size the widget, you ceil-divide the framebuffer size by the scaling factor to get a virtual size. And to paint the widget, you float-divide the framebuffer size by the scaling factor, covering the entire widget except for excess padding. You might have to replace `RendererCommon::destination` with a QRectF, which affects other renderers as well:

https://github.com/86Box/86Box/blob/38b9d4e9fabd6f9f9329046cab24941f1cb6932b/src/qt/qt_renderercommon.hpp#L44

(If you wanted to find the physical size of the widget, you'd multiply the virtual pixel size by the scaling factor, resulting in a size >= the framebuffer size.)

But this introduces a new problem ([Qt bug report](https://bugreports.qt.io/browse/QTBUG-95925)) where switching a screen's DPI scaling factor, or switching between monitors with different DPI scaling factors, causes UI elements to appear too small or large until you _drag_ the window between different DPI monitors (Qt only updates scaling when dragging a window between screens!!!).

Is this the right solution? To me this is a bug worth solving, and this is the way I'd solve it (although I don't know how to fix the other renderers). Should I try changing the code and rebuilding locally, or are you not interested in upstreaming a fix?

**Comment by nyanpasu64** [comment] 2023-04-09 01:08
I found out I also get blur on a 1024x768 desktop at 100% pixel scale and 125% Windows DPI, which is a bigger problem than Windows NT setup since it affects everyday use and not just one-time OS setup. Interestingly, this time the blur *varies* by backend (which I didn't notice in NT Setup):

- Qt (Software) has a slight horizontal blur on the right of the screen, and a heavy vertical blur at the bottom.
- Qt (OpenGL) is sharp.
- OpenGL (3.0 Core) has horizontal blur in the horizontal center, and vertical blur in the vertical center.
	- Direct3D 9 has the same kind of blur, but I'm not sure if the off-by-1 error is identical.
- Vulkan has vertical blur in the center of the screen.

**Comment by OBattler** [comment] 2023-04-09 03:02
I would be very interested it in your potential fix to the bug as I would certainly like it to be fixed.

**Comment by nyanpasu64** [comment] 2023-04-09 03:16
Unfortunately I haven't gotten 86box to build locally:

```
Running C:\Users\user\scoop\shims\cmake.exe -S C:/Users/user/code/86Box -B C:/Users/user/code/86Box/build-Desktop_Qt_5_15_2_MSVC2022_64bit-Debug in C:\Users\user\code\86Box\build-Desktop_Qt_5_15_2_MSVC2022_64bit-Debug.
CMake Error at C:/Users/user/scoop/shims/scripts/buildsystems/vcpkg.cmake:883 (message):
  Could not find .vcpkg-root
Call Stack (most recent call first):
  build-Desktop_Qt_5_15_2_MSVC2022_64bit-Debug/vcpkg-dependencies/toolchain.cmake:6 (include)
  build-Desktop_Qt_5_15_2_MSVC2022_64bit-Debug/CMakeFiles/3.25.2/CMakeSystem.cmake:6 (include)
  CMakeLists.txt:41 (project)


-- Configuring incomplete, errors occurred!
See also "C:/Users/user/code/86Box/build-Desktop_Qt_5_15_2_MSVC2022_64bit-Debug/CMakeFiles/CMakeOutput.log".
CMake process exited with exit code 1.
```

I'm guessing it has something to do with installing CMake and vcpkg using Scoop (which adds shim executables located out of tree) rather than directly. The error above occurs *after* I add symlink `"C:\Users\user\scoop\shims\scripts"` pointing to `C:\Users\user\scoop\apps\vcpkg\2023.01.09\scripts`.

I'm having some particularly bad luck with C++ builds lately, this is the *fourth* time (of 4 attempts) I've tried to build someone else's C++ project in the past week or so, that's failed to work.

In any case I don't have the energy to figure out how to fix the build right now. I'm not looking forward to installing vcpkg directly rather than using a Scoop shim, since I'll have to figure out how to install it and which packages to reinstall in the new location.

Do you have any clue what's wrong? Do I need to use vcpkg to build 86box or not?

**Comment by nyanpasu64** [comment] 2023-04-09 21:14
I have mostly bad news:

- I only managed to get 86box to build in Qt Creator using MSYS2 UCRT (didn't test MinGW64).
- Qt Creator gdb doesn't work properly on UCRT binaries, failing to breakpoint debug builds and failing to decode the stack on release builds.
- I don't know who calls `RendererCommon::onResize` with what values (physical or virtual pixels), since I can't breakpoint it and didn't try adding debug prints. But looking at callers, it seems it's called based on *widget resizing* (overriding `QWidget::resizeEvent(QResizeEvent *event)`) rather than based on the value passed into `MainWindow::resizeContents`.
	- `QResizeEvent` stores an integer `QSize` (even in Qt 6) in virtual pixels, which has less precision than the screen resolution (both in rounded and passthrough DPI scaling).
	- So if you want one on-screen physical pixel per VM pixel, you must pick the size of `QRect(F?) destination` based on the *VM* size in `MainWindow::resizeContents`, rather than the *widget* size passed through Qt. This is a bigger refactoring than I want to implement myself.

New bugs I've discovered:

- Concerningly, when I set the Renderer to "Direct3D 9", then change "HiDPI scaling" or "Window scale factor, the image doesn't fill the entire widget! Even with "HiDPI scaling" checked, the widget is sized based on virtual pixels, but the image is smaller and only fills physical pixels. With it unchecked, the screen is *smaller* than 1x scaling!

![firefox_ldF8tlY9Eq](https://user-images.githubusercontent.com/913957/230796370-43597cac-7623-4b73-b0de-07ff52dd201d.png)

- I could've sworn that enabling overscan produces a blurry window, then switching scale factors produces a not blurry image (because it's calculating the window size using a different dataflow with different rounding errors?). I haven't been able to get a not blurry image though, so maybe this isn't actually the case.

In general, I think that widgets should usually control their behavior based off the "source of truth" (eg. VM framebuffer resolution multiplied by scaling factor), rather than reading properties off GUI elements. So UI elements should be considered a "sink" and "display" for values, rather than a "source of truth". Some exceptions include text/numeric input widgets when a user changes their value (take its value and store it to a source of truth, and subsequently ignore the value of the widget), or using a widget's size to calculate how to paint its contents (but that doesn't apply when trying to draw a fixed-size bitmap into a widget attempting to match the bitmap's size; in 86box you should paint based on the bitmap's dimensions and ignore the widget's extra slack space that only exists because Qt only supports integer virtual pixel widget sizes).

**Comment by OBattler** [comment] 2023-08-19 04:58
They are considered a sink. The problem is that the render area is itself a widget and therefore, gets contorted by QT when using non-integer scaling because of how QT is designed. Unfortunately, QT has no function to set a direct resolution so setting it to resolution divided by DPI scale so QT can then multiply that back is the only way.

As such, I'm unfortunately closing this as CANTFIX until the day comes that QT gets around and realizes we need a function to set direct resolution.

> in 86box you should paint based on the bitmap's dimensions and ignore the widget's extra slack space

The bitmap that's being painted on, is set to the guest's resolution. It's QT that's then contorting it to fit the window size. That's why it's blurry.

**Closed by OBattler** 2023-08-19 04:58 UTC
Labels: bug
