### ISSUE TITLE
Newly created IDE drives say Missing Operating System, even though they are present

### ISSUE THREAD

**Issue by Sunspark-007** [86Box/86Box#4366] opened 2024-04-16 21:38 UTC
### What happened?

Creating a brand new IDE drive and installing with a brand new machine is successful in formatting the drive and copying the MS-DOS 6.22 files over to it, but the machine is unable to boot. Says missing operating system.. seems to be the case with a variety of them. Bios settings are at "default" other than auto-detect drives.

### Configuration file
```ini
[General]
vid_renderer = qt_software
dpi_scale = 0
confirm_save = 0
force_43 = 1
video_filter_method = 0
hide_status_bar = 1
hide_tool_bar = 1

[Machine]
machine = win486pci
cpu_family = i486dx
cpu_speed = 33333333
cpu_multi = 1
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
fpu_type = internal
mem_size = 4096

[Video]
gfxcard = et4000ax

[Input devices]
mouse_type = none

[Sound]
fm_driver = nuked
mpu401_standalone = 1
sndcard = sbprov2
midi_device = mt32

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = none
cassette_mode = load
scsicard_1 = ncr53c810

[Hard disks]
hdd_01_parameters = 26, 8, 615, 0, ide
hdd_01_fn = C:/Users/Peter/Documents/testali.vhd
hdd_01_speed = 1997_5400rpm
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = none
```

### Operating system

Windows 10

### CPU

Core 2 Duo

### 86Box version

v4.1.1 build 5634

### Build architecture

Windows - x64 (64-bit)

### Build type

- [X] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by TC1995** [comment] 2024-04-16 21:41
Most likely CMOS issue.

**Comment by OBattler** [comment] 2024-04-17 14:09
Is the primary partition set to active?

**Comment by Sunspark-007** [comment] 2024-04-17 17:18
I would hope so considering these are clean installs.. I am aware that if you create a drive image, it doesn't like to be used on another machine.. partly because of CHS stuff.. and wants you to start over again.. that's ok, but if the machine isn't changing, it should boot if it's a new image and the dos disk was able to "see" it to copy the files over.

It's weird, because one I looked at, the files were there, but it said missing operating system. MS-DOS should have made it active, unless there is a different issue.. I will have to test more later.

**Comment by Sunspark-007** [comment] 2024-04-18 21:09
I do think there is something glitchy somewhere..

Made a new IDE drive.. still did the missing operating system bit.. even though it was a fresh install using msdos. After it failed again, I dropped to command prompt mode from the setup disk and looked and it didn't seem to have done anything.. so I manually ran FDISK and made sure it had a partition, set active, etc. After that the setup program installed and the drive booted fine..

So, for whatever reason, with scsi the msdos setup installs on its own with a new image, but with ide, you MAY need to do some manual intervention to help the install along.

**Comment by Teppic1** [comment] 2024-04-19 07:48
Based on your config you have a SCSI controller and an IDE drive set up, which isn't going to work. If this isn't the config you're using you should post that instead.

**Comment by OBattler** [comment] 2024-04-24 01:17
I just repeated the process described here, using the exact configuration provided, and it worked fine. So I'm closing this as "can't reproduce".

**Closed by OBattler** 2024-04-24 01:17 UTC
Labels: bug
