### ISSUE TITLE
[BUG / WORKAROUND] OS/2 2.1 SCSI emulation issue

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#387] opened 2019-05-19 21:13 UTC
This is a repost of the original bug report  (#324) regarding OS/2 2.1 posted on September 28, 2018. I have updated this bug report and provided a workaround to this issue.

Okay. So, I managed to install OS/2 2.1 on both 86Box and PCem v15. I installed the built in Super VGA driver for the Tseng ET4000AX emulated graphics card. However, when I tried to install the Multimedia Presentation Manager/2 v1.1 for the Sound Blaster 16 card, OS/2 2.1 fails to load the icons in the desktop background properly.

Here is the output of the screenshots below. The first screenshot is with disk caching enabled:

![With DISKCACHE](https://user-images.githubusercontent.com/32658796/57988025-0875a700-7a3e-11e9-9f35-9b4c51112bf5.png)

The second screenshot is with disk caching disabled:
![DISKCACHE REM'd out](https://user-images.githubusercontent.com/32658796/57988033-19beb380-7a3e-11e9-8055-6470f76bdf17.png)

And I have found a workaround to make OS/2 work by disabling disk caching. If you use the FAT file system, you can boot using a MS-DOS diskette. Simply use the EDIT utility to edit the CONFIG.SYS file. When you do, search for this line below:

"DISKCACHE=512,LW,AC:C"

Add the REM link to disable disk caching: "REM DISKCACHE=512,LW,AC:C"

I hope that this helps. OS/2 2.1 does work on PCem v15. It's just that 86Box has some issues with SCSI emulation.

Machine configuration used:
* DataExpert OPTi-495SX (AMI BIOS running on Intel 486 processor running at 33 MHz), dynarec disabled
* 8 MB RAM (7,808 KB usable, 640 KB base, 7,168 KB extended)
* Tseng ET400AX display card with 1 MB display RAM
* Logitech Serial Mouse on COM port 1 with two buttons
* Sound Blaster 16 ISA card (address: 0x220, MPU-401: 0x330, IRQ: 5, Low DMA channel: 1, High DMA channel: 5, OPL enabled, Roland MT-32 emulation)
* no network
* Parallel port and serial port, all LPT devices disabled
* Adaptec AHA-1542C SCSI Adapter (address: 0x334, IRQ: 9, DMA channel 6, BIOS address: D000H), hard disk controller disabled
* 200 MB SCSI hard disk on ID 0 (800 cylinders, 16 heads, 32 sectors per track)
* 1.44 MB 3.5" floppy drive.

Anyways, please investigate what could be causing this. Thank you for your time.

**Comment by dhrdlicka** [comment] 2019-05-19 22:53
Why not just add the information to the original issue? __Duplicate of #324.__

**Closed by dhrdlicka** 2019-05-19 22:53 UTC
Labels: duplicate
