### ISSUE TITLE
Original Maniac Mansion Sound is off on Tandy 1000 systems

### ISSUE THREAD

**Issue by jznomoney** [86Box/86Box#4700] opened 2024-08-07 20:01 UTC
### What happened?

The sound is wrong being outputted on the latest 86box rev. 4.2.1 build 6044.  I have attached what it should sound like and what it sounds like.  I had a tandy 1000 hx back in the day and I know it sounds wrong.
[86box-Maniac.zip](https://github.com/user-attachments/files/16533491/86box-Maniac.zip)
[Good Version-Maniac.zip](https://github.com/user-attachments/files/16533494/Good.Version-Maniac.zip)

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = AMD Ryzen 9 7900X 12-Core Processor            
emu_build_num = 6044
uuid = 147e066d-e4b4-5e93-8079-be4da823af03

[Machine]
machine = tandy1000hx
cpu_family = 8088
cpu_speed = 4772728
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
mem_size = 640

[Video]
gfxcard = internal

[Input devices]
mouse_type = none

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = none
cassette_mode = load

[Floppy and CD-ROM drives]
fdd_01_type = 35_2dd
fdd_02_type = none
fdd_01_fn = G:/Emulators/pcem/maniac.IMA
```

### Operating system

Windows 11

### CPU

Ryzen 7900x

### 86Box version

4.2.1 Build 6044

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [X] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

I'm not sure when this started happening because the official stable 4.2 build doesn't allow me to run maniac mansion.  even with the ram set to 640k it complains that it needs 384k or more.

**Comment by Digitoxin1** [comment] 2024-08-07 21:47
Just confirmed.  Sound is not correct in 86Box 4.2 build 6000 and is even worse in build 6044.

**Comment by Digitoxin1** [comment] 2024-08-07 22:03
Just tested in 3.11 build 4311.  Sound is not correct in this version either.

**Comment by OBattler** [comment] 2024-08-07 23:00
Test further: https://ci.86box.net/ . We have builds going all the way back to build 885 of July 2017.

**Comment by OBattler** [comment] 2024-08-07 23:06
Seems to sound fine on build 1830 from 2019.

**Comment by Digitoxin1** [comment] 2024-08-07 23:12
> Seems to sound fine on build 1830 from 2019.

I'm not getting proper sound with build 1830

**Comment by OBattler** [comment] 2024-08-07 23:14
What configuration are you running it on? Bacause I am getting proper sound there.

**Comment by Digitoxin1** [comment] 2024-08-07 23:20
`[General]
host_cpu = AMD Ryzen 9 3900X 12-Core Processor            
emu_build_num = 6000
uuid = 4ec7edd7-1151-5c33-8b5b-a808484b382c
force_43 = 1

[Machine]
machine = tandy
cpu_use_dynarec = 0
time_sync = local

[Other peripherals]
hdc = none

[Video]
gfxcard = internal

[Input devices]
mouse_type = none`

**Comment by Digitoxin1** [comment] 2024-08-07 23:22
No idea why it says emu_build_num = 6000, I'm definitely running 1830.  Must be remnants from newer version.

**Comment by OBattler** [comment] 2024-08-07 23:24
I'm testing it on the Tandy 1000 HX, it seems to work properly there.

**Comment by OBattler** [comment] 2024-08-07 23:25
They appear to have a different sound chip - SN6489 vs. NCR8496. Which Tandy was this game made for?

**Comment by Digitoxin1** [comment] 2024-08-07 23:28
> They appear to have a different sound chip - SN76489 vs. NCR8496. Which Tandy was this game made for?

Original Tandy 1000.  It sounds fine on my Tandy 1000 SX.

**Comment by OBattler** [comment] 2024-08-07 23:39
Does it sound correctly on DOSBox-X?

**Comment by Digitoxin1** [comment] 2024-08-07 23:54
> Does it sound correctly on DOSBox-X?

Yes

**Comment by OBattler** [comment] 2024-08-07 23:56
Also, what exactly do you mean by does not sound properly on build 1830?

**Comment by Digitoxin1** [comment] 2024-08-08 00:08
[Maniac_Mansion_Bad_Tandy_1000_SX_Audio_.Build_5634_and_Below.zip](https://github.com/user-attachments/files/16535934/Maniac_Mansion_Bad_Tandy_1000_SX_Audio_.Build_5634_and_Below.zip)

**Comment by OBattler** [comment] 2024-08-08 00:09
That's not how it sounds on 1830 for me... or on 4311, for that matter.

**Comment by OBattler** [comment] 2024-08-08 00:13
Also, I'm trying it on the 1000 HX, I can't try it on the SX because the SX doesn't have DOS in ROM.

**Comment by Digitoxin1** [comment] 2024-08-08 00:18
> Also, I'm trying it on the 1000 HX, I can't try it on the SX because the SX doesn't have DOS in ROM.

SX and HX sound different in build 1830.  HX sounds correct in build 1830.  Build 5634 throws and error when you try to run the game on an HX so I can't test it there.

**Comment by OBattler** [comment] 2024-08-08 00:24
They emulate a different chip - the SX emulates the TI SN, the HX emulates the NCR. Which of the two chips did your real Tandy have?

**Comment by Digitoxin1** [comment] 2024-08-08 00:24
> They emulate a different chip - the SX emulates the TI SN, the HX emulates the NCR. Which of the two chips did your real Tandy have?

TI SN

**Comment by Digitoxin1** [comment] 2024-08-08 00:25
In the latest development build, the game sounds equally wrong on all three Tandy models, but not the same as earlier builds

**Comment by OBattler** [comment] 2024-08-08 00:47
Can you upload a VM so I can test this on the Tandy 1000 SX please?

**Comment by Digitoxin1** [comment] 2024-08-08 01:01
Here is a configuration file with a hard drive image with Maniac Mansion installed on it.  I put a batch file in the root to quickly launch the game (MANIAC.BAT)
[86Box_ManiacMansion_test.zip](https://github.com/user-attachments/files/16536308/86Box_ManiacMansion_test.zip)

**Comment by Digitoxin1** [comment] 2024-08-08 01:03
Here is a configuration file with a hard drive image with Maniac Mansion installed on it. I put a batch file in the root to quickly launch the game (MANIAC.BAT)
[86Box_ManiacMansion_test.zip](https://github.com/user-attachments/files/16536315/86Box_ManiacMansion_test.zip)

**Comment by Digitoxin1** [comment] 2024-08-08 01:05
Looks like this commit changed the audio.  It didn't fix it, but it is now broken in a different way than the audio clip I posted above.
[https://github.com/86Box/86Box/commit/9135083877dbb22a37016e6381b97b9992f3994f](https://github.com/86Box/86Box/commit/9135083877dbb22a37016e6381b97b9992f3994f)

**Comment by Digitoxin1** [comment] 2024-08-08 01:09
The audio is currently broken on the Tandy 1000 HX in the latest development build.  I currently sounds just like the SX.  I cannot determine when the audio stopped working correctly on the HX since the game would not launch on the HX in recent builds until this commit.

[https://github.com/86Box/86Box/commit/608165295bd49eb52188b8e7cc1a410ccd880c93](https://github.com/86Box/86Box/commit/608165295bd49eb52188b8e7cc1a410ccd880c93)

**Comment by OBattler** [comment] 2024-08-08 01:18
Yeah, I have that breakage fixed on my end. I just wonder why it sounds wrong on the TI SN.

**Comment by Digitoxin1** [comment] 2024-08-08 01:23
It hasn't been brought up yet, but it also sounds wrong on the SL/2

**Comment by OBattler** [comment] 2024-08-08 04:27
Yes, they all use the same code. Now, as I said, I do have HX and SL/2 sounding correctly, but I have no idea how to make the SX also sound correctly, short of giving it the NCR chip like DOSBox-X does.

Also, do you have any recording of it from the real Tandy 1000 SX?

**Comment by Digitoxin1** [comment] 2024-08-08 05:13
This was a serious pain in the butt to record.  First, I had to rig up a franken-cable to get the audio from the audio out jack on the back of the Tandy to the line in on my PC across the room.  The Tandy 1000 SX has a rudimentary mixer.  At first I was not getting audio out through the line out from Maniac Mansion.  It turns out Lucasfilm games did not set the appropriate bit to enable the line out, so I had to launch a Sierra game first to enable the line out on the Tandy before I launched Maniac Mansion.   Anyway, here is a recording of the opening theme,

[ManiacMansionV1_Theme.zip](https://github.com/user-attachments/files/16537944/ManiacMansionV1_Theme.zip)

**Comment by Digitoxin1** [comment] 2024-08-08 06:41
To make things more complex, I was doing some research and found out the Tandy 1000 SX can either use an NCR8496 or an SN76496.  I will need to open up my Tandy to figure out which chip it is using.  Also, I discovered this blog entry with audio samples and his PCjr recording sounds like the "bad" audio from 86Box.  It is possible this is not a bug.

[https://nerdlypleasures.blogspot.com/2015/10/the-journey-of-pcjrtandy-sound-chip.html](https://nerdlypleasures.blogspot.com/2015/10/the-journey-of-pcjrtandy-sound-chip.html)

Because the Tandy 1000 SX started shipping with the NCR8496 and the NCR8496 was the chip Tandy used moving forward, maybe the best course of action is to use the NCR8496 for the Tandy 1000 SX leaving the SN76496 for the PCjr and original Tandy 1000 emulation if it is ever added to 86Box.

**Comment by Digitoxin1** [comment] 2024-08-08 13:56
I messaged Aaron Giles, the author of the DREAMM emulator.  He says he is emulating the SN76496.  The sound is correct in DREAMM.

**Comment by OBattler** [comment] 2024-08-08 15:41
Is he emulating it correctly, however?

**Comment by OBattler** [comment] 2024-08-08 15:49
Well, it turns out we have no way of knowing that since DREAMM is not open-source. So he could well be mistakenly emulating it as a NCR. The recordings on the site above from the real hardware, IMHO, confirm the difference.

**Closed** 2024-08-08 16:56 UTC
Labels: bug
