### ISSUE TITLE
Add Packard Bell PB800 (without Yamaha onboard audio)

### ISSUE THREAD

**Issue by TheDell1998** [86Box/86Box#3164] opened 2023-03-02 03:26 UTC
I would like the Intel 440LX-based Slot 1 Packard Bell PB800 (without Yamaha onboard audio) Intel AL440LX (Atlanta) and it has a PhoenixBIOS with Packard Bell logo, and working ACPI. That Packard Bell should be easiest to add in 86Box.

**Comment by pankoza-pl** [comment] 2023-03-02 06:56
the AL440LX BIOS requires I/O-APIC, which is not emulated, so no
The Packard Bell Phoenix (Via Apollo 133) is a better idea

**Comment by TheDell1998** [comment] 2023-03-02 07:06
> the AL440LX BIOS requires I/O-APIC, which is not emulated, so no The Packard Bell Phoenix (Via Apollo 133) is a better idea (now i posted this reply on the right issue, that's why i should look where i post, especially when tired...)
Oh really? So you're adding the Packard Bell Phoenix to your 86Box?

**Comment by TheVirtualComputer** [comment] 2023-03-02 07:18
Is there any reason why I/O-APIC can't be added?

> the AL440LX BIOS requires I/O-APIC, which is not emulated, so no The Packard Bell Phoenix (Via Apollo 133) is a better idea (now i posted this reply on the right issue, that's why i should look where i post, especially when tired...)

Is there any reason why I/O-APIC can't be added? Obviously it would require some work, but I don't see any technological reason why it can't theoretically be added sometime in the future.

**Comment by Cacodemon345** [comment] 2023-03-02 07:31
I/O APIC requires emulation of Local APIC as well, and the latter is far more complicated to do an implementation of than the former.

**Comment by TheVirtualComputer** [comment] 2023-03-02 08:02
Are there any documents (i.e. datasheets) available for this feature (Local APIC, that is)?

**Comment by Cacodemon345** [comment] 2023-03-02 08:04
Local APIC documentation is in the Intel IA-32 architecture documentation, volume 2.

**Comment by TheDell1998** [comment] 2023-03-02 16:33
You should add I/O APIC emulation of Local APIC as well.

**Comment by OBattler** [comment] 2023-03-10 06:05
I don't think the AL440LX requires the APIC. If anything, the problem is that it has an Intel Phoenix BIOS and those tend not to work on 86Box, and I have no idea why. As such, I'm closing this.

**Closed by OBattler** 2023-03-10 06:05 UTC
Labels: feature
