### ISSUE TITLE
i430HX Chipset Drivers Don't Work in an Asus P/I-P55T2P4 VM

### ISSUE THREAD

**Issue by pgalbraith** [86Box/86Box#2950] opened 2022-12-07 01:57 UTC
**Describe the bug**

i430HX chipset drivers don't seem to work in a Win 95 OSR 2.0 system running in an Asus P/I-P55T2P4 VM.  I can install the drivers (apparently successfully) but they just don't seem to work.  After install and reboot, hard drive access ceases soon after the boot process begins.  Booting to safe mode and deinstalling the chipset drivers restores all funtionality, but I was expecting that these drivers should work for this board.

**To Reproduce**
1. Install Win95 OSR 2.0
2. Install i430HX drivers
3. reboot
4. death

**Expected behavior**

I was trying to install them to clear up an unknown device showing in device manager, so clearing that up is the dream!

**Desktop (please complete the following information):**

Host; Win 11
86Box: 3.7.1, 3.11, latest few dailies (to 2022-12-05)

**Additional context**

Apologies if you don't think this should work in the first place!

**Comment by jadasse** [comment] 2022-12-07 12:57
It's recommended to list the exact build numbers you've used.

**Comment by pgalbraith** [comment] 2022-12-07 14:28
I can retry again and get specific builds if it helps, but it seems clear to me that after trying the latest two formal releases (both x32 and x64) and several dailies, the behavior is broad enough across many versions that the 3.7.11 and 3.11 release should be enough to duplicate for anyone who tries.  If it really helps of course please let me know, I'm happy to do this.

**Comment by OBattler** [comment] 2022-12-19 14:50
Which drivers exactly are you using?

**Comment by pgalbraith** [comment] 2022-12-22 23:53
I tried these two:
- https://www.philscomputerlab.com/intel-chipset-drivers.html (first in the list)
- https://theretroweb.com/chipsets/276 (from the downloads link)

If memory serves, I think these looked like they were pretty much the exact same driver release provided from both sources.

**Comment by OBattler** [comment] 2022-12-23 03:45
Can I see your 86box.cfg file?

**Comment by pgalbraith** [comment] 2022-12-25 17:25
Sure, attached.
[86box.zip](https://github.com/86Box/86Box/files/10300417/86box.zip)

**Comment by OBattler** [comment] 2023-11-08 05:07
I can't reproduce this ont he latest build so I'm going to assume it's now fixed.

**Closed** 2023-11-08 05:07 UTC
Labels: bug
