### ISSUE TITLE
Windows NT 4.0 random crashes and not 

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#4135] opened 2024-02-08 02:00 UTC
### What happened?

I installed Windows NT  4.0. After the installation finished, I found random crashes. I don't sure if they are related to CD-ROM. 
But when I clicked on "My PC" I got a blue screen with an error saying "not less or equal", (but now is a different blue screen). 

Here is a screenshot and a screen capture:
https://drive.google.com/file/d/1oAAJsSBbFyf5hN8c_aqfw9o4ONNo9lqI/view?usp=sharing

![Monitor_1_20240207-225239-936](https://github.com/86Box/86Box/assets/31600563/0444bf19-1b21-4137-b6cf-c11324ad6dc4)

Here is the VM: (CFG,HDD,NVR)
https://drive.google.com/file/d/1eEIMQgbckb5QCHdCf3EMOZg2sIjNMW9i/view?usp=sharing

### Configuration file

```ini
[General]
vid_renderer = qt_software
vid_resize = 1

[Machine]
machine = ap61
cpu_family = pentiumpro
cpu_speed = 90000000
cpu_multi = 1.5
fpu_type = internal
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
mem_size = 32768

[Video]
gfxcard = et4000w32p_nc_pci

[Input devices]
mouse_type = ps2

[Sound]
sndcard = sb16_pnp
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Ports (COM & LPT)]
lpt1_device = text_prt

[Storage controllers]
hdc = none
cassette_mode = load
scsicard_1 = ncr53c820

[Hard disks]
hdd_01_parameters = 63, 16, 2000, 0, scsi
hdd_01_fn = 
hdd_01_speed = 1996_5400rpm
hdd_01_vhd_blocksize = 1024
hdd_01_scsi_location = 0:00

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = 525_2hd
cdrom_01_parameters = 1, scsi

cdrom_01_type = NEC_CD-ROM_DRIVE75_1.03

[Tseng Labs ET4000/w32p Rev. D PCI]
memory = 2
```

### Operating system

Windows 10 22H2

### CPU

i5 4210U

### 86Box version

4.1.0.5471

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by TC1995** [comment] 2024-02-08 12:12
It's because the NEC SCSI CD-ROM drive isn't really liked by NT 4.0's cdaudio.sys driver, rename cdaudio.sys to cdaudio.old.

**Comment by OBattler** [comment] 2024-02-09 17:47
Then this can be closed as NOTABUG, at least not a bug on our side.

**Closed by OBattler** 2024-02-09 17:47 UTC
Labels: bug
