### ISSUE TITLE
Clicks of sound

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#721] opened 2020-04-24 08:08 UTC
Clicks of sound appeared in build 2224. This is especially noticeable after loading MS-DOS on any motherboards with Sound Blaster 16 and Fluidsynth enabled. I use build 2094, because bug https://github.com/86Box/86Box/issues/586 has not yet been fixed. Build 2094 does not have these clicks of sound. Can you fix these bugs?

**Comment by OBattler** [comment] 2020-04-24 14:07
Can you do some bisecting to see which exact build introduced the clicks?

**Comment by maximus105** [comment] 2020-04-24 16:48
Clicks of sound appear if you enable Disney Sound Source on LPT1 (both on build 2094 and build 2228). If you do not turn on Disney Sound Source on LPT1, then there is no sound click after loading MS-DOS. However, if you run games like Dyna Blaster, Wolf3D, and then exit them in MS-DOS then the clicks of sound will appear again (even when Disney Sound Source is turned off on LPT1). This is observed on:
[386DX VLB] Award 386DX Clone, i386DX/40
[486 PCI] Rise Computer R418, i486DX2-40
[Socket 7 HX] ASUS P/I-P55T2P4, Pentium MMX-166

**Comment by OBattler** [comment] 2020-04-27 01:14
Yes but which 86Box build introduced these clicks that also appear with the Disney Sound Source turned off?

**Comment by maximus105** [comment] 2020-04-27 07:03
I checked the builds: 1900, 1800, 886. In all these assemblies there are clicks of sound when Disney Sound Source is turned off.

**Comment by maximus105** [comment] 2020-04-30 16:49
The following is written in AUTOEXEC.BAT:
SET BLASTER=A220 I5 D1 H5 P330 T6
![2020-04-30_194622](https://user-images.githubusercontent.com/58270614/80737088-afeacd00-8b1b-11ea-9fce-95c64f01ae4e.jpg)

**Comment by maximus105** [comment] 2020-06-23 16:23
https://drive.google.com/file/d/1k6_OUEI83q5v-Xt8V4vssuXeKxZ3OYUy/view?usp=sharing
Here is the latest build 2385 configured. Run wolf3d.exe from the WOLF3D folder or diagnose.exe from the SB16 folder, and then exit to MS-DOS and sound clicks will appear.

**Comment by mgtroyas** [comment] 2021-06-16 09:38
That's actually a bug on real hardware:
https://www.youtube.com/watch?v=tH0TCgkY24A
https://www.vogons.org/viewtopic.php?t=50071

**Comment by OBattler** [comment] 2021-07-16 05:05
Since this has been confirmed to occur on real hardware as well, I'm closing this.

**Closed by OBattler** 2021-07-16 05:05 UTC
Labels: bug
