### ISSUE TITLE
User interface not showing on Linux

### ISSUE THREAD

**Issue by IDeletedSystem64** [86Box/86Box#1962] opened 2021-12-24 02:20 UTC
**Describe the bug**

The interface and menus don't load when starting 86Box

**To Reproduce**

1. Compile v3.1 from source
2. Launch 86Box (I use a bash script to launch configurations I've made, though this hasn't made a difference in the issue)

**Expected behavior**
The interface and menus are loaded and working

**Screenshots**
![Screenshot_20211223_200506](https://user-images.githubusercontent.com/47640864/147307792-5de8d4cc-f66a-4ab0-944a-63e0101064b3.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 x64 Arch Linux w/ KDE Plasma 
 
 - 86Box version: [e.g. v3.00 build 3333; saying "Latest from Jenkins" isn't helpful]
 v3.1, Build 3402
 - Build information: [i.e. new/old dynarec, architecture and build type]
 Unsure on the dynarec, x64 
 -

**Additional context**
Add any other context about the problem here. If you are using an Optimized build, make sure to try the regular build too before filing a bug report!

**Comment by Cacodemon345** [comment] 2021-12-24 05:30
The interface isn't even implemented yet on Linux.

**Comment by OliverLew** [comment] 2021-12-25 09:34
Is there any references/documentations for Linux users to modify the configuration files? The [documentation here](https://86box.readthedocs.io/en/latest/index.html) doesn't list any details, only leads the users to the GUI which Linux does not have for now. I don't know, for example, available `cpu_family`, or options not present in auto-generated `86box.cfg`.

**Comment by dhrdlicka** [comment] 2021-12-25 10:22
The user interface does not show up because there isn't one yet in the first place. You can use the built-in monitor when launching 86Box from a terminal to mount disk images.

As mentioned, there is also a Qt port in progress. For more information about that, check the UI rewrite thread in the #86box-dev Discord channel.

Closing this issue since this is intended behavior.

**Closed by dhrdlicka** 2021-12-25 10:22 UTC
Labels: notabug
