### ISSUE TITLE
Adding Shared Folders ???

### ISSUE THREAD

**Issue by OltScript313** [86Box/86Box#557] opened 2020-01-17 16:18 UTC
Why not, be able to add shared folders with a folder (or an entire hard drive perhaps)...

Buuuut I think there might be compatibility issues with the file system and the capacity and guest operating system (Windows 95/98, for example)...

Why Not ?! :o

**Comment by dhrdlicka** [comment] 2020-01-17 16:34
Duplicate of #187

**Closed by dhrdlicka** 2020-01-17 16:34 UTC
Labels: duplicate
