### ISSUE TITLE
Fullscreen only opens on primary monitor, not secondary

### ISSUE THREAD

**Issue by x6herbius** [86Box/86Box#1225] opened 2021-01-15 18:43 UTC
**Describe the bug**
If I have the application open on my second monitor and choose to enter fullscreen mode, the fullscreen view is displayed on my primary monitor instead.

The choice of renderer does not appear to affect this bug.

**To Reproduce**
1. Run up a VM (I'm using Windows 98).
2. Move the VM window to a secondary monitor
3. Enter fullscreen mode
4. The VM will be displayed in fullscreen on the primary monitor.

**Expected behavior**
The VM fullscreen should be displayed on the same monitor as the VM window, or should at least provide an option to choose which monitor to display on.

**Desktop (please complete the following information):**
 - Windows 10 on Dell XPS 15 9570
 - 86Box version: v2.07 [245af88d, build 2008]
 - Build type: optimized for Skylake (also reproducible on non-optimised build)

**Additional context**
This is also reproducible on non-optimised build.

**Comment by OBattler** [comment] 2021-03-08 21:56
I myself only have one monitor, so I have no way of testing this. I'm going to need someone who can actually test this, to look into this.

**Comment by OBattler** [comment] 2021-09-22 15:33
Closing this for being a duplicate of the following issue: https://github.com/86Box/86Box/issues/404 .

**Closed by OBattler** 2021-09-22 15:33 UTC
Labels: bug
