### ISSUE TITLE
[BUG] Crystal Stacker v1.41 doesn't work at all in 86Box

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#602] opened 2020-02-24 02:26 UTC
Okay, I have run into this bug regarding Crystal Stacker version 1.41 for DOS for a while. When I attempted to run the game on the SX495 (running at 80486DX2 emulation at 66 MHz) with QEMM 7.53 installed, the game will crash and throw an Exception #13 error stating that the emulated machine attempted to execute an invalid instruction due to a programme error:

![20200224-020634-628](https://user-images.githubusercontent.com/32658796/75125146-8f5c4d80-5668-11ea-8780-78f6ca21bbb7.png)

I had to clean boot from the 1.44 MB floppy disk image with no expanded memory manager present. The good thing is that I get the "NewCreature Design" presents splash screen and moments after the splash screen disappears, Crystal Stacker crashes and throws a General Protection Fault with the following information:

![20200224-020402-086](https://user-images.githubusercontent.com/32658796/75125264-26c1a080-5669-11ea-8526-8851508a0d75.png)

The game can be found on the  T³ Interactive, you can download the freeware game here: http://www.t3-i.com/pages/project.php?id=crystal_stacker

The README.TXT file states that the game requires a 80486 processor and a VGA or better graphics card/processor.

My updated 86Box.cfg file can be found here, because I changed to using a PostScript printer: https://pastebin.com/2aPiGTSM

I can't seem to remember which build of 86Box caused this issue. Can anyone do some research and testing to see what is causing Crystal Stacker to not work at all under 86Box?

**EDIT:** I should have been more clear, but when I ran the game from a 2.88 MB floppy disk on a test VM, the game exits. do to "signal SIGSEGV" (segmentation fault).

Thank you for your time.

**Comment by ppgrainbow** [comment] 2020-04-19 21:58
I managed to get Crystal Stacker working by adding the Sound Blaster 16 environment:

[code]SET SOUND=C:\SB16
SET BLASTER=A220 I5 D1 H5 P330 T6
SET MIDI=SYNTH:1 MAP:E[/code]

The path for the SB16 card assumes if you have the installed the drivers for Sound Blaster 16. If not, only the SET BLASTER and SET MIDI variables can be added.

I'm also wondering if Crystal Stacker v1.41 has compatibility issues with QEMM386 or not. IF so, then, I suspect that this is going to either be marked as NOTABUG or WONTFIX.

:

**Comment by OBattler** [comment] 2020-04-20 00:50
Changed this to not a bug and closing since the game is simply incompatible with QEMM386.

**Closed by OBattler** 2020-04-20 00:50 UTC
Labels: notabug
