### ISSUE TITLE
Add the Suntac 286 machine

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1558] opened 2021-07-20 00:12 UTC
**Is your feature request related to a problem? Please describe.**
No. I recently found some diagrams of the Suntac 286 machine and also the EMS drivers, some of them have the source code.
I don't know if can be implemented or which BIOS correspond to this chipset, (seems to be ST62C005-B and ST62C006)

**Describe the solution you'd like**
To implement this Suntac 286 machine if it is possible.

Here is some documents abount the chipsets, (I don't know if the information is enought).

[ST62C005-B_GSTechnology.pdf](https://github.com/86Box/86Box/files/6844414/ST62C005-B_GSTechnology.pdf)
[ST62C006_GSTechnology.pdf](https://github.com/86Box/86Box/files/6844416/ST62C006_GSTechnology.pdf)

Here is the manual with diagrams of the board at the end of the book:
[Suntac TCI EMS-286.pdf](https://github.com/86Box/86Box/files/6844420/Suntac.TCI.EMS-286.pdf)

Here are the EMS drivers:
The first is an  old 1987 driver, it may be a LIM EMS 3.2 driver with source in ASM file format
[EMS_SUNTAC-62-B1_v1.02.zip](https://github.com/86Box/86Box/files/6844425/EMS_SUNTAC-62-B1_v1.02.zip)

The following image file contains various drivers: 
The Sems4-5.arj contains the .SYS files and DEF and ASD files which contain explanations of its functions. They seems to be LIM 4.0
[SUN-EMS.ZIP](https://github.com/86Box/86Box/files/6844488/SUN-EMS.ZIP)

There is also a SUNTAC.SYS file with a size of  19,437 KB it is dated September 8, 1990, but  I think it is for a different chipset 
it says  "SUNTAC Super286/SuperSX/LCAT"

There are several ROM BIOS for Suntac 286 machines in the Vogons site but I don't know which of them are designed for the
ST62C005-B and ST62C006 chipsets.
Here is the link: [https://www.vogons.org/viewtopic.php?f=46&t=53419](url)

**Comment by OBattler** [comment] 2021-07-20 03:58
Closing this because it's a duplicate of: https://github.com/86Box/86Box/issues/334 .

**Closed by OBattler** 2021-07-20 03:58 UTC
Labels: feature
