### ISSUE TITLE
Blink VGA function in IBM PS/2 does not work

### ISSUE THREAD

**Issue by Notchmaster** [86Box/86Box#3447] opened 2023-07-03 05:16 UTC
**Describe the bug**
When turning on WYSIWYG mode on Lotus 1-2-3 Release 2.3, or launching Lotus 1-2-3 Release 2.4 where WYSIWYG mode is enabled by default, the screen becomes white and is non functional

**To Reproduce**
1. Launch Lotus 1-2-3 Release 2.3
2. Press / to make the menu appear
3. Go to add-in
4. Attach
5. select WYSIWYG.adn
6. No key

**Expected behavior**
The screen should've stayed the same color (https://youtu.be/jHUaneVUkfQ as the video here).
I found a temporary remedy that always gets reset when the application is started
1. Open the WYSIWYG menu (:)
2. Go to display
3. Options
4. Adapter
5. Navigate to blink, and then turn blink off
This may be as help, as the issue seems to be happening related to "blink"

**Screenshots**
![image](https://github.com/86Box/86Box/assets/49874751/e4fe8e3e-a5c6-49e2-868f-06bcfe99f376)
Without WYSIWYG

![image](https://github.com/86Box/86Box/assets/49874751/015b9c22-7dd2-4ddd-97e1-55e735eb7418)
With WYSIWYG (it should've looked like without WYSIWYG, here the program is not operational where the menu and any input to the cells is not visible)

![image](https://github.com/86Box/86Box/assets/49874751/bb76bf0a-7e69-4468-bbfe-a8b07359583d)
With WYSIWYG with Blink turned off (this is how it should look like)

**Desktop (please complete the following information):**
 - OS: Windows 11 64-bit
 - 86Box version: [v3.11 build 4311]
 - Build information: [IBM PS/2 model 80 (type 3), i386DX on 25 speed, 387 FPU, 4 MB ram, Internal VGA controller on display, SCSI 120 MB hard drive]

**Comment by TC1995** [comment] 2023-07-04 17:46
Does it work on non-IBM PS/2 VGA?

**Comment by Notchmaster** [comment] 2023-07-06 06:25
I have another 86box vm that uses a vastly different set of hardware configuration, and it does have the same issue
![image](https://github.com/86Box/86Box/assets/49874751/1cda78ff-a35d-40ec-a85e-ec6c80a499c6)
This VM uses an i486DX-100 and an S3 968 4 MB GPU, with 64 MB of RAM, and it exhibits the same issue

**Comment by OBattler** [comment] 2023-08-14 15:57
In graphics modes, the behavior is by definition dependent on the video BIOS. Try something like an AT with IBM VGA and see if it works there.

**Comment by iamgreaser** [comment] 2023-11-21 05:25
Does it support 640x350 EGA mode? If so, try that **with an "[IBM] EGA" video card** - that should emulate blink in graphics modes somewhat sanely, although I suspect my handling of plane 3 is incorrect here. I'm currently trying to get a bunch of stuff fixed for VGA and SVGA which should emulate blink properly when I'm done fixing stuff up.

To clarify, blink behaviour in EGA-style *graphics* modes toggles bit 3 of the colour according to the blink clock. I don't know how it combines with the plane 3 data (I implemented it as an XOR but I suspect it actually overrides the contents of plane 3), but this will be a good test case for the proper behaviour.

**Comment by OBattler** [comment] 2023-11-21 07:49
> I have another 86box vm that uses a vastly different set of hardware configuration, and it does have the same issue ![image](https://user-images.githubusercontent.com/49874751/251362679-1cda78ff-a35d-40ec-a85e-ec6c80a499c6.png) This VM uses an i486DX4-100 and an S3 968 4 MB GPU, with 64 MB of RAM, and it exhibits the same issue

Wait for the latest 86Box build to compile and see if this issue is fixed on it.

**Comment by iamgreaser** [comment] 2023-11-21 21:19
I've tested with the latest code and it seems to blink between what you'd actually want and that grey screen.
Looks like graphics blink mode is going to need more research - it's definitely a feature, and it's a requirement for mode 0Fh / SCREEN 10, but it's not well documented.

**Comment by OBattler** [comment] 2023-11-22 15:48
Can you upload the VM so this can be reproduced?

**Comment by iamgreaser** [comment] 2023-11-22 22:56
Here's an 86Box VM with DOS 3.31 and Lotus 1-2-3 release 2.3 on an SX495 w/ MR BIOS and a 100 MHz 486-DX4.

[lotus-blink.zip](https://github.com/86Box/86Box/files/13444827/lotus-blink.zip)

Launching 1-2-3 is as simple as 1-2:

1. `cd 123r23`
2. `123`

From there, follow the instructions of the original post. Alternatively: / a a right right right right enter enter

**Closed** 2023-11-23 07:28 UTC
Labels: bug
