### ISSUE TITLE
86Box 3.8.0.4259 S3Virge 325 Did not work Windows 95 OSR 2

### ISSUE THREAD

**Issue by GLwd40** [86Box/86Box#2853] opened 2022-11-12 16:38 UTC
**Describe the bug**
I installed Windows 95. PCI S3 Virge 325 graphics card.
In 86Box version 3.7.1 the card is correctly detected and there is no problem with the installation.

After updating to version 3.8.0.4259, the system does not detect it. There is no way to install it.

**To Reproduce**
1. Install Win95 OSR 2 on version 3.7.1 -> Intel pentium 90, I430nx, Gigabyte GA-586IP, 32 MB RAM
2. Upgrade to 3.8.0.4259

**Screenshots**
![Monitor_1_20221112-164317-194194](https://user-images.githubusercontent.com/118068422/201483987-a70d87e5-b058-4a4f-ac9c-1b4e6a866a68.png)
![Monitor_1_20221112-170653-621621](https://user-images.githubusercontent.com/118068422/201483989-87cc8fa7-4005-48b4-bd05-92ab9c02d8d5.png)
![Monitor_1_20221112-170727-04004](https://user-images.githubusercontent.com/118068422/201483990-e07e56a3-af98-4ad6-96d1-4fb82a7a71ba.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: 86Box 3.8.0.4259 
 - Build information: x32

Cfg File.

[86box.zip](https://github.com/86Box/86Box/files/9995423/86box.zip)

**Comment by TC1995** [comment] 2022-11-12 19:40
Could you try re-installing the pci bus driver first?

**Comment by GLwd40** [comment] 2022-11-13 09:52
yes, but it does nothing.

Only when I start the wizard of adding new hardware, the S3 card and the bus are detected. But still with an exclamation mark.
![Monitor_1_20221113-104328-455455](https://user-images.githubusercontent.com/118068422/201515924-f618f6ba-a60e-4e5e-a096-a159a7196021.png)
![Monitor_1_20221113-104708-728728](https://user-images.githubusercontent.com/118068422/201515925-330f0dec-ad3d-4b0a-8094-59bedd85497c.png)

**Comment by TC1995** [comment] 2022-11-13 11:24
try looking for conflicts in the device manager because I can't reproduce the issue here (on my end).

**Comment by GLwd40** [comment] 2022-11-13 14:06
I found what causes the conflict.
In the PCI bus settings you need to change to use BIOS.

![Monitor_1_20221113-144155-597597](https://user-images.githubusercontent.com/118068422/201525991-d756bfa7-245e-4979-bfc7-799ec9e0452f.png)


In the previous version, it was working on the Use Devices setting.

**Comment by OBattler** [comment] 2022-11-13 16:38
Can you bisect and find out exactly which 86Box build introduced the issue?

**Comment by GLwd40** [comment] 2022-11-13 17:40
I checked on two versions:
Build #4259

Build #4262 -> I have this version installed now.

**Comment by win2kgamer** [comment] 2022-11-13 22:20
I was able to reproduce this issue and after bisecting I found the issue first occurs in build 4207.

**Comment by OBattler** [comment] 2023-08-08 23:40
Does this issue still occur?

**Comment by OBattler** [comment] 2023-08-08 23:42
Actually - I realized what issue this is when I saw the 430NX - yes, the PCI work in build 4207 did indeed break, but this is now fixed with the PCI rewrite caused by RichardG independently discovering the exact same issue.

**Closed by OBattler** 2023-08-08 23:42 UTC
Labels: bug
