### ISSUE TITLE
[BUG] ISA VGA VESA video modes and Neopaint

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#437] opened 2019-10-18 23:30 UTC
I rencently tested some ISA VGA boards, and their respective VESA drivers. And also tested Neopaint DOS software to test which VESA VGA video modes are supported.
The machines I tested are Trigem 286 and AMAJ 386 SX with FPU enabled.

I found several bug: 
1. Video memory is not correctly detected.
A. On OTI-67/77, only 256kb of VRAM detected even with 512k or 1024kb
B. On the recently added HT205, 12mb? of VRAM is detected.

2. Wrong colors on Orchid Fahrenheit 1028 and SPEA Mirage V7. 
3. Video overlapped on some 256 colors 32k/64k video modes.
4. Wrong colors in 16 colors video modes.

Here are the screenshots.

1. HT205 video card
![20191018_201816](https://user-images.githubusercontent.com/31600563/67133955-bc45b300-f1e5-11e9-9967-1ac674873661.png).

2. Orchid Fahrenheit 1028 16 and 256 color modes.

![20191018_202200](https://user-images.githubusercontent.com/31600563/67134270-c23c9380-f1e7-11e9-8bb3-483a3febe1a2.png)

![20191018_202232](https://user-images.githubusercontent.com/31600563/67133993-eb5c2480-f1e5-11e9-8de1-69768d97c19f.png)

3. Tseng ET4000 video card with TLIVESA video driver loaded

![20191018_202532](https://user-images.githubusercontent.com/31600563/67133999-f31bc900-f1e5-11e9-90e9-2e9a5fef37ad.png)
11e9-955a-0b6eac5c7091.png).

Here is a copy of the the VESA drivers, including UNIVESA, a  "universal" vesa driver (it requires  at least a 386 CPU).

https://drive.google.com/open?id=10OO1t_QT5mQ1FgVKSonqxsvRSe1MDHXU

And the installer floppy of Neopaint.
  
https://drive.google.com/open?id=1y0UJi1iJQ536f7fQpxSmzcd2hvAMnOGk

**Comment by TC1995** [comment] 2019-10-19 10:27
Are you sure the 320x200x64k modes are supported on the et4000ax?

**Comment by TC1995** [comment] 2019-10-19 12:09
Also, the S3 pre-864/964 (such as the orchid one and the spea v7 mirage) cards are currently WIP.

**Comment by OBattler** [comment] 2019-10-19 12:11
The S3 cards are known to not be fully compatible with all VESA modes, which is why, for example, the Windows for Workgroups 3.11 256 color drivers fail on them.

**Comment by OBattler** [comment] 2019-10-19 12:12
Also, I remember fixing the 320x200x64k mode once, but the fix might have been lost.

**Comment by OBattler** [comment] 2019-10-19 12:36
> Video memory is not correctly detected.
> A. On OTI-67/77, only 256kb of VRAM detected even with 512k or 1024kb
What are you using to detect the VRAM? Because the BIOS detects it fine.

> B. On the recently added HT205, 12mb? of VRAM is detected.
Same question as above.

> Wrong colors on Orchid Fahrenheit 1028 and SPEA Mirage V7.
No idea what causes those, seems the red channel is missing in 16 color mode, maybe a BIOS bug? While in the 256 color mode, the bottom seems to wrap around, which is strange as the mode fits in 256000 bytes, so even the 256k wrap, if enabled, should not affect it.

> Video overlapped on some 256 colors 32k/64k video modes.
That was a bug in vid_svga_renderer.c, that I have now fixed on my end.

> Wrong colors in 16 colors video modes.
On which card?

**Comment by OBattler** [comment] 2019-10-19 13:13
OK, I misread the Orchid S3 256 color mode, it was 640x480, not 640x400. Then it could have been the 256k wrap, but it's fine on my end, which means it was indeed the banks. 640x480x16 colors also works.

**Comment by OBattler** [comment] 2019-10-19 13:20
How do I get NEOPaint into 320x200x64K mode? It doesn't list it even on an ET4000AX with TLIVESA installed.

**Comment by OBattler** [comment] 2019-10-19 17:16
OK, you were using the ET4000/w32p. Now I can confirm I have indeed fixed those modes.

**Comment by Fenix770** [comment] 2019-10-19 23:20
Hello.
  It seems that The ISA ET4000AX support more video modes than the Trigem Korean VGA with the same amount of ram. However, if you run the TLIVESA driver on the original ET4000AX  the screen becomes green and blue and neopaint can, still, be loaded but you have to work blind.

![20191019_202009](https://user-images.githubusercontent.com/31600563/67152496-e4004e00-f2ad-11e9-90b2-6807608e5a78.png)


As clarification of the earlier
1. I discovered that UNIVESA.EXE  program detects wrong  the memory and board with some VGA cards. I, 
so far tested 


A. OAK 67/77 or TSENG 4000: Detected as Acumos VGA with 256kb.
B. Paradise PVGA1A: Is correctly detected but alwas says it has 256kb.
C. WD90C30-LR: is detected as PVGA1A with 256 kb too. (the 11-LR is detected correctly and has 512kb)

2. Other boards are detected correctly by both UNIVESA.EXE and the Neopaint
But I suspect the wrong colors exist in real harware and it maybe had a buggy implementation of the VBE 1.2 extensions, for two reasons. 

A.The VESA driver for the Fahrenheit 1280 fixes the 16 and 256 color modes. But there was a 32k mode wich still had problems
B. On real hardware, (a K5/166 with a SiS 6205 onborad  video chip with 2mb and VBE 2.0) I can confirm that the 24 bits modes are inverted, altought 16,256 and 64k video modes works ok.

**Comment by OBattler** [comment] 2019-10-20 19:25
I'm going to look more into these video bugs for v2.10, as I suspect major changes might be required to fix someone (and I have major changes for the S3 cards almost done that will be finished and committed when v2.10 starts development).

**Comment by OBattler** [comment] 2024-11-03 04:22
Closing this as stale.

**Closed by OBattler** 2024-11-03 04:22 UTC
Labels: bug, help wanted
