### ISSUE TITLE
ASUS 486SV2G (GX4) Windows 3.11 issue with second IDE controller

### ISSUE THREAD

**Issue by Teppic1** [86Box/86Box#4099] opened 2024-01-29 18:36 UTC
### What happened?

If I add a drive to the secondary IDE controller and set up 32bit access in Win 3.11, Windows gives a warning/error message at start up. Both drives work in DOS.

If the same disk is added to the first controller instead there's no error.

I tried with some other 486 machines using the secondary controller and there's no error.

![DAIRM0l](https://github.com/86Box/86Box/assets/32468801/76711a6f-6dbe-4feb-b6c1-d073a39e9b9b)

### Configuration file

```ini
[General]
vid_renderer = qt_software
force_43 = 1

[Machine]
machine = vli486sv2g
cpu_family = i486dx
cpu_speed = 33333333
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 1
time_sync = local
fpu_type = internal
cpu = 7
mem_size = 8192

[Video]
gfxcard = tvga8900d

[Input devices]
mouse_type = msserial

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = ide_isa_2ch
cassette_mode = load

[Hard disks]
hdd_01_parameters = 17, 15, 900, 0, ide
hdd_01_ide_channel = 0:0
hdd_01_fn = images/msdos6.vhd
hdd_01_vhd_blocksize = 1024
hdd_01_speed = ramdisk
hdd_02_parameters = 17, 15, 900, 0, ide
hdd_02_ide_channel = 1:0
hdd_02_fn = images/storage.vhd
hdd_02_vhd_blocksize = 4096
hdd_02_speed = ramdisk

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_01_turbo = 1
```

### Operating system

Windows 10

### CPU

i7 7500

### 86Box version

5431

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

The motherboard supports dual IDE controllers in the BIOS but doesn't actually have any. Using the internal controller option or dual channel IDE interface option in 86box config doesn't change the result.

**Comment by OBattler** [comment] 2024-01-29 20:03
Closing this as a duplicate of #4060 .

**Comment by Teppic1** [comment] 2024-01-29 20:05
This isn't at all related to https://github.com/86Box/86Box/issues/4060

**Comment by Teppic1** [comment] 2024-01-29 20:13
> Closing this as a duplicate of #4060 .

Can you reopen please. It doesn't seem I am able to.

The bug relates to any ISA/VLC dual channel controller added with a disk on the secondary controller. It's not related to the internal controller issue.

**Comment by OBattler** [comment] 2024-01-29 21:49
I can reproduce this issue. I'm now looking into it.

**Comment by OBattler** [comment] 2024-01-29 21:58
OK, so, this is NOTABUG - at least on our side. We're using a patched BIOS for this machine, dated at some point in 1997, I believe the patch involves exactly adding support for the secondary IDE controller, and it was probably done in a way that's not compatible with Windows 3.1x.

**Closed by OBattler** 2024-01-29 21:58 UTC
Labels: bug

**Comment by Teppic1** [comment] 2024-01-30 00:52
I tried using the last official BIOS (11/03/95-SIS-85C471-I486SV2G-00) and it looks the same - both drives work fine in DOS but Windows gives the same error.

**Comment by OBattler** [comment] 2024-01-30 05:51
Well, this would have to be tested on the real board. I did IDE logging to try to debug this but I saw nothing out of the ordinary there.

**Comment by OBattler** [comment] 2024-01-30 05:55
This mentions one occurrence of this on real hardware: https://groups.google.com/g/comp.os.ms-windows.misc/c/5F5ldNchjCg - apparently, it has to do with the BIOS CHS translation being above 1024 cylinders, which is a bit strange for your configuration where both drives have 900 cylinders but perhaps the BIOS set up the drive to translate from 900 cylinders, 15 heads to something else. But then, why would the problem happen only with secondary IDE?

**Comment by Teppic1** [comment] 2024-01-30 16:24
Yeah looking through that thread it's only about it not working with 1024+ cylinders. As you say everything is fine if you put both drives on the primary controller. Maybe it's a bug in all the BIOS revisions, I'm not sure - this was an early machine to support dual controllers.

I haven't tested other operating systems on this so I don't know if this relates specifically to Windows 3.11's code or something more general.
