### ISSUE TITLE
Tandy 1000 / Tandy 1000 HX - Video corruption after soft reboot (CTRL-ALT-DEL)

### ISSUE THREAD

**Issue by Digitoxin1** [86Box/86Box#4670] opened 2024-07-31 01:10 UTC
### What happened?

When doing a soft reboot from a bootable MS-DOS 5.0 floppy, video corruption occurs.  This happens on Tandy 1000 and Tandy 1000 HX machines.  It does not happen for Tandy 1000 SL-2.

This does not happen on real hardware.

I have attached a screenshoot of the corruption and a floppy image of the boot disk I used.

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = AMD Ryzen 9 3900X 12-Core Processor            
emu_build_num = 6019
uuid = 8c5d14e8-4256-52c0-adb1-ad14b550f135

[Machine]
machine = tandy
cpu_family = 8088
cpu_speed = 7159092
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
mem_size = 640

[Video]
gfxcard = internal

[Input devices]
mouse_type = none

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Ports (COM & LPT)]
serial1_enabled = 0
serial2_enabled = 0

[Storage controllers]
hdc = none
cassette_mode = load

[Floppy and CD-ROM drives]
fdd_02_type = none
```

### Operating system

Windows 10

### CPU

AMD Ryzen 9 3900X

### 86Box version

v4.2.1 build 6019

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

![image](https://github.com/user-attachments/assets/160a72d3-40f6-4fb5-8bfe-578e6cd489e6)
[dos5boot.zip](https://github.com/user-attachments/files/16434941/dos5boot.zip)

**Comment by Digitoxin1** [comment] 2024-07-31 20:11
Just tested with the Tandy 1000 release of MS-DOS 3.30.  Same Issue.

**Comment by Tape-Worm** [comment] 2024-07-31 20:21
I can confirm this as well for Tandy 1000 DOS 3.2.  

However, 2.11 for the Tandy 1000 HX does not exhibit this behaviour, nor does booting from 2.11 in ROM.

**Comment by Fenix770** [comment] 2024-08-03 23:01
I can confirm this also happen on the Tandy 1000 SX.

**Comment by OBattler** [comment] 2024-08-04 03:14
Closing this as NOTABUG since it has been confirmed to also happen on a real Tandy 1000 HX.

**Closed** 2024-08-04 23:22 UTC
Labels: bug
