### ISSUE TITLE
86Box Can't Recapture Mouse&Keyboard after new IMG is Loaded into Floppy Drive

### ISSUE THREAD

**Issue by Mast3rBlast3r** [86Box/86Box#1924] opened 2021-12-11 11:18 UTC
**Describe the bug**

I wanted to install some software (Partition Magic for Windows 95) which comes on one floppy disk (IMG format), but I got non-responsive application again, after IMG file is loaded into floppy drive through Menu, just like with CDROM problem, can't back into Windows again, only Hard Reset remains.. tried 3 times in the row, after Windows 95 is restarted and got the same result, freeze.. I can't recover 86Box with changing Render mode..

**To Reproduce**

you need something like PowerISO software to make new floppy drive image, save as IMG file or find something to download from Archive dot com, they have a great library for retro-computing.. then release mouse from capturing with middle click, in your Win 95 or Win 98 and load your IMG into floppy drive over Menu, then try to get back into Windows with mouse click on 86Box screen..

**Expected behavior**

try to install something which comes on two IMG files for floppy and you'll se what will be after Install asks you something like 'please put the next IMG into your floppy drive..' I expected less complications about installations from the Menu and how to do it.. 

**Screenshots**

I have one, copy from floppy failure..

**Desktop:**
 - OS: Windows 10
 - 86Box version: v3.00 build x32-b3336
 - Build information: My Standard Asus Machine with brand new Pentium MMX 200 CPU

**Additional context**

now I have copy from floppy onto HDD problem, can't copy content of the first IMG file through Windows Commander or Windows Explorer, got a message 'Device is Not Ready', like is empty.. and for the second IMG I copied 4 of 5 files successfully, got a message 'Can't Read File', and I don't have ideas for now what is all about, my IMG files are created with PowerISO 6.3, they worked well with VirtualBox and VMware Workstation, but is OK,  "All things are difficult before they are easy. - Thomas Fuller"
![86box Floopy Crash](https://user-images.githubusercontent.com/95438261/145674449-ec70093b-5421-4d9d-8d0d-617af4983964.png)

**Comment by OBattler** [comment] 2021-12-28 21:18
Closed for being a duplicate of https://github.com/86Box/86Box/issues/1921 .

**Closed by OBattler** 2021-12-28 21:18 UTC
Labels: bug
