### ISSUE TITLE
[i440BX] Microsoft Virtual PC 2007 does not start immediately

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#986] opened 2020-08-28 18:50 UTC
**Describe the bug**
[i440BX] Microsoft Virtual PC 2007 does not start immediately with one or two hard drives, but after 1 minute 50 seconds.

**Screenshots**
![20200828-181313-622](https://user-images.githubusercontent.com/58270614/91602814-a1e77480-e974-11ea-9117-77b4709ebf10.png)

With only three or four hard drives, MS-DOS 6.22 boots normally.
![2020-08-28_212841](https://user-images.githubusercontent.com/58270614/91604689-cc86fc80-e977-11ea-8f32-4e3806424285.png)

**Desktop (please complete the following information):**
 - Windows 10 x64 1909
 - 86Box v2.10 Build 2539
 - Build type: [Optimized Skylake]
 - HD controller type: [Internal IDE], C/H/S: 4161/16/63 (2047 MB)

**Comment by daviunic** [comment] 2020-08-28 19:13
Please try the regular build if you haven't already.

**Comment by maximus105** [comment] 2020-08-28 19:18
Not. It did not help. On a regular build it's the same.

**Comment by Winins0** [comment] 2020-10-17 11:21
I think this is a problem with the AMI BIOS it uses. The long time it takes to open is taken by detecting the hard drives and CD-ROM drives, regardless of the bus. 

And yes, adding 4 drives is a workaround for the issue.

**Comment by maximus105** [comment] 2020-11-19 11:54
Also [i440BX] Microsoft Virtual PC 2007 stops launching altogether when changing the videocard to some other (but obviously supported by this machine, in which the machine was started earlier) or when changing the frequency or type of processor. For this, you have to delete the NVR folder so that this machine starts up again.

**Comment by OBattler** [comment] 2021-07-16 03:32
Closing this because all of these issues are now fixed.

**Closed by OBattler** 2021-07-16 03:32 UTC
Labels: bug

**Comment by maximus105** [comment] 2021-07-16 15:04
No, these bugs have not been fixed. Checked in build 3053. [i440BX] Microsoft Virtual PC 2007 does not start immediately with one or two hard drives, but after 1 minute 50 seconds. With only three or four hard drives, MS-DOS 6.22 boots normally. Also [i440BX] Microsoft Virtual PC 2007 stops launching altogether when changing the video card to another (but obviously supported by this machine, on which the machine was launched earlier) or when changing the frequency or type of processor. To do this, you need to delete the NVR folder in order for the machine to start up again.
Also, a new bug was discovered in build 3053: If you change any device (for example, a video card) while the machine is running and click "OK" in the 86Box configuration window, then the 86Box hangs tightly. In the previous build 3052, this bug was not present.

**Comment by maximus105** [comment] 2021-07-16 15:37
Perhaps this new bug with freeze 86Box, which appeared in build 3053, is somehow related to the bug described in the issue #1553

**Comment by maximus105** [comment] 2021-07-16 17:03
I think the issue was closed prematurely and should be reopened.

**Comment by OBattler** [comment] 2021-07-16 17:24
> No, these bugs have not been fixed. Checked in build 3053. [i440BX] Microsoft Virtual PC 2007 does not start immediately with one or two hard drives, but after 1 minute 50 seconds.

I can't reproduce that. Try clearing the NVR, or not using the new recompiler.

**Comment by maximus105** [comment] 2021-07-17 13:04
> I can't reproduce that. Try clearing the NVR, or not using the new recompiler.

So this is the bug that when changing the video card to another (but, obviously, supported by this machine, on which the machine was launched earlier) or when changing the frequency or type of processor, you need to delete the NVR folder.
Which new recompiler not to use? What is it like?

**Comment by maximus105** [comment] 2021-07-19 05:09
I checked again: these bugs still exist in recent builds. Bugs with long loading times when detecting HDD and freezing when changing equipment have not been fixed.
I think the problem was closed prematurely and should be reopened.

**Comment by Winins0** [comment] 2021-07-19 05:14
The drive check being stuck is intended behavior for this BIOS. VPC07 automatically assigns the cd drive to Secondary Master (1:0) and the BIOS is configured to understand that case. The disk check can also be skipped with the Esc key.

**Comment by maximus105** [comment] 2021-07-19 05:21
Ok, then why does 86Box freeze when changing hardware? For example, when changing the processor frequency from 266 MHz (at which the machine with MS-DOS worked successfully) to 233 MHz. After that, you need to delete the NVR folder for the machine to start normally.

**Comment by OBattler** [comment] 2021-07-19 06:07
I can not reproduce this last problem at all. I just did the exact thing you suggested - changed the CPU from 266 MHz to 233 MHz. No problems.

**Comment by OBattler** [comment] 2021-07-19 06:09
OK, I just reproduced this bug. It seems to be the change in CPUID that causes that - I have no idea why that happens, but it might simply not be designed to handle CPUID switches well, as remember, it wouldn't happen at all on Virtual PC 2007.
