### ISSUE TITLE
USE!UMBs hangs Xi8088

### ISSUE THREAD

**Issue by jadasse** [86Box/86Box#2927] opened 2022-12-01 22:45 UTC
**Describe the bug**
I'm trying to enable my Xi8088 to recognize the full 1024kB memory via USE!UMBs, but when it runs, it hangs the system.

**To Reproduce**
I put
DOS=UMB
DEVICE=USE!UMBS.SYS B800-BFFF
in my config.sys to enable the RAM expansion, I used TEST!UMB  to detect the RAM range

**Expected behavior**
The bootup of the config.sys is supposed to continue after USE!UMBs, but it hangs.

**Screenshots**
![Monitor_1_20221201-173302-515515](https://user-images.githubusercontent.com/71288109/205174105-36e69035-b31b-4e8f-8b7a-ce1f48d15b09.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 Pro Build 22H2
 - 86Box version: v3.11 build 4317
 - Build information: Old Dynarec, Windows 32-bit

**Additional context**
I use an 8088 processor at 16 MHz, 1024 KB of RAM, and the Cirrus Logic GD4528 with XGA-2.

**Comment by Fenix770** [comment] 2022-12-02 01:54
I can confirm the bug! 

But I'm mapping the E000-EFFF memory. Beware that That "Found RAM"  may be the graphics video RAM. It can be mapperd but will  crash the VM when the video card changes to a video mode.

1. I added a memory expansion with ram at E000-EFFF region
2. Enabled the UMB option for those regions on the mainboard configuration
3. I'm ussing DOS 5.0 but, when I boot from a floppy, due the VM crash,  The TEST!UMB utility does not detect the mappeadble RAM at E000-EFFF. (I'm ussing the D000-DFFF for the Micro Mainframe EMS board.)

Screenshot:

![Xi 8088 Umb error 3](https://user-images.githubusercontent.com/31600563/205196702-5de1d0f8-b4e7-47c0-931f-0c55e8336dff.png)
![Xi 8088 UMB bug 002](https://user-images.githubusercontent.com/31600563/205196708-b6df2cf3-139a-4ab7-b713-2b8ad2b9d844.png)
![Xi 8088 UMB bug 001](https://user-images.githubusercontent.com/31600563/205196711-7e67026c-7872-4aa8-a587-9cd757debce6.png)

HDD image file:
[Xi-8088.zip](https://github.com/86Box/86Box/files/10137471/Xi-8088.zip)

**Comment by TC1995** [comment] 2022-12-02 11:44
Well, a 8088 with 16Mhz isn't really good for a start and XGA-2 requires a 386.

**Comment by Fenix770** [comment] 2022-12-02 13:31
I'm not using the XGA on my VM. Also I tested it with a 8088 8Mhz. Btw the XGA should be grayed out on 808x/286 if is not compatible.

**Comment by jadasse** [comment] 2022-12-02 14:23
Thanks for telling me about the XGA-2, I'll disable that later. Also, I am not using any ISA memory expansion cards.

**Comment by jadasse** [comment] 2022-12-03 20:34
> (https://user-images.githubusercontent.com/31600563/205196711-7e67026c-7872-4aa8-a587-9cd757debce6.png)

Also, I don't have any additional checkboxes enabled in my Xi8088 build.

**Comment by Fenix770** [comment] 2022-12-25 17:09
I did some testing on this machine. 
1. For some reason only the D000-DFFF area can be mapped as UMB. I remeber that the entire D000-EFFF did available on old revisions of 86box. I don't remember wich build.
2. The Everex RAM deluxe EMM.SYS driver refuse to start saying there is no EMS RAM, even when there is nothing on the E000-EFFF memory region.
![Xi 8088 USE!UMB](https://user-images.githubusercontent.com/31600563/209476518-fcf601b9-9d6e-403c-853c-8903257fe420.png)

**Comment by Fenix770** [comment] 2022-12-25 19:32
Update: 

1. With the Hercules card is possible to map C000-CFFF. To get a total of 96kb of UMB. But still, the E region cannot be mapped for some reason  and that is needed to use the Everex RAM delux to provide EMS memory.

2. Is, also possible to use the STOPMAX utility included in Dosmax. It relocates part of DOS memory from the HMA to the UMB.
it can be used even on 8088 which has no HMA (no extended emory).

3. As side note I found  some bugs 
    A. The DOS 5.0.  EDIT crash with the Hercules video card.
    
![Xi 8088 results](https://user-images.githubusercontent.com/31600563/209479976-9cba7fa4-659d-46a0-9a42-b6c3ae9e99a1.png)
![Xi8088 results 2](https://user-images.githubusercontent.com/31600563/209479981-d4b07929-3590-454e-8776-4dca6715afc2.png)
B. When I use the MEM command MEM/C|MORE THE VM crash. But MEM /C only works fine.

**Comment by jadasse** [comment] 2022-12-25 19:35
Do you want me to share the VM .zip?

**Comment by OBattler** [comment] 2022-12-25 23:12
Yes.

**Comment by jadasse** [comment] 2022-12-25 23:31
[super8088.zip](https://github.com/86Box/86Box/files/10300771/super8088.zip)

**Comment by jadasse** [comment] 2023-01-02 04:19
Perhaps I should also mention that the memory check upon boot-up goes up to 640 KB instead of the 1024 KB assigned in the VM. 
[super 8088.zip](https://github.com/86Box/86Box/files/10329980/super.8088.zip)

**Comment by jadasse** [comment] 2023-01-02 04:23
![Monitor_1_20230101-232303-846846](https://user-images.githubusercontent.com/71288109/210194987-cd07911f-2cce-4365-92e4-730a3f4b1abe.png)

**Comment by OBattler** [comment] 2023-01-02 05:52
Yes, the BIOS only checks the memory within the first 640 kB.

**Comment by OBattler** [comment] 2023-01-02 05:58
People, you are mapping RAM to E0000-EFFFF while using the 128 kB BIOS, that obviously isn't going to work. Set the BIOS to 64 kB in order to use that option.

**Comment by jadasse** [comment] 2023-01-02 06:14
So, the 64 KB option allows for better UMB compatibility for the 1024 KB RAM?

**Comment by jadasse** [comment] 2023-01-02 06:15
The 64KB option hangs the system.

**Comment by jadasse** [comment] 2023-01-02 06:23
The same thing happens when I try to select any of the options to map the UMB.

**Comment by Fenix770** [comment] 2023-01-02 20:59
I don't remember which build was, but it was possible to map the E000-EFFF region before even with the 128kb BIOS. The 64kb BIOS never worked, the machine is unable to boot with that.

**Comment by OBattler** [comment] 2023-01-05 01:39
> but it was possible to map the E000-EFFF region before even with the 128kb BIOS.

No way, since the 128 kB BIOS itself takes E000-EFFF in addition to F000-FFFF.

**Comment by OBattler** [comment] 2023-06-20 20:28
I think this shoud work now as the 64k option now works again after updating the Xi8088 to the latest BIOS.

**Comment by jadasse** [comment] 2023-06-20 20:50
Apparently 0.9.9 is the lastest revision, but my Xi8088 machine still says 0.9.4.

**Comment by OBattler** [comment] 2023-06-26 23:56
Go to the nvr folder and delete any xi8088 files there.

**Comment by jadasse** [comment] 2023-06-27 02:58
> Go to the nvr folder and delete any xi8088 files there.

It's still hanging. Perhaps it has to do with the RAM map chosen? (It hangs for both 64KB AND 128KB.)

**Comment by OBattler** [comment] 2023-06-27 13:15
You said you're using the Cirrus, but then you give B800-BFFF to UMB's, but that's the main video buffer. No wonder it hangs then, or at least, appears to hang, most likely keeps running but text output is going to the wrong place.

**Comment by jadasse** [comment] 2023-06-27 20:27
> You said you're using the Cirrus, but then you give B800-BFFF to UMB's, but that's the main video buffer. No wonder it hangs then, or at least, appears to hang, most likely keeps running but text output is going to the wrong place.

So what RAM map should I assign?

**Comment by OBattler** [comment] 2023-07-15 21:05
Whatever does not have B800-BFFF assigned to UMB's.

**Closed** 2023-07-15 21:05 UTC
Labels: bug

**Comment by jadasse** [comment] 2023-07-16 16:44
> Whatever does not have B800-BFFF assigned to UMB's.

Apparently there are multiple blocked RAM maps: C000-C7FF also hangs the system upon booting.
