### ISSUE TITLE
MINIX 1.1 randomly crashes when writing to HDD

### ISSUE THREAD

**Issue by krangerich** [86Box/86Box#3864] opened 2023-12-07 14:47 UTC
### What happened?

When using a hard drive with Minix 1.1, the system will randomly crash (with a high probablity) during a write operation

Required:
- Minix 1.1 Disk 1-3 (available here: https://www.minix-vmd.org/cgi-bin/raw/source/std/1.1/Floppies/ )
- PC-DOS or MS-DOS boot disk (e.g. from https://winworldpc.com/product/pc-dos/2x )

Procedure to reproduce

a) Create a machine with 
- any 8088 (e.g. [8088] IBM XT (1986), 4.77 Mhz, 640kB Memory) (or any other, as long as memory is 640kB)
- CGA (or MDA)
- HD Controller: [ISA] IBM PC Fixed Disk Adapter (MFM) 
- Hard Disk: MFM/RLL 10 MB (CHS: 306, 4, 17)
- 2x Floppy 5.25" 360k (Turbo Timings)

b) Boot from PC-DOS or MS-DOS disk

c) Partition the hard disk:
- FDISK 
- Create new DOS partition (the whole space or just a chunk, doesn't matter)

d) reboot

e) Boot from MINIX 1.1 disk 1
You should see "Booting MINIX 1.1" and a menu

f) Switch to disk 2, hit the = key (left of backspace)
Screen should clear, then Disk 2 is loaded into a RAM disk. Wait until the "Please insert /usr diskette .." message appears.

g) Switch to disk 3, hit the ENTER key. When asked for date, hit ENTER

h) Login with "root" / "Geheim"

--- from now on, a crash is possible ---
i) Enter:
mkfs /dev/hd1 2000
/etc/mount /dev/hd1 /user
cd /user
mkdir bin
cp /usr/bin/* /user/bin

Up to now, a crash (freeze, maybe funny chars on the screen) should have been occurred.

The same procedure works fine in PCjs all the time.
The error occurs on MacBook M2 Pro as well as on Linux (Intel CPU).
Reading from the hard disk always works (I think).
Crash occurs with other tested storage controllers as well

Should be noteworthy that MINIX doesn't use the BIOS, but directly talks to the controller using port 0x320+ and DMA 3.
Here is the source code of the hdd driver, maybe it helps:
https://github.com/gdevic/minix1/blob/master/kernel/wini.c

### Configuration file

```ini
[General]
vid_renderer = qt_software
force_43 = 1
confirm_save = 0
vid_resize = 1
confirm_reset = 0
confirm_exit = 0

[Machine]
machine = ibmxt86
cpu_family = 8088
cpu_speed = 16000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
pit_mode = 0
cpu = 5
mem_size = 640

[Video]
gfxcard = cga

[Input devices]
mouse_type = none

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = st506_xt
cassette_mode = load

[Hard disks]
hdd_01_parameters = 17, 4, 306, 0, mfm
hdd_01_fn = hdds/minix10large.img
hdd_01_mfm_channel = 0

[Floppy and CD-ROM drives]
fdd_01_turbo = 1
fdd_02_turbo = 1
```

### Operating system

Ubuntu 22.04

### CPU

i7 7700k

### 86Box version

v4.0.1 (build 5111)

### Build architecture

Linux - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment] 2023-12-07 17:45
Try the latest build, I reverted the 808x code since the interim one I committed during 4.0 development, had too many regressions.

**Comment by krangerich** [comment] 2023-12-07 20:20
Unfortunately, it doesn't make a difference.

But I gained more information. Booting with the MINIX 1.2 Kernel instead works like a charm (any XT version, any clock rate). The 1.2 patches contains some winchester fixes for "Turbo XT clones". 
So the crashes are probably expected behavior for non-original 5150/5160, but it's supposed to work on the original XT at 4.77 Mhz. So I guess, for the IBM XT (in 86box) are some hard disk timings not entirely accurate. 

As a workaround, one can just boot from the 1.2 kernel. Maybe I'll get a deeper understanding of the driver code at some point and can provide exact details.

**Comment by TC1995** [comment] 2023-12-07 20:27
Try without turbo timings on the floppy ones.

**Comment by OBattler** [comment] 2023-12-09 19:20
No, it's the CPU timings that are not entirely accurate - clearly, some instruction is completing too fast. I'm closing this because a cycle-accurate 808x rewrite based on MartyPC is coming in 4.2. Then it can be reopened then, should the issue persist.

**Closed by OBattler** 2023-12-09 19:20 UTC
Labels: bug
