### ISSUE TITLE
XWINGCD and TIECD cause 86box to Crash to Desktop

### ISSUE THREAD

**Issue by Danfun64** [86Box/86Box#2130] opened 2022-02-16 19:33 UTC
**Describe the bug**
Whenever I try to load the DOS CD version of X-Wing, the 86box shell crashes. 

**To Reproduce**
1. Create a 2GB Harddrive (I used Winbox)
2. Create a 86box VM (config is included)
3. Install DOS 6.22 and drivers for CD and Mouse (I used XDVD2, but OAKCDROM has the same effect)
4. Install X-Wing CD
5. Attempt to play X-Wing CD by going into c:\xwingcd and typing either xwingcd(.bat) or bwing(.exe)
6. 86box crashes with no error message.

**Expected behavior**
Simply put, I expected to be able to load and play the game as I normally do.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: v3.2 build 3600 (this bug does NOT occur with v3.0)
 - Build information: 64-bit Windows, stable

**Additional context**
I noticed this bug a few days ago in a dev build as mentioned [here](https://github.com/86Box/86Box/issues/1912#issuecomment-1037464605). My Tie Fighter VM seems perfectly fine, however...
[86Box.cfg.txt](https://github.com/86Box/86Box/files/8082921/86Box.cfg.txt)

**Comment by Danfun64** [comment] 2022-02-16 19:34
autoexec.bat and config.sys attached in zi
[winbox.zip](https://github.com/86Box/86Box/files/8082937/winbox.zip)
p

**Comment by Danfun64** [comment] 2022-02-19 02:04
XWINGCD: 
86Box v3.0.0.3333 - no crash
86Box v3.2.0.3600 - crash
86Box v3.2.1.3602 - crash
86Box v3.3.0.3609 - no crash

TIECD: 
86Box v3.0.0.3333 - no crash
86Box v3.2.0.3600 - no crash
86Box v3.2.1.3602 - no crash
86Box v3.3.0.3609 - crash

**Comment by OBattler** [comment] 2023-08-21 05:42
Does TIECD still crash on the latest build?

**Comment by OBattler** [comment] 2023-08-21 05:53
Closing this for being a duplicate of this: https://github.com/86Box/86Box/issues/1912 .

**Closed by OBattler** 2023-08-21 05:53 UTC
Labels: bug
