### ISSUE TITLE
[BUG] Multiple partition handling issue under OS/2

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#704] opened 2020-04-19 03:19 UTC
I would like to report a bug involving multiple partitions when FDISK'd under OS/2 2.1.

I have created a hard disk image of 504 MB (1,024 cylinders, 16 heads and 63 sectors per track) and decided to split the hard disk into two partitions.

Drive C is the bootable 252 MB primary partition and Drive D is the 251 MB data logical partition. I used the OS/2 2.1 FDISK utility to create the primary partition and a logical drive on the extended partition.

Now, here's what is baffling me, when I view the list of partitions using IMDisk, the partition where OS/2 is installed is listed on partition #2 instead of partition #1. And partition #1 is listed as a data drive.

Here's a screenshot for proof:
![IMDisk Disk Partition](https://user-images.githubusercontent.com/32658796/79678496-2220f080-81b1-11ea-87ed-9043da3311d9.png)

Here is another screenshot of the OS/2 FDISK utility:
![OS_2 FDISK](https://user-images.githubusercontent.com/32658796/79678533-67ddb900-81b1-11ea-9a4d-5317d9a41a08.png)

This bug occurs on both IDE and SCSI hard disks.

Here's the current 86Box.cfg file that I used: https://pastebin.com/VJ8Pc78B

I can't seem to remember which build caused this issue, but more tests will need to be made so that we can be aware of this issue. Please look into this issue and investigate.

Thanks. :)

**Update:** I found that this issue only occurs when creating a hard disk image for the first time although more investigation into this issue needs to be made.

**Comment by ppgrainbow** [comment] 2020-04-19 06:13
So, I did create a OS/2 2.1 VM under Virtual PC 2007. Same thing.

It turns out that IMDisk, which was last updated on November 18, 2018 with version 2.1 fixed a problem when auto-detecting logical drives in extended partitions, OS/2 2.x for some reason seems to NOT like the change at all and as such OS/2 2.x wound up listing the OS/2 boot partition on partition 2 instead of partition 1. :|

**Comment by OBattler** [comment] 2020-04-19 16:28
Marking as not a bug and closing because it's not an 86Box bug.

**Closed by OBattler** 2020-04-19 16:28 UTC
Labels: notabug
