### ISSUE TITLE
Emulated AOpen AP53 boards unable to detect hard drives/CD-ROM drives detected to be non-ATAPI compliant under BIOS versions of R2.10 and below

### ISSUE THREAD

**Issue by TheMajorTechie** [86Box/86Box#1938] opened 2021-12-16 06:12 UTC
**Describe the bug**
On older versions of the AP53 BIOS, obtained via dumping the ROM chips from existing boards, the emulated storage controllers fail to register at all in the BIOS when a hard drive image is attached, and CD-ROM drives with iso images attached are detected by the BIOS to be "non-ATAPI compliant". This results in them being unusable despite being detected in BIOS.

**To Reproduce**

If necessary, delete any existing AP53-related files in the "nvr" folder, as this will prevent the different BIOS revision from loading in.

Using 86box v3.0 build 3333, configure the emulated system to be an AOpen AP53 (Single-voltage Socket 7) using a BIOS revision older than R2.30. The two BIOS revisions known to have this issue are version R2.10 and R1.30, which should be available on https://www.ultimateretro.net/en/motherboards/177 (R1.30 has yet to be posted as of the writing of this report.) These are also attached below:

Additionally, on a side-note, 86Box only counts a rom image as valid if it is _specifically_ named "ap53r2c0.rom". So, place either the R2.10 or R1.30 ROM into the AP53 folder within "machines" and then rename it to "ap53r2c0.rom" to be usable.

Launch 86box and configure it to use "Internal Controller" as the HDD controller. Attach any hard disk image to any IDE channel, and any ATAPI CD-ROM drive to any IDE channel. This can be done at the same time or separately, as it is the same emulation bug that affects both.

Use any video card, any supported CPU, and any amount of memory between 4 and 512MB (this is what the AP53 supports).

Upon booting, hit the delete key to enter the BIOS. Navigate to "Standard" under the Setup category and select it. Within the menu that opens, select the IDE channel that the hard disk has been set to and attempt to auto-detect the disk by selecting "Auto" under "Type" and "Auto" again to start the detection process. The result will be that the drive is not detected.

Alternately, selecting "User" and entering the CHS values of the hard disk image results in the BIOS reporting a Primary Master HDD error. You may also see messages about CD-ROM drives being ATAPI incompatible regardless of what channel they were configured to be on. In fact, within the second screenshot seen below, it is noted that there are in fact no CD-ROM drives configured at all, but the BIOS continues to report them to exist and be "ATAPI Incompatible".

**Expected behavior**
What is expected to happen is that the configured drives should be detected by the BIOS, or otherwise be usable within the OS, whether it be DOS, Windows, Linux, or some other OS.

**Screenshots**
![image](https://user-images.githubusercontent.com/29270676/146315865-fddb8623-7273-4ead-9fec-d1033f630737.png)
![image](https://user-images.githubusercontent.com/29270676/146316570-87cef291-bb97-414b-a262-daa47fcc62b6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: v3.00 build 3333
 - Build information: x64 standard build

**Additional context**
If necessary, I can provide a large number of BIOS builds ranging from R1.30 (my most recent dump) to R3.C0 (the newest revision I've seen anywhere). These BIOS builds were obtained by both scraping AOpen's FTP server and by dumping the ROM chips on old AP53 mainboards.

ROM files: [ap53r210.zip](https://github.com/86Box/86Box/files/7724929/ap53r210.zip)
[ap53r130.zip](https://github.com/86Box/86Box/files/7724938/ap53r130.zip)

**Comment by dhrdlicka** [comment] 2021-12-16 10:55
Using custom BIOS files is not officially supported.

**Comment by OBattler** [comment] 2022-01-10 22:08
I can't reproduce this issue. Please test if it still happens on your end.

**Comment by OBattler** [comment] 2022-07-09 22:43
Closing this because I presume it has been fixed since I could not reproduce it and I got no reply from the reporter. If it re-appears, it can be re-opened.

**Closed by OBattler** 2022-07-09 22:43 UTC
Labels: bug, unsupported
