### ISSUE TITLE
Hardcore hang on Windows 10

### ISSUE THREAD

**Issue by DartPower** [86Box/86Box#1485] opened 2021-06-14 20:39 UTC
Windows 10 very strong hanging when im trying to change the CD image... 
Hangs 86box and explorer processes and im can't kill them (Task Manager lagging and said "Access Denied" to kill process (86box and explorer))

Can help only hard reboot.

OS: Windows 10 20H2
86box version: 86Box-Dev-32-6bd2ba28
Version type: Experimental

**Comment by qeeg** [comment] 2021-06-15 01:48
I have... never even heard of anybody having this problem before. Is there anything that people might consider "unusual" about your system? Also, what language is your Windows install?

**Comment by DartPower** [comment] 2021-06-15 10:34
System language is Russian
But i also can send the config of the 86box for the bug-reproduction try
[86box.zip](https://github.com/86Box/86Box/files/6654920/86box.zip)

**Comment by DartPower** [comment] 2021-06-15 10:35
Ah.. forgot to say: This bug is appear (i think) only when opening the open file dialog

**Comment by qeeg** [comment] 2021-06-15 12:56
Maybe the issue is that the path to your CD image has exclamation points in it?

**Comment by OBattler** [comment] 2021-06-17 00:02
Are you using 86Box -Dev builds and the new OpenGL renderer?

**Comment by OBattler** [comment] 2021-06-17 00:03
OK, yes, you are according to the the configuration. I'm going to report this to the author of the OpenGL-Core renderer.

**Comment by ts-korhonen** [comment] 2021-06-17 03:45
@DartPower have you tried this on the [regular build](http://ci.86box.net/job/86Box)? Does it happen also with that?

**Comment by DartPower** [comment] 2021-06-17 11:02
> @DartPower have you tried this on the [regular build](http://ci.86box.net/job/86Box)? Does it happen also with that?

Now all working. 86Box-32-a389e298

**Comment by ts-korhonen** [comment] 2021-06-18 15:59
@DartPower can you try if the [latest dev build](https://ci.86box.net/job/86Box-Dev/) fixes the issue?

**Comment by DartPower** [comment] 2021-06-18 21:41
Working. Thanks a lot :)

**Comment by OBattler** [comment] 2021-06-18 21:58
Closing this issue then since it has been fixed.

**Closed by OBattler** 2021-06-18 21:58 UTC
Labels: bug
