### ISSUE TITLE
Implement  the special video modes supported by the ET2000 video card.

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1292] opened 2021-02-27 02:32 UTC
**Is your feature request related to a problem? Please describe.**

Well, there is a bug

There is some glitches with text scrolling, for example, when a dir command is executed the text modes moves to left and right.
Apart of that all standard EGA video modes seem to work.

This card supports additional EGA 640x480 video modes at 2,4,8 and16 colors. Also acording some documentation supports  text mode of 132x44.

**Describe the solution you'd like**
The addion of this video modes. But not sure if a proper documentation of this card exist.

Here is a screenshoot of Zpaint it supports the Tseng EVA/480 which I suspect it´s the ET2000. According some articles this video card was launched in late 1986, before the VGA standard. So VGA modes are not supported in this card. 

![Tseng ET2000](https://user-images.githubusercontent.com/31600563/109372637-55301800-7889-11eb-9ecb-f6103e5e6b49.png)

Also here is some information in the Vogons site:
https://www.vogons.org/viewtopic.php?t=76118

**Describe alternatives you've considered**

There are other EGA cards already implemented in 86box, which may be launched in 1987-88. There is the "Super EGA" which I don´t know which brand or model is, but support standard 16 color VGA modes. For example 320x200 and 640x480 at 16 colors. Although it converts the 256 color palette to 64 colors which is similar to the standard EGA 640x350 16 colors. 
Also the ATI EGA 800+ has  graphics bugs with its special EGA 800x560 video mode in Windows 2.0 and should support the standard 16-color VGA video modes (not 256) since the ATI EGA 800 was launched in 1988 and is mentioned in the documentation, maybe, as cheaper solution to the new and more expensive VGA. 
The documentation is cited in the thread  #575.

**Comment by OBattler** [comment] 2021-03-20 05:49
The "Super EGA" is the Chips & Technologies SuperEGA (82C435/82C436).

Also, yes, the Tseng EVA/480 is the ET2000 - the problem is that I'm not sure I can find any datasheet of this card, so at this moment, I don't think I can go beyond standard EGA on it.

**Comment by OBattler** [comment] 2023-01-26 04:25
Closing as CANTFIX due to a complete lack of documentation.

**Closed by OBattler** 2023-01-26 04:25 UTC
Labels: feature

**Comment by TC1995** [comment] 2024-07-26 21:47
Update: the et3000 set might be a hint, as it's said to have the et2000 extended set.

**Comment by Fenix770** [comment] 2024-07-26 22:51
I testd the software again EVA-480 driver for the 640x480x16 video mode works just fine with the ET3000 video card.
I don't know if a ET2000 driver exists for Win 1.x/2x
