### ISSUE TITLE
XTIDE Newer Bios not working

### ISSUE THREAD

**Issue by jvernet** [86Box/86Box#1220] opened 2021-01-12 18:45 UTC
**Describe the bug**
Is there any way to use a newer XTIDE Universal BIOS with X86 ?
Tried to download one of these form this site:
http://www.xtideuniversalbios.org/
The guest send me a CRC error.

**To Reproduce**
1. replace ide_xt.bin with ide_xt.bin downloaded from aboce site
2. Configure a 8086 system with XTIDE card
3. Start

**Expected behavior**
A working XTIDE card ??

**Desktop (please complete the following information):**
 - OS: Windows 10]
 - 86Box version: my own build, Sources as of 12/01/2021
 - Build type: My build

**Comment by OBattler** [comment] 2021-03-16 21:06
The new XTIDE BIOS might be bigger than the old one, and therefore bigger than the amount of memory 86Box allocates it, which results in only part of the BIOS being visible to the emulated machine, hence the CRC error.

**Comment by OBattler** [comment] 2021-05-01 00:29
OK, it turns out XTIDE BIOS'es on the site are distributed without the padding 0xFF's and the checksum. You're going to have to add the padding, calculate the 8-bit checksum, and put it into the last byte.

**Comment by OBattler** [comment] 2021-05-01 00:36
As such, I'm closing this issue as not a bug.

**Closed by OBattler** 2021-05-01 00:36 UTC
Labels: bug
