### ISSUE TITLE
Emulation display freezes after being left idle for a few minutes

### ISSUE THREAD

**Issue by kyousif87** [86Box/86Box#803] opened 2020-06-12 17:48 UTC
**Describe the bug**
Emulation display freezes after being left idle for a few minutes using a number of PC-DOS versions on different IBM computers.
The cursor freezes, nothing happens when I type on the keyboard. 
C+A+D works.

**To Reproduce**
Just leave the system idle for a few minutes

**Expected behaviour**
Being able to use the system after leaving it idle for some time.

**Desktop (please complete the following information):**
 - OS: PC-DOS 3.30 on IBM PC 1982,
BASIC C1.20 on IBM PCjr, 
PC-DOS 5.02 on IBM XT 1986, 
PC-DOS 6.3 and PC-DOS 7.0 revision 1 on IBM AT 286.
 - Version: 2.10 build 2332
 - Build type: Optimized, Skylake.

**Further notes:
- The BASIC ROM on PCjr won't refresh the screen even after C+A+D, although you do hear the POST beep.

**Comment by kkwpsv** [comment] 2020-06-12 18:06
Maybe renderer freeze? see #541 ?

**Comment by kyousif87** [comment] 2020-06-12 18:14
> Maybe renderer freeze? see #541 ?

Possibly, I have not tested it on Windows yet.
But I am also using the Hardware SDL renderer so it could be related.

**Comment by kkwpsv** [comment] 2020-06-12 20:35
> > Maybe renderer freeze? see #541 ?
> 
> Possibly, I have not tested it on Windows yet.
> But I am also using the Hardware SDL renderer so it could be related.

When frozen, you can change renderer and see if it restore.
Freeze has no relation to the client operation system.

**Comment by kyousif87** [comment] 2020-06-12 23:21
> > > Maybe renderer freeze? see #541 ?
> > 
> > 
> > Possibly, I have not tested it on Windows yet.
> > But I am also using the Hardware SDL renderer so it could be related.
> 
> When frozen, you can change renderer and see if it restore.
> Freeze has no relation to the client operation system.

I tried this workaround, and it worked. Thank you for suggesting it! :)

**Comment by OBattler** [comment] 2020-06-17 11:53
Going to close this as a duplicate of #541 .

**Closed by OBattler** 2020-06-17 11:53 UTC
Labels: bug
