### ISSUE TITLE
Change shortcut for Ctrl+Alt+Del and screenshots

### ISSUE THREAD

**Issue by DM-VLK** [86Box/86Box#3061] opened 2023-01-27 15:24 UTC
**Is your feature request related to a problem? Please describe.**

When the program uses the Ctrl+F11 or Ctrl+F12 combination, a reboot or screenshot occurs instead of the intended action (example: Dos Navigator, FAR)

**Describe the solution you'd like**

I propose to assign another shortcut for Ctrl+Alt+Del (for example it may be Ctrl+Alt+End) and for screenshot

**Comment by Zack13358** [comment] 2023-01-30 16:36
Maybe have a "Host key" like VirtualBox has when you have the host key held down, anything you type won't be directed to machine, instead it will be directed to the emulator program itself

**Comment by DM-VLK** [comment] 2023-01-31 12:06
> Maybe have a "Host key" like VirtualBox has when you have the host key held down, anything you type won't be directed to machine, instead it will be directed to the emulator program itself

Interesting idea, but it must be quite an exotic combinations like PrintScreen+F11/F12. The best thing, of course, would be to give the opportunity to assign the combination yourself, as in DosBox.

Right now I'm just editing the resources of the exe file in ResHacker:

```
	VK_PRIOR, 40060, ALT, CONTROL, VIRTKEY
	VK_END, 40012, ALT, CONTROL, VIRTKEY
	VK_HOME, 40013, ALT, CONTROL, VIRTKEY
	VK_PAUSE, 40017, ALT, CONTROL, VIRTKEY
```

**Comment by Zack13358** [comment] 2023-01-31 14:32
I was thinking R ALT for the host key since its a duplicate (in Vbox R CTRL is the host key but that’s already taken by emulate L ALT)

**Comment by DM-VLK** [comment] 2023-01-31 14:43
> I was thinking R ALT for the host key since its a duplicate

I know many programs where LAlt/RAlt and LCtrl/RCtrl and combinations with them are used for different actions. For example, in VMware, I use the "Win+Shift" combination as the host key and I think the default option is unsuccessful. As I understand, 86Box positions itself as an exact emulator of old systems and the choice of such combinations is rather strange, unless most people use it for games where such combinations naturally do not occur.

**Comment by OBattler** [comment] 2023-11-08 06:16
Closing this as essentially a duplicate of the following issue: https://github.com/86Box/86Box/issues/1639 , since they should both be fixed as part of a single implementation of configurable key combinations.

**Closed by OBattler** 2023-11-08 06:16 UTC
Labels: feature
