### ISSUE TITLE
Windows NT 4.0: MO drive formatting broken

### ISSUE THREAD

**Issue by DDXofficial** [86Box/86Box#985] opened 2020-08-28 04:59 UTC
**Build:** 86Box-Dev build 2539
**OS:** Windows NT 4.0 Workstation (Service Pack 1)
**Machine specs:** [listed below]

![image](https://user-images.githubusercontent.com/62580909/91522091-5925b200-e8c7-11ea-857d-d55cc1cfec5f.png)

Formatting some magneto-optical disks (regardless of the file system) seems to be impossible in Disk Administrator, Windows NT 4.0's built-in disk management utility. As corroborated by the screenshots detailing the machine specifications, I'm using a Matshita LF-3000 MO drive (later switched to generic 86Box MO drive). The MO disk image in question is a 640 MB 3.5" ISO 15498 image.

Now, formatting a 128 MB 3.5" ISO 10090 drive was successful, but this begs the question of maximum capacity support for certain MO drives which still has not been documented.

Screenshots detailing the events are attached below.

![image](https://media.discordapp.net/attachments/266245344529088512/748763006879531048/unknown.png)

![image](https://media.discordapp.net/attachments/266245344529088512/748761755068399676/unknown.png)

**Comment by OBattler** [comment] 2021-07-19 01:02
Closing this because this is intended behavior, there emulator should just properly notify the user of supported media size limitations for the specified Magneto-Optical drive.

**Closed by OBattler** 2021-07-19 01:02 UTC
Labels: notabug
