### ISSUE TITLE
Mouse on PB410A

### ISSUE THREAD

**Issue by ArtiomWin** [86Box/86Box#552] opened 2020-01-16 21:25 UTC
Hello. There's an issue with PS/2 and bus mouse on Packard Bell PB410A board: when one of these types of mouse is chosen to emulate, cursor can be seen, but it doesn't move at all.

**Desktop (please complete the following information):**
 - Host OS: Windows 10
 - 86box version: Version 2.10 (build 2053)
 - Guest OS: Windows 3.0 with Multimedia Extensions (Packard Bell OEM)
[cfg.zip](https://github.com/86Box/86Box/files/4073849/cfg.zip)

**Comment by OBattler** [comment] 2020-01-17 15:00
In DOS, all mice seem to work fine (but serial mouse must be set to COM2).

Also, I would need the actual hard disk image to reproduce the bug.

**Comment by OBattler** [comment] 2020-01-17 15:13
The same PS/2 mouse bug problem was also reported by someone else, it's fixed by first loading a DOS mouse driver.

Bus mice use IRQ 5, which is probably conflicting with your Sound Blaster 16.

**Comment by ArtiomWin** [comment] 2020-01-17 15:26
Sure. https://mega.nz/#!oIMjmQJL!MiqyQZm-UefSoAIPj45T83E5Upz8GEzr9nQWpwSxaf0

**Comment by OBattler** [comment] 2020-01-22 15:32
Try the latest build, see if it's fixed, since I fixed a bugs with the CPU and with PIC 2 that might have been the case.

**Comment by ArtiomWin** [comment] 2020-01-22 15:42
Build 2096, still no moves.

**Comment by OBattler** [comment] 2020-01-27 17:16
Does PS/2 mouse work on this Windows on *any* emulated machine? If it does not then, it might not even be an emulator bug, but simply this Windows not supporting PS/2 mouse.

**Comment by ArtiomWin** [comment] 2020-01-27 20:16
I've tested on Award 486 - bus mouse works properly, mouse driver over there is both for bus and PS/2 port.

**Comment by Dizzy611** [comment] 2022-04-23 20:56
Attempted to reproduce, can not test because hard drive image is no longer up on Mega.

**Comment by ArtiomWin** [comment] 2022-04-23 21:23
> Attempted to reproduce, can not test because hard drive image is no longer up on Mega.

Try this one: https://mega.nz/file/cNlU2CjB#jyX3GoGegokOjaqDr6xSYZXfqfEG7a_MG0DjKfwwbwE

**Comment by Dizzy611** [comment] 2022-04-23 21:50
Can confirm this issue is still present in 3.4.1 on Windows x64. Cursor is visible but does not move.

**Comment by saipan7** [comment] 2023-08-25 18:58
the mouse issue still occured in 86box from v3.11 [build 4311] up to the latest 4.0 build [4950] but not occured on PCem v17.

![image](https://github.com/86Box/86Box/assets/127716019/abadff48-18e2-46a0-a805-cdae8cc1c035)

i've attached a floppy disk image contain dos mouse tester, can be use also in windows by double click the test.pif file to run the test.exe in window mode or directly double click the test.exe to run it in fullscreen mode

![image](https://github.com/86Box/86Box/assets/127716019/f74bb132-92aa-4fc0-98d8-eb92ce02905a)

[mouse tester.zip](https://github.com/86Box/86Box/files/12442803/mouse.tester.zip)



there are 2 other issue with PB410A in 86box which do not occur in PCem v17

1. can't read floppy disk on drive A: from windows 3.x

![86box old can't read disk a](https://github.com/86Box/86Box/assets/127716019/77eb1aaf-ea54-48c2-8f7b-6c205bd95323)
![86box new can't read disk a](https://github.com/86Box/86Box/assets/127716019/c8d48e9f-532c-4450-8093-aafb7a4cf264)

2. can't run dos program such as norton commander from windows 3.x (just black screen with blinking cursor on the top left monitor)

![86box old can't open norton commander 5 from windows 3 1](https://github.com/86Box/86Box/assets/127716019/3a76d3a9-886f-4e8a-b4d2-665a4c499455)

![86box new can't open norton commander 5 from windows 3 1](https://github.com/86Box/86Box/assets/127716019/50c50ba1-b93e-4400-aa4f-542f2b0f17c8)

**Comment by OBattler** [comment] 2024-01-14 23:09
It actually does occur on PCem, I literally just tested. The exact same problem - the mouse doesn't move.

**Comment by mfmcosta** [comment] 2024-01-25 12:01
I've tried this just for the sake of trying and it works:
- mouse
- drive a:
![image](https://github.com/86Box/86Box/assets/136728257/0df74b61-37d8-4a72-8f1f-296e813c719d)
- norton commander 5.01 (installed from windows) and running from windows or the DOS prompt
![image](https://github.com/86Box/86Box/assets/136728257/378ff45b-b5c0-4839-9681-bf4a8a857a3a)

use 86Box 32-Bits old recompiler [b5416] and the HDD supplied in this post

**Comment by OBattler** [comment] 2024-01-25 20:47
Nevermind, it turns it was indeed the dynarec causing this. I have a fix incoming that causes the dynamic recompilation to be temporarily suspended on a PS/2 mouse command until the response byte is read, it fixes this.

**Closed** 2024-01-25 20:47 UTC
Labels: bug, hw docs needed, hw testing needed
