### ISSUE TITLE
Return To Castle Wolfenstein `sysinfo.exe` does not detect the size of Voodoo video RAM

### ISSUE THREAD

**Issue by Mast3rBlast3r** [86Box/86Box#1931] opened 2021-12-12 18:06 UTC
**Describe the bug**

after I launched "sysinfo.exe" located in folder where is Return To Castle Wolfenstein installed, I discovered.. that tool doesn't know how much VRAM graphic card has, should be 16 MB (look at the attached picture), I don't know where he is looking for that info, but must be somewhere, if I can guess.. this can't happen on the real machine, so this can be emulation code problem because info is not given, some games can't configure itself properly if precise and correct system info is not given..

maybe is this reason why I can't launch Screamer 2 in 3DFX mode (look at the attached picture), even I have the latest and final driver version 1.07.00 installed for 3dfx Voodoo3 3000..? 

**To Reproduce**

I tested two versions of game (they are playable, it looks great), one I had from before and platinum version, I'll give you this tool from ordinary version I had packed in zip file here (look at attached RTCW_Sysinfo Tolls.zip), run this under Windows 95 to check info, from any folder, you can take this platinum version from here (this tool doesn't exist in this version, unfortunately), and comes on two CDs, serial is written in the comments below.. 

https://archive.org/details/ReturnToCastleWolfensteinUSAThePlatinumEdition

**Expected behavior**

I expected from that sisinfo tool to show exactly how much video memory the graphics card has..
 

**Screenshots**

I have them all, check the images..

**Desktop:**
 - OS: Windows 10
 - 86Box version: v3.00 build x32-b3336
 - Build information: My Standard ASUS Machine with 3dfx Voodoo3 3000

**Additional context**

the best is yet to come.. :)
![86box RTCW_01](https://user-images.githubusercontent.com/95438261/145724042-a27c4a08-c390-4c8c-84f3-0a2ad498af67.png)
![86box RTCW_02](https://user-images.githubusercontent.com/95438261/145724045-e3158c89-9e40-4b12-9032-6add27734094.png)
![86box RTCW_03](https://user-images.githubusercontent.com/95438261/145724046-a5dc48a0-a7f9-4324-850a-929a95cf3ee7.png)
![86box RTCW_04](https://user-images.githubusercontent.com/95438261/145724049-49775571-ed8c-4f06-ad4f-a14e24e88670.png)
![86box RTCW_05](https://user-images.githubusercontent.com/95438261/145724051-1e455468-0704-47a2-b677-2dba06217b0d.png)
![86box RTCW_06](https://user-images.githubusercontent.com/95438261/145724053-79839bd9-2d75-4320-976f-25bf26a648ec.png)
![86box RTCW_07](https://user-images.githubusercontent.com/95438261/145724057-3d17d279-4f3d-4904-b267-a1dc3ca50b73.png)
[RTCW_Sysinfo Tolls.zip](https://github.com/86Box/86Box/files/7699288/RTCW_Sysinfo.Tolls.zip)

**Comment by dhrdlicka** [comment] 2021-12-13 02:13
The driver clearly shows the correct size of video RAM, so I would not rule out the possibility of said program merely not being able to detect it for this specific card.

The Screamer 2 issue might be a separate issue, given it fails to detect the Voodoo completely.

**Comment by Mast3rBlast3r** [comment] 2021-12-13 10:25
OK, thank you, can you tell me please where I can download 86Box debug version, I need something which can leave a log file behind after crash, with info about code where crash happened, because I experienced something like a complete 86Box disappearance from the screen after I tried to run some games from the desktop icon, just like that, the program is not stable..

**Comment by OBattler** [comment] 2021-12-13 10:29
You get debug builds on our Jenkins (ci.86box.net), but you also need to have a debugger installed and pointing at the corresponding 86Box source tree, then run 86Box inside it, reproduce the crash, and then do a backtrace to see where exactly it has crashed.

**Comment by Gogo268** [comment] 2022-01-17 11:46
> The driver clearly shows the correct size of video RAM, so I would not rule out the possibility of said program merely not being able to detect it for this specific card.
> 
> The Screamer 2 issue might be a separate issue, given it fails to detect the Voodoo completely.

DOS glide games only work on voodoo 1 cards properly, therefore resulting into that error. Voodoo 2 and later aren't compatible with early glide games due to some strange compatibility problem, and it only happens with Glide 2.x and 1.x games.

**Comment by Fenix770** [comment] 2022-01-17 13:16
That game was launched in 2001. The game requires a P2 400 MHz and a 16MB 3D graphics card. So the game may work with Voodoo 3 or later. The Voodoo 2 have either 8MB or 12MB. The SLI mode does not add more VRAM, it simply copies the data from one card to another, so it creates a double bus speed.

Here are the links
https://systemreqs.com/es/juego/return-to-castle-wolfenstein
https://www.mobygames.com/game/windows/return-to-castle-wolfenstein/techinfo

Warcraft 3, launched in 2002 have the same system specs. Supports Voodoo 3 and 4/5. But not Voodoo 2/Banshee or earlier.

**Comment by OBattler** [comment] 2022-01-17 14:18
I just took a cursory look at the tool, and it has no strings about the Voodoo's - it mentions Rendition Verite, Nvidia, ATi,e etc., but not the Voodoo's. So I think it's same to conclude the tool simply does not support this graphics card. So as such, not a bug.

And the other problem has also been determined to not be a bug, so as such, I'm closing this issue.

**Closed by OBattler** 2022-01-17 14:18 UTC
Labels: bug, hw testing needed

**Comment by OBattler** [comment] 2022-01-17 14:23
The system information tool appears to obtain the Video memory from Registry key that only exists in Windows 2000 and later, and appears to not exist in Windows 9x.
