### ISSUE TITLE
Cirrus 5434 - display problem

### ISSUE THREAD

**Issue by coolhaken** [86Box/86Box#328] opened 2018-10-20 09:14 UTC
Hi ,

I tried the ETEN Chinese system 24x24 font version under PCem and 86Box. It works, but with incorrect display.
I noticed that Qemu also supports Cirrus. So I copy gd5434.BIN into Qemu's folder and rename it to vgabios-cirrus.bin to replace Qemu's built-in Cirrus rom.Then it looks perfect running ETEN under Qemu.
Maybe there are bugs in PCem and 86Box. Check the following screenshots :
https://imgur.com/9rmFDWg.png
https://imgur.com/KZ3z1Ay.png
I also tried other video cards which ETEN supports, but got the same result. You can look into ETEN's main program "ET24V.COM", as below.
https://imgur.com/mXew5nk.png
Download the test package here (Qemu and PCem) :
https://mega.nz/#!r1ATxCiJ!s6_B3K1cQS2kGL2m97z5f_2yCIAfZSwNjEEXHrE3UMs

**Comment by OBattler** [comment] 2018-10-20 15:34
Since the bug occurs on all cards you tried, I suspect it might be a bug in vid_svga.c.

**Comment by waltje** [comment] 2018-10-20 16:03
Confirmed, happens here, too.

--------------------------------------------
On Sat, 10/20/18, OBattler <notifications@github.com> wrote:

 Subject: Re: [86Box/86Box] Cirrus 5434 - display problem (#328)
 To: "86Box/86Box" <86Box@noreply.github.com>
 Cc: "Subscribed" <subscribed@noreply.github.com>
 Date: Saturday, October 20, 2018, 11:34 AM
 
 Since the bug occurs
 on all cards you tried, I suspect it might be a bug in
 vid_svga.c.
 
 —
 You are
 receiving this because you are subscribed to this thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by TC1995** [comment] 2018-10-21 18:09
Fixed as of 1767.

**Comment by coolhaken** [comment] 2018-10-22 10:57
Thank you very much. :)

**Comment by waltje** [comment] 2018-10-22 23:50
I have a question about that for you... email me at decwiz@yahoo.com ?

Thanks,

Fred

**Comment by coolhaken** [comment] 2018-10-23 06:38
About what ? Why not just ask here ?

**Comment by OBattler** [comment] 2018-11-01 09:54
Closing this as the issue has been solved.

**Closed by OBattler** 2018-11-01 09:54 UTC
