### ISSUE TITLE
GW-286CT-GEAR does not boot

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1551] opened 2021-07-14 23:35 UTC
**Describe the bug**
The machine restart itself in a loop after RAM memory check. the Goldstar 286 works just fine with the same disk image.

Configuration:
CPU: 286/16
RAM: 4mb
Disk: IDE type 9 
Controller: Internal IDE

Here is the CFG and HD image files:

[286 Goldstar HDD type 9.zip](https://github.com/86Box/86Box/files/6819416/286.Goldstar.HDD.type.9.zip)
[286 GW-GEAR-CT.zip](https://github.com/86Box/86Box/files/6819418/286.GW-GEAR-CT.zip)

**To Reproduce**
1. Configure the machine ( I use 4mb of RAM)
2. At the first boot, when finish checking RAM the option "F2" appears to enter the BIOS SETUP
3. Configure the memory I reserve 1mb for EMS memory
4. After this the machine restart itself in a loop after checking RAM memory

**Desktop (please complete the following information):**
 - OS: Windows 10 ver 2004
 - 86Box version: 3.0.0.3045
 - Build type: Dev

**Comment by OBattler** [comment] 2021-07-18 18:42
I have just tested this VM on the latest build and the issue is fixed, so I'm closing this.

**Closed by OBattler** 2021-07-18 18:42 UTC
Labels: bug
