### ISSUE TITLE
86Box window display ratio is incorrect when Guest OS resolution is high

### ISSUE THREAD

**Issue by huoqianyu** [86Box/86Box#1363] opened 2021-04-09 15:56 UTC
**Describe the bug**
When the resolution of the operating system running inside the 86Box is set to 1600x1200 or greater, the 86Box cannot display the screen at the correct scale. 

**To Reproduce**
1. Install any Operating System, such as Windows 2000 inside 86Box, choose a GPU which support high resolution, and set the resolution to 1600x1200 or higher.
2. We can see that the picture displayed inside the 86Box is "squashed" in the height direction. 

**Expected behavior**
The ratio should be correctly set when resolution is set to 1600x1200 or higher.

**Screenshots**
We can see this picture for example:
https://cdn.discordapp.com/attachments/266245344529088512/828418176664076358/1.PNG

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 19043.906
 - 86Box version: Since Build 2810
 - Build type: dev

**Additional context**
I used dichotomy to find the build number which introduced this bug, and finally found that Build 2810 introduced this problem.
Since then, every build has this problem. 

In Jenkens (https://ci.86box.net/job/86Box-Dev/2810) we can see build 2810's changelog:
`Changes
win_ui: rewrite resizing using WM_WINDOWPOSCHANGED (commit: 220fffc) (details / githubweb)
win_ui: fix status bar with resizable windows (commit: 3bc4098) (details / githubweb)
win_ui: remove redundant resizing code (commit: 014f167) (details / githubweb)`

I think maybe these changes about UI resize caused problem.

**Comment by OBattler** [comment] 2021-04-10 05:27
On my end, this happens when the guest is at, say, 1920x1080 already, so it all depends on what is the maximum window size that can fit on your screen.

**Comment by OBattler** [comment] 2021-04-10 05:30
I'm going to close this as not a bug because this is, ultimately, the result of the emulator being put into a resolution that can't fit onto the screen, and I would rather have the squishing than a return to the instability that we once had.

**Closed** 2021-04-10 05:31 UTC
Labels: notabug
