### ISSUE TITLE
Machine closing and not starting

### ISSUE THREAD

**Issue by floridainsummer505** [86Box/86Box#4775] opened 2024-08-30 12:41 UTC
### What happened?

When i start machine it closes

### Configuration file

```ini
[Standard Hayes-compliant Modem #1]
port = 2
baudrate = 4800
listen_port = 0
phonebook_file = C:/Users/Artemchik/Desktop/86ищч/lol.txt
telnet_mode = 0

[Realtek RTL8019AS #2]
mac = 71:e2:81

[General]
vid_renderer = qt_software
host_cpu = Intel(R) Pentium(R) CPU G3440T @ 2.80GHz
emu_build_num = 6000
uuid = 3da961fa-1004-5fb3-9031-849f4196760f

[Machine]
machine = s2dge
cpu_family = pentium2_xeon
cpu_speed = 300000000
cpu_multi = 3
fpu_type = internal
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
mem_size = 524288

[Video]
gfxcard = px_trio64_pci

[Input devices]
mouse_type = logibus

[Sound]
sndcard = sb16_pnp
fm_driver = nuked

[Network]
net_01_card = modem
net_01_net_type = pcap
net_01_host_device = \Device\NPF_{E4C9B849-7A57-4D1F-AA17-D2ECD8C5F0FE}
net_01_link = 0
net_02_card = ne2kpnp
net_02_net_type = slirp
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
fdc = none
hdc = ide_pci
cassette_mode = load

[Hard disks]
hdd_01_parameters = 63, 16, 4161, 0, ide
hdd_01_fn = 98vm.vhd
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = none
fdd_02_type = none
cdrom_02_parameters = 0, atapi
cdrom_02_ide_channel = 0:1
cdrom_02_type = NEC_CD-ROM_DRIVE280_3.08
```

### Operating system

Windows 10

### CPU

Intel(R) Pentium(R) CPU G3440T @ 2.80GHz

### 86Box version

v.4.2.6000

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by floridainsummer505** [comment] 2024-08-30 12:42
oop

**Comment by TC1995** [comment] 2024-08-30 12:58
More information is needed. Also, have you got the right roms?

**Comment by eddmanx** [comment] 2024-08-30 14:48
Where and how does it close? I just installed Windows 98 SE with your config and booted into it just fine.

However, it must be noted that the machine does get stuck during the boot process with build 6116 and up.

**Comment by floridainsummer505** [comment] 2024-08-30 15:38
it closes after some time when i start

**Comment by floridainsummer505** [comment] 2024-08-30 15:39
i had windows 98 se installed there

**Comment by OBattler** [comment] 2024-08-30 15:50
I did just fix the hang. Now to figure out why it stops.

**Comment by OBattler** [comment] 2024-08-30 15:51
> it closes after some time when i start

After how much time does it stop?

**Comment by eddmanx** [comment] 2024-08-30 16:14
> I did just fix the hang. Now to figure out why it stops.

By "stops" do you mean getting stuck on a black screen after the windows logo?

**Comment by OBattler** [comment] 2024-08-30 17:04
No, I mean the issue reported here - 86Box stopping/closing after some time. Which I can't seem to reproduce.

**Comment by OBattler** [comment] 2024-08-30 17:14
Closing this as can't reproduce - I left the Windows 98 install from eddmanx running for over an hour and it didn't close.

**Closed by OBattler** 2024-08-30 17:14 UTC
Labels: bug

**Comment by eddmanx** [comment] 2024-08-30 17:16
I can't see anything wrong on my end either. The only issue now is getting stuck on a black screen with build 6119. It happens with the same machine I posted. I'm using 32-bit NDR though.

**Comment by OBattler** [comment] 2024-08-30 17:36
I did just fix the black scren.
