### ISSUE TITLE
Microsoft Picture It! 2.0 can't seem to install properly

### ISSUE THREAD

**Issue by Astolfo2001** [86Box/86Box#4663] opened 2024-07-27 23:20 UTC
### What happened?

good evening

everytime I try to install _Microsoft Picture It! 2.0_ on my Windows 95 VM, it gives me this error:
![Monitor_1_20240727-164439-167](https://github.com/user-attachments/assets/64d3e162-695f-4f22-a816-7c1d324b8221)

the program seems to start up fine but when I try to uninstall it through Control Panel, it gives me these errors instead:
![Monitor_1_20240727-181953-846](https://github.com/user-attachments/assets/7598c4e6-e5a3-4515-89ff-acd44b8a2275)
![Monitor_1_20240727-181930-487](https://github.com/user-attachments/assets/41c4b7d6-c1cc-433e-9173-ad0fe4004dff)
![Monitor_1_20240727-181941-712](https://github.com/user-attachments/assets/c461e009-d450-4c29-b34b-256e637b2048)

so, what the heck is going on with that program?

And yes, before you ask, I get this error with both the standalone and _Microsoft Publisher 98 Deluxe_ bundle discs.

### Configuration file

```ini
[3Dfx Voodoo Banshee]
memory = 16
bilinear = 1
dithersub = 1
dacfilter = 0
render_threads = 4
recompiler = 1

[Realtek RTL8019AS #1]
mac = b3:a8:c8

[Novell NE2000 #1]
base = 0300
irq = 3
mac = ba:01:68
bios_addr = 00000

[Sound Blaster AWE64 Gold #1]
onboard_ram = 4096
control_pc_speaker = 0
receive_input = 1
receive_input401 = 0

[Standard PS/2 Mouse]
buttons = 4

[Realtek RTL8139C+ #1]
mac = 83:7a:db

[3Dfx Voodoo Graphics]
type = 2
framebuffer_memory = 4
texture_memory = 4
bilinear = 1
dithersub = 1
dacfilter = 0
render_threads = 4
sli = 0
recompiler = 1

[Matrox Mystique 220]
memory = 8

[S3 Trio64V2/DX PCI]
memory = 4

[General]
vid_renderer = qt_software
host_cpu = Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
emu_build_num = 5983
uuid = 52717376-8429-52bd-ba99-f1e6adeba0b2
vid_resize = 1
video_gl_vsync = 1
enable_discord = 1
force_43 = 1

[Machine]
machine = p5a
cpu_family = pentium_p55c
cpu_speed = 166666666
cpu_multi = 2.5
fpu_type = internal
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
mem_size = 65536

[Video]
gfxcard = trio64v2dx_pci
voodoo = 1
video_fullscreen_scale_maximized = 1

[Input devices]
mouse_type = ps2

[Sound]
sndcard = sbawe64_gold
fm_driver = ymfm

[Network]
net_01_card = rtl8139c+
net_01_net_type = pcap
net_01_host_device = \Device\NPF_{94EACA55-1626-497E-BA43-01E0DD9E79F9}
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = internal
cassette_mode = load

[Hard disks]
hdd_01_parameters = 63, 16, 8322, 0, ide
hdd_01_fn = WIN95HDD.vhd
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0
hdd_01_vhd_blocksize = 4096

[Floppy and CD-ROM drives]
fdd_01_type = 35_2ed
fdd_02_type = none
cdrom_01_speed = 72
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 0:1
fdd_01_image_history_01 = Y:/ROMs/DOS & WIN/win95dl16a_boot.img
cdrom_01_type = 86BOX_CD-ROM_1.00
cdrom_01_image_history_01 = Y:/ROMs/DOS & WIN/microsoft-publisher-98-deluxe-cd2-picture-it-2.0.iso
cdrom_01_image_history_02 = Y:/ROMs/DOS & WIN/microsoft-publisher-98-deluxe-cd1.iso
cdrom_01_image_history_03 = Y:/ROMs/DOS & WIN/Microsoft Office 97 Professional Edition SR-2 OEM [X03-73059].iso
cdrom_01_image_path = Y:/ROMs/DOS & WIN/microsoft-picture-it-2.0.iso
```

### Operating system

Windows 11

### CPU

Intel(R) Core(TM) i5-10300H

### 86Box version

v4.2 [build 5983]

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment] 2024-07-28 00:42
Closing this because this is not an 86Box bug as I just attempted to reproduce it and I was unable to (Picture-It! 2.0 installed just fine). Consider reinstalling Windows 95.

**Closed by OBattler** 2024-07-28 00:42 UTC
Labels: bug
