### ISSUE TITLE
Microsoft Virtual PC 2007 motherboard crashes 86Box

### ISSUE THREAD

**Issue by cigaryno** [86Box/86Box#3613] opened 2023-08-21 18:15 UTC
**Describe the bug**
If you try to boot the Virtual PC 2007 motherboard, 86Box crashes in a few seconds.

**To Reproduce**
1. Create a VM with the Microsoft Virtual PC 2007 motherboard.
2. Start the VM.
3. 86Box crashes.

**Expected behavior**
86Box stays running and the emulated motherboard POSTs.

**Screenshots**
_No screenshots_

**Desktop (please complete the following information):**
 - OS: Windows 11 Canary (`25931.1000.amd64fre.rs_prerelease.230811-1316`)
 - 86Box version: 4.0 (from Jenkins)
 - Build information: 4.0.4920 (AMD64, old recompiler)

**Additional context**
_None_

**Comment by OBattler** [comment] 2023-08-21 21:17
Closing this because I can not reproduce this at all - make sure to give 86Box a NX exception because the recompiler executes code blocks and that usually trips NX.

**Closed by OBattler** 2023-08-21 21:17 UTC
Labels: bug
