### ISSUE TITLE
Windows 7 GPU-Z BSOD

### ISSUE THREAD

**Issue by Pixelsuft** [86Box/86Box#1519] opened 2021-07-02 11:00 UTC
**Describe the bug**
When I'm starting GPU-Z and clicking to continue without installation, Windows 7 felts into BSOD

**To Reproduce**
1. Start GPU-Z (my version is 2.39.0)
2. Click to continue without installation
3. See BSOD

**Screenshots**
![image1](https://user-images.githubusercontent.com/68371847/124206330-5611d880-db0d-11eb-8f4f-1f09d5f6a5e6.png)

**Desktop:**
 - OS: [Windows 10]
 - 86Box version: [v3.0 build 3010]
 - Build type: [dev]

**Additional context**
Emulated videocard is `[PCI] Phoenix S3 Trio64`
In safe mode it not starting with error could not start driver in safe mode
![image2](https://user-images.githubusercontent.com/68371847/124264732-0f4cce80-db5f-11eb-8a9f-e5396681a39c.png)

**Comment by OBattler** [comment] 2021-07-04 21:40
This may require 686 instructions that VIA C3 does not have, so closing it for it being intended behavior, but will reopen if someone provides evidence of GPU-Z running on a real VIA C3.

**Closed by OBattler** 2021-07-04 21:40 UTC
Labels: bug
