### ISSUE TITLE
Problems running FlexOS 286 v1.42

### ISSUE THREAD

**Issue by dfawcus** [86Box/86Box#3715] opened 2023-09-30 22:30 UTC
**Describe the bug**

Using an IBM AT machine (286) it is unable to boot the FlexOS 286 1.42 PTK-1 disk.  The FlexOS system panics shortly after loading.  See attached screenshots.

This was seen while using both the the basic IBM-AT and the AMI BIOS IBM-AT (Config files included).  The included harddisk image is simply a file of zeros.

FlexOS 286 seems to exercise even more of the specific 286 behaviours than do early versions of OS/2. It also (if it boots) has the ability to run a limited set of DOS programs while staying in protected mode, by making use of loading restricted forms of segment cache entries (probably by using LOADALL).

The disks can be found on **bitsavers** in [the FlexOS 286 1.42 Dev Kit](http://bitsavers.trailing-edge.com/bits/DigitalResearch/FlexOS/FlexOS_286_1.42_Dev_Kit.zip), the boot / install disk (PTK1.IMD) has been extracted, converted to a raw img, and included in the attached CONFIG.

It would be worth downloading the complete file, and also extracting the SBK ZIP files, as they include the startup source code (C and assembly), along with .OBJ files (including debug symbols) for all of the OS.  This may help in pinpointing where the issue is.

There are other versions (1.3 and 1.31) available on that site, but 1.42 seems like the best to use as it should be the easiest to install.

**To Reproduce**

Start up with the files from the attached CONFIGS.zip file, and wait for the panic shortly after seeing the 'Loading FlexOS 286' message clear off the screen.

**Expected behavior**

The system should boot without a panic, identify itself as being from 'March 14, 1988. Version 1.42', and start executing the CONFIG.BAT file in order to load initial drivers.

**Screenshots**

Panic with AMI BIOS IBM-AT, and IBM BIOS IBM-AT (both are the same):
![IBMAMIAT](https://github.com/86Box/86Box/assets/3442522/0bd2d1bb-7df0-457c-b66c-68d38352d6db)

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu 22.04.2 LTS)
 - 86Box version: v4.0 
 - Build information: 5000 (86Box-Linux-x86_64-b5000.AppImage)

**Additional context**

[SCRSHOT.ZIP](https://github.com/86Box/86Box/files/12775632/SCRSHOT.ZIP)
[CONFIGS.zip](https://github.com/86Box/86Box/files/12775634/CONFIGS.zip)

I recall a similar effect when trying to use FlexOS 2.32 on an earlier version of 86Box. There the panic contains more information. I seem to recall that it happened when interrupts were first enabled, and it triggered by the timer interrupt (from the RTC chip).

I wonder if this is due to the use of a "conforming segment" for the interrupt handlers, as FlexOS uses such, and the exception is a "General Protection"?

From the disp286.a86 source, we have this:

```
; doint - all interrupt come here via comefrom table
;
; This code is run at pl3 and pl0. At initialization it is set to
; conforming code at pl3. All references must be do-able at pl3.
; This includes the references to ipage.
; determine if this was a hw int or sw int
```
and later:
```
;               EXC_SEG is a PL0 CONFORMING selector.
```
So there are some games in play with conforming segments which may be what is leading to the GP exception.

**Comment by dfawcus** [comment] 2023-10-02 23:30
FWIW, I've now built my own version from HEAD as below, and the issue still appears.  I'm starting a bit of an exploration as to the cause, which is a voyage of discovery.

```
commit b1c7834476635f7227a584b5d9defe5f80f09aef (HEAD -> master, origin/master, origin/HEAD)
Author: OBattler <oubattler@gmail.com>
Date:   Thu Sep 28 07:34:20 2023 +0200
```

**Comment by dfawcus** [comment] 2023-10-13 11:45
After a bit of exploring, I believe the above crash relates to the floppy disk simulation.

Using the SBK5.IMD file from the same archive, and following similar procedures, one can start which is the driver development version of the same OS version. This has a built in debugger, which needs a terminal attached to COM1.

I was then able to find that the crash was within the floppy disk interrupt handler, and the source code for it (included in the above archive) indicates that it is somewhat fragile.  So it may be a timing issue triggering bugs inherent in the driver.

By using the debugger, I terminated the floppy driver initialisation, getting beyond that part of the start up code, and hit another crash.  This was from a divide by zero exception.

Based on experience with developing on later versions of FlexOS with faster CPUs, I suspect that may be related to the RTC clock interrupt rate vs CPU rate, but need to verify that.

**Comment by lgj1107** [comment] 2024-02-21 04:53
Changing the floppy disk controller to B215 will not cause any abnormalities, but the screen display will be incorrect.
This should be a fault in the internal controller.

<img width="1015" alt="6B0270A297406CB99E66472144A7061116" src="https://github.com/86Box/86Box/assets/3366897/219bae1b-2e7d-4e8e-8985-acfe8f25938d">

**Comment by OBattler** [comment] 2024-02-24 23:26
The strange thing is - the FDC code is always the exact same, all that changes is an added BIOS.

**Comment by OBattler** [comment] 2024-02-24 23:28
But, there may very well be a bug there - since the 386BSD reset loop appears to have also been traced to the FDC.

**Comment by OBattler** [comment] 2024-02-25 04:52
I'm quite sure we do set it to 1 when needed.

**Comment by OBattler** [comment] 2024-02-25 07:14
Try booting this now - I just fixed the behavior of the RQM bit in DMA mode (it turns out RQM is never supposed to be set in DMA mode), which fixed 386BSD. Perhaps that fixes this, too.

**Comment by cartifanwlr** [comment] 2024-02-25 13:51
> Try booting this now - I just fixed the behavior of the RQM bit in DMA mode (it turns out RQM is never supposed to be set in DMA mode), which fixed 386BSD. Perhaps that fixes this, too.
Confirmed not working on build 5572 with the attached config.
![image](https://github.com/86Box/86Box/assets/109605173/74bf6e33-ba2c-481b-955b-1cad1928118e)

**Comment by OBattler** [comment] 2024-03-03 16:41
It appears to be causing a DOR reset that it shouldn't be.

**Comment by OBattler** [comment] 2024-03-03 16:57
OK, it turns out FlexOS is actually buggy:
> Write FDC 03F4 03
> [0A30:0000027C] Read FDC 03F4 80 [0:00]
> *** 1 repeats ***
> Write FDC 03F4 DF
> fdc_callback(): -1
> fdc_int(1): fdc->fintr = 1
> [0A30:0000027C] Read FDC 03F4 80 [0:00]
> *** 2 repeats ***
> Write FDC 03F4 08
> [0A30:0000027C] Read FDC 03F4 80 [0:00]

It writes this 03 DF 08, which is the SPECIFY command and its two parameters, to port 3F4 (the DSR) instead of to port 3F5, which causes a DSR reset.

**Comment by OBattler** [comment] 2024-03-03 17:08
OK, so bit 7 (soft reset) of the DSR is self-resetting, perhaps the real hardware just so happens to reset that bit back to 1, thereby thwarting the DSR reset?

**Comment by OBattler** [comment] 2024-03-03 17:09
After implementing that, the panic is gone but it now gets stuck on a blinking cursor.

**Comment by OBattler** [comment] 2024-03-03 17:13
OK, by not resetting the status, it works.

**Closed** 2024-03-03 17:19 UTC
Labels: bug

**Comment by dfawcus** [comment] 2024-03-07 13:59
Ah - thanks.  The enhancement should make it a bit easier to continue debugging the image.

I'll get back to my experiments, as see how far I get before the next failure.
