### ISSUE TITLE
 The ports settings give strange results.

### ISSUE THREAD

**Issue by Lutepatious** [86Box/86Box#4553] opened 2024-06-22 09:06 UTC
### What happened?

Some MB port settings give strange results.
(Load setup defaults at BIOS setting)

1. ASUS PCI/I-486SP3G
   Always appeared COM4 (0x2E8)
 
2. ASUS P/I-P55T2P4
  Always disable LPT1 (0x378, 0x3BC or 0x278 ... any BIOS settings)

### Configuration file

```ini
1. ASUS PCI/I-486SP3G

[Standard PS/2 Mouse]
buttons = 4

[General]
vid_renderer = qt_software
host_cpu = 13th Gen Intel(R) Core(TM) i9-13900K
emu_build_num = 5862
uuid = b79fad88-c851-58df-9afe-d717630fc36f

[Machine]
machine = 486sp3g
cpu_family = idx4
cpu_speed = 100000000
cpu_multi = 3
fpu_type = internal
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
mem_size = 16384

[Video]
gfxcard = mach64gx_pci
8514a = 1

[Input devices]
mouse_type = ps2

[Sound]
sndcard = sb16
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
scsicard_1 = ncr53c810
hdc = internal
cassette_mode = load

[Hard disks]
hdd_01_parameters = 63, 16, 1024, 0, ide
hdd_01_fn = D:/86Box/test.vhd
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0
hdd_01_vhd_blocksize = 4096

[Floppy and CD-ROM drives]
fdd_01_type = 35_2ed
fdd_02_type = 525_2hd_dualrpm
cdrom_01_speed = 32
cdrom_01_parameters = 1, scsi
cdrom_01_scsi_location = 0:00
cdrom_01_type = PLEXTOR_CD-ROM_PX-32TS_1.03

2. ASUS P/I-P55T2P4

[General]
vid_renderer = qt_software
host_cpu = 13th Gen Intel(R) Core(TM) i9-13900K
emu_build_num = 5862
uuid = 1586b521-ed5c-5b77-9ed0-3ef5857f5bf9

[Machine]
machine = p55t2p4
cpu_family = pentium_p54c
cpu_speed = 75000000
cpu_multi = 1.5
fpu_type = internal
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
mem_size = 262144

[Video]
gfxcard = elsawin2kprox_964_pci

[Input devices]
mouse_type = ps2

[Sound]
sndcard = sb16
fm_driver = nuked
midi_device = cm32l
midi_in_device = midi_in

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
scsicard_1 = ncr53c810
hdc = internal
cassette_mode = load

[Hard disks]
hdd_01_parameters = 63, 16, 1024, 0, ide
hdd_01_fn = DOS.vhd
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0
hdd_01_vhd_blocksize = 4096

[Floppy and CD-ROM drives]
fdd_01_type = 35_2ed
fdd_02_type = 525_2hd_dualrpm
cdrom_01_speed = 32
cdrom_01_parameters = 1, scsi
cdrom_01_scsi_location = 0:00
cdrom_01_type = PLEXTOR_CD-ROM_PX-32TS_1.03

[Standard PS/2 Mouse]
buttons = 4

[Sound Blaster 16 #1]
base = 0220
base401 = 0330
irq = 5
dma = 1
dma16 = 5
opl = 1
control_pc_speaker = 1
receive_input = 1
receive_input401 = 1

[S3 Vision964 PCI (ELSA Winner 2000 Pro/X)]
memory = 8

[Roland CM-32L Emulation]
output_gain = 100
reverb = 1
reverb_output_gain = 100
reversed_stereo = 0
nice_ramp = 1

[MIDI Input Device]
midi_input = 0
realtime = 0
thruchan = 1
clockout = 1
```

### Operating system

Windows 11

### CPU

Intel Core i9 13900K

### 86Box version

Build 5634 or 5682

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment] 2024-07-21 03:06
Can't reproduce it for the first machine.

**Comment by OBattler** [comment] 2024-07-21 03:10
I can reproduce the second one though, on 5634 - let me see if it still happens on the latest build.

**Comment by OBattler** [comment] 2024-07-21 03:11
It does, but setting the parallel port type to normal fixes it. This is going to be properly fixed in 4.3 when I finally finish the ECP+EPP implementation.

**Closed by OBattler** 2024-07-21 03:11 UTC
Labels: bug
