### ISSUE TITLE
86Box-Dev-32-c91b1f2b sometimes crashes when you use the Ctrl+F11 screenshot shortcut.

### ISSUE THREAD

**Issue by LilShootDawg** [86Box/86Box#350] opened 2018-12-02 02:13 UTC
It'll crash and you have to end the process in task manager even if you X out of the program.
EDIT: It just froze my whole computer. Image: https://imgur.com/a/FePyCEO

**Comment by dhrdlicka** [comment] 2018-12-02 13:53
Could you please provide your configuration files?

**Comment by LilShootDawg** [comment] 2018-12-02 16:58
> [Machine]
machine = ibmxt
mem_size = 640
cpu_use_dynarec = 0
time_sync = local
cpu = 2

[Video]
gfxcard = ega
voodoo = 1

[Input devices]
mouse_type = logibus

[Other peripherals]
hdc = xtide

[General]
window_remember = 1
window_coordinates = 646, 472, 456, 364
vid_renderer = d3d
video_fullscreen_scale = 4

[3DFX Voodoo Graphics]
type = 2
framebuffer_memory = 4
texture_memory = 4
bilinear = 1
dacfilter = 0
render_threads = 2
sli = 1
recompiler = 1

[Standard PS/2 Mouse]
buttons = 4

[Sound]
sound_type = int16

[Hard disks]
hdd_01_parameters = 17, 4, 240, 0, ide
hdd_01_fn = D:\emulators\86Box-Dev-32-6410e0ac - foranything\hdd.img
hdd_01_ide_channel = 0:0

[Floppy drives]
fdd_02_type = none
fdd_01_type = 525_2hd
fdd_01_fn = D:\windowsversions\Microsoft MS-DOS 3.20 [Amstrad OEM] (5.25-360k)\Disk01.img

[Mouse Systems Serial Mouse]
port = 0
buttons = 4

[Hercules]
rgb_type = 0
blend = 0

[EGA]
memory = 256
monitor_type = 9

**Comment by OBattler** [comment] 2019-01-09 07:11
The screenshot code does nothing that can do this. However, if the program running inside the emulator responds to the same key combination, it might be hard freezing the emulator by doing who knows what.

**Comment by OBattler** [comment] 2019-09-22 20:40
Wait, that was not a crash, but a freeze - maybe I need to wait for the mutex there?

**Comment by OBattler** [comment] 2019-09-23 03:44
It seems to becaused by the D3DX screenshot function that is used by the Direct3D 9 renderer. I'm still thinking how to solve this properly - if it was easier to get the rendered buffer, I would make it use lipbng like the DirectDraw and SDL renderers use, but unfortunately, it's not.

**Comment by OBattler** [comment] 2019-10-20 19:30
D3DX is now no longer used, can someone who was able to reproduce this issue, test this and see if it still occurs?

**Comment by OBattler** [comment] 2019-10-20 20:23
From the reports I got, this no longer happens, so I am closing this issue. If anyone gets it again, please open a new one.

**Closed by OBattler** 2019-10-20 20:23 UTC
Labels: bug
