### ISSUE TITLE
Freeze during renderer switching

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [86Box/86Box#298] opened 2018-07-24 09:37 UTC
86box may hang completely - Windows consider it unresponsive and suggest to close application, I am using Win 10 Pro. How to get it - switch between fullscreen and backwards while booting (just after mouse pointer is visible on green background) or installing Windows (IO high activity + fullscreen cause this?). There is other way to confirm it -  I tested it right now - switch from windowed mode into fullscreen when scandisk is running in Win98 - I have got freeze.
I am using d1ce1a91. Emulated machine specs:
Machine - [Socket 7 VX] Award 430VX PCI
CPU - Intel Pentium 75
Videcard - PCI S3 Virge/DX
Memory - 32MB
Renderer - Direct 2D 1.0

I am also tried to switch to different renderer:
DirectDraw - terrible, hangs without any chance to close it, only way is log off or hard reset host machine.
Direct3D - just hangs, without Windows suggestion to close, mouse pointer is misplaced - looks like it still locked up by  emulated machine.
SDL - does not work for me for some reason.

**Comment by dhrdlicka** [comment] 2018-07-25 14:18
First of all, you are using an outdated build. There weren't any changes regarding fullscreen since d1ce1a9, but you should make sure to test the latest available build to prevent reporting bugs that could be already fixed. We are going to try to reproduce your problem and will then get back to you.

For SDL to work your 86Box folder needs to contain `sdl2.dll`, which can be downloaded from https://www.libsdl.org/download-2.0.php (make sure you download the 32-bit version). Be warned that SDL fullscreen is unusable as of now, because mouse input doesn't work yet. We know the exact cause of that bug and it should be fixed soon.

In any case `Ctrl`+`Alt`+`Del` should still work as that is always handled by Windows and regular applications can't override this behavior. Select Task Manager from the security menu and kill 86Box. In case the mouse is still clipped, pressing `Win` seems to fix that.

**Comment by OBattler** [comment] 2018-07-28 21:58
I confirm the bug, I've experienced hangs on switching to or from full screen as well. It's being worked on.

**Comment by dhrdlicka** [comment] 2018-07-31 10:26
The emulator freezes while trying to take control of the video to be able to switch the renderer, so it is not limited to transitions between full screen and windowed modes, but to any renderer change.

**Comment by OBattler** [comment] 2019-05-20 16:59
This appears to be fixed now.

**Comment by dhrdlicka** [comment] 2020-04-27 11:42
Looks like this bug has reappeared when the emulator window is minimized.

**Closed** 2020-04-27 11:42 UTC
Labels: bug
