### ISSUE TITLE
PCjr bios gets zoomed in when I change settings

### ISSUE THREAD

**Issue by ualaa1** [86Box/86Box#1383] opened 2021-04-17 19:52 UTC
**Describe the bug**
Bios gets zoomed in when I change anything from the settings. Also, the status bar at the bottom disappears.
Here is my config file:
[86box.zip](https://github.com/86Box/86Box/files/6329932/86box.zip)

**To Reproduce**
One way to reproduce it is to change the floppy disk size on drive 1 to any size you want

**Expected behavior**
Bios shouldn't be zoomed in.

**Screenshots**
![bandicam 2021-04-17 12-49-22-489](https://user-images.githubusercontent.com/68984176/115125280-d21f6a00-9f7b-11eb-8f86-a273b0064c37.png)
![bandicam 2021-04-17 01-27-16-788](https://user-images.githubusercontent.com/68984176/115125281-d3e92d80-9f7b-11eb-8fd3-a23af70186b0.png)

**Desktop (please complete the following information):**
Windows 10 regular build

**Comment by OBattler** [comment] 2021-04-17 20:24
I can't reproduce this at all. I literally tested the PCjr last night, and changed the settings, multiple times.

**Comment by OBattler** [comment] 2021-04-17 20:26
I see now - this is with window size forced, I think I know where this happens.

**Comment by OBattler** [comment] 2021-04-17 20:48
Try the latest build, see if this is fixed now.

**Comment by ualaa1** [comment] 2021-04-17 22:32
Nope, still happens
![bandicam 2021-04-17 15-31-30-772](https://user-images.githubusercontent.com/68984176/115128349-13bb0f80-9f92-11eb-8e7e-7d1cfe4ec204.png)

**Comment by OBattler** [comment] 2021-07-19 01:22
Does this still happen?

**Comment by OBattler** [comment] 2021-07-30 17:41
I'm going to close this under the assumption that the recent High DPI resize fixes fixed this. If this still happens, it can be reopened.

**Closed by OBattler** 2021-07-30 17:41 UTC
Labels: bug
