### ISSUE TITLE
[i440FX ASUS P/I-P65UP5] Black Screen on Graphical mode.

### ISSUE THREAD

**Issue by Memwhis** [86Box/86Box#950] opened 2020-07-28 13:57 UTC
When I minimized and wait some minutes, I get a black screen and it goes when I do something on the screen.

1. The video mode should be graphical. This not happens on text-mode.
2. Minimize the window and wait some minutes.
3. And click the 86Box icon on the taskbar. And you get the black screen.

**Expected behavior**

Photo: 
![86box](https://user-images.githubusercontent.com/68910239/88675121-461a9900-d0f3-11ea-92a8-fd1d1f77951e.PNG)

 - OS: Windows 10 Home
 - 86Box version: v2.10 build 2509
 - Build type: regular

**Comment by dhrdlicka** [comment] 2020-07-28 13:58
Try changing the renderer in the Video menu to see if display comes back up.

**Comment by Memwhis** [comment] 2020-07-28 14:23
I changed renderer to SDL (Software) but I still get the black screen.

**Comment by OBattler** [comment] 2021-04-07 00:40
Closing this because there have been renderer fixes after this, and it's not certain the issue is still there. If it is, it can be reopened.

**Closed by OBattler** 2021-04-07 00:40 UTC
Labels: bug
