### ISSUE TITLE
Graphical corruption in IBM PCjr cartridge titles

### ISSUE THREAD

**Issue by TheGhostOfInky** [86Box/86Box#4734] opened 2024-08-19 21:25 UTC
### What happened?

Multiple IBM PCjr cartridge games exhibit graphical corruption when being ran on 86Box, I tried all manner of different combinations of graphical settings (RGB and composite, overscan, different renderers, 4:3 scaling, filtering) and none of them resolved the issue. Games are otherwise playable and do not crash, so this seems to be entirely localized to the display subsystem, tried 64k, 128k and 640k memory configurations and the result was unchanged. Screenshots were obtained from the latest version of 86Box in the rob72/86Box copr repo and were confirmed by running the same roms on the latest build (v4.2 b6000) from Github on Windows 11.

![Monitor_1_20240819-214205-256](https://github.com/user-attachments/assets/4a25e0a6-6423-4c4c-9e03-6f430a9de306)
![Monitor_1_20240819-214242-637](https://github.com/user-attachments/assets/4ecdbf22-db3f-4bf9-a0d0-21dc1e4bcb73)
![Monitor_1_20240819-214245-606](https://github.com/user-attachments/assets/790a5c7c-cc27-420b-a61c-8ac57e7933c4)
![Monitor_1_20240819-214319-998](https://github.com/user-attachments/assets/7264f6e2-19ec-429b-baf8-24b21db794d4)
![Monitor_1_20240819-214428-307](https://github.com/user-attachments/assets/64ace118-18be-40ec-bfd1-97ab42ab1b6e)
![Monitor_1_20240819-220536-286](https://github.com/user-attachments/assets/6673f793-84c7-4d20-98c4-360383c2ebde)
![Monitor_1_20240819-220542-615](https://github.com/user-attachments/assets/a80e14a6-d38d-4a67-bbc2-61e64fdf14e2)

### Configuration file

```ini
[IBM PCjr]
display_type = 0

[General]
vid_renderer = qt_software
host_cpu = AMD Ryzen 5 5500U with Radeon Graphics
uuid = 675accdf-bf8e-569b-abd6-831c2fbb5f8a
force_43 = 1

[Machine]
machine = ibmpcjr
cpu_family = 8088
cpu_speed = 4772728
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = disabled
fpu_type = 8087
mem_size = 640

[Video]
gfxcard = internal

[Input devices]
mouse_type = none

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = none
cassette_enabled = 1
cassette_mode = load
cartridge_01_fn = /home/inky/86Box/images/Games/PITFALL2.JRC

[PC/XT XTIDE]
bios = xt

[Floppy and CD-ROM drives]
fdd_02_type = none
```

### Operating system

Fedora Linux 40 and Windows 11 23H2

### CPU

AMD Ryzen 5 5500U

### 86Box version

v4.2 Build 6000

### Build architecture

Linux - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

Same ROMs work flawlessly under DOSBOX-X:

![boot_000](https://github.com/user-attachments/assets/34d46d14-9241-4035-ad09-e064041adf5a)
![boot_001](https://github.com/user-attachments/assets/c421d045-f178-4216-b932-7599102f3180)

**Comment by Digitoxin1** [comment] 2024-08-20 00:47
I cannot reproduce this issue in 86Box using build 6070.  I've attached the Pitfall 2 rom I used.  On an unrelated note, removing a cartridge from 86Box while the game is running will crash the emulator.

[Pitfall II - Lost Caverns (1984) (IBM PCjr).zip](https://github.com/user-attachments/files/16667236/Pitfall.II.-.Lost.Caverns.1984.IBM.PCjr.zip)

**Comment by Digitoxin1** [comment] 2024-08-20 00:49
Here is a screenshot.
![image](https://github.com/user-attachments/assets/a949d125-fb3f-4b99-9e9b-b62d98588043)

**Comment by TheGhostOfInky** [comment] 2024-08-20 06:23
I tested the rom Digitoxin1 posted and on build 6000 and the issue still happened, trying on the latest Appimage Jenkins build (6070) the issue seems resolved with both Pitfall II and Mouser.

As for the emulator crashing when you eject a cartridge that's expected as PCjr cartridges are memory mapped roms, so by removing them you're essentially making the instruction pointer point to floating address lines, much like happened with game consoles and other cartridge based computers (VIC-20, C64, Atari 8-bit, etc).

Looking at the commit history I'm guessing this issue got fixed by commit [760c720](https://github.com/86Box/86Box/commit/760c720), judging by the title, you can close this as already resolved although I think it would be a good idea to add a link to the latest Jenkins artifacts on the issues template and the readme, since it took me some time to find it on the documentation website.

**Comment by Digitoxin1** [comment] 2024-08-20 06:34
Just to be clear, its not just the emulated system that crashed.  86Box itself crashed when removing the PCjr cartridge.  This crash appears to be inconsistent though and doesn't always occur.

**Comment by eddmanx** [comment] 2024-08-20 08:01
> you can close this as already resolved

The author of an issue can also close it.

**Comment by TheGhostOfInky** [comment] 2024-08-20 13:36
> 86Box itself crashed(...) This crash appears to be inconsistent though and doesn't always occur.

86Box crashes when it tries to execute certain illegal instructions/IO operations, depending on the instructions the floating address lines return different garbage opcodes will return, causing either the emulated system or 86Box itself to crash. Ideally 86Box should automatically soft-reset when a cartridge is ejected since no valid state can result from it.

**Comment by OBattler** [comment] 2024-08-21 00:12
That is now done. Therefore, this can be closed now.

**Closed by OBattler** 2024-08-21 00:12 UTC
Labels: bug
