### ISSUE TITLE
The high density floppy disk controllers does not work after the recent changes

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1269] opened 2021-02-05 15:05 UTC
**Describe the bug**

After the recent changes to the DTK high density controllers, they stopped working. The Micronics 215B does not work either.
 
My configuration: AMI XT 8088, 640kb RAM, DTC-5150X controller, 76mb hard disk (C/H/S 1023/9/17) and
CGA grahipcs card.

The issues are:

1.The new Magitronic B215, always detects two 1.44 MB floppy drives, regardless the any different configuration in 86 boxes.

2. The Hard disk controller does not work and the hard disk does not initialize if Magitronic B215 or the DTK PII-151B are present (In spite of both controller uses different upper memory regions)

3. The DTK PII-158B (MiniMicro4) have no issue with the DTC-5150X controller, but does not read the 1.44Mb disks, even on 1.44Mb drives.

Here are my CFG and hard disk files: 

CFG file:
[CFG.zip](https://github.com/86Box/86Box/files/5933311/CFG.zip)

HDD file:
[DTC XT Hard Disk.zip](https://github.com/86Box/86Box/files/5933369/DTC.XT.Hard.Disk.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10 ver 2004
 - 86Box version: 3.0.0.2796 (86Box-32-955b6436)
 - Build type: Regular

**Comment by OBattler** [comment] 2021-02-06 18:35
Just for testing sake, please test this on VARCem as well, to see if the DTK PII-158B can read 1.44 MB disks there.

**Comment by tiseno100** [comment] 2021-02-07 09:03
The Magitronics B215 will require analysis of it's FDC chip datasheet. Seems like there's a register responsible of choosing drive type but it's never accessed by the BIOS for any sorts of reasons.

The MiniMicro 4 has to be confirmed if it was even intended for XT machines at all. I didn't received any issue testing it under an AT board. MiniMicro 1 works with XT machines as intended.

**Comment by Fenix770** [comment] 2021-02-07 11:26
I can confirm that the hard disk boots right with the DTC-5150X, now only *if* I select the "internal controller" option for FDD.
(Before the recent changes both high density DTK controllers worked fine)

I don't know if the disk is bootable on AT machines, since it's MFM and uses a non standard geometry supported only by the DTC-5150X card. 

I tried, for example, the Trigem 286 does not have any 1023 cylinder hard disk type in the options, and the custom geometry disk "type 47" option does not work. (I used the WD MFM/RLL ISA 16-bit controller)
I also tried to use the DTC-5150X with the Trigem and disable the hard disk in the setup BIOS to see if can use the DTC own BIOS with no avail.
According the DTC5150X  manual this card should be compatible with AT machines.

**Comment by Fenix770** [comment] 2021-02-07 22:34
I tested the Amstrad 2086, with "IBM PC fixed disk adapter" (Xebec) and a 20MB hard disk C/H/S 306/8/17.

The machine boots right with any of the high density controllers but:

1. Take several seconds more to boot
2. Any of the cards can read high density floppies (At least the 1.44MB working image I tested)
![Amstrad 2086](https://user-images.githubusercontent.com/31600563/107161325-d0816680-697a-11eb-8275-5f4c648f0a58.png)

Also tested the machine without the EMS board, with the same result.
![Amstrad 2086-2](https://user-images.githubusercontent.com/31600563/107161373-1807f280-697b-11eb-90b7-98f69ea90068.png)

So, maybe, there is some kind of incompatibility with the hard disk controllers.

**Comment by Fenix770** [comment] 2021-02-07 22:53
I tested the Amstrad 2086, with "IBM PC fixed disk adapter" (Xebec) and a 20MB hard disk C/H/S 306/8/17.

The machine boots right with any of the high density controllers but:

1. Take several seconds more to boot
2. Any of the cards cannot read high density floppies (At least the 1.44MB working image I tested)
![Amstrad 2086](https://user-images.githubusercontent.com/31600563/107161325-d0816680-697a-11eb-8275-5f4c648f0a58.png)

Also tested the machine without the EMS board, with the same result.
![Amstrad 2086-2](https://user-images.githubusercontent.com/31600563/107161373-1807f280-697b-11eb-90b7-98f69ea90068.png)

So, maybe, there is some kind of incompatibility with the hard disk controllers.

**Comment by tiseno100** [comment] 2021-02-08 10:42
I'll see what can I do for that. Biggest problem is I can't confirm if those were meant to work flawlessly on XT boards.

**Comment by tiseno100** [comment] 2021-02-08 16:21
Alright. I've fixed the Magitronics. Now the csrd can detect all of it's supported drives capacity just fine.

**Comment by OBattler** [comment] 2021-03-20 05:17
As I believe this was fixed, I'm closing this.

**Closed by OBattler** 2021-03-20 05:17 UTC
Labels: bug
