### ISSUE TITLE
Dynamic VHD out-of-bounds write

### ISSUE THREAD

**Issue by Carmina16** [86Box/86Box#4337] opened 2024-04-07 11:01 UTC
### What happened?

I was playing with some BIOS settings and noticed that the 86box process became stuck. It turned out those were several gigabytes of zeroes written into the HDD file (dynamic VHD with 2MB blocks), apparently because the file pointer was moved out of limit of the maximum size of the disk.

Please make sure that you don't write data outside of limits established by the VHD file structure.

### Configuration file

```ini
N/A
```

### Operating system

Windows 10

### CPU

N/A

### 86Box version

4754

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by cold-brewed** [comment] 2024-04-07 15:10
We'll need your config file, disk (should compress fine if it's all zeroes), `nvr` directory and steps to reproduce.

**Comment by OBattler** [comment] 2024-04-16 17:42
This is most likely already fixed - pretty much every emulated hard disk controller had a buggy implementation of the FORMAT command that errenously a non-zero starting sector. This has since been rectifies. So I'm closing this as fixed, it can be reopened if it's not.

**Closed by OBattler** 2024-04-16 17:42 UTC
Labels: bug
