### ISSUE TITLE
CGA in no brown RGB mode still shows brown

### ISSUE THREAD

**Issue by einstein95** [86Box/86Box#3043] opened 2023-01-20 20:24 UTC
**Describe the bug**
When using CGA display with RGB type set to "Color (no brown)", still shows brown.

**To Reproduce**
1. Set the Display to CGA and RGB type to "Color (no brown)"
3. Boot the PC booter version of King's Quest
4. Press Esc to use RGB mode
5. The credit scroll appears in brown

**Expected behavior**
The credit scroll should appear white, like the composite mode

**Screenshots**
Title screen in RGB (no brown) mode
![Monitor_1_20230121-085935-13013](https://user-images.githubusercontent.com/2461173/213798503-a584dff2-24d5-459c-aed7-6628be6bef14.png)
Title screen in Composite (new) mode
![Monitor_1_20230121-090618-696696](https://user-images.githubusercontent.com/2461173/213798523-d9a45451-bbe9-4741-812e-f9959ecc081c.png)

**Desktop (please complete the following information):**
 - OS: Mac OS X Monterey
 - 86Box version: v3.11 [build 4311] [ab086750e]
 - Build information: release from 86box.net

**Additional context**
Using an MFM image created from kfraw

**Comment by dhrdlicka** [comment] 2023-01-21 18:08
> The credit scroll should appear white, like the composite mode
No, it should appear as dark yellow. CGA has special circuitry to turn dark yellow into brown.

**Comment by einstein95** [comment] 2023-01-26 00:49
> No, it should appear as dark yellow. CGA displays have special circuitry to turn dark yellow into brown.

Indeed, just came across this image on Wikipedia which shows what it should look like (bottom-right)
![image](https://upload.wikimedia.org/wikipedia/en/8/80/KQ_CompVsRGB.png)

**Comment by JimboMumbo** [comment] 2023-01-26 01:41
Sounds remarkable

**Comment by OBattler** [comment] 2023-01-26 04:56
Essentially a duplicate of this issue: https://github.com/86Box/86Box/issues/3032 . Basically, palette is not rebuilt on reset.

**Closed by OBattler** 2023-01-26 04:56 UTC
Labels: bug
