### ISSUE TITLE
1024 cylinders not supported on MFM hard disks

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#822] opened 2020-06-18 22:53 UTC
**Describe the bug**

I created a 76 MFM hard disk with 1024 cylinders with an earlier version of 86box, but in the latest commit it only allows 1023 cylinders. (On PCEm it is type 35 hard disk C/H/S 2014/9/17)

I used one of the supported geometries of the MFM DTC 5150X controller, which supports two hard disk configurations with  1024 cylinders.
Here is the manual of the controller: [http://www.minuszerodegrees.net/manuals/DTC/DTC%205150X%20-%20Installation%20Guide.pdf](url)

**To Reproduce**
I tested the hard disk with 1986 BIOS version of IBM XT. The IBM XT detects correctly 20mb hard disks with DTC or Xebec controller. 
However, the Juko XT machine detects correctly the type 35 hard disk configured with 1023 cylinders, but IBM XT does not.

**Expected behavior**
All XT machines should detect these hard disk because they have to be detected by HD controller and not XT machine directly.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version v 2.10
 - Build type: regular

**Additional context**
Here is my config file: 
[Config.zip](https://github.com/86Box/86Box/files/4801563/Config.zip)

**Comment by OBattler** [comment] 2020-06-19 10:10
This is fixed now - it was an emulator bug caused by the emulator using a maximum of 1023 cylinders for MFM, this is now bumped up to 2047.

**Closed** 2020-06-19 10:10 UTC
Labels: bug
