### ISSUE TITLE
heart of darkness wont start on windows 95

### ISSUE THREAD

**Issue by yoshi200216** [86Box/86Box#5056] opened 2024-12-19 16:23 UTC
### Checklist

- [X] I **have searched** the issue tracker and **was unable** to find an [open](../issues?q=is%3Aissue+is%3Aopen) or [closed](../issues?q=is%3Aissue+is%3Aclosed) issue matching what I'm seeing.
- [X] I **have verified** that the issue is happening in the **[latest nightly build](https://ci.86box.net/job/86Box/lastSuccessfulBuild/artifact/)**, or the latest commit, if building from source.

### What happened?

Hello
the game heart of darkness for windows 95 wont start even if i have a directx 6 graphic card, a fast cd driver and 104 mb of ram

### Configuration file

```ini
[General]
emu_build_num = 6353
host_cpu = 13th Gen Intel(R) Core(TM) i5-13400F
mouse_sensitivity = 0.16
uuid = 16400f5e-ab5d-5ba2-b9e2-60047ebf4eeb
vid_renderer = qt_opengl3
vid_resize = 1
video_filter_method = 0
video_gl_vsync = 1
window_remember = 1

[Machine]
cpu_family = pentium_p54c
cpu_multi = 2.5
cpu_speed = 166666666
cpu_use_dynarec = 1
fpu_type = internal
machine = m7shi
mem_size = 106496

[Video]
gfxcard = voodoo3_3k_pci

[Input devices]
mouse_type = ps2

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[3dfx Voodoo3 3000]
bilinear = 0
dithersub = 0
dacfilter = 0
render_threads = 4
recompiler = 0

[Sound]
midi_device = system_midi
sndcard = sb16

[Hard disks]
hdd_01_fn = juandi
hdd_01_ide_channel = 0:0
hdd_01_parameters = 63, 16, 1377, 0, ide
hdd_01_speed = ramdisk

[Floppy and CD-ROM drives]
cdrom_01_ide_channel = 0:1
cdrom_01_image_history_01 = C:/Users/juand/Downloads/Heart_of_Darkness_pc_cd_es/Heart of Darkness.iso
cdrom_01_image_history_02 = C:/Users/juand/Downloads/Microsoft Internet Explorer 4.01 (4.72.2106.8) (1997) (ISO)/Microsoft Internet Explorer 4.01 (4.72.2106.8) (1997) (ISO)/Disk01.iso
cdrom_01_image_history_03 = C:/Users/juand/Downloads/Microsoft Windows 95 OSR2.1 [Spanish] (OEM) (ISO)/SPAW95B_USB.iso
cdrom_01_image_path = C:/Users/juand/Downloads/Heart-of-Darkness_Win_EN_ISO-Version-11-US-Release/Heart of Darkness (USA).iso
cdrom_01_parameters = 1, atapi
cdrom_01_speed = 24
cdrom_01_type = 86BOX_CD-ROM_1.00
fdd_01_image_history_01 = C:/Users/juand/Downloads/Microsoft Windows 95 OSR2 - Boot Disk (Dell OEM) (3.5-1.44mb)/Microsoft Windows 95 OSR2 - Boot Disk (Dell OEM) (3.5-1.44mb)/disk01.img
fdd_01_image_history_02 = C:/Users/juand/Downloads/Microsoft MS-DOS CD-ROM Extensions 1.25 (3.5)/disk01.img
fdd_01_image_history_03 = C:/Users/juand/Downloads/Microsoft MS-DOS 6.22 Plus Enhanced Tools (3.5)/Disk3.img
fdd_01_image_history_04 = C:/Users/juand/Downloads/Microsoft MS-DOS 6.22 Plus Enhanced Tools (3.5)/Disk2.img
fdd_01_type = 35_2hd

[Monitor #1]
window_coordinates = 0, 23, 1920, 940
window_maximized = 1

[Monitor #2]
window_coordinates = 0, 0, 0, 0

[Microsoft Serial Mouse]
port = 0
buttons = 2

[PS/2 Mouse]
buttons = 2
```

### Operating system

Windows 11 Pro 24H2

### 86Box version

v4.3.0 build 6353

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

**Comment by eddmanx** [comment] 2024-12-19 18:33
Not a bug; copy protection.

**Comment by unreal9010** [comment] 2024-12-19 18:43
It works perfectly fine on my end. Since emulation of copy protection technology isn't supported yet, you need to bypass it.

**Comment by yoshi200216** [comment] 2024-12-19 22:42
How can I bypass the securom copy protection

**Comment by unreal9010** [comment] 2024-12-20 06:25
Provided that you own a legal copy of the game (like I do), you are allowed to download and use a compromised exe file that removes the protection, known as "crack". Make sure it's for your version of the game. For now, this is the only way to make this game working under 86 Box.

**Comment by thedax** [comment] 2024-12-20 06:48
You could also try installing Daemon Tools into your guest, enable the protection emulations in its context menu, and then mount the game's disk image as normal in 86Box. Then there's no need for a cracked executable. No need to copy the disk image into the guest and use the virtual drives either. It may not work for every game but it'd save the need to go looking for possibly hard to find cracks when it does work.

**Comment by OBattler** [comment] 2024-12-20 16:12
I'm closing this as NOTABUG then.

**Closed by OBattler** 2024-12-20 16:12 UTC
Labels: bug
