### ISSUE TITLE
[Bug] Toshiba T1200 with MFM controllers.

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#330] opened 2018-10-25 01:11 UTC
Hello!

I found a bug with both MFM disk controllers. 
I created a 20mb hard disk and I have the following issues.

1. The Xebec controller has an "error reading drive c problem".  This problem occurs when I run the Zsoft Paintbrush exe file, when I load pbrush.exe from DOS or when I use the XCOPY utility of Toshiba DOS 3.3.

This also occurs in PCEM here is the the problem I reported in PCEM [https://pcem-emulator.co.uk/phpBB3/viewtopic.php?f=2&t=3051&p=10929&hilit=t1200#p10929]

2. When I try to use the MFM DTC-5150X on 86box, it does not even boots. In PCEM works and the errors of the  Xebec does not happens.

PD: I also know that the original Toshiba T1200 has an non standard MFM controller created by JVC/Ricoh and it functions has never been documented.Here I found some information but it's not enough to emulate it. [https://knm.org.uk/blog/?s=JVC+26+pin](url)

By the way I also ask you if you could add the Sigma color 400 ROM bios to the roms package, to test it.

Thanks for your hard work in this emulator!

**Comment by OBattler** [comment] 2019-09-27 08:54
Is this bug still present? Build #1844 brought MFM improvements ported from VARCem.

**Comment by Fenix770** [comment] 2019-09-27 20:25
I could not test the machine, because the ROM files or path has changed and the MFM controllers does not appear. And I was unable to find these the new path or files.
I will wait for the new rom files.

Thanks in advance!

**Comment by Exemptus** [comment] 2019-09-27 21:03
I just have configured a T1200, on build #1870, DTC-5150X, HD with 615/4/17 geom (20 Mb). Could not reproduce the bug, seems to work. I am using the new ROM paths as well.

Nothing to do with this bug, but I noticed the "Window scale factor" option does not work with the T1200, with any renderer. It works with any other machine I tried though.

**Comment by OBattler** [comment] 2019-10-01 13:23
The latest commit fixes this new bug.

**Comment by OBattler** [comment] 2019-10-01 13:57
Also, new ROM set is up - see link in README.md.

**Comment by Fenix770** [comment] 2019-10-02 02:06
I tested the last commit. The bug problem occurs with any XT machine with IBM PC MFM (Xebec) disk. It does not ocurs with DTC-5150X. The error may appear with Pbrush inside Win 2.0 too.

![20191001_225633](https://user-images.githubusercontent.com/31600563/66012869-37496280-e49f-11e9-982b-a09ad6bc4717.png)

Here is the hdd image
https://drive.google.com/open?id=1PIz79wcVmo6jzYjKiD8ImDCxhirHDQpr

**Comment by OBattler** [comment] 2019-10-20 20:24
Are we even sure the IBM PC MFM controller is supposed to work on a T1200?

**Comment by OBattler** [comment] 2019-10-20 20:37
Also, what mouse type are you using? If it's a bus mouse, it could be why this happen, as you'd then have both it and the hard disk controller on IRQ 5.

**Comment by OBattler** [comment] 2019-10-20 20:37
OK, nevermind, I just reproduced this issue with the serial mouse, so it's not an IRQ conflict.

**Comment by OBattler** [comment] 2019-10-21 01:13
It's an incompatibility between the Toshiba DOS 3.30 and the IBM/Xebec BIOS. Normal MS-DOS 3.30 and Compaq MS-DOS 3.31 do not show the problem.

**Comment by MoochMcGee** [comment] 2020-01-22 15:24
Can we close this issue please? It's long been resolved, I think.

**Closed** 2020-01-22 15:26 UTC
Labels: notabug
