### ISSUE TITLE
Regressions in latest build

### ISSUE THREAD

**Issue by jvernet** [86Box/86Box#470] opened 2019-11-21 09:24 UTC
**Describe the bug**
Some regressions observed in latest build:
- IBM XT with MDA card: first line of text flickering. This doesn't occur previously, but can't say wich version broke the thing. If you change to DirectDraw, the whole screen badly flicker...
- AMSTRAD Mouse again broken (with AMSMOUSE.COM 7.0.4): again, mouse speed is way too fast, mouse cursor jump averywhere on the screen

**Desktop (please complete the following information):**
 - OS: Windows 10 64
 - Version 2.07

**Comment by OBattler** [comment] 2019-11-22 02:14
From what I know, I never fixed 7.04, and I even marked the older issue as needing hardware testing. As for the MDA, I'mg oing to look at it.

**Comment by jvernet** [comment] 2019-11-22 10:01
It was working with 7.04, at one time, at least

**Comment by OBattler** [comment] 2019-11-22 14:22
Not that I know of, I couldn't get it to work with 7.04 even on PCem, let alone 86Box. Always the same symptom - it sees the mouse but it doesn't seem to detect mouse movement.

Also, I can't seem to reproduce MDA bug.

**Comment by jvernet** [comment] 2019-11-24 09:47
The flickering can be seen with slow host (my Core i5 HP Pro Book with integrated Intel video). With my desktop with a fast video card, it didn't happen, except if you use DirectDraw as rendering.

**Comment by dhrdlicka** [comment] 2019-11-24 12:32
I can see the flickering here on my end as well, with Intel HD Graphics 4400.

I believe this might be caused by a driver issue, which wouldn't be surprising at all, considering DDraw has been deprecated for almost 20 years already and tends to be rendered in software, rather than hardware accelerated.

**Comment by daviunic** [comment] 2019-11-24 12:35
I can confirm XT+MDA flicker, for all three renderers.

**Comment by OBattler** [comment] 2019-11-24 16:26
OK, I fixed it now. It was a missing video_wait_for_buffer() in mda_poll().

**Comment by qeeg** [comment] 2020-03-28 18:35
Can we close this issue maybe?

**Comment by OBattler** [comment] 2024-01-14 23:31
Yes, we can.

**Closed by OBattler** 2024-01-14 23:31 UTC
Labels: bug
