### ISSUE TITLE
[Bug] Video 7 1024i

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#472] opened 2019-11-29 00:28 UTC
**Describe the bug**
In Windows 3.0 there is garbage in the screen in all supported resolution with Video 7 device drivers. (I suppose they are compatible with Win 3.0). I'm using a disk with device drivers launched in april, 1992. They support a wide range of Video 7 VGA cards although not all video modes are supported in all cards.

The integrated Video 7 driver included in Windows 3.0 works right. But the 1992 driver for 640x480 256 colors video mode has the same issue as all the 16 color mode. (the garbage and the mouse cursor is a black square)
 
Also a bug related to the mouse cursor existed in 16 colors video modes and in the 720x512 video mode in 256 color in Pcem with the Packard Bell 410A (486) machine with integrated Video 7 VGA, chip, in spite of being a latter chip (HT 216-32) launched in 1992, also in Windows 3.0.

**Screenshots**

![20191129-000304-614](https://user-images.githubusercontent.com/31600563/69836000-5f95d900-1224-11ea-9341-ca9d5a3e2f42.png)

My OS is Win 10 and I using the last version of 86box (2.07).

Here are the HD image and The floppy with the drivers.

The hard disk:

[Win 30 dos 40 type 35.zip](https://github.com/86Box/86Box/files/3903273/Win.30.dos.40.type.35.zip).

The drivers:

[VIDEO 7 WIN 31.zip](https://github.com/86Box/86Box/files/3903275/VIDEO.7.WIN.31.zip).

Thanks!

**Comment by Fenix770** [comment] 2019-11-29 03:03
PD: I forget to mention. I installed the multimedia extension and windows only starts if the Sound Blaster is present and is version 1.0.

**Comment by TC1995** [comment] 2019-12-01 11:36
Well, looks like a banking issue.

**Comment by OBattler** [comment] 2019-12-04 06:25
The Video 7 / HT-2xx emulation needs rewriting. But if you could upload your 86box.cfg and your nvr folder, that would allow us to run your virtual machine.

**Comment by Fenix770** [comment] 2019-12-04 22:22
Hello!

Here is the folder with NVR and the CFG file.
[386 SX Win 3.0 multimedia beta.zip](https://github.com/86Box/86Box/files/3924205/386.SX.Win.3.0.multimedia.beta.zip)

**Comment by Fenix770** [comment] 2021-02-15 15:33
Hello!

I tested the Video 7 after the recent changes. The drivers for win 3.0/3.1 does not work any more. However The Video 7 driver  included in windows 3.0 (640x480 256 colors) still works. This video card hasn't been implemented in PCEM so I cannot make a comparison:
The 86box build I tested is 3.0.0.2083

**Comment by Fenix770** [comment] 2021-02-15 16:08
Sorry!
The Video 7, card Works!, on the DTK PPM-333P. The problem seems to be related to 82335 based machines. The Shuttle 386SX throws "Memory mismatch error" messages even after configuring the memory size in setup.

**Comment by tiseno100** [comment] 2021-02-15 20:45
Memory mismatch errors happen when you change base memory or touch relocation. You need to configure, save and wait for the mismatch error and then save again without touching anything. I can confirm it as legit behaviour from various 286 machines. It'll be nice if somebody has a real board to confirm.

**Comment by Fenix770** [comment] 2021-02-15 21:50
Yes, it's right, but only once when the memory configuration has changed in 86 boxes, not at every boot. Besides the Video 7 driver I use does not work with the 82335 based machines. I tested all configurations with same IDE hard disk and video card.
The other possibility is that the board does not support the memory amount (Example the Toshiba T3100 supports 1,2,3 and 5 MB configurations but not 4mb).

**Comment by tiseno100** [comment] 2021-02-16 12:16
> 
> 
> Yes, it's right, but only once when the memory configuration has changed in 86box, not at every boot. Once configured correctly it should not appear. Besides the Video 7 driver I use does not work with the 82335 based machines. I tested all configurations with same IDE hard disk and video card.
> The other possibility is that the board does not support the memory amount (Example the Toshiba T3100 supports 1,2,3 and 5 MB configurations but not 4mb).

Well tested your setup and I can confirm it failing in both of the 82335 boards. My speculation is the Video Buffer as the 82335 does program it at it's own likings.

**Comment by OBattler** [comment] 2021-07-18 15:56
Closing this because I'm qu ite sure this has long been fixed with all the work TC1995 and I have done on the Video 7 emulation.

**Closed by OBattler** 2021-07-18 15:56 UTC
Labels: bug
