### ISSUE TITLE
[BUG] Games made by CHAMProgramming Corporation

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#372] opened 2019-03-31 00:08 UTC
I'm having issues running any of the eight games made by the defunct company CHAMPProgramming Corportation. CHAMPProgramming was responsible for making CHAMP Asterocks, CHAMP Centiped-em, CHAMP Invaders, CHAMP Galagon, CHAMP Galaxia, CHAMP Kong, CHAMP Ms. Pac-em, CHAMP Pac-em back in 1997.

Upon playing one of the eight games...take CHAMP Centiped-em for example, I type in CENTIPED.BAT to  launch the game this is the output that I receive in this screenshot:
![20190330_140641](https://user-images.githubusercontent.com/32658796/55283040-9cfd3c00-530e-11e9-93a1-b2bf586ee56d.png)

Upon trying to configure the sound card in the Options section under Sound, I use Port: 220H, DMA: 1 and IRQ: 5. When trying to initalise the sound card, I get this message: 
![20190330_140724](https://user-images.githubusercontent.com/32658796/55282977-0c722c00-530d-11e9-908c-fa4fad9f5774.png)

Everything sounds find when until I exit game. I try to enter any external command under DOS, such as running CHKDSK, this error pops up when I use the QEMM expanded manager:
![20190330_140523](https://user-images.githubusercontent.com/32658796/55282985-493e2300-530d-11e9-9274-d1011c186285.png)

Also, I managed to try to do a clean boot from a floppy disk image, when I try to run Centiped-em from a floppy disk image, it fails to detect sound and when after I exit, when I try to enter a DOS commend or perform other commands, the emulated machine will freeze until I hard reset.

I'm using the registered version of CHAMP Centiped-em and you can find any of the games made by the CHAMPProgramming on this website:: http://www.champ-em.com/index.htm

**MACHINE CONFIGURATION:** DataExpert OPTi-495SX (ISA 486) using a 66 MHz 486DX2 processor, 32 MB RAM (maxed out), Tseng ET4000AX card with 1 MB VRAM, 3 1/2" and 5 1/4" floppy drives, IDE CD-ROM, Adaptec 1540B SCSI adapter with 7 SCSI hard disks installed

Please investigate this issue on what could be causing this bug even if I don't have any additional drivers loaded in the CONFIG.SYS.

Thank you! :)

**Comment by ppgrainbow** [comment] 2019-03-31 00:51
I have found that for some odd reason, I can get Sound Blaster 16 detection on the unmodified release of PCem v14 after I boot and run Centiped-em from a floppy disk image.

In this case, something doesn't seem to be right when trying to run CHAMPProgramming games using the SoundBlaster 16 card on 86Box. :\

**Comment by TC1995** [comment] 2019-04-19 12:19
What version of QEMM are you using?

**Comment by ppgrainbow** [comment] 2019-04-19 16:49
TC1995, I'm using QEMM 7.53. I found that I removed the MEM=0 parameter from the QEMM386.SYS driver on line 31 of the CONFIG.SYS file solved most of my problems.

86Box uses IRQ 5 for Sound Blaster 16 emulation and I found that the problem might have been due to a IRQ misconfiguration. Let me test the CHAMP games under the OS/2 DOS prompt to see if it works too.

If it does, I'll post a screenshot. :)

**Comment by ppgrainbow** [comment] 2019-04-19 16:58
The game is working and it even works in a OS/2 DOS window! XD

![20190419_095428](https://user-images.githubusercontent.com/32658796/56434456-80a74c00-6289-11e9-96cd-efd6d81775fa.png)

The game works, but when I run the game in a enlarged windows, it runs slow due to the limitations of the speed of the 486 processor.

Everything is solved now. :)

**Comment by ppgrainbow** [comment] 2019-04-23 19:45
I would like to point out that somehow, the bug is NOT fixed the Jenkins build, just in the 86Box.exe executable found on /support/requests/Kotori.

**Comment by dhrdlicka** [comment] 2019-05-21 08:11
I assume the problem has been caused by the IRQ misconfiguration, in which case I am closing this as _not a bug_.

**Comment by daviunic** [comment] 2019-05-24 16:55
Apparently still an issue, under investigation again.

**Comment by ppgrainbow** [comment] 2019-05-24 17:25
I found that Jenkins Build #1834 was the last version to have working sound when running CHAMP games such as Centiped-em. Jenkin Builds starting with #1835 doesn't work.

And after exiting the game, I get a display corruption:
![20190524_101952](https://user-images.githubusercontent.com/32658796/58345742-eac58a80-7e0d-11e9-84d0-0c31a7fb5a6c.png)

Build 1835 is what broke sound support in any CHAMP games: https://github.com/86Box/86Box/commit/c1f18d9abc9b578cd3bdfa5c8284db375bc438b2

**Comment by SirScotty1** [comment] 2019-06-09 10:19
Champ Games is actually still around.  Just a day or two ago, he released Galaga for the Atari 2600!!  

http://atariage.com/forums/topic/291235-champ-games-galaga-2600/

**Comment by ppgrainbow** [comment] 2019-09-20 18:41
Good news! The games made by CHAMPProgramming work under the latest Jenkins build.

Can anyone close this issue? :D

**Closed** 2019-09-21 17:28 UTC
Labels: bug
