### ISSUE TITLE
FreeDOS FDISK fails

### ISSUE THREAD

**Issue by KedalionDaimon** [86Box/86Box#4818] opened 2024-09-13 13:50 UTC
### What happened?

The FDISK stage of installing FreeDOS fails, the system does not "see" the harddisk. It tells no harddisk has been detected. The specific emulated machine in question is an "Intel i386SX [ALi M1217] Acrosser AR-B1374", running on Ubuntu 22.04 (the 64 bit AppImage). The failure is the same in 4.2.1 and 4.1.1, including when deleting and recreating 86Box' configuration file. Hence, installing FreeDOS with its own FDISK fails. However, Microsoft's FDISK in MS-DOS 6.22 seems to work just fine.
![Screenshot from 2024-09-13 15-49-22](https://github.com/user-attachments/assets/2fe41f2b-10de-4d33-8fd4-49cc1c23a626)

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = Intel(R) Core(TM) i5 CPU       M 580  @ 2.67GHz
emu_build_num = 6130
uuid = 785c191f-1171-5607-8bb8-62effd8c4251
confirm_save = 0
force_43 = 1
confirm_reset = 0

[Machine]
machine = arb1374
cpu_family = i386sx
cpu_speed = 40000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
mem_size = 8192

[Video]
gfxcard = cga

[Input devices]
mouse_type = none

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = none
cassette_mode = load

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_01_image_history_01 = /home/archon/Documents/var/86box/dos622populated.img

[Hard disks]
hdd_01_parameters = 17, 15, 917, 0, ide
hdd_01_fn = fdos386-type45-917-15-17.img
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0
```

### Operating system

FreeDOS 1.3

### CPU

Intel(R) Core(TM) i5 CPU M 580

### 86Box version

v.4.2.1 6130

### Build architecture

Linux - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

Examination of the disk image with a hex editor shows it is indeed not populated and just filled with zeroes.

**Comment by OBattler** [comment] 2024-09-13 15:02
Set the hard disk controller to something other than none.

**Comment by OBattler** [comment] 2024-09-13 23:37
Wait, this is a duplicate of another issue that was closed as NOTABUG - it's a FreeDOS bug - it doesn't see the hard disk on some machines: https://github.com/86Box/86Box/issues/4426 . I'm closing this as NOTABUG then.

**Closed by OBattler** 2024-09-13 23:37 UTC
Labels: bug
