### ISSUE TITLE
[BUG ASUS P/I-P55TVP4] 86Box crashes when I take a screenshot.

### ISSUE THREAD

**Issue by Memwhis** [86Box/86Box#953] opened 2020-07-30 08:12 UTC
**Describe the bug**
When I installing Windows 95, I want to take a screenshot. But there is a bug that crashes 86Box. This happened on Pentium 133 and 32 MB RAM.

**To Reproduce**
1. Run Windows 95 Setup on MS-DOS,
2. When Setup preparing setup wizard, take a screenshot. I think this happens at 96%.
3. And 86Box is not responding.

**Expected behavior**
I don't want 86Box crash because I need to contribute a wiki website called BetaWiki.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/68910239/88898555-bfa0ad00-d201-11ea-9060-645d1ea40deb.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 8 build 8176
 - 86Box version: v2.10 build 2511
 - Build type: regular

**Comment by daviunic** [comment] 2020-07-30 08:32
Please provide your config file as well.

**Comment by Memwhis** [comment] 2020-07-30 08:43
[General]
video_fullscreen_first = 0

[Machine]
machine = p55tvp4
mem_size = 32768
cpu_use_dynarec = 1
time_sync = disabled
cpu = 6
fpu_type = internal

[Video]
gfxcard = cl_gd5434_isa

[Input devices]
mouse_type = ps2

[Other peripherals]
hdc = none

[Floppy and CD-ROM drives]
fdd_01_type = 35_2ed
fdd_02_type = 525_2hd
cdrom_01_parameters = 0, atapi
cdrom_01_ide_channel = 1:0
cdrom_01_host_drive = 200
cdrom_01_image_path = C:\Users\pc\Documents\Windows Series\Windows 95 (codename Chicago)\4.00.440\chicago_440__x86.iso

[Hard disks]
hdd_01_parameters = 63, 16, 8322, 0, ide
hdd_01_fn = C:\Users\pc\Documents\Windows Series\HDD.HD
hdd_01_ide_channel = 0:0

**Comment by daviunic** [comment] 2020-07-30 09:04
You could've mentioned before this is actually build 440 of Windows 95, not the final build...

**Comment by Memwhis** [comment] 2020-07-30 13:01
Also, this bug happens on MS-DOS 5.00.

**Comment by qeeg** [comment] 2020-07-30 13:17
Maybe try running a version of Windows that's *not* a beta as your daily driver? That might be your issue, as screenshots work perfectly fine for me on Windows 10.

**Comment by creopard** [comment] 2020-08-18 08:19
This also just happened here on 2.10 (b2533) with Windows 98 (on another VX chipset), but I'm not able to reproduce it again at the same point during the boot process.

![win98_lockup](https://user-images.githubusercontent.com/14175483/90486898-f5b6ba00-e139-11ea-901e-6493df09f0cc.jpg)

**Comment by daviunic** [comment] 2020-08-19 08:19
@creopard please provide your full config.

**Comment by Winins0** [comment] 2020-08-19 09:15
@Memwhis Why are you using 8176? Maybe that's the problem.

**Comment by creopard** [comment] 2020-08-19 09:21
Please find the config attached (nothing extraordinary though):

```
[Realtek RTL8029AS]
mac = db:53:65

[General]
video_fullscreen_first = 0
confirm_exit = 0

[Machine]
machine = 430vx
cpu = 14
fpu_type = internal
mem_size = 131072
cpu_use_dynarec = 1
time_sync = local

[Video]
gfxcard = virge375_vbe20_pci

[Input devices]
mouse_type = ps2

[Sound]
sndcard = sb16
midi_device = system_midi

[Network]
net_type = slirp
net_card = ne2kpci

[Other peripherals]
hdc = none

[Hard disks]
hdd_01_parameters = 63, 16, 4063, 0, ide
hdd_01_fn = hd_image.img
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = none
cdrom_01_speed = 24
cdrom_01_parameters = 0, atapi
cdrom_01_ide_channel = 0:1
cdrom_01_host_drive = 200
cdrom_01_image_path = C:\Users\mine\Desktop\Windows 98\Windows98SE_bootable_unattended.iso
```

**Comment by Steve42424** [comment] 2020-09-15 18:16
It happened to me either with every machine. I'm using v2.10 build 2548 on Windows 10. This screenshot feature is unstable.

**Comment by dhrdlicka** [comment] 2021-05-06 01:26
Does this issue still happen on the latest builds?

**Comment by OBattler** [comment] 2021-07-16 04:51
Closing this since I got a report that it no longer happens.

**Closed by OBattler** 2021-07-16 04:51 UTC
Labels: bug
