### ISSUE TITLE
Adding files to a hard drive .img screws up the boot sector

### ISSUE THREAD

**Issue by dfgdgdgfd** [86Box/86Box#263] opened 2018-02-13 13:47 UTC
I have to use .img and not vhd for my purposes, what am I meant to use to do it?  Been using winimage.  Also do any of the 486 boards support large hard drives (over 500mb)?

**Comment by OBattler** [comment] 2018-02-14 11:44
I can not reproduce this on my end. Did you partition and format the image properly (using FDISK.EXE and then FORMAT.COM)? Also, on 486 machines and onwards, make sure to set HDD Controller to None because selecting "PC/AT IDE" adds a second copy of the IDE controller's I/O handlers which yes, will cause such corruption (I really need to look into that).
Also, the Rise Computer R418, which is a 486 PCI machine with the SiS 496/497 chipset, supports hard drives up to 8 GB.

**Comment by MoochMcGee** [comment] 2018-02-14 22:57
@OBattler What about the internal controller option?

**Comment by OBattler** [comment] 2018-03-20 19:12
This should be fixed since I changed a bit how IDE initializes last month (after this was reported), to prevent such mishaps from happening again.

**Closed by OBattler** 2018-03-20 19:12 UTC
