### ISSUE TITLE
Amstrad MegaPC is unable to boot

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1965] opened 2021-12-25 23:15 UTC
**Describe the bug**
The Amstrad MegaPC is unable to boot. I has to issues

1. The internal graphics chip show only a black screen (no text) at startup.
2. If an external video card is used works, but then when I try to type F2 to enter setup as the machine asks at the first time the keyboard does not respond.

**Desktop (please complete the following information):**
 - OS:  Windows 10 21H1
 - 86Box version: 3.1.0.3402
 - Build information: old dynarec, Win32

**Additional context**
I found the original software for this machine including Amstrad DOS 5.0 with a SETUP.EXE utility and the Quadtel EMS hardware driver. I know the emulation of this machine is not complete yet.

**Comment by Fenix770** [comment] 2021-12-26 12:38
I also found the same bug on a VLSI 386SX machine

![Keyboard problem](https://user-images.githubusercontent.com/31600563/147408281-bc6c8694-7620-4164-b4d0-50ad875fb5e6.png)

**Comment by jbarea** [comment] 2022-05-01 17:31
I'm getting the same problem when trying to boot amstrad megapc. Using internal video only gets a black screen, and trying to use any other card gets stuck on the card boot and nothing happens. On pcem15 with inbuilt video works ok.

**Comment by thecheese2022** [comment] 2022-07-19 04:02
there are issues in amstrad megapc
internal graphics not working blackscreen
sounds 1 long and 2 short beeps  in internal graphics

I had to corrupt nvr file because bios password and access bios setup and then config
![Monitor_1_20220718-022400-112112](https://user-images.githubusercontent.com/102922015/179660436-b84593a1-03c6-4978-a0cd-08987ea66b6e.png)
if you change to video in ram in BIOS Shadow

in external video card
bios freeze or crash when pressing the f1 and f2 graphics glitch or black screen
![Monitor_1_20220718-223944-737737](https://user-images.githubusercontent.com/102922015/179659690-e56826d1-0824-4516-a450-04e68d626fc9.png)
![Monitor_1_20220718-224015-814814](https://user-images.githubusercontent.com/102922015/179659743-0ae0edcf-4cea-4f4c-9521-f6c88c557438.png)


boot stuck
![Monitor_1_20220718-224408-175175](https://user-images.githubusercontent.com/102922015/179660020-14926307-e166-4194-8593-dfe03db40370.png)


ram size support 15232kb 16mb
![Monitor_1_20220718-224536-271271](https://user-images.githubusercontent.com/102922015/179660155-02901347-c6fe-410d-b8d0-84725a4e62d2.png)
hdd cfg and nvr
please note that ms-dos 5.0 italian is installed
[megapc ms-dos 5.0 italian.zip](https://github.com/86Box/86Box/files/9137328/megapc.ms-dos.5.0.italian.zip)

**Comment by OBattler** [comment] 2022-07-26 20:46
OK, I can confirm the keyboard is getting stuck. I need to see why.

**Comment by OBattler** [comment] 2023-01-26 04:34
Closing this as this is a part of the wider issue: https://github.com/86Box/86Box/issues/238 .

**Closed by OBattler** 2023-01-26 04:34 UTC
Labels: bug
