### ISSUE TITLE
Complete keyboard failure after inserting floppy disk into Drive A: (1.44M 1.35in)

### ISSUE THREAD

**Issue by aubymori** [86Box/86Box#1199] opened 2020-12-30 19:18 UTC
Hi! I'm running the current latest build of 86Box from ci.86box.net as I'm typing this. After inserting a floppy disk into VM, the keyboard stops working. I've tried disabling IME, different disks, and even a new VM, and nothing works.

**Config:**
https://pastebin.com/2u0hBxMH

**Disk image:**
https://www.mediafire.com/file/0kwqxopn1631gpd/Win311.img/file

**MS-DOS 6.22 Setup Disks (disks I used):**
https://www.mediafire.com/file/i3ocuwilqqi4fxs/MS-DOS_6.22.zip/file

**Device specifications:**

Device name: ASUS-LAPTOP
Processor: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz   2.40 GHz
Installed RAM: 8.00 GB (7.85 GB usable)
Device ID	4F32BE58-1609-4E90-8A14-76A86E9961A8
Product ID: 00330-80000-00000-AA296
System type: 64-bit operating system, x64-based processor
Pen and touch: No pen or touch input is available for this display

**Windows specifications:**

Edition: Windows 10 Pro
Version: 20H2
Installed on: December 13, 2020
OS build: 19042.685
Experience: Windows Feature Experience Pack 120.2212.551.0

**Comment by OBattler** [comment] 2022-10-29 01:43
Closing this as a duplicate of #481.

**Closed by OBattler** 2022-10-29 01:43 UTC
Labels: bug
