### ISSUE TITLE
Running the game MasterType: Training Ground crashes the emulator

### ISSUE THREAD

**Issue by Exemptus** [86Box/86Box#425] opened 2019-10-02 10:58 UTC
The game boots from a 320k floppy, the image can be found here:
https://winworldpc.com/download/1a39c29d-1a45-c29d-11c3-a4c28d587054 
On boot, it auto-executes MTTG.EXE, then immediately 86box crashes to desktop. This was tested on an IBM PC, CGA, floppies only.

**Comment by OBattler** [comment] 2019-10-02 22:58
That is fixed now, though I incorrectly wrote the game's name as Write Master in the commit description, sorry about that.

Basically, the problem is that there's a lot of function calls done in very quick succession and that was sending the stack haywrite. I made the floppy drive poll operate in blocks of 32 operations at once at 32 times the time period to reduce function calls at once. That fixed it.

**Closed by OBattler** 2019-10-02 22:58 UTC
