### ISSUE TITLE
Emm386 stops Nightly Build Machine 6237

### ISSUE THREAD

**Issue by Pellzi** [86Box/86Box#4933] opened 2024-11-02 04:36 UTC
### What happened?

When i try in Dos (6, 6.22, Win95, Win 98) to load emm386.exe Driver (configured in config sys), then in the 86Box shown cursor blinks endless. And nothing geoes.

I tryed out the build 6237. And i don´t know, if this happendes in earlier versions.
I tryed different machine configurations (from 195 -1998), with different amount of memory (64-1536) and with add on cards or without. Always the same Result: The x86Bos stops working, when i load the emm386 driver.
 

### Configuration file

```ini
[Matrox Millennium]
memory = 8

[General]
vid_renderer = qt_software
host_cpu = Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
emu_build_num = 6237
uuid = 7a866d01-2454-5b71-9e5a-84c9adcc193c

[Machine]
machine = ficva503p
cpu_family = pentium_p55c
cpu_speed = 200000000
cpu_multi = 3
fpu_type = internal
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
mem_size = 65536

[Video]
gfxcard = millennium

[Input devices]
mouse_type = msserial

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = none
cassette_mode = load

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_01_turbo = 1
fdd_02_type = none
fdd_01_fn = C:/86Box/86Box-Aktuell/Flp/Dos6B.img
```

### Operating system

Windows 10 23H2 x64 German

### CPU

Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz

### 86Box version

86Box 4.2.2 (build 6237)

### Build architecture

Windows - x64 (64-bit)

### Build type

- [X] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

My config.sys File looks like this:

device=A:\himem.sys
device=A:\emm386.exe noems
dos=high,umb
deviceHigh=A:\ansi.sys

But x86Box never reach ansi.sys.

**Comment by OBattler** [comment] 2024-11-02 18:07
Try changing the graphics card to something to something that's to Matrox.

Also, please upload your boot disk so I can attempt to reproduce this.

**Comment by eddmanx** [comment] 2024-11-02 20:00
Why the config is pointing to A: for himem and emm386?
I just installed DOS 6.22 on that config and EMM386 works fine.

P.S. It's not **x**86box; just 86box.

**Comment by Pellzi** [comment] 2024-11-03 03:17
@eddmax: OK. I thought it is X86Box, because this is written in the top line, when i start the program.
![TopLine](https://github.com/user-attachments/assets/cc8a943e-e1d2-494e-854c-6d1af6ba295e)

I tryed out the newest 86Box Nightly Build 6240. There this problem with the emm386 does not exists. Or is different to the original description from me.
The original emm386 from Win 98 Command works now fine.
But the Program emsmagic.exe produce a flickering Underscore, which blinks all over the screen once, before the cursor change his position, and blinks just one more Time, and so on.  And this with various Mainboards with various Graficcards.
[EMSMAGIC.zip](https://github.com/user-attachments/files/17609022/EMSMAGIC.zip)
Makes it really sense, when i upload a floppy disk image, which was produced by original Windows 98, Startdiskette erstellen.
In which the program emm386, emsmagic and mem was added for test purposes?

During my test with the 86Box i have had the following Error:
![86Box-Error](https://github.com/user-attachments/assets/874c6840-942e-4fd1-8e2f-0c3539b4b7ff)
But disapeard, and is not reproducable. The 86box.cfg i used, was this
[86box.zip](https://github.com/user-attachments/files/17609092/86box.zip)

**Comment by OBattler** [comment] 2024-11-03 04:18
Try the binaries with the old recompiler.

**Comment by jriwanek** [comment] 2024-11-03 06:24
> @eddmax: OK. I thought it is X86Box, because this is written in the top line, when i start the program.

If you look at the end of the line, you can see 86box, the name at the start is whatever the machine got called, I imagine it was shared with you/provided to you, or otherwise obtained elsewhere, rather than made by yourself.

**Comment by Pellzi** [comment] 2024-11-03 14:43
And where in the cfg from the machine i can change this X86Box string, at the beginning?
In [General] there is no line to do this. And there is also no other possibility in other Windows, open by 86Box program to do this.

I can change this string only by the 86Box Manager. Or, the Name of the folder in the Windows Explorer, where the 86Box exe is.

**Comment by eddmanx** [comment] 2024-11-03 20:05
It's better to post the entire machine files here (cfg, nvr, hdd). It'd make reproducing the issue much easier.

**Comment by Pellzi** [comment] 2024-11-05 00:06
@eddmax
This means for me, this fault is reproducable. And has nothing to do with the machine configuration.
Thanks for your work with this emamagic.exe . Because i need it. It´s the only ems manager, i found in my history in the internet, which mangange the ems in real mode. All other i tryed out, switch to protected mode.
Normaly i used it on a real machine with emsmagic /HI /B .

**Comment by Pellzi** [comment] 2024-11-05 00:19
@eddmax
Are you able, to check it, if this cracy behaveour of emsmagic in the 86Box, if this "jumping" cursor jumps is randomly on the screen? Because for me, it looks like, this is in this way. But? How? can? this? be?
And when not, from where it tooks the infos, the cursor should jump to the position?
I have never seen such a behaveour of the cursor on a screen.

**Comment by eddmanx** [comment] 2024-11-05 00:23
This is why you should share the machine files, so that the devs can reproduce the exact situation you are having.

**Comment by Pellzi** [comment] 2024-11-05 01:27
OK, Here they are:
[Emm386Test.zip](https://github.com/user-attachments/files/17625606/Emm386Test.zip)
The cfg, nvr from Folder, and 2 Floppy with Dos6 German. Dos6B did not start, but i dont know why?´I sysed it.

For me, it would be much more convenient, when 86Box would copy the used rom also in the working folder.
Or ist this up to the 86 Manager i use?

**Comment by eddmanx** [comment] 2024-11-05 01:31
Where's the hdd? Are you not booting from hdd?

**Comment by Pellzi** [comment] 2024-11-05 06:47
No, there is no HDD for this emm386 test.
This should make no different.

Probably it would help, to find the right rom, when the Name of the Rom is written in the List, 86Box use.
![RomPath+Name](https://github.com/user-attachments/assets/dee21ba5-8db9-434a-a1b0-e3a8bfc03c12)
This is a Idea, and has nothing to do with the original problem. But solves the Problem, whitch Rom 86Box is using?

**Comment by OBattler** [comment] 2024-12-01 18:45
You look in roms/machines/ym430tx and see which file(s) are there - in this case, YM430TX.003 .

**Comment by OBattler** [comment] 2024-12-01 18:52
On my end, EMSMAGIC reboots the emulated machine, which indicates a triple fault reset.

**Comment by OBattler** [comment] 2024-12-01 19:04
I'm going to close this as CANTFIX, as EMSMAGIC seems to be compressed with who knows what so I can't even debug it properly.

**Closed by OBattler** 2024-12-01 19:04 UTC
Labels: bug

**Comment by eddmax** [comment] 2024-12-03 09:58
folks you are quoting wrong guy above!! 
you supposed to quote " @eddmanx " not me!
