### ISSUE TITLE
VMware Workstation Linux Guest mouse problem

### ISSUE THREAD

**Issue by Slo2018** [86Box/86Box#3027] opened 2023-01-13 04:19 UTC
Mouse not working in Linux Guest (Linux Mint, Ubuntu) in VMware Workstation.

**Comment by Flo9696** [comment] 2023-01-14 06:33
You better ask the question at VMware forums, as this is for 86Box.

You find VMware Workstation forum at:
https://communities.vmware.com/t5/VMware-Workstation/ct-p/3019-home

**Comment by OBattler** [comment] 2023-01-15 11:13
I think the problem is when running 86Box on a Lixu guest under VMWare Workstation.

It also occurs under VirtualBox, so I'm closing this as a duplicate: https://github.com/86Box/86Box/issues/2856 .

**Closed by OBattler** 2023-01-15 11:13 UTC
Labels: bug
