### ISSUE TITLE
OS/2 4.0 Installer Crashes the Emulator

### ISSUE THREAD

**Issue by Xuser641** [86Box/86Box#2925] opened 2022-12-01 15:09 UTC
**Describe the bug**
A few times during the install of OS/2 4.0 the entire emulator would crash occasionally and out of nowhere. Restarting the emulator (and therefore the install process) would sometimes allow me to get past the part that crashed but I never got to the end of the installer (tried 3 times).

**To Reproduce**
1. Setup a emulated machine (I was using a Gigabyte GA-586IP, 100MHz Pentium, 16MB RAM, S3 Trio64, Microsoft Serial Mouse, Soundblaster 16, an IDE hard disk & and atapi cd-rom.)
2. Try to install OS/2 4.0
3. See emulator crash

**Expected behavior**
OS/2 installs normally without crashing the emulator.

**Desktop (please complete the following information):**
Windows 10 64 bit
86box 3.7.1 build 4032
86Box 64 bit

**Additional context**
Just noticed you have a new version out but it does not seem to mention this as one of it's bug fixes so I am going to post this anyway.

**Comment by TC1995** [comment] 2022-12-02 11:43
Try the 32-bit binary of 86box.

**Comment by pgalbraith** [comment] 2023-01-04 04:17
I recently did a warp 4 install in 86box.  OS/2 (or perhaps 86Box, I don't know) seems very sensitive to hardware selection, I used a i430HX Pentium/200 system with no network card (I never could find one that worked) and SB16 (not pnp) audio and that worked.

**Comment by OBattler** [comment] 2023-01-15 11:09
I recommend trying on the latet 86Box to see if the issue is still there.

**Comment by fmillion-mnsu** [comment] 2023-02-27 20:51
32-bit binary seems overall more stable in all cases. I have had other random crashes on the 64-bit binary (the OS/2 one posted by OP is easily reproducible, but I've also had random quits while in Win95 etc), but have had no crashes at all so far on the 32-bit build.

I don't know what this means for Linux or macOS users, but on Windows it seems sticking with 32-bit is the way to go for now.

**Comment by OBattler** [comment] 2023-06-20 20:36
Does the crash still happen on the latest 86Box build?

**Comment by OBattler** [comment] 2023-07-15 21:06
Going to close this until feedback is provided.

**Closed by OBattler** 2023-07-15 21:06 UTC
Labels: bug

**Comment by Xuser641** [comment] 2023-07-27 12:51
Sorry, I keep meaning to get around to trying this out but life keeps getting in the way.
