### ISSUE TITLE
The emulated machine randomly freezes

### ISSUE THREAD

**Issue by eddmanx** [86Box/86Box#5063] opened 2024-12-22 03:01 UTC
### Checklist

- [X] I **have searched** the issue tracker and **was unable** to find an [open](../issues?q=is%3Aissue+is%3Aopen) or [closed](../issues?q=is%3Aissue+is%3Aclosed) issue matching what I'm seeing.
- [X] I **have verified** that the issue is happening in the **[latest nightly build](https://ci.86box.net/job/86Box/lastSuccessfulBuild/artifact/)**, or the latest commit, if building from source.

### What happened?

The machine freezes sometime after booting into windows 98; it might happen a short while after, or take 10-20 minutes. It's not clear what triggers it exactly. Sometimes it ends up in a BSOD. It happens with a fresh installation of Windows 98 SE on a fresh HDD file.

![Screenshot_2024-12-21_203036](https://github.com/user-attachments/assets/6d0274d9-1eaf-458c-9977-403e2646f942)

Because of the nature of the issue, it's not easy to determine at which build the freezing started. It seems to be somewhere in the 6059-6067 range.

(EDIT: to narrow it down a bit:

```
6059	86box CTDs immediately
6060	Graphical glitches, freezes
6061	Freezes
6062	Very slow boot and eventually "disk boot failure"
6063	Freezes
```
So it apparently started somewhere in that range.)

Machine files: https://drive.google.com/file/d/1i9a-rrEFlhC-YKWQI31Hs0mF_hn4mafQ/view

To test, just spend a few minutes browsing folders, scrolling through them and play a bit of minesweeper and solitaire, etc.

### Configuration file

```ini
[PS/2 Mouse]
buttons = 4

[General]
emu_build_num = 6058
host_cpu = AMD Ryzen 7 5700X 8-Core Processor             
rctrl_is_lalt = 1
uuid = df1aa5ec-5185-58d7-a9ff-fa7ca3dad34a
vid_renderer = qt_opengl3
vid_resize = 2
window_fixed_res = 1024x768
window_remember = 1

[Machine]
cpu_family = idx4
cpu_multi = 3
cpu_speed = 100000000
cpu_use_dynarec = 1
fpu_type = internal
machine = 4saw2
fpu_softfloat = 0
time_sync = local
mem_size = 32768

[Video]
gfxcard = stealth3d_2000pro_pci

[Input devices]
mouse_type = ps2

[Sound]
midi_device = system_midi
mpu401_standalone = 1
sndcard = sb16
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Hard disks]
hdd_01_fn = win98-486.vhd
hdd_01_parameters = 63, 16, 14830, 0, ide
hdd_01_speed = ramdisk
hdd_01_vhd_blocksize = 4096
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
cdrom_01_ide_channel = 1:0
cdrom_01_parameters = 1, atapi
cdrom_01_speed = 52
fdd_01_type = 35_2ed
fdd_02_type = none
cdrom_01_type = 86BOX_CD-ROM_1.00

[ATI Mach32 (VLB)]
memory = 4096

[ATI Mach32 (PCI)]
ramdac = 0
memory = 4096

[ATI Mach32 (ISA)]
memory = 4096

[Monitor #1]
window_coordinates = 446, 141, 1024, 768

[Monitor #2]
window_coordinates = 0, 0, 0, 0

[Sound Blaster 16 #1]
base = 0220
base401 = 0000
irq = 5
dma = 1
dma16 = 5
opl = 1
control_pc_speaker = 0
receive_input = 1
receive_input401 = 0

[Roland MPU-IPC-T]
base = 0330
irq = 7
receive_input = 1

[System MIDI]
midi = 2

[Sound Blaster 16]
base = 0220
base401 = 0000
irq = 5
dma = 1
dma16 = 5
opl = 1
control_pc_speaker = 0
receive_input = 1
receive_input401 = 0

[Microsoft Serial Mouse]
port = 0
buttons = 4

[Standard PS/2 Mouse]
buttons = 4

[Storage controllers]
hdc = internal
```

### Operating system

Windows 10 22H2 64-bit

### 86Box version

6130-6364

### Build architecture

Windows - x64 (64-bit)

### Build type

- [X] New recompiler
- [ ] Debug build

### Additional context

Tested with Matrox Millenium and Mach64VT2 and it seems the problem doesn't happen.

**Comment by OBattler** [comment] 2024-12-26 09:40
Closing this as a duplicate of this previous issue (which is being re-opened instead): https://github.com/86Box/86Box/issues/4918 .

**Closed by OBattler** 2024-12-26 09:40 UTC
Labels: bug
