### ISSUE TITLE
Certain machines fail

### ISSUE THREAD

**Issue by ghost** [86Box/86Box#558] opened 2020-01-18 00:36 UTC
On the latest builds of 86Box (at least in the January 17th builds), the following systems fail:
 - **Xi8088** fails to run at all under any circumstances and just displays a blank screen
 - **Amstrad PC1512** fails with with blank screen and with the internal display adapter, with noticeable screen corruption in the center of the screen
 - The **IBM PS/2 Model 55SX** is able to use a 386SX CPU at any speed and a Cyrix 486SLC CPU at 33 MHz or less but fails with a 103 error when running with faster Cyrix CPUs and with a 103 or 108 error with any of the IBM 486SLC CPUs even at 33 MHz. Specifically, the error code 103 corresponds to a _"System board timer interrupt failure"_ and 108 likewise corresponds to a _"System board timer bus test failure"_. I understand that 86Box recently made some changes to the interrupt code, which might be worth investigating, though I'm not sure whether that had anything to do with it since I haven't compared this behavior with earlier builds.

Also, the emulator occasionally crashes when switching between machines, and that's an issue that should also be fixed or at the very least investaged into.

**Comment by OBattler** [comment] 2020-01-18 04:14
Xi8088 I confirm the probkem, will be solved soon (will also require a ROM set update).
The Amstrad PC1512 works fine on my end, make sure you're using the ROM's from our ROM set.
And those IBM PS/2's seem to simply dislike emulated CPU's faster than 33 MHz, has always been so.

And I'm aware of the crash, have so far not been able to reproduce it under GDB, so I have no idea what causes it.

**Comment by OBattler** [comment] 2020-01-18 23:27
I committed the Xi8088 and updated the ROM set. Now both variants of its BIOS should work.

**Comment by OBattler** [comment] 2020-06-17 12:03
Since I believe the IBM PS/2 issues with those CPU's have been rectified, this can be closed.

**Closed by OBattler** 2020-06-17 12:03 UTC
Labels: bug
