### ISSUE TITLE
386BSD 1.44 image hangs on 86box, boots on virtualbox

### ISSUE THREAD

**Issue by randomliegh** [86Box/86Box#530] opened 2020-01-10 21:06 UTC
**Describe the bug**
I have an old ISO of 386BSD which has gzipped boot images on it. 
I gunzipped them and the rawrite utility in an FreeDOS 86Box instance and wrote dist.fs (the install image) to a floppy disk image made by 86box. 

In 86box, when I reboot, the computer hangs. I have tried with several 486 and pentium configurations and all of them hang without booting from the floppy. 

When I use the same image in Virtualbox, it boots successfully and I'm able to run the installer (which crashes for other reasons). 
 
This is using 86Box 2.10, b9ececc3 build 2029 (optimized for Skylake)
Virtualbox 6.1
Windows 10 home edition 1903/64 bit

I've included a zip file that contains the 86manager folder (with cfg and nvr folder) of the 86box machine and two floppy images
1)144-for-86Box-386BSD-dist.flp -which is the bootable floppy image
2)bsd-items.flp -which contains a copy of dist.fs and rawrite.exe
[386BSD_items-for-86Box.zip](https://github.com/86Box/86Box/files/4047947/386BSD_items-for-86Box.zip)

**Comment by OBattler** [comment] 2020-01-22 15:33
I confirm the hang, though I have no idea what causes it.

**Comment by randomliegh** [comment] 2020-01-22 21:33
Thanks for having a look. 

I'm trying to get as much around 4.4BSD working as I'm able to. 

- FreeBSD 1.0 (pre 4.4BSD) boots and installs. 
- FreeBSD 2.0 doesn't seem to.
- NetBSD 0.8 hangs the same way that 386BSD does (I'm guessing for the same reasons)
- NetBSD 1.0 (merged 4.4BSD) boots and completes the installation program (but can't seem to read the SCSI cd; which isn't an 86Box bug). 
 

My sources:
- FreeBSD 1.0: http://ftp-archive.freebsd.org/pub/FreeBSD-Archive/old-releases/i386/ISO-IMAGES/FreeBSD-1.0-RELEASE/  
- FreeBSD 2.0: http://ftp-archive.freebsd.org/pub/FreeBSD-Archive/old-releases/i386/ISO-IMAGES/2.0.5/
- NetBSD 1.0: http://ftp.netbsd.org/pub/NetBSD-archive/NetBSD-1.0/i386/

I'm not sure where I got 0.8 from -probably from virtuallyfun.com

For the sake of comparison, I'm uploading a new NetBSD 1.0 partial install. Partial because I haven't worked out getting the sets onto it yet. But it's enough to show that NetBSD 1.0 can boot and get to a prompt. 

It includes the three floppies needed to reinstall and a 128mb disk image (using defaults: 1023cyl, 15 hd, 17 sect) ready to be booted from.

[NetBSD 1.0-86BoxVM.zip](https://github.com/86Box/86Box/files/4100048/NetBSD.1.0-86BoxVM.zip)

**Comment by MoochMcGee** [comment] 2020-01-22 22:02
NetBSD 1.6.2 uses floppy images that are meant to be 1440 kb but are smaller than that... I can't use the 2880 kb floppy image, because it triple faults 86box for some reason

**Comment by randomliegh** [comment] 2020-01-23 01:50
@MoochMcGee that's why I included disk images in the zip file. I created those images with 86Box (as 1.44) and then wrote the 1.2mb NetBSD files to disk from inside FreeBSD. 

Just using the .fs files won't work for the reason you said -I don't think they'd work even if you set the floppy to 1.2 (haven't tried, though.)

I don't know what 2880 kb you're referring to. This is a picture of what's included in the zipfile; the only disks are the 1.44 images I created and the 128mb hd image.
![zipfile-contents-22Jan2019](https://user-images.githubusercontent.com/33534838/72950241-329f0780-3d37-11ea-9f5d-b878c68ef421.PNG)

**Comment by OBattler** [comment] 2020-06-17 10:41
So 386BSD was hanging because the poll mode of the PIC was not implemented. That is now fixed. However now, 386BSD tripe faults due to a GPF caused by it trying to jump to a CS:EIP whose CS selector is above GDT limit. I'm trying to understand why now.

**Comment by OBattler** [comment] 2020-06-17 11:32
So, I have looked at the 386BSD source code, and it turns out it does a *LOT* of stuff using the cache, and the cache is not implemented at all in 86Box currently. So this will have to be marked as "Future version".

**Comment by lgj1107** [comment] 2024-02-16 09:29
I found something:

[fd.c](https://github.com/386bsd/386bsd/blob/8d3b58e47e69f13085cfc0e19c09312ade27e7c5/arch/i386/stand/fd.c#L197)


When printing FS_STATUS, it can be found that the result of 86box READ DATA command is abnormal. and the data transmitted to bounce is incomplete。

My English is not good enough, sorry.

This is a physical machine：
![1D224E7997B8E350FF55EC3805B34E05](https://github.com/86Box/86Box/assets/3366897/ab4c50f7-47b7-4c6b-8978-5f4f1347cf13)

This is a 86box （5481）：
<img width="639" alt="13B7845F915ABDBF7A9E88A0D85F3CA5" src="https://github.com/86Box/86Box/assets/3366897/5ed6fb70-f9d3-4038-9bd4-d8cf305cebd9">

**Comment by OBattler** [comment] 2024-02-18 11:43
Looks like it might be timing out.

**Comment by lgj1107** [comment] 2024-02-20 08:39
Testing the floppy drive with HDCOPY, it is completely malfunctioning

<img width="919" alt="fa861012b04b1c505a59db6ba3d52eb0" src="https://github.com/86Box/86Box/assets/3366897/a7c0e49b-c27e-41dd-83ee-99cead7c471c">

test file：
[image.zip](https://github.com/86Box/86Box/files/14341572/image.zip)

**Comment by OBattler** [comment] 2024-02-25 05:17
So, I did some FDC logging when attempting to boot 386BSD and indeed, the very last command causes 386BSD to prematurely assume it has finished.

**Comment by OBattler** [comment] 2024-02-25 06:42
It appears to actually work if I don't set the RQM bit of the MSR register until the result phase if in DMA mode:
![imagem](https://github.com/86Box/86Box/assets/10365853/f6397ce7-aad7-4c74-b8b8-d1e734ef5bb5)
I need to verify the behavior, though.

**Comment by OBattler** [comment] 2024-02-25 07:14
It appears the behavior is indeed correct.

**Closed** 2024-02-25 07:13 UTC
Labels: bug
