### ISSUE TITLE
Screenshot format

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#696] opened 2020-04-15 06:39 UTC
**Is your feature request related to a problem? Please describe.**
Screenshots in 86Box are always saved in 720x400, regardless of window resolution and full-screen mode. While in PCem screenshots will be saved correctly (in resolutions depending on the resolution of the window and full-screen mode). Please fix this and add the ability to choose a screenshot format (PNG, TIFF, BMP, JPG)

**Comment by TC1995** [comment] 2020-04-15 15:43
We already save in PNG format.

**Comment by dhrdlicka** [comment] 2020-04-15 16:51
The screenshot resolution is by design -- if the guest VM runs at 720x400 resolution, you will get a 720x400 screenshot no matter what. This behavior is shared with several other virtualization programs, which makes it more consistent, and also makes more sense for post-processing.

Support for more output formats could be added, however, PNG is a pretty universally supported format, and works just fine for our purposes. Furthemore, at a time when every operating system comes with an image editor capable of converting between your suggested formats, I don't think that this is a really necessary feature, so this is pretty low in our backlog.

**Comment by OBattler** [comment] 2020-04-18 22:17
> While in PCem screenshots will be saved correctly (in resolutions depending on the resolution of the window and full-screen mode).
Yes, this was also the case with 86Box, but the problem with that is, it would require getting the render texture from SDL, which would in turn require a rewrite of SDL to an entirely different rendering mode (which incidentally, would also allow OpenGL renderers on Windows). So that will have to wait for v2.20 or so.

As for other formats - PNG is lossless, so it would be trivial to convert it to anything else with another program.

**Comment by OBattler** [comment] 2020-06-17 11:46
I think this once can be closed as well now.

**Closed by OBattler** 2020-06-17 11:46 UTC
Labels: feature request
