### ISSUE TITLE
The Same STOP-Bug Found In Four Played Games within 86Box

### ISSUE THREAD

**Issue by Mast3rBlast3r** [86Box/86Box#1936] opened 2021-12-15 10:50 UTC
**Describe the bug**

I played some games, and the same thing happened very fast, in the first couple of minutes of playing.. if you going forward, you'll lose control and your character will continue to go forward even is taster not pressed, until is blocked with some obstacle, if you do not move.. it's like freezing, if you do rotating with some big robot like in Starseige you'll continue to rotate for 360 degrees all over again, you can't do hard reset, you can't close 86Box, 86Box will become non responsive application and you must force shutdown over Task Manager..

this happened with games Soldier Of Fortune Platinum Edition, Deadly Dozen, Wheel Of Time, Starsiege.. I can't see what is similar between them, because they use different rendering engines and video drivers, Soldier of Fortune uses Default OpenGL, he has 3DFx OpenGL to offer but I can't test this because he always reverted back on Default OpenGL video driver after I said Apply for 3DFx choice, Deadly Dozen has Direct3D only, Wheel Of Time use Glide, Direct3D and Software rendering, Starseige uses Glide and Software.. 

**To Reproduce**

it may be the easiest to find Soldier Of Fortune Platinum Edition and Starseige (abandonware), try to play and to finish first level without crash, games are tested under Windows 95 and Windows 98.. only two of them, Soldier of Fortune and Deadly Dozen I played in PCem 17, on the identical configuration and software installed, I was able to finish first level and to jump on the next without troubles, so that I'm sure this is something specific about 86Box and rewritten code, because it has not been intensively tested..

**Expected behavior**

it is not enough for the emulator to just start the game, it must be stable and allow you to finish it..

**Screenshots**

I have screenshots for all games played, more is on the way..
![86box StopBug_001](https://user-images.githubusercontent.com/95438261/146172993-7df8fc4d-c716-4ffc-ae51-a2f9dbcae74b.png)
![86box StopBug_002](https://user-images.githubusercontent.com/95438261/146173004-6954026e-8956-4282-8a44-fc5263e5f93d.png)
![86box StopBug_003](https://user-images.githubusercontent.com/95438261/146173008-e047e24a-6bf9-484e-93d8-4449a03e8b9b.png)
![86box StopBug_004](https://user-images.githubusercontent.com/95438261/146173014-09255f17-dc4b-4eff-bbd3-15efe0f8b379.png)

**Desktop:**
 - OS: Windows 10
 - 86Box version: v3.00 build x32-b3336
 - Build information: My Standard Asus Machine with Very Standard Configuration

**Additional context**

since I'm new in this and I learning about debugging, someone with more experience should try to intercept these errors and fix them, we still have a lot of games that can be played without problems..

**Comment by OBattler** [comment] 2021-12-15 10:56
I can confirm this, I've had it many times, even i oler games such as Wolfenstein 3D. Sometimes, it looks like the break code for the pressed code is lost (likely to the inaccurate keyboard controller emulation), which causes the key to remain stuck pressed forever. Hopefully, the in-progress keyboard controller (and keyboard) rewrite is going to fix that.

**Comment by tlyakhov** [comment] 2021-12-30 01:59
+1 I get this playing Quake 2 roughly ~5-10 minutes in. (Socket 7, Pentium MMX, Voodoo 2 SLI, Glide, Win98SE)

**Comment by OBattler** [comment] 2022-10-30 01:58
PSA: Closing these keyboard PS/2 issues and mentioning them in the issue opened for the keyboard controller rewrite as that's poised to fix them.

**Closed by OBattler** 2022-10-30 01:58 UTC
Labels: bug
