### ISSUE TITLE
Other brands of IDE CD-ROM drives

### ISSUE THREAD

**Issue by headsetguy37** [86Box/86Box#2383] opened 2022-06-10 19:24 UTC
**Is your feature request related to a problem? Please describe.**
When attempting to set up machines that use standard IDE CD-ROM drives that are not NEC-branded, the drivers provided by those manufacturers will not work with the emulated NEC CD-ROM drive.

Examples:

- Using Acer CPR v1.2 on an Acer V30 system, the MTMCDAI.SYS driver will load for the initial bootup, and it will be able to read from the CD-ROM drive at first; however, when the system partitions the hard drive, reboots, and attempts to extract files from the archives on the CD-ROM, the system throws a "Not ready reading" error.
- Using Sony Vaio restore media on a Sony Vaio system, a similar issue occurs with the Sony CD-ROM driver; it will read the files initially, but when it tries to copy the files, the CD-ROM drive suddenly becomes "not ready".

**Describe the solution you'd like**
I would like to see Sony and Mitsumi's _standard IDE CD-ROM drives_ be emulated.

**Describe alternatives you've considered**
I have been able to complete the restore processes successfully by modifying the boot disks and inserting a generic Oak CD-ROM driver; however, the respective Mitsumi and Sony drivers will not work within the OS, meaning there will be no way to read from the CD-ROM drive after the restore is complete.

**Additional context**
Keep in mind, these are not drives using Sony and Mitsumi's proprietary interfaces, which preceded the ATAPI standard; these are normal, standard, everyday ATAPI/IDE CD-ROM drives, which just so happen to be branded by Sony and Mitsumi, but the drivers will only work with their specific drives. Sadly, I do not have any datasheets or firmware to provide at this time.

**Comment by OBattler** [comment] 2022-06-10 21:38
It sounds to me like this is more a bug somewhere in the CD-ROM code that should be fixed.

**Comment by JimboMumbo** [comment] 2022-06-19 23:18
Me thinks Creative PC-DVD Encore or random DVD IDE Drives would find something helpful. I know I was not fully asked to be implemented in 86box, but sadly there's no datasheet for PC-DVD Encore. It has a manual instead
[creative_dxr3.pdf](https://github.com/86Box/86Box/files/8936575/creative_dxr3.pdf)
.

**Comment by Dizzy611** [comment] 2022-06-19 23:59
Biggest issue with the PC-DVD drives is that most of them are iirc designed to be used with MPEG2 hardware decoder cards, something that's afaik unlikely to ever be implemented in 86box

**Comment by JimboMumbo** [comment] 2022-06-20 00:04
You're right, It should not happen that way. What's next?

**Comment by OBattler** [comment] 2022-10-30 01:10
I would like the two CD-ROM drivers in quetion so I can attempt to reproduce the issues.

**Comment by headsetguy37** [comment] 2022-10-30 01:55
Sure thing!
MTMCDAI.SYS (Mitsumi): https://www.dropbox.com/s/v5inbd8lma9km2x/MTMCDAI.SYS?dl=0
ATAPI_CD.SYS (Sony): https://www.dropbox.com/s/a7limuv8ctn1rke/ATAPI_CD.SYS?dl=0

In case you also want to try reproducing the restore CD issues, here's Acer CPR (use the Acer V30 motherboard, and enter DS.AA600.001 when prompted for an image number): https://archive.org/details/acercprharddriverecoverycdversion1.21995

And here's the Vaio CD (use the Sony Vaio PCV-90 and enter "PCV90" when prompted): https://archive.org/details/sony-recovery-cd-1996

**Comment by OBattler** [comment] 2022-10-30 02:17
Strange... the Sony driver now tells me there are no drives found.

**Comment by OBattler** [comment] 2022-10-30 03:32
The Sony CD-ROM driver is a no go - it appears to expect proprietary behavior that I have no way to figure out.

**Comment by OBattler** [comment] 2022-10-31 01:15
Committed the MTMCDAI.SYS fix - the driver uses the READ CD command to read the data, which was breaking on multi-sector files such as PKUNZIP.EXE on the Acer CPR CD due to not making sure the DRQ does not fall in the middle of a sector.

Since the other issue is a no go, I'm closing this.

**Closed by OBattler** 2022-10-31 01:15 UTC
Labels: feature

**Comment by headsetguy37** [comment] 2022-10-31 03:24
Not to complain, but I noticed that the commit was for SCSI CD-ROM drives; the Mitsumi driver was for an ATAPI drive.

**Comment by headsetguy37** [comment] 2022-10-31 04:05
In build 4198, I am still getting a "Not ready reading drive E" error during Acer CPR setup, whether I check "Earlier drive" or not.
