### ISSUE TITLE
OPENSTEP 4.2 doesn't notice the CD being ejected

### ISSUE THREAD

**Issue by jvernet** [86Box/86Box#504] opened 2019-12-20 20:45 UTC
**Describe the bug**
- bad rendering of some fonts=>sign of wrong FPU emulation (got the same with Previous Emulator,wich is an 68k emulator, needed to correct FPU emulation)
- eject CD do not work (Nextstep do not get the Eject action on the drive)

**To Reproduce**
Machine: 486 PCI Rise Computer
PCI IDE Adapter
PCI BusLogic BT-958D

CD and ZIP drive on SCSI

Installed OpenStep 4.2

**Comment by TC1995** [comment] 2019-12-20 20:46
Well, for the CD, I believe you need to manually eject the CD from the OS itself, that's how I've done so in Nextstep 3.1 and 3.3.

**Comment by jvernet** [comment] 2019-12-20 21:53
Yep, but OpenStep does'nt notice the disk change/disk eject, keep saying "you can eject disk 0". Need to reboot to take it in account.
Note that it works with the ZIP Drive, if you eject a ZIP, it is corectly handled.
You didn't noticed any problems with fonts with NS 3.3 ?
Also, 64 Mb of RAM make NS 4.2 crash -that's not the case on real hardware-

**Comment by TC1995** [comment] 2019-12-20 22:01
for 3.3, no font problems at all, though I've used the s3 964 drivers.

**Comment by jvernet** [comment] 2019-12-21 09:33
Just to show what it look like
![20191220-212845-344](https://user-images.githubusercontent.com/16312616/71306153-41636900-23dd-11ea-8dd7-f22ddcfc0062.png)

**Comment by dhrdlicka** [comment] 2019-12-21 23:48
What is the display adapter?

**Comment by jvernet** [comment] 2019-12-22 08:13
S3 Virge. But it does the same with any adpater.
Interesting: Checkit 3.0 report FAILED NPU tests:
![20191222-081132-099](https://user-images.githubusercontent.com/16312616/71319200-50105580-249b-11ea-8db0-21e3c8fef072.png)

I'm searching for other NPU/FPU tests suites

**Comment by jvernet** [comment] 2019-12-22 08:51
More tests with MCPDIag.exe, an intel tool to test 387/467 accuracy. Well....
![20191222-084308-191](https://user-images.githubusercontent.com/16312616/71319531-d333aa80-249f-11ea-973d-34bb1846a905.png)

[Intel387SX.zip](https://github.com/86Box/86Box/files/3992287/Intel387SX.zip)

**Comment by dhrdlicka** [comment] 2019-12-22 10:52
Spun the FPU flaws into a separate issue. Please report a single bug per issue in the future.

**Comment by OBattler** [comment] 2019-12-27 03:16
So this leaves the CD-ROM problem here. This is where having the OPENSTEP 4.2 source code would help as then we'd know exactly what its driver expects to see on eject.

**Comment by dhrdlicka** [comment] 2019-12-28 14:51
Reproduced on Apple Rhapsody DR2 (version 5.1).

Would the [Darwin 0.1 source code](https://virtuallyfun.com/2017/03/11/sourcecode-darwin-0-1-located/) (corresponds to version 5.3, which is Mac OS X Server 1.0) be of any help?

**Comment by OBattler** [comment] 2020-01-22 04:38
Does the problem occur on that as well?

**Comment by TC1995** [comment] 2020-02-01 21:46
Hmm, drivers for the Virge on OpenStep?

**Comment by TC1995** [comment] 2020-02-02 14:20
Ok, not being an NeXTSTEP/OPENSTEP expert, but I think the eject thing should be first done within the OS itself, which also ejects the cd from the emulator automatically as well.

**Comment by OBattler** [comment] 2020-02-02 16:08
To jvernet, try ejecting the CD using the OS on the latest 86Box, I suspect the problem was accidentally fixed at some point since TC1995 can't reproduce it any longer.

**Comment by OBattler** [comment] 2020-06-17 12:14
I was told by @TC1995 that this bug is no longer reproducible, so I'm closing this.

**Closed by OBattler** 2020-06-17 12:14 UTC
Labels: bug
