### ISSUE TITLE
FTP issues from Windows host to DOS guest

### ISSUE THREAD

**Issue by Yoghoo** [86Box/86Box#4684] opened 2024-08-03 15:41 UTC
### What happened?

I am trying to get FTP working stable but got issues with connection drops and uploads not completing. Seems there is a buffer issue somewhere as it seems to upload the whole file but in the end (when the progress bar of the FTP client is at 100%) it will fail. 

Tried it with Slirp and Npcap (using a wired nic). With active FTP for Slirp and active+passive FTP for Npcap. Also tried 3 different guest network cards (PCI and ISA) and even a completely different machine type. But all have the same problem. Just to rule it out i also tried 3 different host FTP client programs. On the guest I am using the MTCP ftp server. In addition I disabled the firewall but this didn't solve it either.

Small files will work most of the times but larger ones (~100+ Kb) will all fail. The only workaround I found is to limit the FTP speed to 5KiB/s. This is of course extremely slow even for DOS. Initial connection is always working and also browsing will work without problem.

If you need more information let me know.

### Configuration file

```ini
[General]
vid_renderer = qt_opengl
host_cpu = AMD Ryzen 7 5700X 8-Core Processor             
emu_build_num = 6000
uuid = 720e4f50-8b71-5706-98c5-3874af4a1635
scale = 3
vid_resize = 1
window_remember = 1
iconset = winbox
force_43 = 1
confirm_reset = 0

[Machine]
machine = 486sp3c
cpu_family = am5x86
cpu_speed = 160000000
cpu_multi = 4
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
fpu_type = internal
mem_size = 16384

[Video]
gfxcard = cl_gd5434_vlb
video_fullscreen_scale_maximized = 1

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked
sndcard = sb16
midi_device = mt32

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0
net_01_card = ne2kpci
net_01_net_type = slirp
net_02_card = modem
net_02_net_type = slirp

[Ports (COM & LPT)]
serial2_enabled = 0
lpt1_device = postscript

[Storage controllers]
hdc = internal
cassette_mode = load

[Hard disks]
hdd_01_parameters = 63, 16, 4063, 0, ide
hdd_01_fn = C-DRIVE.vhd
hdd_01_speed = ramdisk
hdd_01_vhd_blocksize = 4096
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = none
fdd_01_turbo = 1
cdrom_01_speed = 72
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 1:0
cdrom_01_image_path = Y:/Temp
cdrom_01_type = 86BOX_CD-ROM_1.00

[Monitor #1]
window_coordinates = 0, 23, 2752, 1011
window_maximized = 1

[Monitor #2]
window_coordinates = 0, 0, 0, 0

[Roland MPU-IPC-T]
base = 0330
irq = 2
receive_input = 1

[Sound Blaster 16 #1]
base = 0220
base401 = 0330
irq = 5
dma = 1
dma16 = 5
opl = 1
control_pc_speaker = 0
receive_input = 1
receive_input401 = 1

[System MIDI]
midi = 0

[Standard Hayes-compliant Modem #2]
port = 0
baudrate = 115200
listen_port = 2323
telnet_mode = 0

[Standard PS/2 Mouse]
buttons = 2

[Cirrus Logic GD5434 (VLB)]
memory = 4

[Realtek RTL8029AS #1]
mac = 93:6b:6a
bios = 0

[SLiRP Port Forwarding #1]
0_external = 21
```

### Operating system

Windows 11

### CPU

AMD Ryzen 7 5700X

### 86Box version

4.2

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by cold-brewed** [comment] 2024-08-03 16:17
It's entirely possible that the issue could be a limitation of the dos ftp server, packet drivers, etc. Performing a wireshark packet capture during the transfer may give you some hints.

That said, could you upload the disk and nvr folder somewhere for us to try and reproduce? Along with instructions for starting the ftp server in the guest.

A few questions:
* Have you tried guest -> host FTP (pcap)?
* Have you tried guest -> guest FTP (pcap)?

**Comment by bvrielink** [comment] 2024-08-03 16:48
I just tried guest -> host (Slirp) and that has the same issue. Using Windows 3.11 and Total Commander to FTP to my NAS FTP server. FTP from guest to host is no problem. But FTP from host to guest has this problem. 

I didn't try guest -> guest. Will upload my nvr folder. But my disk is a little troublesome as it contains passwords and personal licensed software. If really needed I need to make a copy and remove things but that will take some time.

[nvr.zip](https://github.com/user-attachments/files/16482278/nvr.zip)

**Comment by cold-brewed** [comment] 2024-08-03 17:25
> FTP from guest to host is no problem

This makes me think that the problem is with the dos ftp server or drivers. I would expect it to be an issue both ways if the problem was with 86box networking.

But I'm a little confused, you also mentioned:
> I just tried guest -> host (Slirp) and that has the same issue

Are you saying guest -> host was not an issue with pcap? Could you clarify?

**Comment by OBattler** [comment] 2024-08-03 17:26
I suspect that the guest FTP server is old and does not behave exactly according to the modern standards expected by modern FTP clients - I have this exact same problem almost constantly with the FileZilla client on the host with almost every FTP server, where large uploads will just stall at 100% until I manually terminate them.

**Comment by OBattler** [comment] 2024-08-03 17:34
So I think this can be closed as NOTABUG.

**Comment by bvrielink** [comment] 2024-08-03 17:34
Problems are the same when using PCAP or Slirp. Tried them both with exactly the same problem. Using Slirp at the moment as that is what I like to use in the future as well.

It has nothing to do with the DOS FTP server. As I tested in Windows 3.11 as well as a client on my guest to my modern NAS FTP server. Same behavior as using my DOS FTP server on my guest to my host FTP client. Also MTCP server for DOS is very popular (in retro circles at least) and current as it is still being developed on. I also use it on around 10 real retro PC's without any issues.

**Comment by bvrielink** [comment] 2024-08-03 17:35
Why is it closed while still answering the questions?

**Comment by cold-brewed** [comment] 2024-08-03 17:54
We'll still need a way to reproduce. If your existing disk has personal information then you'll need to create a new / minimal image that exhibits the same issue.

**Comment by bvrielink** [comment] 2024-08-03 17:57
To make it more clear here is an overview.

Bad (for both Slirp and PCAP):
Upload from host FTP client to DOS guest FTP server
Upload from host FTP server to Windows 3.11 guest FTP client

Good (for both Slirp and PCAP):
Upload from DOS guest FTP server to host with FTP client
Upload from Windows 3.11 guest FTP client to host FTP server

So in summary: FTP from guest to host is ok. But from host to guest is not. It doesn't matter if it's using PCAP or Slirp or if one side is the server or the client.

**Comment by bvrielink** [comment] 2024-08-03 19:45
Here's the image. It will start the FTP server automatically. User/pw is ftp/secret. Port is 21. Config is above.
[DOS.zip](https://github.com/user-attachments/files/16482662/DOS.zip)

**Comment by bvrielink** [comment] 2024-08-04 18:08
Wireshark capture on loopback. This is from Kubuntu 22.04 which has the same issue as on Windows 11 Pro.
[ftp.zip](https://github.com/user-attachments/files/16488515/ftp.zip)

**Comment by Carmina16** [comment] 2024-08-04 22:31
The issue is the guest never receive the FIN packet and the host waits for the confirmation from the guest which obviously never comes.

**Comment by bvrielink** [comment] 2024-08-05 11:37
> The issue is the guest never receive the FIN packet and the host waits for the confirmation from the guest which obviously never comes.

From the info I gathered I think so as well. Seems like a fifo/buffer/dma issue on the 86Box machine. Can't quite figure it out from the sources of 86Box where the problem is unfortunately.

**Comment by OBattler** [comment] 2024-08-06 02:13
I think some controlling for variables is in order here:
1. Is the host network card using which you're talking to your real retro machine the same one using which you're talking to the emulated machine?
2. What happens when you attempt to do similarly large transfers from your host to any online FTP server (try eg. the 86Box FTP whose details you will find pinned in #86box on the Discord server) (I regularly have the identical problem to there)?
3. When using PCap, are you connecting the emulated machine directly to the host network, using NAT, or using bridging?
4. Does the host network use any NAT/router?

**Comment by bvrielink** [comment] 2024-08-06 07:00
Hi OBattler.

1. Yes
2. Tried the 86Box FTP server. Same problem with that as well. FTP is hanging at 99% when downloading a 786kb file.
3. Default PCap settings So I guess bridged. 
4. No

**Comment by bvrielink** [comment] 2024-08-07 13:56
I didn't mention this yet but I got this problem only with FTP. Mapping a drive with a Samba server and copying files from and to it is working correctly.

**Comment by bvrielink** [comment] 2024-08-08 06:58
Tried Dosbox-X which a NE2000 network card and Slirp and there FTP is working correctly. I know it's not the same but this is just to exclude the host network and Slirp as the culprit.

**Comment by OBattler** [comment] 2024-08-08 17:26
> Tried the 86Box FTP server. Same problem with that as well. FTP is hanging at 99% when downloading a 786kb file.
Are you download it to the host or to the guest?

**Comment by OBattler** [comment] 2024-08-08 17:34
Also, try the NE2000 ISA instead of the RTL8029AS PCI and see if there's any difference.

**Comment by OBattler** [comment] 2024-08-08 17:42
I just started the VM and connected to its FTP server using FileZilla FTP Client on port 21, and downloaded a 315 kB file - no problems.

**Comment by bvrielink** [comment] 2024-08-08 17:44
> Also, try the NE2000 ISA instead of the RTL8029AS PCI and see if there's any difference.

Tried it already with 3 PCI and ISA cards (see above). Also the NE2000 which I always try out first. All have the same problem. 

>Are you download it to the host or to the guest?

Download from host to guest. The other way works.

**Comment by OBattler** [comment] 2024-08-08 17:45
I'm doing that now - uploading a 97 MB file to the guest stalled at 3.2% so the bug is confirmed. I suspect there is packet loss.

**Comment by OBattler** [comment] 2024-08-08 17:46
After a long time, it progressed to 5.3%.

**Comment by bvrielink** [comment] 2024-08-08 17:46
Also another observation: the download is pretty slow until it fails (around 30kb/s). Upload is going very fast.

**Comment by OBattler** [comment] 2024-08-08 17:49
Yeah, this makes perfect sense. I think the threading is being a problem - packets going out from 86Box work fine as they don't go through a thread, but incoming packets get lost.

**Comment by bvrielink** [comment] 2024-08-08 17:54
> Yeah, this makes perfect sense. I think the threading is being a problem - packets going out from 86Box work fine as they don't go through a thread, but incoming packets get lost.

Could be the case indeed as Samba is working and is single threaded.  FTP needs 3: thread to listen for incoming connections, a thread to process the control connection and a thread to process the data connection.

**Comment by OBattler** [comment] 2024-08-08 18:30
No, 86Box's network stack is itself threaded.

**Comment by OBattler** [comment] 2024-08-08 21:05
What CPU does your real old machine have?

**Comment by bvrielink** [comment] 2024-08-08 21:20
> What CPU does your real old machine have?

My guest you mean? I tried 286/6, 286/16, 486/66, 486/160 and Pentium II/200. All have the same problem.

**Comment by OBattler** [comment] 2024-08-08 21:34
No, your real, physical retro machine.

**Comment by bvrielink** [comment] 2024-08-08 22:10
> No, your real, physical retro machine.

The hosts I tried it on are a laptop with a Intel Core i7-4710HQ 3.5Ghz CPU running Kubuntu 24.04 and my desktop with a AMD Ryzen 7 5700X 4.2Ghz and Windows 11 Pro. 

If you're talking about my "real" retro pc's (so without 86Box) I got around 15 of them. All generations from XT to Core2Duo.

**Comment by OBattler** [comment] 2024-08-08 22:23
Can you tell me which exact PCI NIC's you tried in 86Box? Because I just found a DP8390 regression that was causing it and now I'm currious is something else has an unrelated bug that's causing the same symptoms.

**Comment by OBattler** [comment] 2024-08-09 03:24
Well, I guess this *can* be closed again, if the same symptom is found with a non-DP8390-using NIC, it can be reopened.

**Comment by cold-brewed** [comment] 2024-08-09 14:30
@bvrielink OBattler has committed a fix for the issue. We verified the fix with the system you provided.

Could you download the latest version from jenkins and retry? You'll need build 6049 or greater.

**Comment by OBattler** [comment] 2024-08-09 14:59
Also, you mention the 3C501 and the DEC21140 but your VM does not include the drivers for both, so I can't test those.

**Comment by bvrielink** [comment] 2024-08-09 15:15
Just tested build 6051. Still failing. 

I uploaded a 286 machine so it does of course not include PCI packet drivers. Can upload all that you need. But please tell me what you need. But for this moment the 286 machine I uploaded should be enough. It's using a NE2000 at the moment and is failing for me with the latest build. 

Like I told before it will fail at around 99%. Looks like the last kilobytes in the received buffers are not written or flushed or something like that. I can upload a huge file which will continue running until 99% or so. But I test mainly with smaller files which exhibit the same behavior. 

How did you test the fix? Can you reproduce it with my machine or not? I tested it on Linux and Windows hosts with different hardware so it would be a mystery for me if it can not be reproduced. If so what can we do so that you can reproduce it?

**Comment by OBattler** [comment] 2024-08-09 15:26
No, you uploaded a 486 machine.

I tested the fix by uploading a file to the VM using the FileZilla FTP client. Before the fix, the upload was crawling, now it works fine. I also just tested the DEC 21140 and the 3c501, both also successful.

**Comment by OBattler** [comment] 2024-08-09 15:29
And if you don't believe me, this is with the 3c501:
![imagem](https://github.com/user-attachments/assets/60df8f2b-6ace-4676-a7ec-92f8ef9d418e)
This was a 97 MB file.

**Comment by OBattler** [comment] 2024-08-09 15:42
Also, you said this:
> Tried the 86Box FTP server. Same problem with that as well. FTP is hanging at 99% when downloading a 786kb file.
Then how can it be an 86Box bug when you're having the exact same problem with a FTP server hosted on a physical machine in Hetzner's datacenter in Germany? Yes, it's the 86Box FTP server, but it's not being run on 86Box.

**Comment by bvrielink** [comment] 2024-08-09 15:43
Ah that's right. I later changed it to a 286 to check if a slower CPU would fix it. 

But I tested the build also on that 486 that you're testing right now. So it seems we can not reproduce it then.

I did all I can think off and tried to deliver all the information which could be needed or asked for. Spent literally many many hours on this problem. And I know this works with real machines in my environment as most of the 86Box machines I made are exact copies of real hardware here. 

Any ideas left?

**Comment by bvrielink** [comment] 2024-08-09 15:45
> Also, you said this:
> 
> > Tried the 86Box FTP server. Same problem with that as well. FTP is hanging at 99% when downloading a 786kb file.
> 
> Then how can it be an 86Box bug when you're having the exact same problem with a FTP server hosted on a physical machine in Hetzner's datacenter in Germany? Yes, it's the 86Box FTP server, but it's not being run on 86Box.

Please read carefully this whole issue. I clearly stated that it depends if the 86Box guest is a FTP server or a FTP client and which way it will fail.

**Comment by OBattler** [comment] 2024-08-09 16:19
The VM you sent me has the guest act as the FTP server. What do I need to do with it to reproduce the bug?

**Comment by OBattler** [comment] 2024-08-09 16:35
Restarted the VM, now I'm trying to download that 97 MB file from it.

**Comment by OBattler** [comment] 2024-08-09 16:37
Download successful.

**Comment by OBattler** [comment] 2024-08-09 16:37
Now if the problem occurs when attempting to the guest as a FTP *client*, then I'm going to need a different VM to test this.

**Comment by bvrielink** [comment] 2024-08-09 16:38
> The VM you sent me has the guest act as the FTP server. What do I need to do with it to reproduce the bug?

If guest is a FTP server then upload a file (700kb or so) from your host to guest. If guest is a FTP client then download from a FTP server. FTP command line client is installed in c:\utils\mtcp. But you need to set some variables and the packet driver. See c:\utils\ftp.bat for an example (minus starting the FTP server of course).

**Comment by OBattler** [comment] 2024-08-09 16:40
I uploaded a 97 MB file to the guest FTP server and showed you the screenshot above. No problems, upload finished successfully.

**Comment by OBattler** [comment] 2024-08-09 16:42
Added my own notes in bold:

> Bad (for both Slirp and PCAP):
> Upload from host FTP client to DOS guest FTP server - **can not reproduce, I uploaded a 97 MB file that way with no problems.**
> Upload from host FTP server to Windows 3.11 guest FTP client - **I have not yet tested that.**

So transfers going from the host to the guests are bad. I tested the first one and it works correctly on my end. Let me test the latter.

**Comment by bvrielink** [comment] 2024-08-09 16:52
Here's some screenshots on my end:

![afbeelding](https://github.com/user-attachments/assets/f7af98ed-72d0-458c-a6c8-d66cad49f5e3)
![afbeelding](https://github.com/user-attachments/assets/0c11526f-0008-495a-90fd-53ddbd749aca)

Then after a couple of minutes it will fail:
![afbeelding](https://github.com/user-attachments/assets/fa34f536-08bd-4811-8cda-37d351c43eaf)

It wrote this on the guest (so missing 10 or 20kb) while the client is at 100% :
![afbeelding](https://github.com/user-attachments/assets/30ec3513-899a-4cb5-85d4-9c93ffad3009)

**Comment by OBattler** [comment] 2024-08-09 16:58
I have just reproduced the issue: 
![imagem](https://github.com/user-attachments/assets/cba19cb9-e8e9-4f25-9c45-5d93a9130c0a)
It stalls here, at 99%, like you said.

**Comment by bvrielink** [comment] 2024-08-09 17:00
Nice! Tried it with Total Commander in Windows 3.11 as well with the same results.

**Comment by OBattler** [comment] 2024-08-09 17:01
![imagem](https://github.com/user-attachments/assets/6a00a650-fee1-4a50-b340-8d97d2956678)
This is on the host with no 86Box involvement, no stall. So it is confirmed to be an 86Box bug.

**Comment by Carmina16** [comment] 2024-08-09 20:36
Still fails, at least with NE2000 in build 6051.

**Comment by OBattler** [comment] 2024-08-10 04:37
Yes, if you look above, I managed to reproduce it myself as well and have been investigating it but I'm not yet quite sure what's wrong, why this is happening.

**Comment by OBattler** [comment] 2024-08-10 15:44
OK so, on my end, this only happens with SLiRP, and not with PCap.

**Comment by bvrielink** [comment] 2024-08-14 20:49
> OK so, on my end, this only happens with SLiRP, and not with PCap.

Tested it again with Npcap and indeed it's working. Don't know why it failed last time. Maybe because it takes a very long time to finish the upload. It stays a long time at 100% before really finishing the upload. But it gets through in the end. Sorry about that. The transfer speeds are really slow for both upload and download btw. It's around 1/3 of the speed of a 10Mbps ISA card.

**Comment by OBattler** [comment] 2024-08-14 20:56
I can't reproduce that for PCap, at all, I have no stalls with it, and I get 1.5 MiB/s speeds with it.

With SLiRP, however, yes, it's slow and stalls a lot. I still have no idea why, but it must be due to how we call SLiRP.

**Comment by OBattler** [comment] 2024-08-14 20:58
For the PCap slowness, see if the firewall on your host may be messing with things.

**Comment by OBattler** [comment] 2024-09-13 23:39
At this point, I'm closing this as a CANTFIX - there's something going on with SLiRP threading, and it's going to be looked at in the future.

**Closed by OBattler** 2024-09-13 23:39 UTC
Labels: bug, cantfix, may be fixed in the future

**Comment by OBattler** [comment] 2025-06-09 06:18
This is now actually fixed.
