### ISSUE TITLE
CD-ROM reading Issues caused by changes in build 6111

### ISSUE THREAD

**Issue by pankoza2-pl** [86Box/86Box#4770] opened 2024-08-29 11:19 UTC
### What happened?

When Booting from CD-ROM (using known good bootable ISOs), the BIOS either: does a loud beep and says "Press a key to reboot" or fails to boot from CD-ROM entirely (This happens with a Windows NT 5.0 CD and a DOS 5.0 boot CD). Also, DOS CD-ROM drivers hang the system or fail detection. On some boards and configuration, I can get into NT 5.0 but booting causes a BSOD INACCESIBLE_BOOT_DEVICE, and my DOS 5.0 Boot CD sometimes fails to find command interpreter after loading CD-ROM driver. 

What did I expect to happen: The system boots from CDs and reads them properly

Below are various error screens I have encountered when working with CD-ROMs:

![Monitor_1_20240829-130249-391](https://github.com/user-attachments/assets/bcbfbe95-16ce-44e8-80f6-3505b5e83e34)
![Monitor_1_20240829-131107-620](https://github.com/user-attachments/assets/b9d21386-2c6c-48e4-bcb7-25aab33cc2d7)
![Monitor_1_20240829-131440-619](https://github.com/user-attachments/assets/6b935793-2ef0-492f-86e0-823f2fe4f107)
![Monitor_1_20240829-131650-815](https://github.com/user-attachments/assets/e4f28468-1beb-44c4-882e-575aef640724)

### Configuration file

```ini
[Sound Blaster 16 #1]
base = 0220
base401 = 0330
irq = 5
dma = 1
dma16 = 5
opl = 1
control_pc_speaker = 0
receive_input = 1
receive_input401 = 0

[General]
vid_renderer = qt_software
host_cpu = AMD FX-8370 Eight-Core Processor               
emu_build_num = 6111
uuid = 341bf5b2-1edc-5330-92d8-acd452c9d571
force_43 = 1

[Machine]
machine = 686bx
cpu_family = pentium2_od
cpu_speed = 66666666
cpu_multi = 1
fpu_type = internal
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = disabled
mem_size = 131072

[Video]
gfxcard = px_trio64_pci

[Input devices]
mouse_type = ps2

[Sound]
sndcard = sb16
midi_device = system_midi
fm_driver = ymfm

[Network]
net_01_card = pcnetpci
net_01_net_type = slirp
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = internal
cassette_mode = load

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = none
cdrom_01_speed = 72
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 0:1
cdrom_01_type = 86BOX_CD-ROM_1.00
cdrom_01_image_history_01 = D:/Disk Images/Microsoft Windows 2000 (''NT 5.0'' 5.0.1671.1) (x86 beta) [Japanese].iso
cdrom_01_image_history_02 = D:/Disk Images/Win2K SP4.iso
cdrom_01_image_history_03 = D:/Disk Images/DOS 5.0.iso
fdd_01_image_history_01 = D:/Disk Images/Boot-1.44M (5).img
cdrom_01_image_history_04 = D:/Disk Images/5.00.1773.1_x86fre_client-workstation_retail_ja-jp-NTWKS50J.iso

[AMD PCnet-PCI II #1]
mac = 35:98:c9
```

### Operating system

Windows 11 x64

### CPU

AMD FX-8370 Eight-Core Processor 4.00GHz

### 86Box version

v4.2.1 build 6111

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by pankoza2-pl** [comment] 2024-08-29 11:24
Actually, that NT 5.0 build seems to just not like 440BX once it gets booted on it, but it should be working on the Asus 440FX Socket 8 board, yet it does not boot on that either with build 6111

**Comment by TC1995** [comment] 2024-08-29 11:31
Make sure you set the hdd and cdrom's properly.

**Comment by pankoza2-pl** [comment] 2024-08-29 11:35
I did, still various weird issues that are fixed by downgrading to build 6110

**Comment by MrPepka** [comment] 2024-08-29 11:37
This is probably the result of a bug I reported and which was fixed in this build - https://github.com/86Box/86Box/issues/4766 Apparently the code regarding CD-ROM support needs to be looked at again

**Comment by pankoza2-pl** [comment] 2024-08-29 11:38
exactly what I was talking

**Comment by OBattler** [comment] 2024-08-29 16:05
I can't reproduce this at all.

**Comment by OBattler** [comment] 2024-08-29 16:08
Wait... your CD-ROM is set to primary slave without a primary master. This isn't going to work, at all.

**Comment by OBattler** [comment] 2024-08-29 16:11
And even then I can't reproduce it.

**Comment by OBattler** [comment] 2024-08-29 16:25
![imagem](https://github.com/user-attachments/assets/86a38567-fc9a-4b70-8853-1c1ad54a604a)

**Comment by pankoza2-pl** [comment] 2024-08-29 16:52
> Wait... your CD-ROM is set to primary slave without a primary master. This isn't going to work, at all.

tried with a HDD too, removed from config temporarily

**Comment by pankoza2-pl** [comment] 2024-08-29 16:58
[86box.txt](https://github.com/user-attachments/files/16802752/86box.txt)
This config is proper, could Install NT5 Beta 1 on 6110, but on 6111 CD-ROM is not bootable

**Comment by eddmanx** [comment] 2024-08-29 17:14
I can reproduce it too, it fails to boot from the CD. Build 6111 32-bit ODR.

**Comment by OBattler** [comment] 2024-08-29 18:47
OK, try on 6112.

**Comment by pankoza2-pl** [comment] 2024-08-29 19:28
Now works when CD is already inserted when the machine is powered up, but you need to restart if you insert the CD while the system is booting (even when inserted on Video BIOS phase) for it to recognize the boot sector on CD
so it's 99% fixed

**Comment by eddmanx** [comment] 2024-08-29 19:50
> you need to restart if you insert the CD while the system is booting (even when inserted on Video BIOS phase) for it to recognize the boot sector on CD

Yea, it doesn't recognize the CD like that. Build 6110 works fine.

**Closed** 2024-08-29 22:57 UTC
Labels: bug
