### ISSUE TITLE
PS/2 Model 70 Ref disk freeze

### ISSUE THREAD

**Issue by ArtiomWin** [86Box/86Box#514] opened 2019-12-28 21:33 UTC
Recent builds of 86box have some issues with PS/2s (tested on Models 70 and 80) - systems are freezing on POST with reference disks inserted.
[IBM PS2 Model 70.zip](https://github.com/86Box/86Box/files/4007488/IBM.PS2.Model.70.zip)
![20191228-213014-006](https://user-images.githubusercontent.com/31134876/71549681-b41ea680-29d2-11ea-899e-fd2d1a7818c2.png)

 - OS: Windows 10
 - Version v2.10 (build 2030)

**Comment by OBattler** [comment] 2019-12-29 12:31
Could you biset to see which build introduces the problem?

**Comment by ArtiomWin** [comment] 2019-12-29 14:02
I can't say, but that problem affects PS/2 version of 3,5' floppy drives - regular 3,5' drive emulation works properly, even on PS/2. I think emulation of specifically 72X6068 is just incomplete.

**Comment by OBattler** [comment] 2019-12-31 21:01
Wait, make sure the floppy drive is set to the non-PS/2 version, because MCA PS/2 FDC's don't do the DENSEL swapping that ISA PS/2 FDC's do.

**Comment by OBattler** [comment] 2020-01-12 18:36
Well, since this was caused by setting the wrong floppy drive types, this can be closed as not a bug.

**Closed by OBattler** 2020-01-12 18:36 UTC
Labels: bug
