### ISSUE TITLE
[i440BX] ASUS P3B-F machine freezes

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#1252] opened 2021-01-26 15:49 UTC
**Describe the bug**
[i440BX] ASUS P3B-F machine freezes when starting with Windows XP already installed or when trying to install ReactOS.

**To Reproduce**
1. Run the ReactOS installation image and the system will freeze at the stage until the system language selection list appears. At the same time, other machines on the i440BX chipset, for example ABIT BF6, work fine (Installing ReactOS runs smoothly and also boots normally with Windows XP).

**Expected behavior**
A system with Windows XP installed should start without freezing when switching from another similar i440BX machine. Also, the ReactOS installation should run without errors and freezes, like on other i440BX machines.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro v1909
 - 86Box v3.00 build 2788
 - Build type: regular or optimized

**Additional context**
It is possible that this bug is somehow related to a bug found earlier on this machine:
https://github.com/86Box/86Box/issues/1091

**Comment by OBattler** [comment] 2021-01-26 21:48
It can't be related to #1091, since the change done there was reverted later as far as the P3B-F and all other AT+ boards are concerned.

**Comment by OBattler** [comment] 2021-03-08 23:03
I can not reproduce this at all on my end, on build 2814. Windows XP starts just fine on the P3B-F.

**Comment by OBattler** [comment] 2021-03-08 23:08
Just tried on build 2788, and no hang on P3B-F there, either.

**Comment by maximus105** [comment] 2021-03-09 06:22
@OBattler Try running the ReactOS install image on this machine. At the stage of choosing a language, this machine hangs up.

**Comment by maximus105** [comment] 2021-03-11 09:43
These freezes on this machine may be due to the incorrect saving of the BIOS (NVR files) and occur if, for example, you change some device in the 86Box, for example, a video card and try to load the operating system. For example, WinXP freezes. 86Box just crashes at the WinXP boot stage. If after that you go into the BIOS and just save the BIOS settings, without changing anything, then there may be no freeze at the boot stage. Also, after the successful installation of ReactOS on this machine, at the stage of the last reboot after installation, 86Box crashes, while the ReactOS boot file in the image of the connected HDD in 86Box is damaged and further loading of the newly installed ReactOS is no longer possible.

**Comment by OBattler** [comment] 2021-03-20 05:44
This sounds like the flash contents are getting corrupted. We're going to investigate this.

**Comment by maximus105** [comment] 2021-03-22 06:04
In earlier builds of 86Box, after successfully installing ReactOS during the last reboot phase, 86Box does not crash and boots fine, but there may be a blue screen in ReactOS. That is, something was improved, and something was degraded, and not only in this machine, but also in other machines. But for sure in some build it was possible to install ReactOS without errors and without 86Box crashes.

**Comment by OBattler** [comment] 2021-04-03 21:27
Does this work in the latest build? I did fix an AT+ PIC bug.

**Comment by maximus105** [comment] 2021-04-04 11:06
Build 2882 also crashes 86Box after installing ReactOS v0.4.15-x86-Dev at the last reboot stage.

![2021-04-04_115153](https://user-images.githubusercontent.com/58270614/113506537-22df9d80-954e-11eb-9e2c-28e332771f18.png)

Tested on [i440BX] ASUS P3B-F, [i440BX] ABIT BF6 and [i440BX] Gigabyte GA-686BX. After 86Box crashes, if you check the IMG image of the connected HDD in the 86Box on which the installation took place with the CHKDSK command, then it will contain lost clusters in the boot files of ReactOS, and therefore it is impossible to download and continue installing ReactOS.

In build 2767, 86Box crashes after the installed ReactOS v0.4.15-x86-Dev at the stage of the last reboot (but the clusters in the connected IMG image are not damaged yet, which allows, despite the 86Box crash, to load ReactOS and continue installing it).

In build 2766 everything works fine without 86Box crashes on [i440BX] ASUS P3B-F after ReactOS v0.4.15-x86-Dev installed at the last reboot stage and subsequent boot, ReactOS installation and reboot without errors and without 86Box crashes.

![2021-04-04_135630](https://user-images.githubusercontent.com/58270614/113506582-5b7f7700-954e-11eb-8135-0d1adaca6b89.png)

**Comment by OBattler** [comment] 2021-04-06 04:23
Yes, I'm aware of the crashes, they are a separate issue that already has another issue open here.

But are at least the freezes gone now?

**Comment by maximus105** [comment] 2021-04-06 07:12
Do you mean WinXP hangs when changing hardware in 86Box? I haven't tested it yet. I checked the ReactOS installation and found out that only in build 2766 the installation works correctly, in 2767 86Box crashes already appear. Perhaps these crashes also apply to WinXP. I also tested Duke Nukem 3D on the [i440BX] ASUS P3B-F, no freezes, no sticky keyboard or no games when playing for 10 minutes.
In addition, a bug was found on [i440BX] ABIT BF6: At the POST stage, memory testing is very slow with distorted visibility of the memory size digits, if you just go into the BIOS and exit with saving the settings. If you delete the NVR files for this board after that, the memory will be tested normally (fast). This was all tested on build 2882.

**Comment by maximus105** [comment] 2021-04-06 16:54
A bug has been found on [i440BX] ASUS P3B-F, which appeared in build 2879. After passing POST before loading MS-DOS v6.22, after a long pause, the message "Non-System disk or disk error" appears, after which MS-DOS v6.22 can still be loaded. Build 2878 does not have this bug and MS-DOS v6.22 boots normally right away.
![2021-04-06_194619](https://user-images.githubusercontent.com/58270614/113748702-7e0dbd80-9711-11eb-94d1-727cebe514c4.png)

**Comment by OBattler** [comment] 2021-04-06 22:41
Is this from a floppy or from the hard disk?

**Comment by OBattler** [comment] 2021-04-06 22:53
OK, it's caused by IDE. Just committed a workaround for that.

**Comment by OBattler** [comment] 2021-04-11 07:50
Do the freezes still happen?

**Comment by maximus105** [comment] 2021-04-12 14:26
In build 2912 everything works fine without crashing 86Box on [i440BX] ASUS P3B-F after installing ReactOS v0.4.15-x86-Dev at the last stage of reboot and then downloading, installing and rebooting ReactOS without errors and without 86Box crashes. But the installed ReactOS hangs when you click Shut Down. If you click "Restart", it does not freeze, it reboots normally and 86Box does not crash. The same is true for WinXP.
But WinXP still hangs: if you click "Shutdown" in WinXP, the 86Box hangs (but the percentage of emulation in the 86Box window changes), but the shutdown does not occur. If after that you press "Hard Reset" in 86Box or just close the 86Box window, then the next time you start the machine with WinXP, 86Box crashes at the stage of loading the WinXP logo. If after that you just go into the BIOS on this machine and just save and exit (without changing anything), then the next WinXP boot occurs normally and without 86Box crashes.

**Comment by maximus105** [comment] 2021-04-16 06:05
Also [i440BX] Microsoft Virtual PC 2007 stops launching altogether when changing the videocard to some other (but obviously supported by this machine, in which the machine was started earlier) or when changing the frequency or type of processor. For this, you have to delete the NVR files so that this machine starts up again. This was also described in the issue
https://github.com/86Box/86Box/issues/986

**Comment by maximus105** [comment] 2021-04-22 17:10
In build 2941 86Box crashes when the [i440BX] ASUS P3B-F machine starts up. If you delete the NVR files for this machine, it starts up normally. If after that you enter the BIOS and exit with saving (without changing anything), then when you start the machine [i440BX] ASUS P3B-F 86Box crashes.

**Comment by OBattler** [comment] 2021-05-02 14:34
This is now closed since I received a report that the issues are now fixed.

**Closed by OBattler** 2021-05-02 14:34 UTC
Labels: bug
