### ISSUE TITLE
[BUG] Windows 95 RTM crashes during setup

### ISSUE THREAD

**Issue by PentiumMMX166** [86Box/86Box#1883] opened 2021-12-01 07:02 UTC
**Describe the bug**
When it does the preparing to copy portion of the install, it crashes with SUWIN caued a general protection fault in module <unknown> then it kicks me back to the DOS prompt.

**To Reproduce**
1. Go to the CD ROM icon
2. Click on the Windows 95 RTM English (OEM) Iso from Winworld PC
3. do the first parts of the setup till you get to the preparing to copy portion

**Expected behavior**
It should go straight to the installing portion.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: Build 3322
 - Build type: regular

**Additional context**
the Floppy version doesn't crash unlike the CD version.

**Comment by dhrdlicka** [comment] 2021-12-01 10:57
Please add screenshots and proper information about the exact build you're using. "Regular" is not really helpful given the recent overhaul of Jenkins.

**Comment by TC1995** [comment] 2021-12-03 11:13
This doesn't happen on my end, but it a different issue is on the asus tx97 using its built-in IDE.

**Comment by creopard** [comment] 2021-12-29 17:40
There was once a similar issue in VMware with a faulty boot disk, that did not assign the CD-ROM to letter "D:", as the Windowa 95 OEM expected it to be, see:
https://communities.vmware.com/t5/VMware-Workstation-Pro/Workstation-6-Windows-95-install-error-SUWIN-caused-a-General/m-p/212629/highlight/true#M6916

Since the Floppy version did not crash, it might be the same issue in your case as well?

**Comment by OBattler** [comment] 2023-01-26 04:13
Closing with CANTIX since I can't even reproduce it, so creopard is probably right. Make sure your boot floppy maps the CD-ROM to drive D:.

**Closed by OBattler** 2023-01-26 04:13 UTC
Labels: bug
