### ISSUE TITLE
NON-USB keyboard doesn't work with 86Box?

### ISSUE THREAD

**Issue by Mast3rBlast3r** [86Box/86Box#1900] opened 2021-12-03 07:57 UTC
my standard NON-USB "Cherry" keyboard doesn't work with 86Box?? but she worked with PCem, only after connecting the USB keyboard I was able to test 86Box and to setup Windows 98.. this is the first emulator I tested that doesn't support old hardware, not so obsolete yet, although it likes to emulate it on many different ways..

**Desktop

- Windows 10 1909 18363.535
- 86Box-Windows-32-b3336
- ASUS-P55T2P4 + K6 233

thank you guys for this awesome project, it means a lot to me to see old software and old games that I loved alive and in action again..

**Comment by OBattler** [comment] 2021-12-03 09:52
What kind of connector does this keyboard use?

**Comment by Mast3rBlast3r** [comment] 2021-12-03 11:15
it's a standard PS/2 keyboard with 5 PIN DIN connector.. I think i discovered what is the problem with NON-USB keyboard.. or where the trouble can be.. when I started experimenting with PCem emulator to discover the most stable machine I noticed.. that he had lost touch with the keyboard more then once, then I changed the Rendering type from Auto to OpenGL trying to reset it without a reset, and he reconnected the keyboard, PCem never lost the NON-USB keyboard connection in OpenGL mode.. the same problem happened here, on the first run 86Box did not recognize the NON-USB keyboard, but then I changed the rendering to SDL (OpenGl) and now my NON-USB keyboard is working again with 86Box.. something is wrong with that Default Rendering type, can't capture standard keyboard and keep connection..

**Comment by OBattler** [comment] 2021-12-03 11:52
That's strange. I use a PS/2 keyboard myself, and it works fine with the emulator regardless of the renderer.

What emulated machine are you using? Perhaps something else is going on.

**Comment by Mast3rBlast3r** [comment] 2021-12-04 07:47
at this moment I can't say I know exactly where the problem is, because it works a little and then it doesn't work again.. and changing Rendering mode does not help like with PCem, something is different.. usually works after closing and restarting 86Box, last night I installed Windows 95 on Socket 7 [VIA VP3] FIC PA-2012 machine and I lost mouse and keyboard signal after Windows is loaded.. I don't know why, I'll try again.. can be something about VM machines, can be something about my configuration.. I have one VMware VM active in background all the time, busy about recovering damaged CD drives, so I plugged in again USB keyboard to continue with two keyboards.. I'll write detailed report only if I can reproduce error precisely..

**Comment by OBattler** [comment] 2021-12-15 23:24
I can see what the problem is - you're hitting the well-known problem with the current lackluster keyboard controller emulation. I have an in-progress rewrite of that, hopefully that's going to fix these problems.

**Comment by OBattler** [comment] 2022-10-30 01:57
PSA: Closing these keyboard PS/2 issues and mentioning them in the issue opened for the keyboard controller rewrite as that's poised to fix them.

**Closed by OBattler** 2022-10-30 01:57 UTC
Labels: bug
