### ISSUE TITLE
Strong degradation of image quality on a CGA video card

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#3603] opened 2023-08-19 10:46 UTC
**Describe the bug**
Strong degradation of image quality on a CGA video card with filter method linear. Noticeably strong soap in the image with the filter method linear. On a real CGA monitor, the image is sharper and more similar to the image with the filter method linear that was in build 4798. This bug was introduced in build 4799 and persists until the latest build. In build 4798 everything works fine.

**To Reproduce**
1. Start the machine with CGA Mono Gray RGB or CGA Color RGB graphics card with filter method linear.
2. Compare images in build 4798 and in build 4799, 4800.
3. A strong degradation of image quality is noticeable after build 4798.

**Expected behavior**
The image on the CGA video card with filter method linear should be clear as in build 4798.

**Screenshots**
CGA Mono Gray RGB Build 4798:
![CGA Mono Gray RGB Build 4798](https://github.com/86Box/86Box/assets/58270614/64038a4f-c79a-4f9b-b01c-0851ba4b93d8)

CGA Mono Gray RGB Build 4799:
![CGA Mono Gray RGB Build 4799](https://github.com/86Box/86Box/assets/58270614/f5237e0b-0844-410c-a5e8-feec48102acd)

CGA Color RGB Build 4798:
![CGA Color RGB Build 4798](https://github.com/86Box/86Box/assets/58270614/1bee70b5-ae7e-45a3-b64d-57286730e5cc)

CGA Color RGB Build 4799:
![CGA Color RGB Build 4799](https://github.com/86Box/86Box/assets/58270614/33d04645-eddf-4de1-8ac0-8f43db7f0346)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 v22H2
 - 86Box v4.0.0 x86 Build 4908
 - Build type: qt, regular, old recompiler

**Comment by OBattler** [comment] 2023-08-19 13:45
> On a real CGA monitor, the image is sharper and more similar to the image with the filter method linear that was in build 4798. This bug was introduced in build 4799 and persists until the latest build. In build 4798 everything works fine.

1. I seriously doubt the image is much sharper on a real CGA monitor, it's a CRT from 1981, not a modern LCD monitor, CRT's were never that sharp.

2. It's not a bug. It was caused by rendering only 200 lines, which is what the real monitor does. Therefore, I'm closing with NOTABUG.

**Closed by OBattler** 2023-08-19 13:45 UTC
Labels: bug
