### ISSUE TITLE
Cirrus Logic GD5480 VGA not working

### ISSUE THREAD

**Issue by kzmidze** [86Box/86Box#3760] opened 2023-10-15 11:19 UTC
### What happened?

1. GD5480 VGA Bug: Cirrus Logic GD5480 VGA not working. Using Cirrus Logic GD5446 VGA, it works.
![Monitor_1_20231015-180221-594](https://github.com/86Box/86Box/assets/117635969/504388b3-af0f-4bdd-9202-31ed0b5d6463)
2. GA-6GXU Bug: On Windows 98, ACPI Restart (click Start - Shutdown - Restart) will stuck on "Windows is shutting down", but ACPI Shutdown (click Start - Shutdown - Shutdown) has no issue.

### Configuration file

```ini
[General]
vid_renderer = qt_opengl3
confirm_exit = 1

[Machine]
machine = 6gxu
cpu_family = pentium2_xeon
cpu_speed = 200000000
cpu_multi = 2
cpu_use_dynarec = 1
fpu_softfloat = 1
time_sync = local
fpu_type = internal
cpu = 4
mem_size = 524288

[Video]
gfxcard = cl_gd5480_pci

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked
sndcard = sbawe64

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0
net_01_card = ne2kpci
net_01_net_type = slirp

[Storage controllers]
hdc = internal
cassette_mode = load
scsicard_1 = bt958d

[Standard PS/2 Mouse]
buttons = 4

[BusLogic BT-958D PCI #1]
bios = 1

[Realtek RTL8029AS #1]
mac = 5a:94:30

[Hard disks]
hdd_01_parameters = 63, 16, 16644, 0, scsi
hdd_01_scsi_location = 0:00
hdd_01_fn = Win98.vhd
hdd_01_vhd_blocksize = 1024

[Floppy and CD-ROM drives]
cdrom_01_speed = 72
cdrom_01_parameters = 1, scsi
cdrom_01_scsi_location = 0:01
fdd_01_type = none
fdd_02_type = none
cdrom_01_host_drive = 200
cdrom_01_type = 86BOX_CD-ROM_1.00
```

### Operating system

Windows 11

### CPU

Dell XPS 13 9305

### 86Box version

v4.0 build 5096

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by borisvolk117** [comment] 2023-10-15 11:52
Ah, it seems that all ACPI machines cannot perform ACPI reset in Windows. I use [Slot 1] MSI MS-6168 and it stucks on "Windows is shutting down", too.

**Comment by OBattler** [comment] 2023-10-15 17:36
1. CL-GD 5480 not working is not a bug - Windows 98 SE does not have drivers for it. You need to find a driver somewhere and install it.
2. ACPI shutdown is also not a bug - not all machines have a proper ACPI HAL. Also, you somehow concluded the all ACPI machines are affected based on only two being tested.

As such, I'm closing this with NOTABUG.

**Closed by OBattler** 2023-10-15 17:36 UTC
Labels: bug
