### ISSUE TITLE
Emulator crash on WinNT3.51

### ISSUE THREAD

**Issue by MarekKnapek** [86Box/86Box#2552] opened 2022-08-01 12:37 UTC
**Describe the bug**
Emulator crashed.

**To Reproduce**
Host computer is x64 Windows laptop.
Guest computer is Award 486 clone.
Guest operating system is Windows NT 3.51.
Guest application is Visual Studio 1.10 for NT.
I opened project with single *.c file, that file size is 18 MB.
Other guest programs running: WinHelp, Total Commander with FTP.
Not able to reproduce again.

**Expected behavior**
Not crash.

**Screenshots**
Full memory dump in moment of crash is available as attachment.

**Desktop (please complete the following information):**
86Box 3.7 build 4008.

**Additional context**
Dump file (57 MB compressed 7z): https://mega.nz/file/6V8gBLRZ#SN-SB2dHBJsO3oNI817ZmwHO4sHfu-kJE4iT0tz2pbE

**Comment by OBattler** [comment] 2022-08-01 13:54
Upload the VM (hard disk image, cfg, nvr folder) please, so I can attempt to reproduce this crash.

**Comment by OBattler** [comment] 2022-10-27 19:57
Closing this because the material required to reproduce the bug has not been provided.

**Closed by OBattler** 2022-10-27 19:57 UTC
Labels: bug

**Comment by MarekKnapek** [comment] 2022-10-27 23:37
Hi @OBattler, I'm sorry I cannot reproduce the bug. But I have my host Windows machine set up to create full memory dump (on Linux this is called core dump) when any program crashes. Is this dump file not useful for you? Do you keep *.pdb files for all 86box releases? From my experience having *.dmp in moment of crash together with *.pdb+*.exe+sources is like 90% of determining the cause of the crash.
