### ISSUE TITLE
Title"Specify Dimensions" does not work in current version of 86Box

### ISSUE THREAD

**Issue by Moltresrider** [86Box/86Box#4139] opened 2024-02-10 20:11 UTC
### What happened?

I set my guest resolution to 1600x1200.

I wanted to make the window that same size

I went to View - Specify Dimensions and inputted 1600 and 1200 and clicked OK

What happened was, the windows did NOT resize. It is still at 640x480 which does not mach the resolution of the guest.

Making the window maximized makes it 1920x1080, but specifying 1600 x 1200 still does not resize the window

Expected results: When entering 1600x1200 in "Specify dimension" the window should resize to that size. 

### Configuration file

```ini
[General]
vid_renderer = qt_software
sound_gain = 5
vid_resize = 2
window_fixed_res = 1600x1200

[Machine]
machine = cuv4xls
cpu_family = c3_samuel
cpu_speed = 700000000
cpu_multi = 7
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
fpu_type = internal
mem_size = 507904

[Video]
gfxcard = voodoo3_3500_si_agp

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked
sndcard = cmi8338
sound_type = int16
midi_device = mt32

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = none
cassette_mode = load

[Hard disks]
hdd_01_parameters = 63, 16, 24380, 0, ide
hdd_01_fn = W98.vhd
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0
hdd_01_vhd_blocksize = 4096

[Floppy and CD-ROM drives]
fdd_01_type = none
fdd_02_type = none
cdrom_01_speed = 72
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 0:1
cdrom_01_type = TOSHIBA_CD-ROM_XM-5302TA_0305
fdd_01_check_bpb = 0
cdrom_01_image_history_01 = windows98se.iso
cdrom_01_image_history_02 = Windows 98/Drivers/v3_3500TV_11.iso
cdrom_01_image_history_03 = Windows 98/Drivers/voodoo3-3500
cdrom_01_image_history_04 = Windows 98/Drivers

[3dfx Voodoo3 3500 SI]
bilinear = 1
dithersub = 1
dacfilter = 0
render_threads = 4
recompiler = 1

[Ensoniq AudioPCI (ES1371)]
codec = 1414676739
receive_input = 1
```

### Operating system

Windows 10 64-bit

### CPU

Core i7

### 86Box version

4.01 build 5111

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by Moltresrider** [comment] 2024-02-10 20:16
I would also like to add that "force 4:3 Display Ratio" also is nonfuntional

**Comment by maximus105** [comment] 2024-02-10 20:47
> I went to View - Specify Dimensions and inputted 1600 and 1200 and clicked OK

You also need to click "Lock to this size".
You also need to click "Remember size & position", then the 86Box window will be saved in the place on the screen where you placed it.

**Comment by Moltresrider** [comment] 2024-02-10 20:48
Still does not work. Tried that.

**Comment by maximus105** [comment] 2024-02-10 20:50
> I would also like to add that "force 4:3 Display Ratio" also is nonfuntional

"Force 4:3 Display Ratio" works (turns on and off) the first time you launch 86Box, when there are no window size settings in 86Box.cfg yet.

**Comment by maximus105** [comment] 2024-02-10 21:10
1. Remove 86Box.cfg
2. Run 86Box.exe
3. Turn on "Resizeable window" and "Remember size & position"
4. Set "Specify dimensions..." to 1600x1200, enable "Lock to this size" and click OK
5. Move the window to the center of the monitor screen
6. In "Specify dimensions...", disable "Lock to this size" and click OK
7. Close 86Box
8. Run 86Box.exe
9. The window will be saved in the place on the monitor screen where you moved it
10. In "Specify dimensions..." the window dimensions will be saved as 1600x1200 and the "Lock to this size" option will be disabled
That is, everything works.

**Comment by OBattler** [comment] 2024-02-12 07:00
Remember that when you try to resize the window to a size bigger than the guest resolution, the OS may prevent resizing to that size. I'm quite sure I can't resize the window to 1600x1200 on my 1920x1080 monitor, but there's nothing I can do about that - it's an OS limitation.

**Comment by OBattler** [comment] 2024-02-12 07:01
Actually, I just tested - and I could resize fine to that. But yes, you need to tell it to lock to that size.

**Comment by OBattler** [comment] 2024-02-12 07:03
And force 4:3 only works in windowed mode (so not in full-screen or maximized), and at that only when the window is not set to be resizable. This is as intended. When maximimed, the full-screen stretching mode applies so just set that to 4:3 as well.

As such, I'm closing this issue with NOTABUG.

**Closed by OBattler** 2024-02-12 07:03 UTC
Labels: bug
