### ISSUE TITLE
Emulator crashes (sometimes) when opening MS-DOS Prompt on Windows 95

### ISSUE THREAD

**Issue by chungy** [86Box/86Box#2350] opened 2022-05-18 17:13 UTC
**Describe the bug**
When running Windows 95 and opening the MS-DOS Prompt, 86Box crashes about 1-in-3 times it is attempted.

Tested on: 3.4.1 (self-build), 3.4.1 AppImage, 180ceba8262fd75f884c0f0aaca827e6929a3c82 (self-build)

I am using Shuttle HOT-7 as a system to test on. Config: [86box.zip](https://github.com/86Box/86Box/files/8718541/86box.zip)

Clues given via gdb:
```
[0117:0000B991] Illegal instruction 00008B55 (FF)

Thread 17 "86Box" received signal SIGSEGV, Segmentation fault.

(gdb) bt
#0  0x00007fffdeda3b61 in  ()
#1  0x00007fffb97fb800 in  ()
#2  0x81a9e901de8c9a00 in  ()
#3  0x00007fffb97fb810 in  ()
#4  0x0000555555775bc7 in opF6_a16 (rmdat=0) at /home/chungy/src/86Box/src/cpu/x86_ops_misc.h:65
```

**To Reproduce**
1. Run Windows 95 (I am using 95C, specifically)
2. Click Start→Programs→MS-DOS Prompt
2a. If doesn't crash, close DOS window, try again.
3. 86Box segfaults.

**Expected behavior**
86Box not crashing.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux x86_64
 - 86Box version: 3.4.1 and 180ceba8262fd75f884c0f0aaca827e6929a3c82
 - Build information: dunno? GCC 12.1, Qt 5...

**Comment by chungy** [comment] 2022-05-27 16:34
Just an update to note that 86Box 3.5 still exhibits the issue -- and I've also seen it happen with Windows 98 and Me with various other motherboard and CPU options.

Basically any time a virtual 8086 is created in Windows, there's a chance that 86Box crashes. All these OSes launch virtual 8086 very frequently, even in the background, causing the emulator to be very unreliable for Win9x usage.

**Comment by anthonycapriglione** [comment] 2022-07-11 07:29
I can confirm this issue on 86box 3.5 as well

**Comment by Drakknar** [comment] 2022-08-12 19:09
Can confirm this is the case with Windows 98 SE on 3.7.1. 

Host machine:
Windows 11 22H2 x64 
AMD Ryzen 9 5900X
32GB RAM

VM:
AOpen X59 Pro (Super Socket 7)
Pentium MMX 166
128MB RAM
S3 ViRGE/DX (375)
Voodoo2
SB AWE32 PnP
SLiRP, AMD PCNet-Fast III

**Comment by OBattler** [comment] 2022-10-27 02:17
Closing this since it appears to be fixed now.

**Closed by OBattler** 2022-10-27 02:17 UTC
Labels: bug
