### ISSUE TITLE
Tandy 1000 and PCjr audio plays at wrong pitch in some games

### ISSUE THREAD

**Issue by Digitoxin1** [86Box/86Box#2706] opened 2022-10-03 03:47 UTC
**Describe the bug**
In some older games, the Tandy/PCjr audio plays at the wrong pitch.  I have included a link to an example of this happening.  The game in the example is The Black Cauldron v1.1M.   This version of the game boots from the floppy and does not require DOS.

[https://www.youtube.com/watch?v=HcoWIg4QbEk](https://www.youtube.com/watch?v=HcoWIg4QbEk)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: 3.7,1
 - Build information: 86box-windows-64-b4032.zip

**Comment by Digitoxin1** [comment] 2022-11-26 07:01
This is now happening for me on all versions of The Black Cauldron using 86Box v3.11.   I've tried the game while emulating the Tandy 1000, Tandy 1000 HX, and Tandy 1000 SL/2 with the same issue.  I've also tried emulating under different speeds and disabling devices like joysticks and a mouse with no change.

**Comment by Exemptus** [comment] 2023-01-15 12:26
I can confirm this also happens with the PCjr version of Touchdown Football (a known perfect preserved image, self-booting). Everything is at the right speed, except the speech, which is far too fast. Funnily enough this also happens with MAME and DOSBox, so it seems to be common to several emulators.

**Comment by OBattler** [comment] 2024-01-14 23:56
Closing this because this is being tracked in 4044.

**Closed by OBattler** 2024-01-14 23:56 UTC
Labels: bug
