### ISSUE TITLE
Windows lock screen will cause the screen to freeze

### ISSUE THREAD

**Issue by shijie001** [86Box/86Box#1100] opened 2020-11-18 17:00 UTC
Windows lock screen will cause the screen to freeze

**To Reproduce**
Lock the screen, then unlock. The game screen freezes. Whether it is playing games, or dos command line. 
In fact, the game is still running normally, but the output is not refreshed.

This problem only occurs in SDL (hardware). There is a solution, switch to SDL (Software). Then the screen started to refresh again. You can also switch back to SDL (hardware).

OS: Windows 10
86Box version: I have tested many versions and all have the same problem.
3.0.0.2654
D:\projects\86Box\86Box-32-9fb3a3ed\
3.0.0.2642
D:\projects\86Box\86Box-32-48883a46\
3.0.0.2625
D:\projects\86Box\86Box-32-cfb559de\
3.0.0.2613
D:\projects\86Box\86Box-32-5e470656\
2.10.0.2374
D:\projects\86Box\86Box-32-5290bcf7 
2.10.0.2018
D:\projects\86Box\86Box-32-15bf5841\
2.7.0.2008
D:\projects\86Box\86Box-32-245af88d\

Build type: regular

**Comment by daviunic** [comment] 2020-11-18 17:11
Sounds like a standard renderer hang.

**Comment by dhrdlicka** [comment] 2020-11-18 17:12
Duplicate of #541.

**Closed by dhrdlicka** 2020-11-18 17:12 UTC
Labels: bug
