### ISSUE TITLE
Windows XP causes crash during second stage under Wine/Linux.

### ISSUE THREAD

**Issue by foxlet** [86Box/86Box#1203] opened 2021-01-04 02:49 UTC
**Describe the bug**
86box aborts during the second stage of Windows XP's setup, using an installation of Windows XP Professional SP2.

**To Reproduce**
1. Run Windows XP setup from CD image.
2. Wait for second stage, fill out regional and user information.
3. Crash.

**Expected behavior**
Windows XP finishes setup and system boots.

**Screenshots**
N/A

**Desktop:**
 - OS: Void Linux (x86_64)
 - 86Box version: 86Box v3.0 [ef139803, build 2765]
 - Build type: regular

**Additional context**
86box configuration uses a Pentium II Xeon/450 on a Slot 2 board. Running under `wine-6.0-rc5`.
[86box-crash.log](https://github.com/86Box/86Box/files/5762800/86box-crash.log)
[86box.cfg.txt](https://github.com/86Box/86Box/files/5762811/86box.cfg.txt)

**Comment by explorerdotexe** [comment] 2021-01-04 09:50
Did the crash happen around the "Registering Components" part of setup by any chance?

**Comment by superoskar6** [comment] 2021-05-17 15:32
Happens to me as well on the latest build running under Windows 10 1809. It happens during the registering components part, and doesn't produce any crash logs afterwards.

**Comment by OBattler** [comment] 2021-07-30 17:35
Closing this, because it's a duplicate of #1192.

**Closed by OBattler** 2021-07-30 17:35 UTC
Labels: bug
