### ISSUE TITLE
Random freeze in Windows 98 SE (OEM)

### ISSUE THREAD

**Issue by silverlays** [86Box/86Box#1944] opened 2021-12-18 17:16 UTC
**Describe the bug**
My Win98 SE freeze randomly since version 3.0.

**To Reproduce**
1. Launch VM
2. Do something usual in the Windows GUI and wait from some minutes to like an hour.

**Desktop (please complete the following information):**
 - OS: Guest: Windows 98 SE (OEM) SP3 // Host: Windows 10 21H2
 - 86Box version: regular v3.0-3333 (x86) => v3.1-3385 (x86)
 - Build information: same with ODR and NDR
 - Specs: FIC VA-503+ // P_MMX 200Mhz // 256 RAM // (AGP) 3Dfx Voodoo 3 3000 // Sound Blaster AWE 32 // 2x IDE HDD and 1x IDE CDROM 72x // No network // PS2 Mouse.

**Additional context**
Like I said before, it randomly freeze when i just browse with explorer, renaming stuff, playing game, etc... There is no real pattern to reproduce.

When it freeze, i tried to change renderer, CTRL-ALT-DEL, move the mouse, hit a key, but nothing happen. I had to "Hard Reset" everytime.

Thanks in advance for answers.

**Comment by postalesdeamor** [comment] 2021-12-19 07:26
Me too, random freezes.  But always that I try to load "Redline Racer" 3dfx glide version.

**Comment by OBattler** [comment] 2021-12-21 00:57
Perhaps try switching to a different Voodoo 3 3000 driver, because it must be the driver you're using causing the emulator lock up, it's likely executing an unimplemented Voodoo 3 command.

**Comment by silverlays** [comment] 2021-12-21 00:59
> Perhaps try switching to a different Voodoo 3 3000 driver, because it must be the driver you're using causing the emulator lock up, it's likely executing an unimplemented Voodoo 3 command.

Good advice 👍 I'll try that and make some feedback after few tests

**Comment by Mast3rBlast3r** [comment] 2021-12-27 23:30
did you change the option in Bios before installing Windows 98SE, about.. is PNP System Installed from No to Yes?
I forgot once, and the installation crashed with a blue screen and a message Fatal Exception Error, and later.. Windows was unstable, he doesn't seem to be able to communicate with Bios properly..
 Windows crashed again after I tried to open Device Manager in System/Control Panel, it is good to know to make a difference whether the problem is in the emulator or Windows maybe..

I installed Windows 98SE on the same machine, FIC VA-503+, and I had a problem I couldn’t solve, I had a conflict in Device Manager, it looks like Windows has only two IRQ numbers available and both are assigned to the printer and the music card, I couldn't change the configuration manually, because I was not offered that option as usual, as with other machines..

try these drivers, version 1.07.00, from here..

https://www.philscomputerlab.com/drivers-for-voodoo-3.html

**Comment by silverlays** [comment] 2021-12-28 02:33
@Mast3rBlast3r 
> id you change the option in Bios before installing Windows 98SE, about.. is PNP System Installed from No to Yes?

Yes i did, but AFTER installation to be honest. In addition, I have this IRQ conflict issue too (for printer and floppy controller)
Thanks for the drivers, i'm currently trying with the 1.30.00 version atm, it seems to work, but I'm not sure yet.

**Comment by Mast3rBlast3r** [comment] 2021-12-28 07:30
I tested all versions of drivers for Voodoo 3 3000, in Windows 98, just to see if there are any differences, and i found that not all games will run if you don't have the latest and final version installed,  version 1.07.00, like Hidden & Dangerous, it looks like it was game compiled for the latest driver version..

I found that the 86Box is stable for longer run, I left him playing against the computer opponents all night long, under Windows 98, Empire Earth (a lot of small people gather resources to build a civilization), and he worked in the morning, without any problems..

**Comment by kode54** [comment] 2022-10-26 08:10
I'm using the 1.07.00 drivers from the above linked site, and the machine still locks up randomly. I tried running Final Reality, and it locks up before it even displays the startup logo.

**Comment by OBattler** [comment] 2022-11-06 16:26
Does this still happen with the latest Voodoo fixes?

**Comment by silverlays** [comment] 2022-11-06 23:28
Sadly yes. My VM freezed (with looping sound) after 2 benchmarks (3DMark 99 & Final Reality) and while I was playing Blood 2 Demo 😿
Tested with : 86Box x64 ODR #4243 With VooDoo 3 PCI v1.07.00

**Comment by OBattler** [comment] 2023-07-15 21:21
Does this still happen? Since there have been x64 recompiler fixes since then.

**Comment by OBattler** [comment] 2023-11-08 06:18
Closing this because I'm going to assume this has been fixed due to a lack of feedback for a year now. It can be reopened, should the issue be reproduced on the current builds.

**Closed by OBattler** 2023-11-08 06:18 UTC
Labels: bug

**Comment by silverlays** [comment] 2023-11-08 17:23
Ooh damn! I'm REALLY sorry I forgot this one 😢 And yes, this issue was fixed long time ago now. Thanks @OBattler
