### ISSUE TITLE
Add the TOPCAT chipset emulation to Olivetti M290

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1369] opened 2021-04-11 16:21 UTC
**Is your feature request related to a problem? Please describe.**
No. It's a feature.

**Describe the solution you'd like**
The Olivetti M290 is dev branched right now, but works just fine. I found that machine has a TOPCAT chipset. A found the datasheet of a TOPCAT chipset, I'm not sure, but says this chipset is designed for 286/386SX, so I think it's for this machine.
It can provide EMS memory.

Here is the description of the M290 machine
[https://www.ardent-tool.com/Olivetti/Docs/service_guide/systems1/cap32.pdf](url)

Here is the datasheet:
[https://www.datasheetarchive.com/pdf/download.php?id=d851a99261b463d43ad0ddcb99d6388ed14f10&type=O&term=topcat](url)

Also found the EMS device driver for that board with the source code in ASM format. Is available here:

[https://github.com/karcherm/topemm](url)

The driver was reprogrammed to work with TOPCAT chipset.

**Additional context**
According Greatpsycho the TOPCAT driver is somewhat similar, but not equal to the SCAMPsx chipset used by the Commodore 386SX/25, but not sure how similar is it.

**Comment by waltje** [comment] 2021-04-11 18:36
That is not a datasheet, its a 'product brief', or, a short description of what itcan do, and for which markets it was designed.

    On Sunday, April 11, 2021, 12:21:36 PM EDT, Fenix770 ***@***.***> wrote:  
 
 


Is your feature request related to a problem? Please describe.
No. It's a feature.

Describe the solution you'd like
The Olivetti M290 is dev branched right now, but works just fine. I found that machine has a TOPCAT chipset. A found the datasheet of a TOPCAT chipset, I'm not sure, but says this chipset is designed for 286/386SX, so I think it's for this machine.
It can provide EMS memory.

Here is the datasheet:
https://www.datasheetarchive.com/pdf/download.php?id=d851a99261b463d43ad0ddcb99d6388ed14f10&type=O&term=topcat

Also found the EMS device driver for that board with the source code in ASM format. Is available here:

https://github.com/karcherm/topemm

The driver was reprogrammed to work with TOPCAT chipset.

Additional context
According Greatpsycho the TOPCAT driver is somewhat similar, but not equal to the SCAMPsx chipset used by the Commodore 386SX/25, but not sure how similar is it.

**Comment by Fenix770** [comment] 2021-04-11 19:01
Sorry! You're right.
I found two other larger PDF files which contain diagrams of these chipsets. May be, this contains the information required:
In theory the TOPCAT can use either the VL82C320A or the VL82C331A. I fount the VL82C320A and the VL82C331 Without "A".
and the SCAMP.

The VL82C320A:

https://www.datasheetarchive.com/pdf/download.php?id=6a14f5ca13e71787e89e106f6074bd7335150c&type=M&term=VL82C320A

The VL82C331:

https://www.datasheetarchive.com/pdf/download.php?id=89b43bc9c20e3d1275711dc170d3e7c38e4d13&type=O&term=VL82C331

The SCAMP-Lite (VL82C335) (I don't know if it's for the Commodore 386SX)

https://www.datasheetarchive.com/pdf/download.php?id=c2fe420d49ca87e471a7f3b39bc431465ce02c&type=M&term=VL82C331

**Comment by waltje** [comment] 2021-04-11 19:12
I believe all these links refer to the 82C325 cache controller.
Be careful about how DSarchive names its stuff... very often, its named wrong. Theydo this do trick people, because whether its the datasheet people are looking for ornot, they still get their advertising income...
One of the links down the page does link to the 82C330 system controller, which isone of the chips needed for Topcat systems.

    On Sunday, April 11, 2021, 3:01:21 PM EDT, Fenix770 ***@***.***> wrote:  
 
 


Sorry! You're right.
I found two other larger PDF files which contain diagrams of these chipsets. May be, this contains the information required:
In theory the TOPCAT can use either the VL82C320A or the VL82C331A. I fount the VL82C320A and the VL82C331 Without "A".
and the SCAMP.

The VL82C320A:

https://www.datasheetarchive.com/pdf/download.php?id=6a14f5ca13e71787e89e106f6074bd7335150c&type=M&term=VL82C320A

The VL82C331:

https://www.datasheetarchive.com/pdf/download.php?id=89b43bc9c20e3d1275711dc170d3e7c38e4d13&type=O&term=VL82C331

The SCAMP-Lite (VL82C335) (I don't know if it's for the Commodore 386SX)

https://www.datasheetarchive.com/pdf/download.php?id=c2fe420d49ca87e471a7f3b39bc431465ce02c&type=M&term=VL82C331

**Comment by waltje** [comment] 2021-04-11 19:33
This is the "proper" manual Obat would need for implementation:
http://ftpmirror.your.org/pub/misc/bitsavers/components/vti/VTI_TOPCAT_VL82C286_82C386_PC_AT_Chipset_Oct90.pdf
This is the one for the VTI (VLSI Tech) product, although I am prettysure the Chips (C&T) one is at least very similar.  The EMS driver youreferred to is actually for this (VTI) one ;-)
--fred

    On Sunday, April 11, 2021, 3:01:21 PM EDT, Fenix770 ***@***.***> wrote:  
 
 


Sorry! You're right.
I found two other larger PDF files which contain diagrams of these chipsets. May be, this contains the information required:
In theory the TOPCAT can use either the VL82C320A or the VL82C331A. I fount the VL82C320A and the VL82C331 Without "A".
and the SCAMP.

The VL82C320A:

https://www.datasheetarchive.com/pdf/download.php?id=6a14f5ca13e71787e89e106f6074bd7335150c&type=M&term=VL82C320A

The VL82C331:

https://www.datasheetarchive.com/pdf/download.php?id=89b43bc9c20e3d1275711dc170d3e7c38e4d13&type=O&term=VL82C331

The SCAMP-Lite (VL82C335) (I don't know if it's for the Commodore 386SX)

https://www.datasheetarchive.com/pdf/download.php?id=c2fe420d49ca87e471a7f3b39bc431465ce02c&type=M&term=VL82C331

**Comment by tiseno100** [comment] 2021-04-17 13:54
Datasheets do exist for it but it'll require someone with knowledge of how EMS works on 86Box to write it.

**Comment by Fenix770** [comment] 2021-04-29 16:32
I checked the datasheet again. I discovered That the Topcat chipset was included on the M290-25 and M290-30. I don't sure if other models inlude this chip, but these models have a 286/20, VGA video chip, and the setup BIOS is integrated.
The original M290 (without other numbers). Have a 286/12, EGA and requires the setup disk to configure the system. So I suspect it is a different chipset. 
Maybe, if some time in the future the SCAMP chipset is added and have similarities with the TOPCAT, some of these machines can be added.

**Comment by OBattler** [comment] 2021-05-27 04:50
> Maybe, if some time in the future the SCAMP chipset is added
That was 28 days ago. SCAMP was added quite some time before that, for one of those Commodore 386's.

But I think I've had enough of Olivetti stuff for time being, given how problematic they tend to be to emulate. Maybe I'm going to revisit the idea in the future. In the meantime, I'm closing this issue.

**Closed by OBattler** 2021-05-27 04:50 UTC
Labels: feature
