### ISSUE TITLE
Certain CDs have file not found

### ISSUE THREAD

**Issue by ualaa1** [86Box/86Box#3854] opened 2023-12-01 06:41 UTC
### What happened?

Games that seem affected so far:
Discworld II
City of Lost Children
Pinball World
Links LS 1997

I have tried with multiple dumps of the games, and it seems that for some reason 86-Box can't seem to find the files for these CDs. To reproduce these issues, mount the disks onto the D drive and try to look for files. On 86-Box, files don't seem to exist, but when testing them on Dosbox-X they were able to be found. 

### Configuration file

```ini
[General]
vid_renderer = qt_software
sound_gain = 18

[Machine]
machine = 486sp3g
cpu_family = i486dx2_pc330
cpu_speed = 66666666
cpu_multi = 2
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
fpu_type = internal
mem_size = 16384

[Video]
gfxcard = stb_velocity3d_pci

[Input devices]
mouse_type = msserial

[Sound]
fm_driver = nuked
sndcard = sbawe32
midi_device = cm32ln
mpu401_standalone = 1

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = none
cassette_mode = load

[S3 ViRGE/VX (STB Velocity 3D) PCI]
memory = 8
bilinear = 1
dithering = 1

[Sound Blaster AWE32]
base = 0220
emu_base = 0620
base401 = 0000
irq = 5
dma = 1
dma16 = 5
onboard_ram = 28672
opl = 1
receive_input = 1
receive_input401 = 0

[Hard disks]
hdd_01_parameters = 63, 16, 4266, 0, ide
hdd_01_fn = largedos.vhd
hdd_01_speed = ramdisk
hdd_01_vhd_blocksize = 4096
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2ed
fdd_01_turbo = 1
fdd_02_type = 35_2ed
fdd_02_turbo = 1
cdrom_01_speed = 72
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 0:1
fdd_02_image_history_01 = cspu.IMA
fdd_01_image_history_01 = Disk06.img
cdrom_01_host_drive = 200
cdrom_01_image_path = Games/DW2_CD1.CUE
cdrom_01_image_history_01 = Games/Legends of Heroes 3 Korean.ISO
cdrom_01_image_history_02 = Games/Legends of Heroes 3 (Chinese).cue
cdrom_01_type = 86BOX_CD-ROM_1.00

[FluidSynth]
sound_font = C:/Users/19099/Desktop/em/dos3/SC-55.SoundFont.v1.2b.sf2
output_gain = 20
chorus = 1
chorus_voices = 3
chorus_level = 20
chorus_speed = 30
chorus_depth = 80
chorus_waveform = 0
reverb = 1
reverb_room_size = 20
reverb_damping = 0
reverb_width = 5
reverb_level = 90
interpolation = 2

[S3 ViRGE/VX (Diamond Stealth 3D 3000) PCI]
memory = 8
bilinear = 1
dithering = 1

[S3 Trio64V+ PCI (Phoenix)]
memory = 4

[Roland CM-32LN Emulation]
output_gain = 20
reverb = 1
reverb_output_gain = 20
reversed_stereo = 0
nice_ramp = 1
```

### Operating system

Windows 10

### CPU

Intel Core i7-9750H 

### 86Box version

4.0.1

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

Comparison (using Discworld 2):
On 86-Box using dir/w on drive D:
![Monitor_1_20231130-222803-561](https://github.com/86Box/86Box/assets/68984176/8e1a33f0-15b4-48b6-a91a-7702ead62122)

On Dosbox-X using dir/w on drive D:
![bandicam 2023-11-30 22-26-41-018](https://github.com/86Box/86Box/assets/68984176/67dbd7dd-5eb7-4c2e-ab57-b01e291acea9)

**Comment by OBattler** [comment] 2023-12-01 21:21
I can't reproduce this at all, so it must be the DOS CD-ROM driver you're using.

**Comment by ualaa1** [comment] 2023-12-02 04:29
I uploaded the VM, NVR, and config files on here: https://file.io/Decqtu3xGN1A

**Comment by OBattler** [comment] 2023-12-04 09:19
This is VIDE-CDD version 2.15: [VIDE-CDD.zip](https://github.com/86Box/86Box/files/13544118/VIDE-CDD.zip) .

**Comment by OBattler** [comment] 2023-12-05 19:20
So I'm closing this with NOTABUG on our side - use the driver I just linked.

**Closed by OBattler** 2023-12-05 19:20 UTC
Labels: bug
