### ISSUE TITLE
[BUG] Problem with the "input" section

### ISSUE THREAD

**Issue by Zartan78** [86Box/86Box#1647] opened 2021-09-02 08:38 UTC
**Describe the bug**
The program does not update the "input" section of the config file correctly, in particular the "mouse" subsection.
When changing items from the dropdown menu, the new items are appended to the config file, while the old items are not removed.

**To Reproduce**
1. set mouse input as desired in 86box manager
2. check the config file: there is now a "mouse" section with correct data
3. change the mouse item in 86box manager to another value
4. check the config file again: the new mouse type is added, and the old one is still present.

**Expected behavior**
Changing items in the dropbox menus should replace entries, not simply addding new ones

**Environment (please complete the following information):**
 - windows 10 pro x64
 - tested with several 86box versions, ranging from 2.7 to 3.0.0.3142
 - 86Box Manager Version = 1.7.2
 

This problem creates issues in the guest operating systems (so far i tried both windows 98SE and Windows ME). These include erratic mouse behavior, unresponsive mouse cursor, mouse cursor not present at all.

**Comment by OBattler** [comment] 2021-09-02 19:29
I can't reproduce this at all.

**Comment by OBattler** [comment] 2021-09-02 20:02
I suspect this is a conflation of two problems:
- 86Box appending new device configuration sections, which yes, currently happens because I haven't made it clean up the old ones;
- PS/2 mouse behaving errativally which is a known bug and is completely unrelated to this, and will hopefully be fixed by the on-going keyboard controller etc. rewrite.

**Comment by Zartan78** [comment] 2021-09-08 17:48
[86box.zip](https://github.com/86Box/86Box/files/7130860/86box.zip)


sorry for the late reply, I thought the issue was closed and was busy with other things, Here is the cfg file, if you still need it. Thanks for your interest.

**Comment by OBattler** [comment] 2022-11-06 16:31
I'm going to consider this fixed since noone has had such issues since then, and I have personally tested both 98 SE and ME, and had no mouse problems. I know that back then, some machines erroneously had the PS/2 flag while not having a PS/2 keyboard controller at all, misleading users. Those have since been corrected.

**Closed by OBattler** 2022-11-06 16:31 UTC
