### ISSUE TITLE
DOS 3.31 and 4.01 random reboot with QEMM 5.11/6.02

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#3716] opened 2023-10-01 22:29 UTC
**Describe the bug**

I installed QEMM v5.11 on two 386 machines, one with DOS 3.31 and the other DOS 4.01. Both machines have an issue, on some random circumtances the machine performs a soft reset. The issue is more noticeable under DOS 4.01. For example Commander Keen V, freezes at the DOS prompt on DOS 4.01, I upgraded to QEMM v6.02 but the issue persists. QEMM 6 works fine on MS-DOS 5.0.

Configurations I tested:

MS-DOS 3.31 with QEMM v5.11
MS-DOS 4.01 with QEMM v5.11
MS-DOS 4.01 with QEMM upgraded to v6.02

HDD files:
[386 DOS 331 Qemm v5.zip](https://github.com/86Box/86Box/files/12778380/386.DOS.331.Qemm.v5.zip)
[386 SX DOS 4.0 QEMM v5.zip](https://github.com/86Box/86Box/files/12778381/386.SX.DOS.4.0.QEMM.v5.zip)

CFG+NVR files:
[386 DOS 4.0 QEMM 386 v5.zip](https://github.com/86Box/86Box/files/12778382/386.DOS.4.0.QEMM.386.v5.zip)
[386 DOS 3.31 QEMM 5.zip](https://github.com/86Box/86Box/files/12778383/386.DOS.3.31.QEMM.5.zip)

**To Reproduce**
1. On the DOS 4.01 machine run Keen 5 (on the C:\juegos\keen5\keen5.exe)
2. The machine freezes

1. Run the QEMM Manifest (type MFT at DOS Prompt)
2. Click on Expanded Memory and select the Timing and/or Benchmark option
3. The machine performs a warm reset.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: 4.0.05022
 - Build information: old dynarec, Win x32

**Additional context**
Add any other context about the problem here. If you are using an Optimized build, make sure to try the regular build too before filing a bug report!

**Comment by OBattler** [comment] 2024-01-15 00:01
Closing this as essentially a duplicate of #1864.

**Closed by OBattler** 2024-01-15 00:01 UTC
Labels: bug
