### ISSUE TITLE
Windows 3.11 for Workgroups setup crash

### ISSUE THREAD

**Issue by Xuser641** [86Box/86Box#3663] opened 2023-08-30 20:03 UTC
**Describe the bug**
Around 90% through copying files from the setup disks, the setup crashes with 3 errors:
APPLICATION ERROR - WINSETUP caused a General Protection Fault in module KRNL386.EXE at 0001:5675
APPLICATION ERROR - WINSETUP caused a General Protection Fault in module USER.EXE at 0001:40B6
(Crash to DOS)
Standard Mode: Bad Fault in MS-DOS Extender.
Fault 000D: Stack Dump: 0000 0000 0070 
Raw Fault Frame: EC=0000 IP=5D19 CS=037F FL=3087 SP=FFD8 SS=02DF

**To Reproduce**
1. Setup a virtual machine 
2. Install DOS
3. Try to install Windows 3.11
4. See crash and error messages around 90% through.

**Expected behavior**
Setup should complete without crashing.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - 86Box version: 4.0 build 5000
 - Build information: old dynamic recompiler, x86

**Additional context**
Tried with 2 different configs, same result. Config File Attached for Test Machine 2 (Test Machine 1 uncaptured and erased)

[86box.txt](https://github.com/86Box/86Box/files/12479716/86box.txt)

**Comment by OBattler** [comment] 2023-09-01 05:04
I can't reproduce this at all.

**Comment by Xuser641** [comment] 2023-09-01 17:29
Oh, OK... what could be wrong then?

**Comment by cigaryno** [comment] 2023-09-01 19:00
What is your VM configuration for reference?

**Comment by OBattler** [comment] 2023-09-01 19:07
I used Xuser641's 86box.cfg.

**Comment by OBattler** [comment] 2023-09-09 17:41
I would say this has been fixed with the PIC commit.

**Closed by OBattler** 2023-09-09 17:41 UTC
Labels: bug
