### ISSUE TITLE
Mylex 486 645mb hard disk  recognized by DOS as 424mb.

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1431] opened 2021-05-06 23:17 UTC
**Describe the bug**
I created a 645mb hard disk (type 47) on the Mylex 486. The hard disk works right but it's recognized as 424mb hard disk instead as 645mb. I'm ussing MS-DOS 6.2 which supports up to 2gb hds.

**To Reproduce**
1. Create a 645mb disk
2. Enter setup of the Mylex 486.
3. Boot from DOS floppy disk
4. Create the HD partition with DOS FDISK command or use an MS-DOS installation disk.

Also I add the HD, if anyone want to test it:
[Mylex 486 HD  type 47.zip](https://github.com/86Box/86Box/files/6438062/Mylex.486.HD.type.47.zip)

**Expected behavior**
This disk should be recognized because the BIOS supports it. I think the 1024 cylinder limit still exist in 486 machines.

**Screenshots**

![Mylex 486](https://user-images.githubusercontent.com/31600563/117376306-3fe9f200-aea7-11eb-8ca7-7b329f03aeb3.png)

![645MB HD](https://user-images.githubusercontent.com/31600563/117376322-46786980-aea7-11eb-8dd4-6550a4034ec9.png)

![Chkdsk](https://user-images.githubusercontent.com/31600563/117376373-6314a180-aea7-11eb-98d3-92dd73fccf4e.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - 86Box version: 3.0.0.2983
 - Build type: Dev

**Additional context**

I have an unrelated question: Now the 486 machines are divided according the CPU socket types used by the motherboards.
But all 486 machines support all clock frequencies. But, the Mylex 486, for example, supports only 16,20,25,33 and 50mhz (DX1?) CPUs.
The same happens to early 1991 486 BIOS machines.

**Comment by ppgrainbow** [comment] 2021-05-06 23:31
As far as I know, the BIOS in these 486 motherboards made in 1992 (ASUS ISA-486, Chaintech 4xxSX/SC) as well as the Mylex MV486 only support up to 1,024 cylinders, 16 heads and 17 sectors per track for a maximum total of 504 MB per drive.

As for the Socket 2-based 486 emulated motherboards, they should be limited to a 66 MHz 80486 DX2. Only Socket 3-based 486 emulated motherboards support CPU speeds 75 MHz to 133 MHz.

**Comment by OBattler** [comment] 2021-05-06 23:42
504 MB is 1024/16/63, not 1024/16/17, but in any case, yes, a lot of these old BIOS'es are limited to that and do not yet support LBA. You may be able to input whatever CHS you like, but DOS is going to see it within CHS limits, in this case, 1024/15/54, which is exactly the size your DOS is seeing.

> This disk should be recognized because the BIOS supports it.
Which is a fallacious assumption -  just because you can enter any arbitrary value, that doesn't mean the BIOS actually supports it.

> But all 486 machines support all clock frequencies.
Because we haven't gone through that yet. We're going to.

Anyway, I'm closing this as not a bug.

**Closed by OBattler** 2021-05-06 23:42 UTC
Labels: bug
