### ISSUE TITLE
[linux] 86Box-Linux-x86_64-b3602.AppImage permission denied

### ISSUE THREAD

**Issue by arrowgent** [86Box/86Box#2158] opened 2022-02-21 17:34 UTC
**Describe the bug**

permission denied when run

**To Reproduce**
```
chmod +x 86Box-Linux-x86_64-b3602.AppImage 
./86Box-Linux-x86_64-b3602.AppImage 
APPRUN_ERROR: Permission denied
```

**Expected behavior**

application starts
does not require `SUDO`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - 86Box version: 86Box-Linux-x86_64-b3602
 - Build information: [x86_64

**Additional context**
Add any other context about the problem here. If you are using an Optimized build, make sure to try the regular build too before filing a bug report!

first time downloading and running

**Comment by arrowgent** [comment] 2022-02-21 17:43
```
chmod +x 86Box-Linux-x86_64-b3602.AppImage
./86Box-Linux-x86_64-b3602.AppImage --appimage-extract
cd squashfs-root
./AppRun
```

`APPRUN_ERROR: Permission denied`

same error

**Comment by ata-star** [comment] 2022-03-06 18:22
current build on recent Linux Mint works for me

**Comment by richardg867** [comment] 2022-10-24 22:30
Probably related to #2159, which I saw first.

Your Ubuntu setup has something incredibly cursed going on. I don't know if it's `/tmp` on a separate filesystem that is mounted as `noexec`, or you're trying to run the AppImage under `firejail`; whatever it is, it's not right. I even tried running the latest build on Ubuntu 18.04.0 (vs. 18.04.6 on #2159) and it started fine.

Also closing this one as cannot reproduce. If you're still trying to run 86Box and haven't moved on to another distribution or emulator, I highly suggest that you extract the AppImage, run `strace ./AppRun` and provide a full log.

**Closed by richardg867** 2022-10-24 22:30 UTC
Labels: bug
