### ISSUE TITLE
Pcchips m579

### ISSUE THREAD

**Issue by TechGuyC** [86Box/86Box#3692] opened 2023-09-16 12:17 UTC
**Describe the bug**

The emulated motherboard Pcchips M579 has 2 Bugs

1-The power supply is AT instead of ATX

2-Sometimes when "Del" is pressed during bios post it dosen't go to the config screen and freezes

**To Reproduce**

1-For the Bios post error:
Start the emulator with the Pcchips M579 config,then press Del

2-For the power supply error:
If you are using windows 95,98,ME,XP on the emulator,click on start,
then click the shutdown option and turn off the computer

**Expected behavior**

1-The bios should go to the config when del is pressed

2-The motherboard should power off automatically,because the motherboard
is in the super socket 7 List and all the other super socket 7 motherboards power off automatically

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Windows 11
 - 86Box version 4.0
 - Build information:[x86_64,New Dynarec]

**Additional context**
The "Del" error also happens in the Pcchips M729 motherboard

**Comment by pankoza2-pl** [comment] 2023-09-16 18:57
another bug: PCI Video Cards are not working on this board while they work on the real thing

**Comment by pankoza2-pl** [comment] 2023-09-16 18:59
also, it doesn't power off automatically because BIOS does not support ACPI despite the Chipset supporting it, because PCChips was known for poorly designing their boards and BIOSes

**Comment by TechGuyC** [comment] 2023-10-02 16:34
Also,Windows 98 does not shutdown in the Pcchips M729,but instead of showing "now it's safe to turn off your computer",
it is stuck on the windows 98 logo with the message "Windows is shutting down"

**Comment by OBattler** [comment] 2023-10-04 03:12
We can't fix the shutdown thing - it's a PCChips'ism and most likely, also occurs on real hardware.

**Comment by OBattler** [comment] 2023-10-04 23:36
The PCI graphics cards problem is now fixed - ALi M1543(C) relocatable IDSEL was causing the PCI graphics card's PCI mapping to get clobbered, now that no longer happens. I can't reproduce the DEL problem, and the AT power supply is NOTABUG - the current behavior is for an AT power supply, but I'm going to be looking into implementing the ATX ACPWR SMI# in 4.1.

**Closed by OBattler** 2023-10-04 23:36 UTC
Labels: bug

**Comment by borisvolk117** [comment] 2023-10-05 04:11
The orignal motherboard has both ATX and AT connector, so it maybe expects AT behavior.
https://theretroweb.com/motherboard/image/m579-front-607da2716b8dc045980074.jpg
