### ISSUE TITLE
Voodoo 2 is broken since build 2648

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#1137] opened 2020-11-30 12:03 UTC
**Describe the bug**
In build 2647, Quake 2 for DOS starts and works fine with Voodoo 2 SLI 1024x768:

![2020-11-30_131710](https://user-images.githubusercontent.com/58270614/100605871-40d39200-3311-11eb-918d-cb8a0c9fa049.png)

In build 2648, Quake 2 for DOS will no longer start (error message) with Voodoo 2 SLI 1024x768:

![2020-11-30_132956](https://user-images.githubusercontent.com/58270614/100605913-50eb7180-3311-11eb-807b-2e648e559b9e.png)

In the latest build, Quake 2 for DOS is already started with Voodoo 2 SLI 1024x768, but artifacts are visible in the image:

![2020-11-30_132611](https://user-images.githubusercontent.com/58270614/100605930-58127f80-3311-11eb-92c3-8251de9bcf84.png)

**To Reproduce**
1. In 86Box create a DOS 6.22 machine with Voodoo 2 SLI 8MB
2. Download Quake 2 for DOS: http://dk.toastednet.org/Q2DOS/
3. For Voodoo 2, copy the glide3x.dxe file from the voodoo\cvg folder to the game folder from the archive Q2DOS_EXE_Latest.7z
4. Add the game resource files from the full version of Quake 2 to the baseq2 folder
5. Run Q2.exe
6. Set parameters in the game:
    graphics renderer [3Dfx OpenGL]
    video mode [1024x768]
7. See error

**Expected behavior**
The image should be without artifacts, as in build 2647

**Desktop (please complete the following information):**
- OS: Windows 10 Pro x64 v2009
- 86Box v3.00 build 2694
- Build type: regular

**Comment by OBattler** [comment] 2020-12-04 05:56
Does the Voodoo 2 problem also happen with PCem?

**Comment by maximus105** [comment] 2020-12-04 08:52
PCem 17 also shows artifacts on Voodoo 2 SLI:

![2020-12-04_104313](https://user-images.githubusercontent.com/58270614/101142156-e773a780-361d-11eb-88ea-ee15fb2138f9.png)

**Comment by JimboMumbo** [comment] 2022-07-02 19:25
maybe we could revisit voodoo2 spec ref sheet to correct the problem, but it's impossible to fix the corrupted textures like that (ex, Midtown Madness). maybe sooner. veeery soon.

**Comment by maximus105** [comment] 2022-07-26 16:12
Artifacts in Quake 2 for DOS on Voodoo 2 SLI 1024x768 have changed in the latest build. These artifacts are also present on Voodoo 3.
![2022-07-26_190133](https://user-images.githubusercontent.com/58270614/181055180-ac2bb7d1-3969-4ea9-bc43-dac370d6dd15.png)

**Comment by Maxpointe** [comment] 2022-09-01 17:13
Hi,

Still have the issue with Voodoo 2 DX5 or DX6 driver in build 4079...
![issue](https://user-images.githubusercontent.com/38501264/187973033-75f924c7-c4c0-4fe3-9a24-106640322548.png)

I'm not in SLI. It's sad because it's fast.

**Comment by maximus105** [comment] 2022-11-04 14:46
Issue not fixed.
In Quake 2 for DOS with Voodoo 2 SLI 1024x768 has artifacts in build 4224:
![2022-11-04_163757](https://user-images.githubusercontent.com/58270614/200002884-49e42e2c-c123-4bb8-b6ff-5544e876d27c.png)

In Quake 2 for DOS with Voodoo 2 SLI 1024x768 everything is fine in build 2647:
![2022-11-04_163216](https://user-images.githubusercontent.com/58270614/200002959-dd30f6cc-64cc-4ad6-9356-30d8c1483af0.png)

**Comment by Maxpointe** [comment] 2022-11-04 17:15
Seems ok in build 4226 with Voodoo2 SLI but in 800x600 (Tonic Trouble was working well in 4224) :

![image](https://user-images.githubusercontent.com/38501264/200036166-6ff76048-ccad-4891-83aa-81ba4b3364a8.png)

**Comment by AITUS95** [comment] 2022-11-04 17:47
ok for me too with same settings ..
![Monitor_1_20221104-182920-67067](https://user-images.githubusercontent.com/48457684/200041820-03505d4d-fcb9-43a9-bd9b-0168f0aa82ee.png)
![Monitor_1_20221104-182936-673673](https://user-images.githubusercontent.com/48457684/200041843-9aa0604e-a5bc-4f0f-b030-d76816f1a540.png)

**Comment by maximus105** [comment] 2022-11-05 05:59
You need to run Quake 2 for DOS, not Quake 2 for Windows. These are different games. And in Quake 2 for DOS you need to enable trilinear texture filtering.

**Comment by maximus105** [comment] 2022-11-10 07:20
Issue not fixed. The issue needs to be reopened.

**Comment by OBattler** [comment] 2022-11-10 15:03
Can you upload your VM with Quake 2 for DOS?

**Comment by maximus105** [comment] 2022-11-10 17:13
https://drive.google.com/file/d/1qSRRPM1B8f0xdWEz7uAhfHNklk0UL3A7/view?usp=share_link

**Comment by jriwanek** [comment] 2022-11-12 20:38
@maximus105 
![Monitor_1_20221112-152936-793793](https://user-images.githubusercontent.com/3143407/201493620-a5b9891d-82d7-435f-9dc9-4fe6c8986574.png)

Tested on build 4224, your VM, no settings changed, did make sure that trilinear and 1024x768 were set though, the above pic is from that test, also tested on build 4262, also no visible issues, I suggest you update your graphics drivers and make sure they're compatible with the renderer you used (QT - OpenGL).

**Comment by jriwanek** [comment] 2022-11-12 22:19
Okay, thanks to Richard, I *finally* found a way to reproduce the problem, turns out it happens on the x64 build of 86box, which you neglected to mention you were using. For now as you're not using a large amount of RAM, you can switch to the 32 bit build of 86box, for note, unless you're using very large amounts of RAM in your guest, there's no practical benefit to using the x64 build.

**Comment by Siggy122** [comment] 2022-12-23 20:13
I have Broken texture with Voodoo 2 on Midtown Madness in a 86box Windows 98 machine

**Comment by TC1995** [comment] 2022-12-23 20:18
siggy122, build of 86box? Same as the report?

**Comment by Siggy122** [comment] 2022-12-23 20:27
> siggy122, build of 86box? Same as the report?
Yes!
![image](https://user-images.githubusercontent.com/37003955/209402525-ac323222-bab6-4849-9e1d-23e8b09e7d86.png)

and there is also some strange colored (in case) "." dot on top of all ingame menu screen

![image](https://user-images.githubusercontent.com/37003955/209402741-a965d98d-0882-4b7a-a253-9aefed78e858.png)

**Comment by Siggy122** [comment] 2022-12-23 20:38
> siggy122, build of 86box? Same as the report?

I'm Sorry the build is the latest "4311" as screenshoot
filename "86Box-Windows-64-b4311.zip"

**Comment by TC1995** [comment] 2022-12-23 20:39
probably the 64-bit dynarec, use the x86 (32-bit one).

**Comment by Siggy122** [comment] 2022-12-23 20:47
with the 32 bit version filename "86Box-Windows-32-b4311.zip" it works now but still I get those strange pixel "." blinking on ingame menu and ingame

**Comment by OBattler** [comment] 2023-01-26 04:43
Closing this because the remaining bug has been determined to be exclusive to x64 builds of 86Box and now has its own, separate issue here: https://github.com/86Box/86Box/issues/2923 .

**Closed by OBattler** 2023-01-26 04:43 UTC
Labels: bug
