### ISSUE TITLE
Tale of Peter Rabbit - Sound Blaster 16 option missing voices

### ISSUE THREAD

**Issue by ualaa1** [86Box/86Box#4683] opened 2024-08-03 02:35 UTC
### What happened?

In the SETUP program, when configuring the game to use Sound Blaster 16 ASP and entering the game afterwards using PETER, it gives a warning about sound outputs not working correctly.  While music plays, voices do not play at all. It works correctly when configuring to Sound Blaster Pro instead
In order to test it, go into game after configuring sound, and select the read to me option. There should be a female narrator if it works correctly.
Files are here (NVR, HD, Settings), game is in directory Peter: https://files.catbox.moe/0w4kuk.7z

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
emu_build_num = 6000
uuid = 8ec07f16-0be1-5a53-9f7b-3745a1048a10
sound_gain = 18

[Machine]
machine = 486sp3g
cpu_family = pentium_p24t
cpu_speed = 83333333
cpu_multi = 2.5
cpu_use_dynarec = 1
fpu_softfloat = 0
time_sync = local
fpu_type = internal
mem_size = 32768

[Video]
gfxcard = trio64v2dx_pci

[Input devices]
mouse_type = ps2

[Sound]
fm_driver = nuked
sndcard = sbawe32
midi_device = fluidsynth
mpu401_standalone = 1

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
fdc = none
hdc = none
cassette_mode = load

[S3 Trio64V2/DX PCI]
memory = 4

[Sound Blaster AWE32 #1]
base = 0220
emu_base = 0620
base401 = 0000
irq = 5
dma = 1
dma16 = 5
onboard_ram = 28672
opl = 1
control_pc_speaker = 0
receive_input = 1
receive_input401 = 0

[FluidSynth]
sound_font = C:/Users/19099/Desktop/em/dos3/SC-55.SoundFont.v1.2b.sf2
output_gain = 10
chorus = 1
chorus_voices = 3
chorus_level = 20
chorus_speed = 30
chorus_depth = 80
chorus_waveform = 0
reverb = 1
reverb_room_size = 20
reverb_damping = 0
reverb_width = 5
reverb_level = 90
interpolation = 2

[Hard disks]
hdd_01_parameters = 63, 16, 4063, 0, ide
hdd_01_fn = big hd.vhd
hdd_01_vhd_blocksize = 4096
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2ed
fdd_02_type = 35_2ed
fdd_02_turbo = 1
cdrom_01_speed = 72
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 0:1
fdd_01_image_history_01 = FIre.img
fdd_01_image_history_02 = disk1.img
fdd_01_image_history_03 = Disk06.img
cdrom_01_image_history_01 = peter
fdd_01_image_history_04 = cspu.IMA
cdrom_01_image_history_02 = Games/Detritus - The Daemon's Quest (1996)(Manyk).iso
cdrom_01_image_history_03 = Games/Inherit the Earth.cue
cdrom_01_image_history_04 = Games/Shakii the Wolf.CUE
cdrom_01_image_path = Games/Kids Can Read! The Tale of Peter Rabbit (USA) (En,Es).cue
cdrom_01_type = 86BOX_CD-ROM_1.00
```

### Operating system

Windows 11

### CPU

Intel Core i7-9750H 

### 86Box version

4.2 build 6000

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

Warning Screenshot when configured to use Sound Blaster 16 ASP:
![Monitor_1_20240802-192353-077](https://github.com/user-attachments/assets/924524c5-9e79-4a03-87a4-419feb298589)

**Comment by eddmanx** [comment] 2024-08-03 14:40
I'm not sure but it's possible something is wrong with the game itself. During the installation of the game, if you pock SB 16 ASP, it correctly fills out the KA.CNF file and sound works properly.

```
SoundDevice    : SoundBlaster 16ASP
AutoRead       : On 
Music          : On
DigitizedSound : On 
ExtraMemory    : Automatic
MusicDevParams : A220
SoundDevParams : A220 I5 D1
```

However, if you use the SETUP program and change the sound device to something else and then change it back to SB16 ASP, then the **MusicDevParams** and **SoundDevParams** fields would be empty, and hence it'd fail to detect the card properly.

If you manually fill out those two fields, then it'd work properly again.

P.S.

In any case, it seems your game files are bad. The game freezes on the third screen although the music keeps playing. I've tried my own files and it doesn't freeze.

**Comment by ualaa1** [comment] 2024-08-03 15:53
I have changed the files in the link to a version that seems less glitchy.

**Comment by eddmanx** [comment] 2024-08-03 16:16
> I also ran a quick test with Dosbox-X and it doesn't seem to happen after changing the setup to Soundblaster Pro and then back to Soundblaster 16. Voices still working and no warning on prompt

What's the IRQ in Dosbox-X?

P.S. Are you on the 86box discord server? It'd be much faster to discuss these issues over there.

**Comment by ualaa1** [comment] 2024-08-03 16:57
I believe Dosbox-X by default uses IRQ 7. 86Box uses IRQ 5
Proof that Dosbox-X works: https://files.catbox.moe/1wpjr5.mp4

**Comment by eddmanx** [comment] 2024-08-03 17:18
I don't doubt Dosbox-X works; the game works fine in 86box too when SB16 is set to IRQ 7, even after using the SETUP tool. This looks like a game bug.

To make sure, In Doxbox open the KA.CNF file and see if the fields are empty. If they are, then it's pretty much confirmed.

**Comment by TC1995** [comment] 2024-08-03 17:19
or, to verify that dosbox-x is not cheating, just boot off a vhd/raw hdd within said emulator (dosbox-x).

**Comment by TC1995** [comment] 2024-08-03 17:51
Ok, situation is normal, it defaults to irq 7 in the setup.

**Comment by OBattler** [comment] 2024-08-03 17:51
Then this can be closed as NOTABUG - it works with IRQ 7 on both DOSBox-X and 86Box, breaks with another IRQ, and it has been determined to default to IRQ 7 in Setup.

**Closed by OBattler** 2024-08-03 17:51 UTC
Labels: bug

**Comment by eddmanx** [comment] 2024-08-03 21:54
It does work with other IRQs besides 7 if you manually add it to the game's setup config file, but yea, for some reason it fails to fill the IRQ field at all and leaves it blank, which causes it to fallback to the hardcoded default, IRQ 7.
