### ISSUE TITLE
Amstrad 3086: Internal XTA-IDE controller and mouse type

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1516] opened 2021-06-30 15:08 UTC
**Is your feature request related to a problem? Please describe.**

Actually is related to: 

1. The addition of the internal XTA-IDE to Amstrad 3086. According this web page [https://www.seasip.info/AmstradXT/models.html#pc3086](url) This site was creted by John Elliot, the user who included some patches in PCem.

2. The Amstrad 3086 not seem to have the internal XT mouse controller like the models 1512,1640 and 2086 have. 

I think so because the OEM software included with Amstrad 1512,1640 and 2086 all the three have the same mouse driver (ver 5.00b) despite having different software but not in the DOS 3.30 for the 3086. (The Amstrad 2086 includes DOS 3.3 and Win 2.0).
On the other hand Amstrad decided, for the 3086,3286 and 3386 to include the software for these three models only one package with DOS 3.30. This does not include the any mouse driver, but include a version of DEVICE.COM for 3086 (similar to the included in 2086), but the same disk includes a SETUP.EXE for AT based Amstrad.
 
3. When I use the Serial Mouse on the 3086:

a. The Microsoft Mouse driver 7.04 does not detect the Mouse when serial mode.
b. The Amstrad Mouse Driver, also  detects the mouse driver but does not respond
c. The CuteMouse v1.9 detects and works fine with the Mouse
d. Geoworks v1.2 works just fine with the internal serial mouse driver.

Amstrad DOS 3.30 for the 3086/3286/3386:
[System DiskAmstrad PC3x86.zip](https://github.com/86Box/86Box/files/6741844/System.DiskAmstrad.PC3x86.zip)

Mouse drivers:
The Mouse.com/sys files are Miscrosoft seial mouse ver 7.04. The \amstrad subdirectory includes the Amstrad ver 7.04 mouse.
[Mouse.zip](https://github.com/86Box/86Box/files/6741938/Mouse.zip)

Screenshots: 

![Amstrad 3086 001](https://user-images.githubusercontent.com/31600563/123984582-1fb44c00-d99b-11eb-9f3e-bcbb5cb73914.png)

![Amstrad 3086 002](https://user-images.githubusercontent.com/31600563/123984586-20e57900-d99b-11eb-82b1-6883266eacd4.png)

**Comment by OBattler** [comment] 2024-02-18 11:36
Closing since this is a duplicate of #1296.

**Closed by OBattler** 2024-02-18 11:36 UTC
Labels: feature
