### ISSUE TITLE
ESDI-formatted HD fails to boot on ECS 386/32

### ISSUE THREAD

**Issue by DJSaunders03** [86Box/86Box#4784] opened 2024-09-02 06:32 UTC
### What happened?

I was using an ESDI hard drive with the Western Digital WD1007V-SE1 ESDI controller with the Elitegroup ECS 386/32 motherboard in 86Box.

After I set the BIOS configuration, I went ahead and created a DOS partition with which I'd format the hard drive, and I also made sure to transfer the system to the hard drive. After I copied all the files over and ejected the floppy, I restarted the machine.

It was supposed to boot from the ESDI hard drive from here on out. Instead, it displayed a "Disk Boot Failure" error.

I initially believed that I needed to also do low-level formatting of the hard drive in addition to the DOS formatting, so I used WDFMT (Western Digital FORMAT) to format the drive, and I used the WD1007V-SE1 manual as a guide. After that, I installed MS-DOS as normal and did high-level formatting with it. I was hoping this would get the motherboard to recognize the ESDI drive once this was done. After the system was transferred to the hard drive and all the DOS files were copied over... same result.

However, the motherboard _is_ able to recognize MFM/RLL, IDE, and SCSI hard drives with no issue after the DOS install and the system transfer.

### Configuration file

```ini
[General]
vid_renderer = qt_software
host_cpu = Intel(R) Pentium(R) CPU G3260T @ 2.90GHz
emu_build_num = 6130
uuid = 08d5eb8d-8a03-5baf-8724-492ccea9e133

[Machine]
machine = ecs386
cpu_family = i386dx
cpu_speed = 20000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
cpu_waitstates = 1
fpu_type = 387
mem_size = 3072

[Video]
gfxcard = pvga1a

[Input devices]
mouse_type = msserial

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = esdi_at
cassette_mode = load

[Paradise PVGA1A]
memory = 256

[Hard disks]
hdd_01_parameters = 17, 15, 1224, 0, esdi
hdd_01_esdi_channel = 0
hdd_01_fn = vhd01.vhd
hdd_01_speed = 1989_3500rpm

[Floppy and CD-ROM drives]
fdd_01_type = 525_2hd
fdd_02_type = none
```

### Operating system

Windows 10

### CPU

Intel Pentium G3260T

### 86Box version

v4.2.1 build 6130

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

This issue was tested by @ppgrainbow in the 86Box Discord server, and on ppgrainbow's end, the motherboard also failed to boot off of an ESDI hard disk.

**Comment by OBattler** [comment] 2024-09-02 15:07
1. We don't know if it's an 86Box bug, a BIOS bug or what it is.
2. Was my suggestion of not setting the hard disks in CMOS setup tried?
3. It's a known bug, if I haven't fixed by now, it's because I found no way of fixing it.

**Comment by OBattler** [comment] 2024-09-02 17:57
Confirmed - the ECS AMI BIOS is crap and doesn't care about option ROM's (other than the video BIOS) at all. Therefore, I'm closing this as NOTABUG.

**Closed by OBattler** 2024-09-02 17:57 UTC
Labels: bug
