### ISSUE TITLE
SDL Software Performance Issue

### ISSUE THREAD

**Issue by Fanta-Shokata** [86Box/86Box#1937] opened 2021-12-15 19:40 UTC
**Describe the bug**
I'm experiencing some odd performance issues running with SDL Software renderer. Emulating 386DX, when I'm launching a program or game from floppy or hard drive, title bar shows around 81-84% in the title bar. With PCem I have no issues emulating 386DX machine. I've tried playing with waitstates but no luck this time.

**Steps to reproduce**

Choose 386DX processor emulation in the settings, select SDL Software renderer, booting any app or game from any floppy or hard drive.

**Desktop**

- OS: Windows 10 Home 21H1 64-bit
- 86Box version: 3.0.0.3333
- Build information: regular

**Comment by TC1995** [comment] 2021-12-15 19:55
Well, we aim for accuracy, it might be this that decreases the speed.

**Comment by Fanta-Shokata** [comment] 2021-12-15 21:30
This issue didn't happen for me in 86Box 2.07.

**Comment by OBattler** [comment] 2021-12-16 00:43
I can't reproduce this at all. I can emulate a 386DX just fine. Try changing the renderer.

**Comment by Fanta-Shokata** [comment] 2021-12-16 10:58
I've tried changing renderer but this didn't help.

**Comment by OBattler** [comment] 2021-12-16 11:09
What is your host CPU?

**Comment by Fanta-Shokata** [comment] 2021-12-16 12:13
Intel Celeron 1005M 1,9 GHz

**Comment by Cacodemon345** [comment] 2021-12-16 12:19
That is a very weak CPU to run the software renderer on.

**Comment by Fanta-Shokata** [comment] 2021-12-16 12:33
But I didn't have any performance problems with SDL software renderer on early builds of 86Box 3.0.

**Comment by Cacodemon345** [comment] 2021-12-16 12:34
Still such weak CPUs are usually combined with a comparably strong GPU.

**Comment by Fanta-Shokata** [comment] 2021-12-16 12:47
I've tried OpenGL renderers and I have the same effects.

**Comment by OBattler** [comment] 2021-12-16 12:55
Can you find out which exact build of 86Box introduced the problem?

**Comment by Fanta-Shokata** [comment] 2021-12-16 13:10
This happened somewhere between February and December 2021

**Comment by OBattler** [comment] 2021-12-16 13:26
Yes, but I need to know the exact build so I can determine what caused it.

**Comment by Fanta-Shokata** [comment] 2021-12-16 13:33
I forgot the exact build.

**Comment by OBattler** [comment] 2021-12-16 13:53
Well, find it out. We have every single build on Jenkins, so you can just download from there.

**Comment by Fanta-Shokata** [comment] 2021-12-16 14:07
This was 86Box Milestone build.

**Comment by OBattler** [comment] 2021-12-16 14:20
Please download the old builds and test them one by one to determine in which exact build does the performance decrease.

**Comment by Fenix770** [comment] 2021-12-16 22:10
Hello. I write to here to say I tested two years ago 86box on Celeron B800 (dual-core at 1.5 ghz) it can emulate a 486 DX/33 with dynamic recompiler. I didn't test any 386, but 386 does not have a dynamic recompiler option so the slowdown can exist.

**Comment by Fanta-Shokata** [comment] 2021-12-16 22:20
Unfortunately issue exists in every build I've tried.

**Comment by OBattler** [comment] 2021-12-17 00:38
Then I would like an explanation of how on Earth that is possible, given that that commit only changed machine files and therefore could in no way have affected performance.

**Comment by OBattler** [comment] 2021-12-17 00:41
If you are using the 497.09 WHQL version of the Nvidia drivers, downgrade to an older version, as it has now been found out that that version degrades 86Box performance.

**Comment by Fanta-Shokata** [comment] 2021-12-17 10:29
I don't even have NVIDIA graphics card.

**Comment by OBattler** [comment] 2021-12-21 00:58
What graphics card do you have then?

**Comment by Fanta-Shokata** [comment] 2021-12-21 11:45
Intel HD Graphics

**Comment by OBattler** [comment] 2021-12-21 11:55
Have you actually tried the latest builds of 86Box since I have done some performance-improving changes since then?

**Comment by Fanta-Shokata** [comment] 2021-12-21 16:45
Still no improvement.

**Comment by OBattler** [comment] 2021-12-23 10:35
Then I have no idea what's wrong. It's clearly not the emulator, also because the build you identified as supposedly being the first one with the issue, did absolutely no changes that could have caused it.

**Comment by Fenix770** [comment] 2021-12-28 14:08
I recently discovered a serius performance issue. in the last 3402 commit. The render are using an huge amount of GPU power.
Tested on both Interl HD4400 and Nvidia 820M. 

It uses about 20% of GPU for software render about 45% for hardware and OpenGL regardless of the emulated machine. I have not tested OpenGL 3.0 yet. It is a lot for a simple 8086/8. Performance degradation is noticeable with a 486 DX/2 50 even with the dynamic recompiler enabled.
![high CPU usage](https://user-images.githubusercontent.com/31600563/147574332-63bbc0c6-4eae-445a-b240-9ba86684d48a.png)

**Comment by ts-korhonen** [comment] 2021-12-28 15:44
@Fenix770 can you double check that by trying with both 3401 and 3402? According to the changelog 3402 only updated Japanese translation and that should not have such effect.

**Comment by Fenix770** [comment] 2021-12-28 20:47
No. It also affects build 3333. I'll check older commits

**Comment by Fenix770** [comment] 2021-12-28 20:51
Amstrad 3086 crash after loading Norton commander 3.0 on bulid 3307.

**Comment by Fenix770** [comment] 2021-12-28 21:06
The GPU usage is 15% with Hardware/OpenGL on commit 3100 which seems correct to me. But the Amstrad and other XT problems with Geoworks is still present. I think is not realted to WD XTA-IDE because the same happens with ST-RLL controller on commit 3100.

![Amstrad 3086 ST-RLL](https://user-images.githubusercontent.com/31600563/147607062-1b8b341e-3726-4f59-813d-94f27d3d1376.png)

![Asmtrad 3086 on 3200-3250 commits](https://user-images.githubusercontent.com/31600563/147607070-15eb1679-c1c2-408c-8be3-a78975d61f57.png)

**Comment by OBattler** [comment] 2021-12-28 21:39
So which exact build between 3100 and 3307 caused this?

**Comment by Fenix770** [comment] 2021-12-29 13:52
The render issue is present 3250 but not in 3200. So the bug must be one betwwen them. I also found a graphics garbage on Amstrad on commits 3100, 3150 and 3170. The "bad handler error" with Geoworks and XT machines may be much older.

**Comment by OBattler** [comment] 2021-12-29 15:23
So which exact build between 3200 and 3250 caused the render issue?

**Comment by Fenix770** [comment] 2021-12-29 18:11
I'll check them be patient.

**Comment by Fenix770** [comment] 2021-12-29 18:54
I found it. The render problem appeared in commit 3228. The 3228 doubles the GPU usage. The performance degradation may be not noticeable on slower 286/386.

![Commit 3228](https://user-images.githubusercontent.com/31600563/147694290-902ccc86-ff90-4784-8e83-49213d084aed.png)

![commit 3227](https://user-images.githubusercontent.com/31600563/147694303-ed9cbf0a-b01d-4ec4-a5f8-c0a85116f8fd.png)

**Comment by OBattler** [comment] 2022-01-06 13:20
I'm closing this since this is now fixed.

**Closed by OBattler** 2022-01-06 13:20 UTC
Labels: bug
