### ISSUE TITLE
[Color400] cursor sometimes disappears

### ISSUE THREAD

**Issue by waltje** [86Box/86Box#331] opened 2018-10-25 07:16 UTC
On (at least) the AMI 286 Clone machine, in (standard) text80 mode,
the cursor sometimes seems to disappear after the DOS prompt is
displayed.

Typing a(ny) character will show it again.

Oh. I just noticed its every other character, really.  Something to do with that comment about
'half the size' ?

**Comment by OBattler** [comment] 2018-10-25 17:03
It could be, I have no idea. I'm still waiting for someone to compile me a build of PCem with the Sigma in so I can see if such issues occur there are as well or are caused by my adaptation to 86Box.

**Comment by OBattler** [comment] 2018-11-03 11:47
OK, this is now fixed in the latest commit.

**Closed by OBattler** 2018-11-03 11:47 UTC

**Comment by waltje** [comment] 2018-11-03 23:32
Confirmed.

--------------------------------------------
On Sat, 11/3/18, OBattler <notifications@github.com> wrote:

 Subject: Re: [86Box/86Box] [Color400] cursor sometimes disappears (#331)
 To: "86Box/86Box" <86Box@noreply.github.com>
 Cc: "Fred N. van Kempen" <decwiz@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Saturday, November 3, 2018, 7:47 AM
 
 OK, this is now fixed in the
 latest commit.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.
