### ISSUE TITLE
emulation of AAM opcode

### ISSUE THREAD

**Issue by Baron-von-Riedesel** [86Box/86Box#2551] opened 2022-08-01 12:01 UTC
**Describe the bug**
The x86 AAM opcode is usually regarded as a part of the BCD arithmetic - it converts, as an example, the value 34h ( which is 52 in decimal ) in AL to 0502h in AX, so the 2 decimal digits are now separated in 2 8-bit registers.

However, there is a semi-documented feature hidden in this instruction: the AAM opcode is encoded as "D4h 0Ah", and the second byte is kind of an argument. If one modifies "D4h 0Ah" to "D4h 10h", this modified instruction ( let's call it "AAM 10h" ) will again separate 2 digits in AL, but this time not interpret them as decimal, but as hex digits: in the example above, AL=34h will then give the result AX=0304h.

This trick is used in FreeDOS DEBUG.COM ( I'm the maintainer of this little program ) in the line assembler part to optimize size. 

As it has turned out in my tests, 86Box ( v3.7) does ignore the second byte of the AAM instruction and always fills AX with "decimal" digits. Hence FreeDOS debug.com's line assembler is unusable in 86Box.

**To Reproduce**
- install a DOS ( FreeDOS/MS-DOS/DR-DOS )
- copy FreeDOS DEBUG.COM ( attached ) to the HD
- start it
- enter A ( this starts the line assembler )
- enter push 0 ( debug will reject the perfectly valid instruction )

**Expected behavior**
That FD debug.com works as if run on real hardware or emulators like Qemu/DosEmu

[DEBUG.COM.zip](https://github.com/86Box/86Box/files/9233678/DEBUG.COM.zip)

**Comment by OBattler** [comment] 2022-08-01 13:47
Confirmed to work correctly on the emulated Pentium 75: 
![imagem](https://user-images.githubusercontent.com/10365853/182162096-ea9ab932-2d36-44cb-8225-06f7123bc5d3.png)
.

**Comment by OBattler** [comment] 2022-08-01 13:50
Also works correctly on 808x:
![imagem](https://user-images.githubusercontent.com/10365853/182162918-f44cea3f-5abf-437b-905f-c853cb8e16ed.png)
.

**Comment by OBattler** [comment] 2022-08-01 13:52
> enter push 0 ( debug will reject the perfectly valid instruction )

If you're trying to do this on 808x, then of course it will reject it, as PUSH imm does not exist on 808x.

**Comment by Baron-von-Riedesel** [comment] 2022-08-01 14:25
Sorry, "push 0" is among the few instructions that are accepted -
"push ax" or "mov ax, 1" are instructions that are not accepted.

**Comment by Baron-von-Riedesel** [comment] 2022-08-01 14:38
> if (!base || !cpu_isintel) base = 10;

A side note: opcode "D4h 00h" ( AAM 00 ) is supposed to generate an exception 00, in all modes.

**Comment by OBattler** [comment] 2022-08-01 18:05
> Well, the K6 is an AMD cpu, and perhaps that's it?

Yes, I think that's it. So that's intended behavior then. Though, I find it rather strange that AMD of all manufacturers, doesn't support this, given that they even had access to the Intel microcode.

Perhaps it's Cyrix and WinChip that are supposed not to?

In any case, I have just written a program that tests this instruction and asked people to run it on real hardware. Once I have enough results, I am going to change the implementation based on them.

**Comment by OBattler** [comment] 2022-08-01 21:41
It has now been verified that AAM with divisors other than 10 are in fact supported on AMD CPU's, the fix has been committed, and AAM now also correctly raises a divide exception when the divisor is 0.

**Closed** 2022-08-01 21:40 UTC
Labels: bug

**Comment by Baron-von-Riedesel** [comment] 2022-08-02 04:00
I can confirm that FD Debug's line assembler now works smoothly.

**Comment by ecm-pushbx** [comment] 2022-08-05 16:20
I disabled the use of `aam 16` in my fork, lDebug, in 2019 precisely because there are machines that do not support it. Reference: https://hg.pushbx.org/ecm/ldebug/rev/d93c10d310a7

**Comment by Diicorp95** [comment] 2022-08-07 21:41
> Sorry, "push 0" is among the few instructions that are accepted -
> "push ax" or "mov ax, 1" are instructions that are not accepted.

AFAIK, quite the opposite. In 808x, you can't `PUSH` a value itself; you can only `PUSH` a register.

The correct code for a 808x CPU is
```asm
mov ax, $ABCD
push ax
```

**Comment by ecm-pushbx** [comment] 2022-08-08 03:09
> AFAIK, quite the opposite. In 808x, you can't `PUSH` a value itself; you can only `PUSH` a register.

This doesn't matter. FreeDOS Debug and lDebug can assemble 186 level instructions regardless of the CPU they are running on. So `push 0` should work, as in should succeed to assemble.

**Comment by Diicorp95** [comment] 2022-08-08 14:19
> FreeDOS Debug and lDebug can assemble 186 level instructions regardless of the CPU they are running on.

For sure. But I'm talking about the 808x processors. The 8080 family could not `PUSH` data that's supplied as an operand.

Source: [Intel documentation, page 78 in this copy](https://edge.edx.org/c4x/BITSPilani/EEE231/asset/8086_family_Users_Manual_1_.pdf).

**Comment by ecm-pushbx** [comment] 2022-08-08 14:48
You misspelled 8086/8088 as "8080" there.

Anyway it doesn't matter to this bug report what instruction set the 808x processors support. I'm not contesting your comments, `push imm8` and `push imm16` certainly are 186+ instructions.

It's just irrelevant because @Baron-von-Riedesel was talking about assembling the instruction in Debug's line assembler, not about executing the instruction. To that end the embedded assembler and **its code** that gets executed matters, not the instruction being fed into it as input text.

**Comment by Diicorp95** [comment] 2022-08-08 17:25
> You misspelled 8086/8088 as "8080" there.

I meant the 8080 family. That includes both 8086 and 8088.
