### ISSUE TITLE
Prince of Persia Freeze during the game

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1156] opened 2020-12-06 00:13 UTC
**Describe the bug**
When playing the game Prince of Persia the Prince moves slowly if it is another objet or enemy guard and freezes during gameplay, it also occurs with CGA and Hercules video modes. In addition to that in several XT based machines is not possible to use the arrow keys to play games and I have to use NUM key pad keys (8,4,6,2). The arrow keys act as letters instead. 

**To Reproduce**
1.Start MS-DOS
2. Put the 720k floppy in drive A
3.Type Prince to start

**Expected behavior**
 I remember playing the game with an XT, with 360kb floppies, and  the arrow keys worked. In AT 286 and later the arrow keys work correctly.

PD: The arrow keys bug is very old
**Screenshots**
![20201205-235033-042](https://user-images.githubusercontent.com/31600563/101267915-d8cfe200-373c-11eb-8306-53b66e1c36b4.png)

Here is the hard disk Image File and Floppy image.
[Amstrad 2086 20mb Xebec Hard Disk.zip](https://github.com/86Box/86Box/files/5648057/Amstrad.2086.20mb.Xebec.Hard.Disk.zip)
[PRINCE OF PERSIA 1.3.zip](https://github.com/86Box/86Box/files/5648058/PRINCE.OF.PERSIA.1.3.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: Latest commit
 - Build type: Regular

**Additional context**
The Harddisk geometry C/H/S is 306/8/17 with a 20mb size and IBM PC 'Xebec' controller. Also, I have the original OEM software for the Amstrad 2086 installed with DOS 3.3 and Windows 2.03.

**Comment by OBattler** [comment] 2020-12-06 07:50
XT keyboards never had arrow keys, except for those on the numpad.

As for the freeze bug, I'm going to look into that.

**Comment by jvernet** [comment] 2020-12-06 08:24
Except that Amstrad 2086/3086 keyboard DO HAVE arrows keys. They are not working under 2086 emulation, nor PPC1512, wich also have arrows keys !

**Comment by daviunic** [comment] 2020-12-06 10:24
@Fenix770 please do not submit issues where you put "latest commit" as the affected 86Box version, because that is not helpful. We display the commit hash and build number in the emulator for a reason (as well as on Jenkins), so next time please submit that information like the issue template tells you to.

**Comment by maximus105** [comment] 2020-12-06 13:02
I tested this on a regular build 2709 in an [8088] American XT Computer. Prince of Persia is freeze at the second level.

**Comment by Fenix770** [comment] 2020-12-06 15:11
I already found the keyboard I had, back in the time. Early keyboards had no arrows unlike latter models. According this Wikipedia article I had a 101-key (Model M) keyboard from 1986, it was not IBM brand but had exactly the same layout. The keyboard had a switch in the back to choose AT or XT modes according with the machine type.

[https://en.wikipedia.org/wiki/IBM_PC_keyboard](url)

Here is a screenshot (altough it is a german keyborad) 
![Keyboard](https://user-images.githubusercontent.com/31600563/101283878-0314b480-37bc-11eb-9de4-3328e789c393.png)

**Comment by Fenix770** [comment] 2020-12-06 15:23
I forgot to mention. The build number I'm using is 57ff5a04.

**Comment by Fenix770** [comment] 2020-12-07 00:54
I found a new bug,  I tested Prince of Persia v1.3, in ADI 386 SX as well as Award 386 DX. After pressing the shift key during the game the Prince always behaves as if the shift key were held all the time an do one on step at once.
I suspect the bug may be related to recent changes made to the AT keyboard emulation.

**Comment by OBattler** [comment] 2020-12-18 21:42
Fenix770, which XT machines to the arrow keys not work? I just fixed them on Tandys, going to fix them on the Amstrads as well now, but for other machines, I have no idea... Olivetti maybe?

**Comment by OBattler** [comment] 2020-12-18 23:10
Fixed them on the Amstrads as well now. Now I just need to know on which XT's exactly they are also broken. I tested them on the IBM XT 1986 and they work fine.

As for the problems on AT+, the AT+ keyboard controller and keyboard emulation is still the old one, so full of bugs. They should be fixed by the rewrite.

Now I'd like to know on which 86Box build the Prince of Persia freezes started happening.

**Comment by Fenix770** [comment] 2020-12-19 00:17
I think almost XT based machines launched after 1986 should have the Model M keyboard. As for Tandy machines I'm not sure if the models 1000 (original) 1000/A and 1000/HD uses the model F keyboard type. If I recall correctly the setup program of  some SCI Sierra games asked the user if the installed keyboard is Tandy 1000 type or IBM compatible.

When running the specific Tandy HX/TX version of Tandy Deksmate in the HX model, some keys (like enter) are in strange places like the "-" key on the numpad.

Maybe a possible solution, for XT machines, would be to let the user to choose either the F or M keyboard when configuring the machine, if the they supports both of them.

As for the Prince of Persia game worked flawlessly on AT machines before. I'll try the PoP game again on Amstrad 2086 and Tandy 1000 SL/2

**Comment by Fenix770** [comment] 2020-12-19 00:58
I have recently tested the game with the Amstrad 2086 and Tandy 1000 SL/2.

On the Amstrad the arrow keys work, but when I try to combine the left or right keys with shift key to do shorter steps it does nothing. The shift key works with the keys 4 and 6 of the numpad.

On the Tandy 1000 SL/2 the arrow keys behaves like the ESC key. In fact, inside the SETUP utility of Prince of Persia the all arrow keys ask If I want to save the configuration before exiting. And during the game the arrow keys put the game on pause like the ESC key.

On both machines a slowdown occurs when two or more objects are in motion. Like when the prince is running and a gate is opening or closing or when both the prince and an enemy guard are fighting. But is much more noticeable on Tandy 1000.
On Tnady 1000 I used Tandy 16 color graphics and Tandy 3-voice and DAC for music.
On Amstrad 2086 I used the built-in VGA graphics.

I played the game as a kid back in the early 90's with an XT clone 1mb RAM, Hercules graphics, and played from 360 KB floppies since that machine had no hard disk. There was no noticeable slowdown during the gameplay, but the loading time was very long.

**Comment by OBattler** [comment] 2020-12-19 11:22
First off, you're comparing an XT clone with Tandy and Amstrad which are not really XT clones.

Now, about the arrow keys on the Tandy - are you sure the game even supports the Tandy arrow keys? They have different scan code from the normal 101/102 key ones, and that might be confusing the game.

About the Amstrad - the arrow keys work as intended. They are supposed to ignore the shift - the arrow keys of a 101/102-key keyboard when used on the XT (or Amstrad) would do that as well. The reason for that is simple - when Num Lock is off, shift+numpad does the numbers, while when Num Lock is on, shift+numpad does the arrow keys and so on. So even a real 101/102-key keyboard, when used on the XT (or Amstrad), has to insert fake shifts, so that arrow keys always behave as arrow keys, regardless of shift and Num Lock. As such, I don't see any way for shift+arrow keys to be a thing in XT mode. In AT mode, yes, it can be because both the arrow keys themselves and the fake shifts are E0-prefixed, so they can be distinguished.

That is, of course, assuming that the arrow keys in XT mode are supposed to ignore shift. I need to verify this behavior.

As for the slowdown, can you see which build exactly introduced the slowdown?

**Comment by OBattler** [comment] 2020-12-19 11:35
I just committed an overhaul of the arrow keys processing code, see if shit+arrow keys work correctly now.

**Comment by jvernet** [comment] 2020-12-19 12:00
To me, arrow keys do not work: they produce number, as if they are mapped to the keypad...
And I move the mouse, it act as if I used the arrows keys...
1512/1640 emulation
Seems to be OK with 2086/3086
With the PPC, work in dos, not in most software like Multiplan

**Comment by OBattler** [comment] 2020-12-19 13:26
According to John Elliott's information that he provided to this site: https://www.win.tue.nl/~aeb/linux/kbd/scancodes-3.html#ss3.1 , the PC1512 and PC1640 had a completely different keyboard that did not have arrow keys.

As for stuff like Multiplan on the PPC512/640, from what I know, the PPC512/640 BIOS seems to be expecting Num Lock to work in reverse (which also affects the the arrow keys where I have to invert the fake shift logic), but that might conflict with Multiplan which expects Num Lock to work normally. Unfortunately, I have no way of fixing that, without figuring out where that BIOS reads the initial state of Num Lock so that that can be fixed.

**Comment by jvernet** [comment] 2020-12-19 13:32
Your right. No arrow keys on Amstrad PC 1512. At least, they should act as keys 4 8 6 2 from keyboard (that is arrow key when not in Num Lock mode). Here, they only act as Num key, whenever Num Lock is active or not.
For the PPC, need to experiment with real hardware.

**Comment by OBattler** [comment] 2020-12-19 15:03
> Here, they only act as Num key, whenever Num Lock is active or not.

Looks like PC1512 (and possibly PC1640?) does not suffer from the "inverted Num Lock" problem. I need to test this.

**Comment by OBattler** [comment] 2020-12-19 15:08
Yes, that is indeed the case. Committed a fix for that now. Now, even the arrow keys work correctly on those two machines.

**Comment by Fenix770** [comment] 2020-12-19 15:56
I tested the last commit you made 3.0.0.2736. At the beginning the game act as if the shift key were held, but unexpectedly after pressing the shift key and num lock, It started to work as before this commit (arrow keys work but not combined with shift).
Unfortunately, I don't remember if shift+arrow keys worked on the real XT clone I had, back in the day.

Also, I found another strange behavior: The game works extremely slow when using 16-color graphics mode:
I tested:

-Amstrad 1640 with EGA video mode
-Tandy 1000 SL/2 with Tandy graphics and 
-Amstrad 2086 with both EGA and VGA video modes. 

The Tandy 1000 run slow but is playable

Both Amstrad machines run *very* slow in EGA  video mode and are nearly unplayable.

The Amstrad 2086 with VGA mode the game run much faster, even faster than the Tandy 1000, despite being (the VGA mode) more demanding.

**Comment by OBattler** [comment] 2020-12-19 16:55
Which build of 86Box introduced the slowness?

**Comment by Fenix770** [comment] 2020-12-19 18:07
There is an old closed post dated 3 Sep 2017. [https://github.com/86Box/86Box/issues/182](url) I mentioned Prince of Persia and other games, which may be led to confusion,  but the slowdown affected the VGA video mode even more than the others.

**Comment by jvernet** [comment] 2020-12-20 10:01
Not yet good for PC1512 numéric keypad. Holding Shift and a number produce twice the keystroke (aka 44 66 55 etc).not everywhere (DOS LINE, GEM, but not RPED)./

**Comment by OBattler** [comment] 2020-12-20 13:06
I noticed that myself as well but I have no idea how to fix it.

**Comment by OBattler** [comment] 2020-12-20 13:31
Fenix770> I'm not sure what causes the slowdown. It's interesting that it doesn't happen on PCem with any CPU and with 86Box with 286+, so it defintiely looks like some 808x instruction is running slower than it should, which makes me thinks there is currently no way to fix this and it's going to have to wait for reenigne to reimplement his 808x emulation according to the microcode and me to then port that to 86Box.

**Comment by OBattler** [comment] 2024-01-14 23:37
Closing this as it's being tracked in https://github.com/86Box/86Box/issues/4044.

**Closed** 2024-01-14 23:39 UTC
Labels: bug
