### ISSUE TITLE
In almost all simulations of machines prior to the 480, the hard disk is not recognized.

### ISSUE THREAD

**Issue by wlnklove** [86Box/86Box#4603] opened 2024-07-07 13:48 UTC
### What happened?

In the 86box, I experimented with all the models from the 8088 to the 80486 period. Even with the correct configuration of the hard disk controller and the hard disk, the hard disk is still not recognized.

### Configuration file

```ini
[General]
vid_renderer = qt_software
language = system
iconset = winbox

[Machine]
machine = ibmps2_m50
cpu_family = 286
cpu_speed = 25000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
fpu_type = 287xl
mem_size = 1024

[Video]
8514a = 1
xga = 1
gfxcard = internal

[Input devices]
mouse_type = msserial

[Sound]
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = ide_mcide
cassette_mode = load

[Microsoft Serial Mouse]
port = 0
buttons = 4

[Hard disks]
hdd_01_parameters = 17, 4, 306, 0, ide
hdd_01_fn = 2.vhd
hdd_01_speed = ramdisk
hdd_01_vhd_blocksize = 4096
hdd_01_ide_channel = 1:0

[Floppy and CD-ROM drives]
fdd_01_fn = E:/PCemV15WinHHB/MS-DOS/Microsoft MS-DOS 5.00 (3.5-720k)/Microsoft MS-DOS 5.00 (3.5-720k)/Disk01.img

[Standard PS/2 Mouse]
buttons = 5

[PC/XT XTIDE]
bios = xt

[IBM PS/2 SCSI Adapter (Spock) #1]
bios_ver = 1
```

### Operating system

windows10

### CPU

i7 7700k

### 86Box version

4.1.1

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment] 2024-07-08 18:40
I can not reproduce this at all, I have plenty of emulated machines using hard disks with that exact CHS and they work just fine. You must be doing something wrong - are you actually configuring the hard disk correctly in CMOS setup?

Because of this, I'm closing this with NOTABUG - the emulator works are intented, you're doing something wrong.

**Closed by OBattler** 2024-07-08 18:40 UTC
Labels: bug
