### ISSUE TITLE
Prince of Persia crash on 8088/NEC V20 

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#2885] opened 2022-11-21 01:06 UTC
**Describe the bug**
I found a strange bug in both PoP 1.0 and 1.3 versions. The 1.0 has no sound/music (it should produce music at startup from the PC speaker) and after pressing Enter to start the game it crashes (the prince never gets up). I tested different configurations. 
The issue always happens if I use a 8088/NEC V20, regardless of the video card, (I tested Hercules, CGA and EGA)

Configuration I tested:
Not working: 
PC-V20: with Hercules, CGA and EGA. MS-DOS 3.30
Micoms XL-7 Turbo: Tested with Hercules and CGA with a 8088/8 and NEC V20/10,  with MS-DOS 3.20

Working (seems to be all 8086 machines)
Olivetti M240: 8086/8 with CGA and Olivetti Go 708. with Olivetti MS-DOS 3.30
Amstrad 1640: 8086/8 with the internal EGA chip (very slow but works). with Amstrad MS-DOS 3.20

I think it may be some changed related to the 8-bit memory bus of the 8088/V20. 

Here are the floppy-image files: 
[Prince of Persia 1.0 720.IMA.zip](https://github.com/86Box/86Box/files/10051221/Prince.of.Persia.1.0.720.IMA.zip)
[PRINCE OF PERSIA 1.3.IMA.zip](https://github.com/86Box/86Box/files/10051222/PRINCE.OF.PERSIA.1.3.IMA.zip)

**To Reproduce**
1. Start a VM with a 8088/V20 CPU 
2. With the Version 1.0, simply type "PRINCE" on the drive A. On version 1.3 it has to be configured with the "SETUP" program first and then type "PRINCE"
3. On version 1.3 there is music but crash after typing ENTER. On version 1.0 there is no music and crash after starting level 1. the Prince never gets up 

**Screenshots**
Not Working:
![PoP 8088 bug 004](https://user-images.githubusercontent.com/31600563/202937550-32ab274f-cbc2-4613-a04c-71daf54fd970.png)
![PoP 8088 bug 003](https://user-images.githubusercontent.com/31600563/202937554-1c3c4144-4ed6-41db-b10c-0e11f4f014ae.png)

Working:
![PoP 8088 bug 007](https://user-images.githubusercontent.com/31600563/202937585-b1fbc158-aed5-4438-9918-839edafafa77.png)
![PoP 8088 bug 006](https://user-images.githubusercontent.com/31600563/202937590-2cdb1f74-83ca-4bed-8676-64d5d4413266.png)
![PoP 8088 bug 005](https://user-images.githubusercontent.com/31600563/202937591-a7a5c2a9-9555-4903-84d1-65384ce1bcda.png)

**Desktop (please complete the following information):**
 - OS: Win 10 21H1
 - 86Box version: 3.11.0.4290
 - Build information: old dynarec, Win32

**Comment by Fenix770** [comment] 2022-11-21 01:17
The bug also exist on builds 4276 and 4265.

**Comment by OBattler** [comment] 2022-11-22 14:04
Will test this, but I suspect it's an icompatibility with those two specific machines.

**Comment by Fenix770** [comment] 2023-08-26 22:16
Update: Tested on build 4.0.0.4958 Win 32 old dynarec

I tested the Micoms 8088 machine. This issue happens to both Prince of Persia and Bubble Booble when a 808x CPU is used, a Hercules graphics card is also used and uses the PC speaker as sound device. The issue happens if these 3 conditions  both games don't work. If use the CMS/Game blaster on both games, they work however there are sync problems. 

1. On PoP the prince never gets up, on level 1 (with the 3 conditions), but with the CMS sound card there are slow down when enemy guards or other devices are present.

2. On Bubble Bobble the Bubble never blasts (with these 3 conditions), but with the CMS sound card both the dragon and enemies down too fast at the start of each level but then both moves slowly during the game but the "hurry-Up" speed up comes too fast too.

**Comment by OBattler** [comment] 2023-12-09 19:37
Does this still happen?

**Comment by Fenix770** [comment] 2023-12-09 21:52
I can confirm this issue is still present! I tested the Hyosung 88T (8088 based) and Compaq 8086. 
The issue happens in the same way, when an 808x CPU+ PC speacker + and the Hercules graphics card is used.
Works if either, I change the graphics card to CGA or if I add the CMS/Adlib sound card.

**Comment by OBattler** [comment] 2024-01-14 23:43
Closing this as essentially a duplicate of #382.

**Closed by OBattler** 2024-01-14 23:43 UTC
Labels: bug
