### ISSUE TITLE
cdman 2 black screen, freeze

### ISSUE THREAD

**Issue by honx4amiga** [86Box/86Box#1688] opened 2021-09-13 22:15 UTC
if i want to play cdman2 (a pac man clone), emulation freezes. i can see the menu but once i start a game or demo the screen goes black and nothing happens. i can't reboot using ctrl + f12, i have to perform hard reset.
currently i'm using latest build 3181. i did also backtrack back to build 2980 which is the oldest build i currently have, there this problem also occurs.
but i remember playing cdman2 in 86box. and the game is installed on my emulated hard drive since december 20 2020, therefore the game must have worked in earlier version. otherwise i wouldn't have installed it on hard drive. if i recall correctly, at that time i used the latest "stable" version of 86box, which was 2.07, it was before i started downloading "daily" builds from ci.86box.net. so it obviously worked in latest stable 2.07 version.

i attach a floppy image with that game.
[cdman2.zip](https://github.com/86Box/86Box/files/7157575/cdman2.zip)

my configuration is:
machine type i486 (socket 2 and 3), machine [sis486] rise computer r418
display [pci] s3 vision964 (diamond stealth64 vram)
emulated operating system is ms dos 6.22
86box 3.0 build 3181, host os: windows 7 ultimate

**Comment by OBattler** [comment] 2021-09-13 22:53
The stable version is build 2008. You can bisect starting from there to determine which build broke it.

**Comment by OBattler** [comment] 2021-09-13 23:01
I have not been able to reproduce this bug so far.

**Comment by OBattler** [comment] 2021-09-13 23:06
OK, I can indeed reproduce it on the Rise Computer R418.

**Comment by honx4amiga** [comment] 2021-09-13 23:10
i got it to work. somehow the game relies on monochrome memory space (b000-b7ff) which i utilized for upper memory usage in 3 of 4 memory configurations.
cdman2 does WORK in the one and only configuration for very old (monochrome) games which does not alienate monochrome space.
but that's somehow funny. because cdman isn't a monochrome game! so why is it using monochrome space?

**Comment by OBattler** [comment] 2021-09-13 23:13
OK, the bug I'm seeing, already happens on build 2008 (ie. 2.07 stable). But the menu is completely corrupted in additional to that black screen.

**Comment by honx4amiga** [comment] 2021-09-13 23:18
maybe i'm lucky but i haven't seen any menu corruption so far. :)
only black screen if monochrome space is alienated as i found out a few minutes ago. :D

**Comment by OBattler** [comment] 2021-09-13 23:20
It turns out there's corrupted floppy reads on the Rise Computer R418. Will investigate further tomorrow.

**Comment by OBattler** [comment] 2021-09-14 12:25
OK, it turns out the problem *I* had was because I misconfigured the floppy drive in CMOS setup (1.44 MB drive, but CMOS setup was set to 1.2 MB), after that, the game works.

And yes, using the monochrome space for UMB's can cause such problems. This game most likely uses the 128k mapping (A0000-BFFFF), so it gets tripped on. So since it's not a bug, I'm closing this.

**Closed by OBattler** 2021-09-14 12:25 UTC
Labels: bug
